---
title: "'mini.ai' 업데이트"
author: Evgeni Chasnovski
date: 2022-08-07
categories: [update, reddit]
description: 이제 tree-sitter 기반의 텍스트 객체 지원
---

*원래 [Reddit에 게시됨](https://www.reddit.com/r/neovim/comments/wiamjt/miniai_now_supports_textobjects_based_on/)*

{{< video 2022-08-07-update-mini-ai-tree-sitter/demo.mp4 >}}

['mini.ai'](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-ai.md)는 `a`/`i` 텍스트 객체(textobject, `di(` 또는 `va"`와 같은)를 확장하고 생성하기 위한 ['mini.nvim'](https://github.com/nvim-mini/mini.nvim) 플러그인의 모듈입니다. 자세한 내용은 [발표 게시물](2022-07-28-announce-mini-ai.qmd)과 [도움말 파일](https://github.com/nvim-mini/mini.nvim/blob/55618446b0bb4d3ed37ff7f9f8cf6db56d34e139/doc/mini.txt#L254)을 참조하세요.

이제 내보내기 된 `MiniAI.gen_spec.treesitter()` 함수를 통해 tree-sitter 사양을 지원합니다. 이 기능이 작동하려면 사용자는 각 대상 언어에 대해 지정된 캡처(capture)가 있는 'textobjects' 쿼리 파일을 가지고 있어야 합니다. ['nvim-treesitter/nvim-treesitter-textobjects'](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)를 설치하거나 (텍스트 객체 기능을 활성화하지 않고) 'after/queries/<language>/textobjects.scm' 파일 내에 수동으로 생성하여 이를 가질 수 있습니다.

[여기](https://github.com/nvim-mini/mini.nvim/blob/c173c9fa0cecdf287787501679ce0bad058096d5/doc/mini.txt#L336-L345)에서 'mini.ai'와 'nvim-treesitter-textobjects'의 상세한 비교를 볼 수 있습니다. 간단히 말해서: 'nvim-treesitter-textobjects'는 쿼리를 함께 제공하지만 'mini.ai'는 제공하지 않습니다. 반면 'mini.ai'는 `v:count`, 다양한 검색 방식, 연속 적용(동일한 텍스트 객체의 점진적 선택), 그리고 `next`/`last` 텍스트 객체 변형을 지원하지만 'nvim-treesitter-textobjects'는 지원하지 않습니다.

'mini.ai'의 주요 목적은 대부분의 경우에 유용한 일반 텍스트 기반 텍스트 객체(괄호, 따옴표, 밑줄 등)를 만드는 것이지만, Lua 함수를 통한 확장도 가능하도록 설계되었습니다. 약간의 베타 테스트 후, [Oliver Leete](https://github.com/Oliver-Leete)가 매우 편리한 텍스트 객체 사양을 가능하게 하는 최소한의 API 변경에 대해 [훌륭한 제안](https://github.com/nvim-mini/mini.nvim/discussions/36#discussioncomment-3320103)을 해주었습니다. 그 덕분에 이제 가능해졌습니다.

**수정**: 제안 덕분에 이제 최신 `main` 브랜치는 단일 캡처 대신 캡처 배열을 지원합니다. 따라서 사용자는 `MiniAi.gen_spec.treesitter({ a = { '@conditional.outer', '@loop.outer' }, i = { '@conditional.inner', '@loop.inner' } })`와 같이 정의할 수 있습니다 (제공된 모든 매칭 중에서 최적의 영역을 선택합니다).
