---
title: "'mini.surround' 업데이트: 사용자 정의 주변 텍스트"
author: Evgeni Chasnovski
date: 2022-04-20
categories: [update, reddit]
description: 사용자 정의 주변 텍스트 및 검색 방식과 같은 새로운 기능
---

*원래 [Reddit에 게시됨](https://www.reddit.com/r/neovim/comments/u7v9ex/minisurround_new_features_custom_surroundings_and/)*

안녕하세요, Neovim 사용자 여러분!

저의 [mini.nvim](https://github.com/nvim-mini/mini.nvim) 플러그인의 여러 모듈 중 하나인 [mini.surround](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-surround.md)의 두 가지 새로운 기능을 공유하고자 합니다. 이것은 텍스트 주변(surround) 작업을 위한 모듈입니다 ('tpope/vim-surround' 또는 'machakann/vim-sandwich'의 Lua 구현체에 추가 기능이 더해진 것이라고 생각하시면 됩니다). 주변 텍스트 추가, 삭제, 교체, 찾기, 하이라이트를 지원합니다. 이 모든 기능은 dot-repeatable(점 반복 가능)이며 '함수 호출', '태그', '대화형'(사용자에게 입력을 요청)과 같은 추가 내장 주변 텍스트 기능을 제공합니다. 그리고 이제 두 가지 큰 새로운 기능이 추가되었습니다.

## 사용자 정의 주변 텍스트 (Custom surroundings)

`config.custom_surroundings`를 사용하여 자신만의 주변 텍스트를 정의하거나 기존의 것을 수정할 수 있습니다. 이를 통해 공백이 포함된 괄호를 추가하거나 Latex 명령이나 Lua 긴 괄호(`[[...]]`)를 위한 커스텀 주변 텍스트를 추가하는 등 사용자의 요구에 맞게 설정을 확장할 수 있습니다. 다음은 예시입니다:

```lua
require('mini.surround').setup({
  custom_surroundings = {
    -- Lua 긴 괄호
    s = {
      -- "입력"(삭제와 같은 작업)에 대한 설정은 Lua 패턴으로 수행됩니다
      input = { find = '%[%[.-%]%]', extract = '^(..).*(..)$' },
      -- "출력"(추가와 같은 작업)에 대한 설정은 일반 텍스트로 수행됩니다
      output = { left = '[[', right = ']]' },
    },
    -- 공백과 함께 삽입하려면 `(`를 사용하고, `)`는 여전히 공백 없이 추가합니다
    ['('] = { output = { left = '( ', right = ' )' } },
  },
})
```

이제 예를 들어 `sds`(`sd` - 'surround delete', `s` - 커스텀 주변 텍스트 식별자)를 입력하면 Lua의 긴 괄호를 찾아 삭제합니다. 자세한 내용은 [문서](https://github.com/nvim-mini/mini.nvim/blob/8134370549e73a5a72d24ffc7ea6a881cf4502ad/doc/mini.txt#L3795)를 참조하세요.

## 검색 방식 (Search method)

이 기능 전까지 'mini.surround'는 커서가 왼쪽 파트와 오른쪽 파트 사이에 있는 "감싸는(covering)" 주변 텍스트만 검색했습니다. 이제 이 동작은 `config.search_method` 옵션으로 사용자 정의할 수 있습니다. 예를 들어 값을 `'cover_or_next'`로 설정하면 `aaa (bbb)` 행의 시작 부분에서 `sd)`를 입력하여 `aaa bbb`와 같이 편집할 수 있습니다. 사용 가능한 방식은 'wellle/targets.vim'의 방식을 다소 단순화한 버전입니다. 자세한 내용은 [문서](https://github.com/nvim-mini/mini.nvim/blob/8134370549e73a5a72d24ffc7ea6a881cf4502ad/doc/mini.txt#L3880)를 참조하세요.

---

이 두 기능은 오래전에 추가되었어야 했지만, 많은 예외 케이스가 있어 코드를 건드리는 것이 조심스러웠습니다. 이제 마음을 다잡고 자동화된 테스트를 작성했으므로 훨씬 안전하게 진행할 수 있게 되었습니다.

이 기능을 사용해 보시고 의견을 들려주세요!
