---
title: "'mini.ai' 발표"
author: Evgeni Chasnovski
date: 2022-07-28
categories: [announce, reddit]
description: a/i 텍스트 객체 확장 및 생성 ('targets.vim'과 유사하지만 Lua로 구현되어 약간 다름)
---

*원래 [Reddit에 게시됨](https://www.reddit.com/r/neovim/comments/wa819w/miniai_extend_and_create_ai_textobjects_like/)*

{{< video 2022-07-28-announce-mini-ai/demo.mp4 >}}

안녕하세요, Neovim 사용자 여러분!

`a`/`i` 텍스트 객체(textobject, `di(` 또는 `va"`와 같은)를 확장하고 생성하기 위한 [mini.nvim](https://github.com/nvim-mini/mini.nvim)의 20번째 모듈 [mini.ai](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-ai.md)를 발표하게 되어 믿을 수 없을 정도로 기쁩니다. 이 모듈은 일부 내장 텍스트 객체(`a(`, `a)`, `a'` 등)를 강화하고, 새로운 객체(`a*`, `a<Space>`, `af`, `a?` 등)를 생성하며, 사용자가 직접 자신만의 객체를 만들 수 있게 해줍니다.

기능:

- Lua 패턴과 함수를 사용한 사용자 정의 `a`/`i` 텍스트 객체 생성. 지원 기능:
    - 점 반복(Dot-repeat).
    - `v:count`.
    - 다양한 검색 방식(`cover`, `cover_or_next`, `cover_or_prev`, `cover_or_nearest`). **수정**: 이제 `next`, `prev` (강력한 `an`/`in`/`al`/`il` 텍스트 객체) 및 `nearest`도 지원합니다.
    - 연속 적용 (비주얼 모드를 벗어나지 않고 선택 영역 업데이트).
    - 여러 텍스트 객체에 대한 별칭(Alias).

- 포괄적인 내장 텍스트 객체 (비디오에 표시됨):
    - 균형 잡힌 괄호 (공백 포함/미포함) 및 별칭.
    - 균형 잡힌 따옴표 및 별칭.
    - 사용자 프롬프트로부터 파생된 객체.
    - 태그.
    - 함수 호출.
    - 인수(Argument).
    - 구두점, 숫자 또는 공백 단일 문자에 대한 기본값.

- 텍스트 객체의 왼쪽/오른쪽 가장자리로 점프하기 위한 동작(Motions).

- **모든 'mini.nvim' 모듈**의 기능으로서, 런타임 설정값을 버퍼에 로컬로 설정할 수 있습니다. 이를 통해 특정 조건(예: 파일 유형별)에 대해서만 커스텀 텍스트 객체를 정의할 수 있습니다.

더 많은 정보는 [도움말 파일](https://github.com/nvim-mini/mini.nvim/blob/bca7dabca76606ab101009e7b0fe128fa037bf54/doc/mini.txt#L245)에서 확인할 수 있습니다. [여기](https://github.com/nvim-mini/mini.nvim/blob/bca7dabca76606ab101009e7b0fe128fa037bf54/doc/mini.txt#L507-L547)에 'mini.ai'로 정의할 수 있는 텍스트 객체의 몇 가지 예시가 있습니다.

이것은 제가 'mini.nvim'에 대해 받은 [첫 번째 모듈 요청](https://github.com/nvim-mini/mini.nvim/issues/4)이었으며, 마침내 구현하게 되어 기쁩니다. 처음에는 [mini.surround](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-surround.md)와 동일한 "백엔드"를 가질 계획이었습니다. 하지만 텍스트 객체 정의와 알고리즘을 약간 변경하면 훨씬 더 강력한 텍스트 객체(별칭 등)를 구현할 수 있다는 아이디어를 얻었습니다. 'mini.ai'의 공개 베타 테스트가 끝나면 그 로직을 'mini.surround'로 옮길 계획입니다 (이는 현재의 커스텀 텍스트 객체 정의에 대한 부드러운 지원 중단으로 이어질 것입니다).

사용해 보시고 의견을 들려주세요! 여기 댓글이나 [전용 베타 테스트 이슈](https://github.com/nvim-mini/mini.nvim/issues/98)를 이용해 주시기 바랍니다. 특히 기본 텍스트 객체에 대한 여러분의 생각이 궁금합니다 (베타 테스트 이슈에 더 많은 정보가 있습니다).

또한 'mini.nvim' 플러그인에 대한 정보를 공유해주시는 것만으로도 큰 도움이 됩니다. 감사합니다!
