---
title: "릴리스 0.9.0"
author: Evgeni Chasnovski
date: 2023-06-08
categories: [release, reddit]
description: 색상, 주석 및 유지 관리
---

*원래 [Reddit에 게시됨](https://www.reddit.com/r/neovim/comments/14498im/mininvim_release_090_colors_comments_and/)*

안녕하세요, Neovim 사용자 여러분!

다시 한번 [mini.nvim](https://github.com/nvim-mini/mini.nvim) 버전 0.9.0 출시 소식을 전하게 되어 매우 기쁩니다. 이번 릴리스는 주로 색상과 관련된 세 개의 새로운 모듈, 'mini.comment'의 흥미로운 새로운 기능, 그리고 일부 유지 관리 작업에 관한 것입니다.

관심 있으신 분들은 [전체 릴리스 설명](https://github.com/nvim-mini/mini.nvim/releases/tag/v0.9.0)을 참조해 주세요.

------

세 개의 새로운 모듈(모두 색상 관련)이 베타 테스트를 마쳤습니다:

- [mini.colors](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-colors.md) - 모든 색상 테마 수정 및 저장. 다른 사용자들이 "이 색상 테마가 전반적으로 마음에 들지만 좀 더 밝게/어둡게/채도를 높게/채도를 낮게/배경을 투명하게/`cterm` 속성을 지원하게/등등 하고 싶다"와 같은 일반적인 문제를 해결하도록 돕기 위해 색상 이론과 Neovim 색상 테마를 깊이 있게 탐구한 결과물입니다.
- [mini.hues](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-hues.md) - 설정 가능한 색상 테마 생성. 색상 이론에 대한 더 많은 통찰력을 얻은 후, ([mini.base16](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-base16.md)과 같은 미리 정의된 표준을 따르지 않는) 나만의 색상 테마 생성기를 직접 만들어 보겠다는 자신감이 생겼습니다. 결과는 마음에 듭니다. 특히 현재 제 데일리 테마인 `randomhue` 색상 테마가 그렇습니다.
- [mini.hipatterns](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-hipatterns.md) (**30번째 모듈**) - 텍스트 내 패턴 하이라이트. [folke/todo-comments.nvim](https://github.com/folke/todo-comments.nvim)과 [NvChad/nvim-colorizer.lua](https://github.com/NvChad/nvim-colorizer.lua) 사이의 좀 더 유연하고 가능성이 많은 절충안이라고 생각하시면 됩니다.

------

[mini.comment](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-comment.md)는 Neovim 0.9.0의 새로운 기능에 맞춰 대대적으로 업데이트되었습니다:

- **Tree-sitter를 인식하는 로컬 주석 처리가 바로 작동합니다**. 로컬에서 활성화된 언어에 대한 tree-sitter 정보를 사용하여 'commentstring' 옵션값을 유추합니다. 대부분의 경우에 잘 작동하며 보통 ['JoosepAlviste/nvim-ts-context-commentstring'](https://github.com/JoosepAlviste/nvim-ts-context-commentstring)이 더 이상 필요하지 않습니다. 안타깝게도 TSX와 같이 (과도하게) 복잡한 일부 경우에는 여전히 필요할 수 있습니다.
- 주석 구조를 더 세밀하게 커스터마이징할 수 있는 새로운 `options.custom_commentstring` 옵션이 추가되었습니다. 이곳에서 'JoosepAlviste/nvim-ts-context-commentstring'을 사용할 수 있습니다.
- 관련 'commentstring'을 계산하는 내장 로직을 나타내는 새로운 `get_commentstring()` 함수가 추가되었습니다.

------

오랫동안 기다려온 Neovim<=0.6 지원 중단과 관련된 많은 유지 관리 작업이 있었습니다. 이는 'mini.nvim'이 마침내 자동 명령, 매핑 및 기본 하이라이트 그룹 생성과 같은 일반적인 작업에 Lua API를 사용할 수 있게 되었음을 의미합니다. 또한 내보내는 함수가 줄어들어(대부분 자동 명령 및 매핑 작업을 위한 것이었음) 테스트와 문서가 간소화되었습니다.

------

새로운 색상 테마를 사용해 보고 싶거나, 직접 수정해 보고 싶거나, 패턴에 하이라이트를 추가하고 싶거나, tree-sitter를 인식하는 주석 처리를 바로 사용하고 싶다면 지금이 좋은 기회입니다!

읽어주셔서 감사합니다! 다음 모듈 릴리스에서 뵙기를 바랍니다!
