---
title: "MiniMax - MINI의 정수를 담은 Neovim 설정"
author: Evgeni Chasnovski
date: 2025-10-13
categories: [announce]
description: "MiniMax는 MINI를 주축으로 하는 독립적이고 즉시 사용 가능한 Neovim 설정 모음입니다."
---

안녕하세요, Neovim 사용자 여러분!

드디어 "공식적인" MINI 설정 예시를 발표하게 되어 매우 기쁘고 다행스럽게 생각합니다. 이름은 [MiniMax](../MiniMax/index.md)입니다.

이번 발표로 오늘은 세 가지 MINI의 생일이 되었습니다:

- 'mini.nvim' 플러그인 자체가 출시된 지 [4년 전](2021-10-13-announce-mini-nvim.qmd)입니다.
- 'mini.pick' 모듈이 출시된 지 [2년 전](2023-10-13-announce-mini-pick.qmd)입니다.
- 그리고 오늘, MiniMax의 생일이 추가되었습니다.

---

MiniMax는 단순한 단일 설정 그 이상으로 설계되었습니다. 특정 조건에 맞춰 정교하게 제작된 [설정들의 컬렉션](../MiniMax/configs/index.md)입니다. 현재는 각 안정 버전의 Neovim에 대한 전용 설정을 제공할 계획이며, 향후 다른 조건들도 고려될 수 있습니다 (물론 가까운 미래는 아닐 것입니다). 제가 알기로 이러한 방식은 기존의 "미리 구성된 설정(preconfigured configurations)"들 사이에서도 꽤 독특한 시도입니다. 이는 MiniMax를 단순한 설정 이상으로 유용하게 만들 것입니다. 시간이 지나면 Neovim 버전을 변경할 때 어떤 변경 사항들을 적용하는 것이 좋을지에 대한 좋은 참고 자료가 될 것이기 때문입니다.

설정 자체는 [매우 간결한 구조](../MiniMax/configs/nvim-0.11/index.qmd)를 가지고 있습니다: 작은 'init.lua'와 시작 시 로드되는 4개의 'plugin/' 파일로 구성됩니다. 이 구조와 내용은 제가 오랫동안 메인으로 사용해 온 설정을 기반으로 합니다.

오늘날의 관점에서 보면 MiniMax는 'nvim-lua/kickstart.nvim'과 스타일이 비슷합니다. 설정 파일에는 많은 문서화 주석이 포함되어 있으며 **사용자가 직접 읽도록 제작되었습니다**. MiniMax를 설정하고 나면, 이를 미세 조정하고 업데이트하는 것은 여러분의 몫입니다. MiniMax는 [배포판(distro)이나 Neovim에 관한 종합 가이드가 아닙니다](../MiniMax/index.md#what-it-is-not).

한번 확인해 보시고 의견을 들려주세요. 저는 현재 상태를 최대한 사용하기 편하고, 정교하며, 오타가 없도록 만드는 데 집중하고 싶습니다. 당분간은 새로운 특정 옵션이나 플러그인 추가에 대한 제안은 받지 않을 예정입니다.

---

MiniMax 개발 과정에서 유용한 피드백을 주신 [Pete Kazmier](https://github.com/pkazmier) 님께 감사의 마음을 전합니다.

그리고 지속적인 성원을 보내주시는 *여러분 모두*에게 감사드립니다! 앞으로도 이런 생일을 더 많이 함께 맞이할 수 있기를 바랍니다!
