---
title: "mini.pairs 문서"
---

_이 문서는 'mini.nvim'의 `main` 브랜치에서 생성되었습니다._

<a name="mini.pairs" href="mini-pairs.qmd#mini.pairs"><b>mini.pairs</b></a> 자동 페어(Autopairs)

MIT 라이선스 Copyright (c) 2021 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:

- 커서의 인접 문자(왼쪽 문자 및 오른쪽 문자)에 따라 "쌍을 이루는" 두 문자로 작업하는 기능입니다.


- 사용은 [MiniPairs.map()](mini-pairs.qmd#minipairs.map)이나 [MiniPairs.setup()](mini-pairs.qmd#minipairs.setup) (전역 매핑용), [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf) (버퍼 매핑용)을 사용하여 적절한 매핑을 만들어야 합니다.


- 페어는 특별한 <span class="help-syntax-keys">\<BS\></span> (모든 구성된 모드) 및 <span class="help-syntax-keys">\<CR\></span> (입력 모드 전용) 매핑에 대해 자동으로 등록됩니다. 페어 내부에서 키를 누르면 페어 전체를 삭제하거나 페어 내부에 추가 빈 줄을 각각 삽입합니다.
  참고: 이러한 매핑은 기존 매핑을 재정의하지 않는 경우 자동으로 생성됩니다.

하지 않는 것:

- 괄호 균형 등에 기반한 스마트한 동작은 제공하지 않습니다. 기본 동작은 거의 항상 동작(페어 삽입, 점프)을 수행하는 것입니다. 문자를 명시적으로 삽입(해당 문자만 삽입)하려면 문자 앞에서 수동으로 [i\_CTRL-V](https://neovim.io/doc/user/helptag.html?tag=i_CTRL-V)를 누르세요.


- "열기" 및 "닫기" 기호로 여러 문자를 사용하는 것은 지원하지 않습니다. 이를 위해서는 스니펫(snippets)을 사용하세요.


- 파일 타입에 따른 의존성을 지원하지 않습니다. 단일 기호를 삽입하려면 [i\_CTRL-V](https://neovim.io/doc/user/helptag.html?tag=i_CTRL-V)를 사용하거나, `autocmd` 명령 또는 'after/ftplugin' 방식을 사용하여 다음과 같이 하세요:

    - `:lua MiniPairs.map_buf(0, 'i', <*>, <pair_info>)` - 현재 버퍼에서 '<span class="help-syntax-keys">\<*\></span>'에 대한 새 매핑을 만듭니다.

    - `:lua MiniPairs.unmap_buf(0, 'i', <*>, <pair>)` - 현재 버퍼에서 `<pair>` 페어를 등록 해제하면서 키 `<*>`의 매핑을 해제합니다. 참고: 이는 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf)에 의한 매핑을 되돌립니다. 매핑이 [MiniPairs.map()](mini-pairs.qmd#minipairs.map)으로 수행된 경우, 일반적인 Neovim 방식인 `inoremap <buffer> <*> <*>`로 버퍼에 대해 매핑을 해제하세요 (이는 `<*>` 키가 기본적으로 수행하는 작업을 수행하도록 매핑합니다).

    - 버퍼에 대해 모듈을 비활성화합니다 ('비활성화' 섹션 참조).

#### 설정 {#module-setup}


이 모듈은 `require('mini.pairs').setup({})`으로 설정이 필요합니다 (`{}`를 `config` 테이블로 교체하세요). 이는 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniPairs`를 생성합니다 (예: `:lua MiniPairs.*`).

`config` 구조와 기본값은 [MiniPairs.config](mini-pairs.qmd#minipairs.config)를 참조하세요.

이 모듈은 런타임 옵션이 없으므로 `vim.b.minipairs_config`를 사용하는 것은 효과가 없습니다.

#### 매핑 예시 {#module-examplemappings}



  ```lua
  -- `MiniPairs.setup()`의 `config` 내부에서 따옴표 등록
  mappings = {
    ['"'] = { register = { cr = true } },
    ["'"] = { register = { cr = true } },
  }

  -- 줄 시작 부분에 `<`를 입력하면 `<>` 페어 삽입, <CR>은 등록하지 않음
  local lt_opts = {
    action = 'open',
    pair = '<>',
    neigh_pattern = '\r.',
    register = { cr = false },
  }
  MiniPairs.map('i', '<', lt_opts)

  local gt_opts = { action = 'close', pair = '<>', register = { cr = false } }
  MiniPairs.map('i', '>', gt_opts)

  -- Tex 파일에서만 대칭형 `$$` 페어 생성
  local map_tex = function()
    MiniPairs.map_buf(0, 'i', '$', { action = 'closeopen', pair = '$$' })
  end
  vim.api.nvim_create_autocmd(
    'FileType',
    { pattern = 'tex', callback = map_tex }
  )
  ```

#### 참고 {#module-notes}



- 선택한 완료(completion) 플러그인을 지원하려면 <span class="help-syntax-keys">\<CR\></span>의 적절한 매핑을 수행해야 합니다:

    - [mini.completion](mini-completion.qmd#mini.completion)에 대해서는 '도움이 되는 키 매핑' 섹션을 참조하세요.

    - "hrsh7th/nvim-cmp"의 현재 구현에서는 커스텀 매핑을 만들 필요가 없습니다. 기본 설정을 사용하면 팝업이 보이는 경우 완료 선택을 확인하고, 그렇지 않은 경우 페어를 확장합니다.

- 터미널 모드에서 매핑이 있으면 다음과 충돌할 수 있습니다:

    - 인터프리터(`ipython`, `radian`)의 자동 페어링 기능.

    - 터미널 자체의 Vim 모드.

#### 비활성화 {#module-disabling}


비활성화하려면 `vim.g.minipairs_disable` (전역) 또는 `vim.b.minipairs_disable` (버퍼용)을 `true`로 설정하세요. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈 기능 비활성화를 위한 정확한 규칙 작성은 사용자의 몫으로 남겨둡니다. 일반적인 레시피는 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### setup() {#minipairs.setup .help-syntax-right-anchor}

<p align="center">`MiniPairs.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minipairs.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniPairs.config](mini-pairs.qmd#minipairs.config)를 참조하세요.

#### 사용법 {#minipairs.setup-usage}



  ```lua
  require('mini.pairs').setup() -- 기본 설정 사용
  -- 또는
  require('mini.pairs').setup({}) -- {}를 설정 테이블로 교체
  ```

---

### config {#minipairs.config .help-syntax-right-anchor}

<p align="center">`MiniPairs.config`</p>
#### 기본값 {#minipairs.config-defaults}



  ```lua
  MiniPairs.config = {
    -- 이 `config`의 매핑이 생성될 모드
    modes = { insert = true, command = false, terminal = false },

    -- 전역 매핑. 각 우측항(right hand side)은 페어 정보여야 합니다.
    -- 최소한 다음 필드가 있는 테이블입니다 (|MiniPairs.map()|에서 자세히 확인):
    -- - <action> - "open", "close", "closeopen" 중 하나.
    -- - <pair> - 사용될 두 문자로 된 페어 문자열.
    -- 기본적으로 페어는 `\` 뒤에 삽입되지 않으며, 따옴표는 <CR>에 의해 인식되지 않고,
    -- `'`는 문자 뒤에 페어를 삽입하지 않습니다.
    -- 테이블의 일부만 조정할 수 있습니다 (다른 부분은 기본값을 사용함).
    -- 특정 키를 매핑하지 않으려면 테이블 대신 `false`를 제공하세요.
    mappings = {
      ['('] = { action = 'open', pair = '()', neigh_pattern = '^[^\\]' },
      ['['] = { action = 'open', pair = '[]', neigh_pattern = '^[^\\]' },
      ['{'] = { action = 'open', pair = '{}', neigh_pattern = '^[^\\]' },

      [')'] = { action = 'close', pair = '()', neigh_pattern = '^[^\\]' },
      [']'] = { action = 'close', pair = '[]', neigh_pattern = '^[^\\]' },
      ['}'] = { action = 'close', pair = '{}', neigh_pattern = '^[^\\]' },

      ['"'] = { action = 'closeopen', pair = '""', neigh_pattern = '^[^\\]',   register = { cr = false } },
      ["'"] = { action = 'closeopen', pair = "''", neigh_pattern = '^[^%a\\]', register = { cr = false } },
      ['`'] = { action = 'closeopen', pair = '``', neigh_pattern = '^[^\\]',   register = { cr = false } },
    },
  }
  ```

---

### map() {#minipairs.map .help-syntax-right-anchor}

<p align="center">`MiniPairs.map`(<span class="help-syntax-special">{mode}</span>, <span class="help-syntax-special">{lhs}</span>, <span class="help-syntax-special">{pair_info}</span>, <span class="help-syntax-special">{opts}</span>)</p>
전역 매핑 만들기

이는 [nvim\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_keymap\(\))의 래퍼이지만 매핑의 우측항(문자열) 대신 페어 정보가 있는 테이블을 예상합니다.

[nvim\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_keymap\(\)) 대신 이 함수를 사용하면 <span class="help-syntax-keys">\<BS\></span> 및 <span class="help-syntax-keys">\<CR\></span>에 의해 인식될 페어를 자동으로 등록할 수 있습니다.
또한 `pair_info`에서 매핑 설명을 유추합니다.

#### 매개변수 {#minipairs.map-parameters}



<span class="help-syntax-special">{mode}</span> `(string)` [nvim\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_keymap\(\))용 `mode`.

<span class="help-syntax-special">{lhs}</span> `(string)` [nvim\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_keymap\(\))용 `lhs`.

<span class="help-syntax-special">{pair_info}</span> `(table)` 페어 정보가 있는 테이블. 필드:

  - <span class="help-syntax-keys">\<action\></span> - [MiniPairs.open()](mini-pairs.qmd#minipairs.open)용 "open",
    [MiniPairs.close()](mini-pairs.qmd#minipairs.close)용 "close", 또는 [MiniPairs.closeopen()](mini-pairs.qmd#minipairs.closeopen)용 "closeopen" 중 하나.

  - <span class="help-syntax-keys">\<pair\></span> - 액션 함수에 전달될 두 문자열 페어.
    멀티바이트 문자를 포함할 수 있습니다.

  - <span class="help-syntax-keys">\<neigh_pattern\></span> - 액션 함수에 전달될 선택적 인접 패턴. 두 문자로 된 인접 문자와 일치하게 됩니다 (멀티바이트 문자를 포함할 수 있음).
    기본값: `'..'` (인접 문자에 의한 제한 없음).

  - <span class="help-syntax-keys">\<register\></span> - 이 페어가 [MiniPairs.bs()](mini-pairs.qmd#minipairs.bs)에서 <span class="help-syntax-keys">\<BS\></span> 및/또는 [MiniPairs.cr()](mini-pairs.qmd#minipairs.cr)에서 <span class="help-syntax-keys">\<CR\></span>에 의해 인식될지에 대한 정보가 포함된 선택적 테이블.
    불리언 필드 <span class="help-syntax-keys">\<bs\></span> 및 <span class="help-syntax-keys">\<cr\></span>을 가져야 합니다 (둘 다 기본값은 `true`).

<span class="help-syntax-special">{opts}</span> `(table|nil)` [nvim\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_keymap\(\))용 선택적 테이블 `opts`. 요소 `expr` 및 `noremap`은 인식되지 않습니다 (기본적으로 `true`).

---

### map_buf() {#minipairs.map_buf .help-syntax-right-anchor}

<p align="center">`MiniPairs.map_buf`(<span class="help-syntax-special">{buffer}</span>, <span class="help-syntax-special">{mode}</span>, <span class="help-syntax-special">{lhs}</span>, <span class="help-syntax-special">{pair_info}</span>, <span class="help-syntax-special">{opts}</span>)</p>
버퍼 매핑 만들기

이는 [nvim\_buf\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_keymap\(\))의 래퍼이지만 매핑의 문자열 우측항 대신 [MiniPairs.map()](mini-pairs.qmd#minipairs.map)과 유사한 페어 정보 테이블을 예상합니다.

[nvim\_buf\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_keymap\(\)) 대신 이 함수를 사용하면 <span class="help-syntax-keys">\<BS\></span> 및 <span class="help-syntax-keys">\<CR\></span>에 의해 인식될 페어를 자동으로 등록할 수 있습니다.
또한 `pair_info`에서 매핑 설명을 유추합니다.

#### 매개변수 {#minipairs.map_buf-parameters}



<span class="help-syntax-special">{buffer}</span> `(number)` [nvim\_buf\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_keymap\(\))용 `buffer`.

<span class="help-syntax-special">{mode}</span> `(string)` [nvim\_buf\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_keymap\(\))용 `mode`.

<span class="help-syntax-special">{lhs}</span> `(string)` [nvim\_buf\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_keymap\(\))용 `lhs`.

<span class="help-syntax-special">{pair_info}</span> `(table)` 페어 정보가 있는 테이블.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [nvim\_buf\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_keymap\(\))용 선택적 테이블 `opts`.
  요소 `expr` 및 `noremap`은 인식되지 않습니다 (기본적으로 `true`).

---

### unmap() {#minipairs.unmap .help-syntax-right-anchor}

<p align="center">`MiniPairs.unmap`(<span class="help-syntax-special">{mode}</span>, <span class="help-syntax-special">{lhs}</span>, <span class="help-syntax-special">{pair}</span>)</p>
전역 매핑 삭제

제공된 `pair`를 등록 해제하는 [nvim\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_del_keymap\(\))의 래퍼입니다.

#### 매개변수 {#minipairs.unmap-parameters}



<span class="help-syntax-special">{mode}</span> `(string)` [nvim\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_del_keymap\(\))용 `mode`.

<span class="help-syntax-special">{lhs}</span> `(string)` [nvim\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_del_keymap\(\))용 `lhs`.

<span class="help-syntax-special">{pair}</span> `(string)` <span class="help-syntax-keys">\<BS\></span> 및 <span class="help-syntax-keys">\<CR\></span> 모두에서 등록 해제되어야 하는 페어.
  혼동을 피하기 위해 명시적으로 제공되어야 합니다.
  페어를 등록 해제하지 않으려면 `''`을 제공하세요.

---

### unmap_buf() {#minipairs.unmap_buf .help-syntax-right-anchor}

<p align="center">`MiniPairs.unmap_buf`(<span class="help-syntax-special">{buffer}</span>, <span class="help-syntax-special">{mode}</span>, <span class="help-syntax-special">{lhs}</span>, <span class="help-syntax-special">{pair}</span>)</p>
버퍼 매핑 삭제

제공된 `pair`를 등록 해제하는 [nvim\_buf\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_del_keymap\(\))의 래퍼입니다.

참고: 이는 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf)에 의한 매핑만 되돌립니다. 매핑이 [MiniPairs.map()](mini-pairs.qmd#minipairs.map)으로 수행된 경우, 버퍼에 대해 기본 동작으로 되돌립니다:

  ```lua
  -- `X` 키가 기본적으로 수행하는 작업을 수행하도록 매핑
  vim.keymap.set('i', 'X', 'X', { buffer = true })
  ```

#### 매개변수 {#minipairs.unmap_buf-parameters}



<span class="help-syntax-special">{buffer}</span> `(number)` [nvim\_buf\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_del_keymap\(\))용 `buffer`.

<span class="help-syntax-special">{mode}</span> `(string)` [nvim\_buf\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_del_keymap\(\))용 `mode`.

<span class="help-syntax-special">{lhs}</span> `(string)` [nvim\_buf\_del\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_del_keymap\(\))용 `lhs`.

<span class="help-syntax-special">{pair}</span> `(string)` <span class="help-syntax-keys">\<BS\></span> 및 <span class="help-syntax-keys">\<CR\></span> 모두에서 등록 해제되어야 하는 페어.
  혼동을 피하기 위해 명시적으로 제공되어야 합니다.
  페어를 등록 해제하지 않으려면 `''`을 제공하세요.

---

### open() {#minipairs.open .help-syntax-right-anchor}

<p align="center">`MiniPairs.open`(<span class="help-syntax-special">{pair}</span>, <span class="help-syntax-special">{neigh_pattern}</span>)</p>
"열기" 기호 처리

비대칭 페어('(', '[' 등)의 "열기" 기호에 대한 [:map-<span class="help-syntax-keys">\<expr\></span>](https://neovim.io/doc/user/helptag.html?tag=:map-<expr>) 매핑으로 사용됩니다. 인접 문자가 제공된 패턴과 일치하지 않으면 함수는 "열기" 기호가 됩니다. 일치하면 전체 페어를 붙여넣고 [<span class="help-syntax-keys">\<Left\></span>](https://neovim.io/doc/user/helptag.html?tag=<Left>)를 사용하여 페어 내부로 이동합니다.

실제 매핑을 위해 [MiniPairs.map()](mini-pairs.qmd#minipairs.map) 및 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf) 내부에서 사용됩니다.

#### 매개변수 {#minipairs.open-parameters}



<span class="help-syntax-special">{pair}</span> `(string)` 페어를 나타내는 두 문자 문자열.

<span class="help-syntax-special">{neigh_pattern}</span> `(string|nil)` 두 인접 문자에 대한 패턴.
  문자 "\r"은 줄 시작을, "\n"은 줄 끝을 나타냅니다.

#### 반환 {#minipairs.open-return}


`(string)` "열기" 동작을 수행하는 키.

---

### close() {#minipairs.close .help-syntax-right-anchor}

<p align="center">`MiniPairs.close`(<span class="help-syntax-special">{pair}</span>, <span class="help-syntax-special">{neigh_pattern}</span>)</p>
"닫기" 기호 처리

비대칭 페어(')', ']' 등)의 "닫기" 기호에 대한 [:map-<span class="help-syntax-keys">\<expr\></span>](https://neovim.io/doc/user/helptag.html?tag=:map-<expr>) 매핑으로 사용됩니다. 인접 문자가 제공된 패턴과 일치하지 않으면 함수는 "닫기" 기호가 됩니다. 일치하면 커서 오른쪽의 기호가 "닫기" 기호와 같으면 해당 기호를 넘어 점프하고([<span class="help-syntax-keys">\<Right\></span>](https://neovim.io/doc/user/helptag.html?tag=<Right>) 사용), 그렇지 않으면 삽입합니다.

실제 매핑을 위해 [MiniPairs.map()](mini-pairs.qmd#minipairs.map) 및 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf) 내부에서 사용됩니다.

#### 매개변수 {#minipairs.close-parameters}



<span class="help-syntax-special">{pair}</span> `(string)` 페어를 나타내는 두 문자 문자열.

<span class="help-syntax-special">{neigh_pattern}</span> `(string|nil)` 두 인접 문자에 대한 패턴.
  문자 "\r"은 줄 시작을, "\n"은 줄 끝을 나타냅니다.

#### 반환 {#minipairs.close-return}


`(string)` "닫기" 동작을 수행하는 키.

---

### closeopen() {#minipairs.closeopen .help-syntax-right-anchor}

<p align="center">`MiniPairs.closeopen`(<span class="help-syntax-special">{pair}</span>, <span class="help-syntax-special">{neigh_pattern}</span>)</p>
"closeopen" 기호 처리

" 및 '와 같은 '대칭형' 기호에 대한 [:map-<span class="help-syntax-keys">\<expr\></span>](https://neovim.io/doc/user/helptag.html?tag=:map-<expr>) 매핑으로 사용됩니다.
오른쪽 문자가 페어의 두 번째 문자와 같으면 해당 문자 너머로 이동하거나([<span class="help-syntax-keys">\<Right\></span>](https://neovim.io/doc/user/helptag.html?tag=<Right>) 사용), 그렇지 않으면 조건부로 페어를 붙여넣는([MiniPairs.open()](mini-pairs.qmd#minipairs.open) 사용) 'closeopen 동작'을 시도합니다.

실제 매핑을 위해 [MiniPairs.map()](mini-pairs.qmd#minipairs.map) 및 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf) 내부에서 사용됩니다.

#### 매개변수 {#minipairs.closeopen-parameters}



<span class="help-syntax-special">{pair}</span> `(string)` 페어를 나타내는 두 문자 문자열.

<span class="help-syntax-special">{neigh_pattern}</span> `(string|nil)` 두 인접 문자에 대한 패턴.
  문자 "\r"은 줄 시작을, "\n"은 줄 끝을 나타냅니다.

#### 반환 {#minipairs.closeopen-return}


`(string)` "closeopen" 동작을 수행하는 키.

---

### bs() {#minipairs.bs .help-syntax-right-anchor}

<p align="center">`MiniPairs.bs`(<span class="help-syntax-special">{key}</span>)</p>
[<span class="help-syntax-keys">\<BS\></span>](https://neovim.io/doc/user/helptag.html?tag=<BS>) 처리

입력 모드에서 <span class="help-syntax-keys">\<BS\></span>에 대한 [:map-<span class="help-syntax-keys">\<expr\></span>](https://neovim.io/doc/user/helptag.html?tag=:map-<expr>) 매핑으로 사용됩니다. 인접 문자가 현재 버퍼에 대해 인식된 전체 페어와 같으면 페어 전체를 삭제합니다(입력 키 뒤에 <span class="help-syntax-keys">\<Del\></span> 실행을 통해). 페어는 전역 또는 현재 버퍼 매핑에 등록되어 있는 경우 현재 버퍼에 대해 인식됩니다. 페어는 [MiniPairs.map()](mini-pairs.qmd#minipairs.map) 또는 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf)를 호출한 결과로 등록됩니다.

[MiniPairs.setup()](mini-pairs.qmd#minipairs.setup) 내부에서 기본적으로 매핑됩니다.

이는 다른 입력 모드 키를 수정하여 인접 페어를 존중하도록 하는 데 사용될 수 있습니다. 예시:

  ```lua
  local map_bs = function(lhs, rhs)
    vim.keymap.set('i', lhs, rhs, { expr = true, replace_keycodes = false })
  end

  map_bs('<C-h>', 'v:lua.MiniPairs.bs()')
  map_bs('<C-w>', 'v:lua.MiniPairs.bs("\23")')
  map_bs('<C-u>', 'v:lua.MiniPairs.bs("\21")')
  ```

#### 매개변수 {#minipairs.bs-parameters}



<span class="help-syntax-special">{key}</span> `(string|nil)` 사용할 키. 기본값: `'<BS>'`.

#### 반환 {#minipairs.bs-return}


`(string)` "백스페이스" 동작을 수행하는 키.

---

### cr() {#minipairs.cr .help-syntax-right-anchor}

<p align="center">`MiniPairs.cr`(<span class="help-syntax-special">{key}</span>)</p>
[i\_<span class="help-syntax-keys">\<CR\></span>](https://neovim.io/doc/user/helptag.html?tag=i_<CR>) 처리

입력 모드에서 <span class="help-syntax-keys">\<CR\></span>에 대한 [:map-<span class="help-syntax-keys">\<expr\></span>](https://neovim.io/doc/user/helptag.html?tag=:map-<expr>) 매핑으로 사용됩니다. 인접 문자가 현재 버퍼에 대해 인식된 전체 페어와 같으면 "닫기" 기호를 다음 줄에 놓습니다(`<CR><C-o>O` 사용). 페어는 전역 또는 현재 버퍼 매핑에 등록되어 있는 경우 현재 버퍼에 대해 인식됩니다. 페어는 [MiniPairs.map()](mini-pairs.qmd#minipairs.map) 또는 [MiniPairs.map\_buf()](mini-pairs.qmd#minipairs.map_buf)를 호출한 결과로 등록됩니다.

참고: [i\_CTRL-O](https://neovim.io/doc/user/helptag.html?tag=i_CTRL-O) 사용 효과에 대응하기 위해 일부 관련 모드 변경 이벤트는 일시적으로 무시됩니다 (['eventignore'](https://neovim.io/doc/user/helptag.html?tag='eventignore') 사용).

[MiniPairs.setup()](mini-pairs.qmd#minipairs.setup) 내부에서 기본적으로 매핑됩니다.

#### 매개변수 {#minipairs.cr-parameters}



<span class="help-syntax-special">{key}</span> `(string|nil)` 사용할 키. 기본값: `'<CR>'`.

#### 반환 {#minipairs.cr-return}


`(string)` "새 줄" 동작을 수행하는 키.
