---
title: "mini.cmdline 문서"
---

_ 'mini.nvim'의 `main` 브랜치에서 생성됨 _

<a name="mini.cmdline" href="mini-cmdline.qmd#mini.cmdline"><b>mini.cmdline</b></a> 커맨드 라인 조정

MIT 라이선스 Copyright (c) 2025 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:


- 설정 가능한 지연 시간으로 자동 완성. [cmdline-completion](https://neovim.io/doc/user/helptag.html?tag=cmdline-completion) 및 수동으로 ['wildchar'](https://neovim.io/doc/user/helptag.html?tag='wildchar')를 누르는 경험을 향상시킵니다. Neovim>=0.11이 필요하지만, Neovim>=0.12를 권장합니다.


- 입력 중에 단어를 자동 수정합니다. 명령 및 옵션과 같이 고정된 후보 세트에서 가져와야 하는 단어만 기본적으로 자동 수정됩니다.


- 입력 중에 명령 범위를 자동으로 미리 봅니다. 범위 줄과 설정 가능한 컨텍스트 줄을 플로팅 윈도우로 표시합니다.

하지 않는 기능:


- 커맨드 라인 UI의 사용자 정의. [vim.\_extui](https://neovim.io/doc/user/helptag.html?tag=vim._extui) (Neovim>=0.12에서)를 사용하세요.


- 자동 완성 후보의 사용자 정의. [cmdline-completion](https://neovim.io/doc/user/helptag.html?tag=cmdline-completion)을 통해 계산됩니다.

#### 설정 {#module-setup}


이 모듈은 `require('mini.cmdline').setup({})`(`{}`를 `config` 테이블로 교체)으로 설정이 필요합니다. 이는 스크립팅 또는 수동으로(`:lua MiniCmdline.*`) 사용할 수 있는 전역 Lua 테이블 `MiniCmdline`를 생성합니다.

`config` 구조 및 기본값은 [MiniCmdline.config](mini-cmdline.qmd#minicmdline.config)를 참조하세요.

`vim.b.minicmdline_config` 내부에 버퍼별로 런타임 설정 설정을 로컬로 재정의할 수 있으며, 이는 `MiniCmdline.config`와 동일한 구조여야 합니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

#### 권장 옵션 값 {#module-suggestedoptionvalues}


일부 옵션은 자동으로 설정됩니다([MiniCmdline.setup()](mini-cmdline.qmd#minicmdline.setup) 전에 설정되지 않은 경우):

- ['wildmode'](https://neovim.io/doc/user/helptag.html?tag='wildmode')는 덜 거슬리는 자동 완성을 위해 "noselect,full"로 설정됩니다. Neovim>=0.11 및 활성화된 `config.autocomplete`가 필요합니다.

- ['wildoptions'](https://neovim.io/doc/user/helptag.html?tag='wildoptions')는 퍼지 매칭을 활성화하기 위해 "pum,fuzzy"로 설정됩니다.

#### 비교 {#module-comparisons}



- [folke/noice.nvim](https://github.com/folke/noice.nvim):

    - 주로 커맨드 라인의 시각적인 측면에 초점을 맞춥니다. 이 모듈은 UI를 변경하지 않고 워크플로우를 개선하는 것을 목표로 합니다.


- [nacro90/numb.nvim](https://github.com/nacro90/numb.nvim):

    - 숫자로 정의된 단일 줄 범위만 미리 보도록 설계되었습니다. 이 모듈은 하나 및 두 줄 범위 모두에 대해 모든 형식의 [:range](https://neovim.io/doc/user/helptag.html?tag=:range) 및 [:range-offset](https://neovim.io/doc/user/helptag.html?tag=:range-offset)을 처리합니다.

    - 대상 줄을 일반 창에 직접 표시합니다. 이 모듈은 전용 플로팅 윈도우를 사용합니다.


- 내장 [cmdline-autocompletion](https://neovim.io/doc/user/helptag.html?tag=cmdline-autocompletion) (Neovim>=0.12에서):

    - 이 모듈은 Neovim>=0.12에서 이를 자동 완성의 기반으로 사용합니다. 그 위에 설정 가능한 지연 시간과 조건자(predicate)를 추가로 제공합니다.


- 내장 [vim.\_extui](https://neovim.io/doc/user/helptag.html?tag=vim._extui) (Neovim>=0.12에서):

    - 주로 커맨드 라인의 시각적인 측면에 초점을 맞춥니다. 이 모듈은 UI를 변경하지 않고 워크플로우를 개선하는 것을 목표로 합니다.

#### 하이라이트 그룹 {#module-highlightgroups}



- `MiniCmdlinePeekBorder` - 자동 미리보기 창의 테두리.

- `MiniCmdlinePeekLineNr` - 자동 미리보기 창의 줄 번호.

- `MiniCmdlinePeekNormal` - 자동 미리보기 창의 기본 전경색/배경색.

- `MiniCmdlinePeekSep` - 자동 미리보기 창의 statuscolumn 구분 기호.

- `MiniCmdlinePeekSign` - 자동 미리보기 창의 기호.

- `MiniCmdlinePeekTitle` - 자동 미리보기 창의 제목.

#### 비활성화 {#module-disabling}


매핑에서의 동작을 비활성화하려면 `vim.g.minicmdline_disable`(전역) 또는 `vim.b.minicmdline_disable`(버퍼용)을 `true`로 설정하세요. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈의 기능을 비활성화하기 위한 정확한 규칙을 작성하는 것은 사용자의 몫으로 남겨둡니다. 공통 레시피는 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### setup() {#minicmdline.setup .help-syntax-right-anchor}

<p align="center">`MiniCmdline.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minicmdline.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniCmdline.config](mini-cmdline.qmd#minicmdline.config)를 참조하세요.

#### 사용법 {#minicmdline.setup-usage}



  ```lua
  require('mini.cmdline').setup() -- 기본 설정 사용
  -- 또는
  require('mini.cmdline').setup({}) -- {}를 설정 테이블로 교체
  ```

---

### config {#minicmdline.config .help-syntax-right-anchor}

<p align="center">`MiniCmdline.config`</p>
#### 기본값 {#minicmdline.config-defaults}



  ```lua
  MiniCmdline.config = {
    -- 자동 완성: 입력 시 `:h 'wildmenu'` 표시
    autocomplete = {
      enable = true,

      -- 자동 완성을 트리거할 지연 시간 (ms)
      -- 양수 값의 경우 Neovim>=0.12를 권장합니다.
      delay = 0,

      -- 자동 완성을 트리거할 시점에 대한 사용자 정의 규칙
      predicate = nil,

      -- 더 일관된 wildmenu 동작을 위해 화살표 키를 매핑할지 여부
      map_arrows = true,
    },

    -- 자동 수정: 존재하지 않는 단어(명령, 옵션 등) 조정
    autocorrect = {
      enable = true,

      -- 사용자 정의 자동 수정 규칙
      func = nil,
    },

    -- 자동 미리보기: 명령의 대상 범위를 플로팅 윈도우에 표시
    autopeek = {
      enable = true,

      -- 범위 줄 위아래로 표시할 컨텍스트 줄 수
      n_context = 1,

      -- 미리보기 창을 표시할 시점에 대한 사용자 정의 규칙
      predicate = nil,

      -- 창 옵션
      window = {
        -- 플로팅 윈도우 설정
        config = {},

        -- statuscolumn을 렌더링하는 함수
        statuscolumn = nil,
      },
    },
  }
  ```

#### 일반 {#minicmdline.config-general}



- 각 기능은 별도의 테이블을 통해 설정됩니다.

- 기능을 비활성화하려면 `enable = false`를 사용하세요.

#### 자동 완성 {#minicmdline.config-autocomplete}


`config.autocomplete`는 자동 완성( ['wildmenu'](https://neovim.io/doc/user/helptag.html?tag='wildmenu')의 자동 표시)을 설정하는 데 사용됩니다.

`autocomplete.delay`는 wildmenu를 표시하기 위해 ['wildchar'](https://neovim.io/doc/user/helptag.html?tag='wildchar')가 트리거되는 지연 시간(디바운스 스타일)을 정의합니다. 기본값: 0. 참고: 깜박임을 줄이려면 양수 값에 대해 Neovim>=0.12를 권장합니다([wildtrigger()](https://neovim.io/doc/user/helptag.html?tag=wildtrigger\(\)) 덕분입니다).

`autocomplete.predicate`는 현재 커맨드 라인 상태에서 자동 완성을 트리거할지 여부를 결정하는 조건을 정의합니다. 입력 데이터가 있는 테이블을 인수로 받아 완성을 표시하려면 `true`를, 그렇지 않으면 `false`를 반환해야 합니다. 현재 커맨드 라인 상태에서 가능한 지연 시간 전에 호출됩니다. 기본값: [MiniCmdline.default\_autocomplete\_predicate()](mini-cmdline.qmd#minicmdline.default_autocomplete_predicate).

입력 데이터 필드:

- <span class="help-syntax-keys">\<line\></span> `(string)` - 현재 커맨드 라인 텍스트. [getcmdline()](https://neovim.io/doc/user/helptag.html?tag=getcmdline\(\))을 참조하세요.

- <span class="help-syntax-keys">\<pos\></span> `(number)` - 현재 커맨드 라인 열. [getcmdpos()](https://neovim.io/doc/user/helptag.html?tag=getcmdpos\(\))를 참조하세요.

- <span class="help-syntax-keys">\<line_prev\></span> `(string)` - 마지막 변경 전의 커맨드 라인 텍스트.

- <span class="help-syntax-keys">\<pos_prev\></span> `(number)` - 마지막 커서 이동 전의 커맨드 라인 열.

완성 유형에 따라 완성을 차단하는 예시(일부는 느릴 수 있기 때문):

  ```lua
  local block_compltype = { shellcmd = true }
  require('mini.cmdline').setup({
    autocomplete = {
      predicate = function()
        return not block_compltype[vim.fn.getcmdcompltype()]
      end,
    },
  })
  ```

일반 Ex 명령에 대해서만 완성을 활성화하는 데 유사한 방식을 사용할 수 있습니다. `return vim.fn.getcmdtype() == ':'`를 조건자 출력으로 사용하세요.

#### 자동 수정 {#minicmdline.config-autocorrect}


`config.autocorrect`는 자동 수정(입력 시 잘못된 단어를 자동으로 조정함)을 설정하는 데 사용됩니다. 이는 커맨드 라인 끝에 단일 문자를 추가할 때만 작동합니다. 이미 입력된 단어를 편집할 때는 자동 수정이 트리거되지 않습니다(자동 수정을 수정할 수 있게 함).

자동 수정 시점은 모든 키를 누른 후 [getcmdcomplpat()](https://neovim.io/doc/user/helptag.html?tag=getcmdcomplpat\(\))를 기반으로 자동으로 계산됩니다. 키 입력이 완성 패턴에 문자를 추가하지 않으면 키 입력 전의 패턴에 대해 수정을 시도합니다. 또한 명령을 실행하기 직전에도 마지막 단어에 대한 자동 수정 시도가 있습니다.

참고:

- 이는 주로 오타 수정을 위한 것이며 퍼지 매칭의 단축키가 아닙니다. 후자를 자동으로 수행하는 것은 너무 거슬립니다. 이를 위해서는 명시적으로 퍼지 완성을 사용하세요(기본적으로 설정됨).


- 기본 자동 수정은 명령 및 옵션과 같이 고정된 후보 세트에서 가져와야 하는 단어에 대해서만 수행되며, 문자열 거리가 가장 짧은 후보를 선택합니다. 자세한 내용은 [MiniCmdline.default\_autocorrect\_func()](mini-cmdline.qmd#minicmdline.default_autocorrect_func)를 참조하세요.


- 일부 커맨드 라인 [abbreviation](https://neovim.io/doc/user/helptag.html?tag=abbreviation)과 일치하는 단어는 자동 수정되지 않습니다.


- 현재 명령이 단일 인수만 예상하는 경우(예: [:colorscheme](https://neovim.io/doc/user/helptag.html?tag=:colorscheme)), 명령을 실행하기 직전에만 자동 수정이 발생합니다.

`autocorrect.func`는 자동 수정을 사용자 정의하는 데 사용할 수 있는 함수입니다. 입력 데이터가 있는 테이블을 인수로 받아 올바른 단어가 포함된 문자열 또는 자동 수정을 하지 않을 경우 `nil`을 반환해야 합니다. 기본값: [MiniCmdline.default\_autocorrect\_func()](mini-cmdline.qmd#minicmdline.default_autocorrect_func).

입력 데이터 필드:

- <span class="help-syntax-keys">\<word\></span> `(string)` - 자동 수정할 단어. 빈 문자열이 아님.

- <span class="help-syntax-keys">\<type\></span> `(string)` - 단어 유형. [getcmdcompltype()](https://neovim.io/doc/user/helptag.html?tag=getcmdcompltype\(\))의 출력.

#### 자동 미리보기 {#mini-cmdline.config-autopeek}


`config.autopeek`은 자동 미리보기를 설정하는 데 사용됩니다: 명령의 대상 범위를 플로팅 윈도우에 표시합니다. 창은 커맨드 라인 위에 나타나며 현재 버퍼를 보여주고 왼쪽 및 오른쪽(존재하고 왼쪽과 다른 경우) 범위 줄에 초점을 맞춥니다.

`autopeek.n_context`는 대상 위아래로 표시할 줄 수를 정의합니다. 범위 자체는 기본적으로 statuscolumn 기호로 시각화됩니다. 기본값: 1.

`autopeek.predicate`는 현재 커맨드 라인 상태에서 미리보기 창을 표시할지 여부를 결정하는 조건을 정의합니다. 입력 데이터가 있는 테이블을 인수로 받아 미리보기를 하려면 `true`를, 그렇지 않으면 `false`를 반환해야 합니다. 현재 커맨드 라인 텍스트에서 범위를 파싱할 수 있고 그것이 버퍼 줄인 경우(명령이 없거나 [:command-addr](https://neovim.io/doc/user/helptag.html?tag=:command-addr)이 `lines`임)에만 호출됩니다. 기본값: [MiniCmdline.default\_autopeek\_predicate()](mini-cmdline.qmd#minicmdline.default_autopeek_predicate).

입력 데이터 필드:

- <span class="help-syntax-keys">\<left\></span> `(number)` - 범위의 왼쪽 가장자리. 반드시 가장 작은 숫자는 아님.

- <span class="help-syntax-keys">\<right\></span> `(number)` - 범위의 오른쪽 가장자리. 단일 줄 범위의 경우 `left`와 동일함.

- <span class="help-syntax-keys">\<cmd\></span> `(string)` - 전체 명령 이름. 유효한 명령이 (아직) 입력되지 않은 경우 빈 문자열일 수 있음.

`autopeek.window`는 미리보기 창의 동작을 정의합니다. `autopeek.window.config`는 플로팅 윈도우 특성을 정의하는 테이블이거나 그러한 테이블을 반환하는 호출 가능한 객체입니다. [nvim\_open\_win()](https://neovim.io/doc/user/helptag.html?tag=nvim_open_win\(\))에서와 동일한 구조여야 합니다.

`autopeek.window.statuscolumn`은 미리보기 창의 ['statuscolumn'](https://neovim.io/doc/user/helptag.html?tag='statuscolumn') 값을 사용자 정의하는 데 사용할 수 있는 특수 함수입니다. 입력 데이터가 있는 테이블을 인수로 받아 줄 [v:lnum](https://neovim.io/doc/user/helptag.html?tag=v:lnum)에 대해 표시할 문자열을 반환해야 합니다. 기본값: [MiniCmdline.default\_autopeek\_statuscolumn()](mini-cmdline.qmd#minicmdline.default_autopeek_statuscolumn). 입력 데이터 필드는 `autopeek.predicate`와 동일합니다.

범위 줄에 `<` 및 `>` 기호를 표시하는 예시:

  ```lua
  function(data)
    local n, l, r = vim.v.lnum, data.left, data.right
    local s = n == l and (n == r and '* ' or '< ') or n == r and '> ' or ''
    -- `:h 'statusline'` 구문을 통한 명시적 하이라이팅 필요
    return '%#MiniCmdlinePeekSign#' .. s
  end
  ```

참고:

- 미리보기 창은 현재 버퍼를 직접 보여주므로 모든 extmark, 가상 텍스트, 가상 줄 등도 표시됩니다.

- 가상 줄이 있는 경우 0이 아닌 컨텍스트는 안정적으로 작동하지 않을 수 있습니다.

- 미리보기를 시도할 때 Visual 선택에서 직접 커맨드 라인 모드로 들어간 경우 Visual 선택을 의도적으로 숨깁니다. `'<,'>` 범위를 미리보는 것은 이미 선택 영역을 시각화합니다. 이 경우에 대해 자동 미리보기를 비활성화하려면 `require('mini.cmdline').setup()`을 실행하기 전에 다음 코드를 추가하세요:

    ```lua
    local disable = vim.schedule_wrap(function()
      local is_from_visual = vim.startswith(vim.fn.getcmdline(), "'<,'>")
      MiniCmdline.config.autopeek.enable = not is_from_visual
    end)
    local reenable = function() MiniCmdline.config.autopeek.enable = true end

    vim.api.nvim_create_autocmd('CmdlineEnter', { callback = disable })
    vim.api.nvim_create_autocmd('CmdlineLeave', { callback = reenable })
    ```

---

### default_autocomplete_predicate() {#minicmdline.default_autocomplete_predicate .help-syntax-right-anchor}

<p align="center">`MiniCmdline.default_autocomplete_predicate`(<span class="help-syntax-special">{data}</span>, <span class="help-syntax-special">{opts}</span>)</p>
기본 자동 완성 조건자

#### 매개변수 {#minicmdline.default_autocomplete_predicate-parameters}



<span class="help-syntax-special">{data}</span> `(table)` 입력 자동 완성 데이터. [MiniCmdline.config](mini-cmdline.qmd#minicmdline.config)에 설명된 대로입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 향후 사용을 위해 예약됨.

#### 반환 {#minicmdline.default_autocomplete_predicate-return}


`(boolean)` 커맨드 라인에 아직 문자가 포함되지 않은 경우 `false`, 그렇지 않으면 `true`. 이는 숫자 범위에 대해 자동 미리보기를 더 쉽게 사용할 수 있게 합니다.

---

### default_autocorrect_func() {#minicmdline.default_autocorrect_func .help-syntax-right-anchor}

<p align="center">`MiniCmdline.default_autocorrect_func`(<span class="help-syntax-special">{data}</span>, <span class="help-syntax-special">{opts}</span>)</p>
기본 자동 수정 함수


- `opts.strict_type=true`이고 입력 `type`이 적절하지 않은 경우 입력 단어를 반환합니다.

- `opts.get_candidates()`를 통해 후보를 가져옵니다. 기본값: 주로 빈 패턴과 입력 `type`을 사용한 [getcompletion()](https://neovim.io/doc/user/helptag.html?tag=getcompletion\(\)). `help` 및 `option` 유형은 예외이며, 둘 다 각자의 방식으로 사용 가능한 모든 후보를 나열합니다.

- 다메라우-레벤슈타인 거리(Damerau–Levenshtein distance, 한 단어를 다른 단어로 변환하는 데 필요한 삭제/삽입/교체/전치 횟수가 가장 적은 단어, 전치를 약간 선호함)가 가장 짧은 후보를 선택합니다. 참고 사항:

    - 유형 `'command'`는 또한 모든 유효한 후보 약어 중에서 선택합니다.

    - 대소문자를 구분하는 경우와 무시하는 경우 모두에 대해 비교가 수행됩니다.

#### 매개변수 {#minicmdline.default_autocorrect_func-parameters}



<span class="help-syntax-special">{data}</span> `(table)` 입력 자동 수정 데이터. [MiniCmdline.config](mini-cmdline.qmd#minicmdline.config)에 설명된 대로입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<strict_type\></span> `(boolean)` - 고정된 후보 세트에서 단어를 가져와야 하는 유형(명령 또는 옵션 이름 등)으로만 출력을 제한할지 여부. 참고: [:help](https://neovim.io/doc/user/helptag.html?tag=:help)는 이미 오타를 처리하는 "정교한 알고리즘"을 가지고 있으므로 `help` 유형은 포함하지 않습니다. 기본값: `true`.

  - <span class="help-syntax-keys">\<get_candidates\></span> `(function)` - 후보의 소스. `data`를 인수로 사용하여 호출되며 선택할 수 있는 문자열 후보 배열을 반환해야 합니다. 기본값: 대부분의 유형에 대해 - 빈 패턴과 입력 `type`을 사용한 [getcompletion()](https://neovim.io/doc/user/helptag.html?tag=getcompletion\(\)); `help` 및 `option` 유형의 경우 - 각각 사용 가능한 모든 도움말 태그 및 옵션 이름(길고 짧은 이름).

#### 반환 {#minicmdline.default_autocorrect_func-return}


`(string)` 자동 수정된 단어.

---

### default_autopeek_predicate() {#minicmdline.default_autopeek_predicate .help-syntax-right-anchor}

<p align="center">`MiniCmdline.default_autopeek_predicate`(<span class="help-syntax-special">{data}</span>, <span class="help-syntax-special">{opts}</span>)</p>
기본 자동 미리보기 조건자

#### 매개변수 {#minicmdline.default_autopeek_predicate-parameters}



<span class="help-syntax-special">{data}</span> `(table)` 입력 자동 미리보기 데이터. [MiniCmdline.config](mini-cmdline.qmd#minicmdline.config)에 설명된 대로입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 향후 사용을 위해 예약됨.

#### 반환 {#minicmdline.default_autopeek_predicate-return}


`(boolean)` 명령이 [:command-preview](https://neovim.io/doc/user/helptag.html?tag=:command-preview)를 정의하면 `false`, 그렇지 않으면 `true`. 이는 특히 ['inccommand'](https://neovim.io/doc/user/helptag.html?tag='inccommand')가 `split`으로 설정된 경우 [:substitute](https://neovim.io/doc/user/helptag.html?tag=:substitute)와 같은 명령에 대해 자동 미리보기를 더 쉽게 사용할 수 있게 합니다.

---

### default_autopeek_statuscolumn() {#minicmdline.default_autopeek_statuscolumn .help-syntax-right-anchor}

<p align="center">`MiniCmdline.default_autopeek_statuscolumn`(<span class="help-syntax-special">{data}</span>, <span class="help-syntax-special">{opts}</span>)</p>
기본 자동 미리보기 statuscolumn


- 미리 본 범위와의 관계에 따라 줄 옆에 기호를 표시합니다. `MiniCmdlinePeekSign` 그룹으로 하이라이트됩니다.

- 범위의 왼쪽 및 오른쪽 부분에 대한 줄 번호를 표시합니다. `MiniCmdlinePeekLineNr` 그룹으로 하이라이트됩니다.

- 전용 구분 문자로 statuscolumn과 버퍼 텍스트를 분리합니다. `MiniCmdlinePeekSep` 그룹으로 하이라이트됩니다.

참고 사항:

- 출력을 계산하기 위해 [v:lnum](https://neovim.io/doc/user/helptag.html?tag=v:lnum) 및 [v:virtnum](https://neovim.io/doc/user/helptag.html?tag=v:virtnum)을 사용하므로 ['statuscolumn'](https://neovim.io/doc/user/helptag.html?tag='statuscolumn') 함수의 일부로만 사용하도록 설계되었습니다.

`mid` 기호를 조정하는 예시:

  ```lua
  local peek_stc_opts = { signs = { mid = '+' } }
  local peek_stc = function(data)
    return MiniCmdline.default_autopeek_statuscolumn(data, peek_stc_opts)
  end
  require('mini.cmdline').setup({
    autopeek = { window = { statuscolumn = peek_stc } },
  })
  ```

#### 매개변수 {#minicmdline.default_autopeek_statuscolumn-parameters}



<span class="help-syntax-special">{data}</span> `(table)` 입력 미리보기 데이터. [MiniCmdline.config](mini-cmdline.qmd#minicmdline.config)에 설명된 대로입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<signs\></span> `(table)` - 표시할 기호. 가능한 필드:

      - <span class="help-syntax-keys">\<same\></span> `(string)` - `left=right`인 범위에서. 기본값: `'🭬'`.

      - <span class="help-syntax-keys">\<left\></span> `(string)`  - `left` 줄에서. 기본값: `'┌'`.

      - <span class="help-syntax-keys">\<mid\></span> `(string)`   - 범위 내부에서. 기본값: `'┊'`.

      - <span class="help-syntax-keys">\<right\></span> `(string)` - `right` 줄에서. 기본값: `'└'`.

      - <span class="help-syntax-keys">\<out\></span> `(string)` - 범위 외부에서. 기본값: `''` (기호 없음).

      - <span class="help-syntax-keys">\<virt\></span> `(string)` - 가상 줄. 기본값: `'•'`.

      - <span class="help-syntax-keys">\<wrap\></span> `(string)` - 줄 바꿈된 줄. 기본값: `'↳'`.

  - <span class="help-syntax-keys">\<sep\></span> `(string)` - statuscolumn과 버퍼 텍스트를 구분하기 위해 끝에 배치할 문자열. 기본값: `'│'`

  참고: 모든 기호와 구분 기호는 ['statuscolumn'](https://neovim.io/doc/user/helptag.html?tag='statuscolumn')에서의 특별한 의미 때문에 모든 `%`를 `%%`로 이스케이프해야 합니다.

