---
title: "mini.operators 문서"
---

_'mini.nvim'의 `main` 브랜치에서 생성됨_

<a name="mini.operators" href="mini-operators.qmd#mini.operators"><b>mini.operators</b></a> 텍스트 편집 오퍼레이터

MIT 라이선스 Copyright (c) 2023 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:

- 오퍼레이터:

    - 텍스트를 평가(evaluate)하고 그 출력으로 교체합니다.

    - 텍스트 영역을 교환(exchange)합니다.

    - 텍스트를 배가(multiply, 복제)합니다.

    - 레지스터의 내용으로 텍스트를 교체(replace)합니다.

    - 텍스트를 정렬(sort)합니다.


- 텍스트 오브젝트, 줄, 선택 영역에 대해 작동하도록 구성 가능한 자동 매핑을 제공합니다.
  [MiniOperators.make\_mappings()](mini-operators.qmd#minioperators.make_mappings)를 사용하여 더 세밀하게 제어하거나 비활성화할 수 있습니다.


- 모든 오퍼레이터는 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])와 점 반복(dot-repeat)을 지원합니다.

자세한 내용은 [MiniOperators-overview](mini-operators.qmd#minioperators-overview) 및 [MiniOperators.config](mini-operators.qmd#minioperators.config)를 참조하세요.

#### 설정 {#module-setup}


이 모듈은 `require('mini.operators').setup({})`으로 설정이 필요합니다 (`{}`를 사용자 `config` 테이블로 교체하세요). 이는 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniOperators`를 생성합니다 (`:lua MiniOperators.*`로 사용 가능).

사용 가능한 설정은 [MiniOperators.config](mini-operators.qmd#minioperators.config)를 참조하세요.

런타임 설정(`config.mappings` 제외)을 `vim.b.minioperators_config`를 사용하여 버퍼별로 재정의할 수 있으며, 이는 `MiniOperators.config`와 동일한 구조여야 합니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

#### 비교 {#module-comparisons}



- [gbprod/substitute.nvim](https://github.com/gbprod/substitute.nvim):

    - "replace" 및 "exchange" 변형을 제공하지만, 이 모듈의 다른 기능은 제공하지 않습니다.

    - 범위에 대한 "replace/substitute" 기능을 제공하지만, 이 모듈은 설계상 이를 제공하지 않습니다 (이는 [:s](https://neovim.io/doc/user/helptag.html?tag=:s) 기능과 유사하면서도 정신적 복잡성을 크게 낮추지 않기 때문입니다).

    - "Replace"는 붙여넣은 텍스트를 강조하지만, 이 모듈은 그렇지 않습니다.

    - "Exchange"는 버퍼 간에 작동하지 않지만, 이 모듈은 작동합니다.


- [svermeulen/vim-subversive](https://github.com/svermeulen/vim-subversive):

    - "replace" 기능의 주요 영감이 되었으므로 이 오퍼레이터에 대해서는 대부분 유사합니다.

    - 범위에 대한 "replace/substitute" 기능을 제공하지만, 이 모듈은 설계상 이를 제공하지 않습니다.


- [tommcdo/vim-exchange](https://github.com/tommcdo/vim-exchange):

    - "exchange" 기능의 주요 영감이 되었으므로 이 오퍼레이터에 대해서는 대부분 유사합니다.

    - 버퍼 간에 작동하지 않지만, 이 모듈은 작동합니다.


- [christoomey/vim-sort-motion](https://github.com/christoomey/vim-sort-motion):

    - 줄 단위 정렬에 [:sort](https://neovim.io/doc/user/helptag.html?tag=:sort)를 사용하는 반면, 이 모듈은 일관된 정렬 알고리즘을 사용합니다 (기본값은 [MiniOperators.default\_sort\_func()](mini-operators.qmd#minioperators.default_sort_func) 참조).

    - 정렬 알고리즘을 사용자 정의할 수 없지만, 이 모듈은 가능합니다 ([MiniOperators.config](mini-operators.qmd#minioperators.config)의 `sort.func` 참조).

    - 문자 단위 영역에 대해 쉼표만 구분자로 사용하지만, 이 모듈은 세미콜론이나 공백으로도 구분할 수 있습니다 (기본값은 [MiniOperators.default\_sort\_func()](mini-operators.qmd#minioperators.default_sort_func) 참조).

#### 하이라이트 그룹 {#module-highlightgroups}



- `MiniOperatorsExchangeFrom` - 교환할 첫 번째 영역.

하이라이트 그룹을 변경하려면 [nvim\_set\_hl()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_hl\(\))을 사용하여 직접 설정하세요.

#### 비활성화 {#module-disabling}


주요 기능을 비활성화하려면 `vim.g.minioperators_disable`(전역) 또는 `vim.b.minioperators_disable`(버퍼별)을 `true`로 설정하세요. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈 기능 비활성화를 위한 정확한 규칙 작성은 사용자의 몫으로 남겨둡니다. 일반적인 방법은 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### 개요 {#minioperators-overview .help-syntax-right-anchor}

오퍼레이터는 ([d](https://neovim.io/doc/user/helptag.html?tag=d), [c](https://neovim.io/doc/user/helptag.html?tag=c) 등과 유사하게) 텍스트 오브젝트, 모션 또는 비주얼 선택 영역에 대해 수행될 동작을 정의합니다. 필요한 경우 제공된 레지스터도 존중할 수 있습니다 ("replace" 오퍼레이터와 같이).

이 모듈은 각 오퍼레이터를 별도의 전용 함수로 구현합니다 (예: "replace" 오퍼레이터의 경우 [MiniOperators.replace()](mini-operators.qmd#minioperators.replace)). 각 함수는 `mode`를 인수로 받아 그에 따라 동작합니다.


- `mode`가 `nil`인 경우(또는 명시적으로 제공되지 않은 경우), ['operatorfunc'](https://neovim.io/doc/user/helptag.html?tag='operatorfunc')를 이 전용 함수로 설정하고 표현식 매핑에서 호출된 것으로 가정하여 `g@`를 반환합니다. 자세한 내용은 [:map-operator](https://neovim.io/doc/user/helptag.html?tag=:map-operator) 및 [:map-expression](https://neovim.io/doc/user/helptag.html?tag=:map-expression)을 참조하세요.


- `mode`가 "char", "line" 또는 "block"인 경우, `operatorfunc`로 동작하며 [`[](https://neovim.io/doc/user/helptag.html?tag=`[) 및 |`]| 마크 사이의 영역에 대해 동작을 수행합니다.


- `mode`가 "visual"인 경우, [`<](https://neovim.io/doc/user/helptag.html?tag=`<) 및 |`>| 마크 사이의 영역에 대해 동작을 수행합니다.

특정 오퍼레이터에 대한 자세한 내용은 해당 함수 도움말을 참조하세요.


- 평가 (Evaluate): [MiniOperators.evaluate()](mini-operators.qmd#minioperators.evaluate)

- 교환 (Exchange): [MiniOperators.exchange()](mini-operators.qmd#minioperators.exchange)

- 배가 (Multiply): [MiniOperators.multiply()](mini-operators.qmd#minioperators.multiply)

- 교체 (Replace):  [MiniOperators.replace()](mini-operators.qmd#minioperators.replace)

- 정렬 (Sort):     [MiniOperators.sort()](mini-operators.qmd#minioperators.sort)

#### 매핑 {#minioperators-overview-mappings}


<a name="minioperators-mappings" href="mini-operators.qmd#minioperators-mappings"><b>MiniOperators-mappings</b></a>

모든 오퍼레이터는 [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 실행 중에 자동으로 매핑됩니다. 매핑 키는 해당 `config` 항목의 `prefix` 필드에서 유추됩니다. 모든 내장 충돌 매핑은 제거됩니다 (Neovim>=0.11의 [gra](https://neovim.io/doc/user/helptag.html?tag=gra), [grn](https://neovim.io/doc/user/helptag.html?tag=grn) 등). [gx](https://neovim.io/doc/user/helptag.html?tag=gx) 및 [v\_gx](https://neovim.io/doc/user/helptag.html?tag=v_gx)는 모두 `gX`로 재매핑됩니다 (이미 사용 중이 아닌 경우).

각 오퍼레이터에 대해 다음 매핑이 생성됩니다.


- 일반 모드에서 텍스트 오브젝트에 대해 작동. `prefix`를 직접 사용합니다.

- 일반 모드에서 줄에 대해 작동. `prefix`에 마지막 문자를 추가합니다. 이는 [operator-doubled](https://neovim.io/doc/user/helptag.html?tag=operator-doubled) 및 [guu](https://neovim.io/doc/user/helptag.html?tag=guu), [gUU](https://neovim.io/doc/user/helptag.html?tag=gUU)와 같이 세 글자 이상의 오퍼레이터에 대해 확립된 패턴과 일치합니다.

- 비주얼 모드에서 비주얼 선택 영역에 대해 작동. `prefix`를 직접 사용합니다.

"replace"의 기본 매핑 예시:

- 일반 모드에서 텍스트 오브젝트에 작동하는 `gr`.
  사용 예: `griw`는 "inner word"를 기본 레지스터로 교체합니다.

- 일반 모드에서 줄에 작동하는 `grr`.
  사용 예: `grr`은 현재 줄을 교체합니다.

- 비주얼 모드에서 비주얼 선택 영역에 작동하는 `gr`.
  사용 예: `viw`로 "inner word"를 선택하고 `gr`로 교체합니다.

매핑을 사용자 정의하는 두 가지 제안된 방법:


- [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 호출 시 `prefix`를 변경합니다. 예를 들어, 다음과 같이 하면:

    ```lua
    require('mini.operators').setup({ replace = { prefix = 'cr' } })
    ```

  매핑이 `gr` / `grr` / `gr` 대신 `cr` / `crr` / `cr`이 됩니다.


- 접두사로 빈 문자열을 제공하여 자동 매핑 생성을 비활성화하고 [MiniOperators.make\_mappings()](mini-operators.qmd#minioperators.make_mappings)를 직접 사용합니다. 예를 들어:

    ```lua
    -- "replace"의 자동 생성 비활성화
    local operators = require('mini.operators')
    operators.setup({ replace = { prefix = '' } })

    -- 사용자 정의 매핑 만들기
    operators.make_mappings(
      'replace',
      { textobject = 'cr', line = 'crr', selection = 'cr' }
    )
    ```

---

### setup() {#minioperators.setup .help-syntax-right-anchor}

<p align="center">`MiniOperators.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minioperators.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniOperators.config](mini-operators.qmd#minioperators.config)를 참조하세요.

#### 사용법 {#minioperators.setup-usage}



  ```lua
  require('mini.operators').setup() -- 기본 설정 사용
  -- 또는
  require('mini.operators').setup({}) -- {}를 사용자 설정 테이블로 교체
  ```

---

### config {#minioperators.config .help-syntax-right-anchor}

<p align="center">`MiniOperators.config`</p>
#### 기본값 {#minioperators.config-defaults}



  ```lua
  MiniOperators.config = {
    -- 각 항목은 하나의 오퍼레이터를 설정합니다.
    -- `prefix`는 `setup()` 중에 매핑되는 키를 정의합니다.
    -- 일반 모드에서는 텍스트 오브젝트와 줄에 대해, 비주얼 모드에서는 선택 영역에 대해 작동합니다.

    -- 텍스트를 평가하고 그 출력으로 교체
    evaluate = {
      prefix = 'g=',

      -- 평가를 수행하는 함수
      func = nil,
    },

    -- 텍스트 영역 교환
    exchange = {
      -- 참고: 기본 `gx`는 `gX`로 재매핑됩니다.
      prefix = 'gx',

      -- 새 텍스트를 이전 들여쓰기에 맞게 다시 들여쓸지 여부
      reindent_linewise = true,
    },

    -- 텍스트 배가 (복제)
    multiply = {
      prefix = 'gm',

      -- 복제 전 텍스트를 수정할 수 있는 함수
      func = nil,
    },

    -- 레지스터의 내용으로 텍스트 교체
    replace = {
      -- 참고: 기본 `gr*` LSP 매핑은 제거됩니다.
      prefix = 'gr',

      -- 새 텍스트를 이전 들여쓰기에 맞게 다시 들여쓸지 여부
      reindent_linewise = true,
    },

    -- 텍스트 정렬
    sort = {
      prefix = 'gs',

      -- 정렬을 수행하는 함수
      func = nil,
    }
  }
  ```

#### 평가 (Evaluate) {#minioperators.config-evaluate}


`evaluate.prefix`는 [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 중에 오퍼레이터 매핑 키를 자동으로 유추하는 데 사용되는 문자열입니다. [MiniOperators-mappings](mini-operators.qmd#minioperators-mappings)를 참조하세요.

`evaluate.func`는 텍스트 영역을 실제로 평가하는 데 사용되는 함수입니다. `nil`(기본값)인 경우 [MiniOperators.default\_evaluate\_func()](mini-operators.qmd#minioperators.default_evaluate_func)가 사용됩니다.

이 함수는 선택된 텍스트를 나타내는 콘텐츠 테이블을 입력으로 받고, 출력으로 줄 배열(한 항목당 한 줄)을 반환해야 합니다. 콘텐츠 테이블에는 영역 줄들의 배열인 `lines`와 문자 단위, 줄 단위, 블록 단위에 따라 `v`, `V`, `\22`(이스케이프된 `<C-v>`) 중 하나인 `submode` 필드가 있습니다.

언어별로 평가를 사용자 정의하려면 버퍼별 설정(`vim.b.minioperators_config`)에서 `evaluate.func`를 설정하세요. [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

#### 교환 (Exchange) {#minioperators.config-exchange}


`exchange.prefix`는 [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 중에 오퍼레이터 매핑 키를 자동으로 유추하는 데 사용되는 문자열입니다. [MiniOperators-mappings](mini-operators.qmd#minioperators-mappings)를 참조하세요.

참고: 기본값 "gx"는 [gx](https://neovim.io/doc/user/helptag.html?tag=gx) / [v\_gx](https://neovim.io/doc/user/helptag.html?tag=v_gx)를 덮어씁니다. 대신 이들은 `gX`로 재매핑됩니다 (이미 사용 중이 아닌 경우). 내장 기능(커서 위치의 URL 열기)과 함께 `gx`를 계속 사용하려면 다른 `config.prefix`를 선택하세요.

`exchange.reindent_linewise`는 새로 놓인 줄 단위 텍스트가 교체된 텍스트의 들여쓰기를 유지해야 하는지 여부를 나타내는 불리언 값입니다. 즉, `false`인 경우 영역들이 들여쓰기를 유지한 채 교환되고, `true`인 경우 그렇지 않습니다.

#### 배가 (Multiply) {#minioperators.config-multiply}


`multiply.prefix`는 [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 중에 오퍼레이터 매핑 키를 자동으로 유추하는 데 사용되는 문자열입니다. [MiniOperators-mappings](mini-operators.qmd#minioperators-mappings)를 참조하세요.

`multiply.func`는 선택적으로 복제된 텍스트를 업데이트하는 데 사용되는 함수입니다. `nil`(기본값)인 경우 텍스트가 그대로 사용됩니다.

콘텐츠 테이블을 입력으로 받고( "Evaluate" 섹션 참조), 출력으로 줄 배열을 반환해야 합니다.

#### 교체 (Replace) {#minioperators.config-replace}


`replace.prefix`는 [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 중에 오퍼레이터 매핑 키를 자동으로 유추하는 데 사용되는 문자열입니다. [MiniOperators-mappings](mini-operators.qmd#minioperators-mappings)를 참조하세요.

`replace.reindent_linewise`는 새로 놓인 줄 단위 텍스트가 교체된 텍스트의 들여쓰기를 유지해야 하는지 여부를 나타내는 불리언 값입니다.

#### 정렬 (Sort) {#minioperators.config-sort}


`sort.prefix`는 [MiniOperators.setup()](mini-operators.qmd#minioperators.setup) 중에 오퍼레이터 매핑 키를 자동으로 유추하는 데 사용되는 문자열입니다. [MiniOperators-mappings](mini-operators.qmd#minioperators-mappings)를 참조하세요.

`sort.func`는 텍스트 영역을 실제로 정렬하는 데 사용되는 함수입니다. `nil`(기본값)인 경우 [MiniOperators.default\_sort\_func()](mini-operators.qmd#minioperators.default_sort_func)가 사용됩니다.

콘텐츠 테이블을 입력으로 받고( "Evaluate" 섹션 참조), 출력으로 줄 배열을 반환해야 합니다.

문자 단위 영역에 대해 사용자에게 사용자 정의 구분자를 묻는 `sort.func` 예시:

  ```lua
  local sort_func = function(content)
    local opts = {}
    if content.submode == 'v' then
      -- 구분자를 있는 그대로(Lua 패턴이 아님) 처리하도록 요청
      local delimiter = vim.fn.input('정렬 구분자: ')
      -- 주변 공백을 분할의 일부로 처리
      opts.split_patterns = { '%s*' .. vim.pesc(delimiter) .. '%s*' }
    end
    return MiniOperators.default_sort_func(content, opts)
  end

  require('mini.operators').setup({ sort = { func = sort_func } })
  ```

---

### evaluate() {#minioperators.evaluate .help-syntax-right-anchor}

<p align="center">`MiniOperators.evaluate`(<span class="help-syntax-special">{mode}</span>)</p>
텍스트를 평가하고 그 출력으로 교체

영역을 `config.evaluate.func`의 출력으로 교체합니다. 기본적으로는 영역 서브모드에 따라 텍스트를 Lua 코드로 평가하는 [MiniOperators.default\_evaluate\_func()](mini-operators.qmd#minioperators.default_evaluate_func)입니다.

#### 매개변수 {#minioperators.evaluate-parameters}



<span class="help-syntax-special">{mode}</span> `(string|nil)` `nil`, `'char'`, `'line'`, `'block'`, `'visual'` 중 하나.

---

### exchange() {#minioperators.exchange .help-syntax-right-anchor}

<p align="center">`MiniOperators.exchange`(<span class="help-syntax-special">{mode}</span>)</p>
텍스트 영역 교환

2단계 로직을 갖습니다.

- 첫 번째 호출은 영역을 교환할 영역으로 기억하고 `MiniOperatorsExchangeFrom` 하이라이트 그룹으로 강조합니다.

- 두 번째 호출은 교환을 수행합니다. 기본적으로 "두 영역 모두 얀크(yank)"하고 각각을 서로 교체하는 두 단계의 동작입니다.

참고:

- 첫 번째 단계 후 교환을 중지하려면 `<C-c>`를 사용하세요.


- 교환되는 영역은 서로 다른 (문자, 줄, 블록) 단위 서브모드를 가질 수 있습니다.


- 대부분의 겹치는 영역 사례에서 작동하지만, 공식적으로 지원되지는 않습니다.

#### 매개변수 {#minioperators.exchange-parameters}



<span class="help-syntax-special">{mode}</span> `(string|nil)` `nil`, `'char'`, `'line'`, `'block'`, `'visual'` 중 하나.

---

### multiply() {#minioperators.multiply .help-syntax-right-anchor}

<p align="center">`MiniOperators.multiply`(<span class="help-syntax-special">{mode}</span>)</p>
텍스트 배가 (복제)

영역을 (레지스터에 영향을 주지 않고) 복사하여 바로 뒤에 놓습니다.

참고:

- 두 가지 유형의 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])를 지원합니다. 기본 `config.multiply.prefix`를 사용하는 `[count1]gm[count2][textobject]`는 `[count2][textobject]`에 의해 정의된 영역의 `[count1]`개 복사본을 만듭니다. 예: `2gm3aw` - `3aw`의 복사본 2개.


- "line" 매핑(기본적으로 `gmm`)에 대한 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])는 이전 참고의 `[count1]`으로 처리됩니다.


- "얀크(yank)" + "붙여넣기(paste)" 대신 이것을 사용하는 장점:

   - 어떤 레지스터도 수정하지 않는 반면, 별도의 단계는 복제된 텍스트를 보관할 레지스터가 필요합니다.

   - 대부분의 경우 별도의 단계는 "얀크" + "커서 이동" + "붙여넣기"가 되겠지만, "multiply"는 이를 한 번에 수행합니다.

#### 매개변수 {#minioperators.multiply-parameters}



<span class="help-syntax-special">{mode}</span> `(string|nil)` `nil`, `'char'`, `'line'`, `'block'`, `'visual'` 중 하나.

---

### replace() {#minioperators.replace .help-syntax-right-anchor}

<p align="center">`MiniOperators.replace`(<span class="help-syntax-special">{mode}</span>)</p>
레지스터의 내용으로 텍스트 교체

참고:

- 두 가지 유형의 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])를 지원합니다. 기본 `config.replace.prefix`를 사용하는 `[count1]gr[count2][textobject]`는 `[count2][textobject]`에 의해 정의된 영역 위에 레지스터 내용을 `[count1]`개 놓습니다. 예: `2gr3aw` - `3aw` 위에 레지스터 내용 2개.


- "line" 매핑(기본적으로 `grr`)에 대한 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])는 이전 참고의 `[count1]`으로 처리됩니다.


- "비주얼 선택" + "[v\_P](https://neovim.io/doc/user/helptag.html?tag=v_P)로 붙여넣기" 대신 이것을 사용하는 장점:

   - 오퍼레이터로서 점 반복이 가능하므로 여러 번 교체해야 하는 경우 누적 이득이 있습니다.

   - 자동으로 들여쓰기를 다시 조정할 수 있습니다.

#### 매개변수 {#minioperators.replace-parameters}



<span class="help-syntax-special">{mode}</span> `(string|nil)` `nil`, `'char'`, `'line'`, `'block'`, `'visual'` 중 하나.

---

### sort() {#minioperators.sort .help-syntax-right-anchor}

<p align="center">`MiniOperators.sort`(<span class="help-syntax-special">{mode}</span>)</p>
텍스트 정렬

영역을 `config.sort.func`의 출력으로 교체합니다. 기본적으로는 서브모드에 따라 텍스트를 정렬하는 [MiniOperators.default\_sort\_func()](mini-operators.qmd#minioperators.default_sort_func)입니다.

참고:

- "line" 매핑은 문자 단위입니다 (한 줄을 줄 단위로 정렬하는 것은 별 의미가 없기 때문입니다). 이로 인해 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])도 지원되지 않습니다.

#### 매개변수 {#minioperators.sort-parameters}



<span class="help-syntax-special">{mode}</span> `(string|nil)` `nil`, `'char'`, `'line'`, `'block'`, `'visual'` 중 하나.

---

### make_mappings() {#minioperators.make_mappings .help-syntax-right-anchor}

<p align="center">`MiniOperators.make_mappings`(<span class="help-syntax-special">{operator_name}</span>, <span class="help-syntax-special">{lhs_tbl}</span>)</p>
오퍼레이터 매핑 만들기

#### 매개변수 {#minioperators.make_mappings-parameters}



<span class="help-syntax-special">{operator_name}</span> `(string)` 이 모듈의 기존 오퍼레이터 이름.

<span class="help-syntax-special">{lhs_tbl}</span> `(table)` 매핑 키 테이블. 다음 필드들이 있어야 합니다.

  - <span class="help-syntax-keys">\<textobject\></span> `(string)` - 텍스트 오브젝트에 대해 작동하는 일반 모드 매핑.

  - <span class="help-syntax-keys">\<line\></span> `(string)` - 줄에 대해 작동하는 일반 모드 매핑. 보통 텍스트 오브젝트 매핑 뒤에 [\_](https://neovim.io/doc/user/helptag.html?tag=_)가 붙는 별칭입니다. "sort"의 경우 줄 전체에 대해 좌우 공백 없이 문자 단위로 작동합니다 (한 줄을 줄 단위로 정렬하는 것은 의미가 없기 때문입니다).

  - <span class="help-syntax-keys">\<selection\></span> `(string)` - 선택 영역에 대해 작동하는 비주얼 모드 매핑.

  특정 매핑을 만들지 않으려면 빈 문자열을 제공하세요. 참고: `line` 매핑을 만들려면 `textobject` 매핑이 설정되어 있어야 합니다.

#### 사용법 {#minioperators.make_mappings-usage}



  ```lua
  require('mini.operators').make_mappings(
    'replace',
    { textobject = 'cr', line = 'crr', selection = 'cr' }
  )
  ```

---

### default_evaluate_func() {#minioperators.default_evaluate_func .help-syntax-right-anchor}

<p align="center">`MiniOperators.default_evaluate_func`(<span class="help-syntax-special">{content}</span>)</p>
기본 평가 함수

텍스트를 Lua 코드로 평가하고 마지막 줄의 객체를 반환합니다 (마지막 줄에 `return`이 없는 경우 앞에 붙인 것과 같습니다).

동작은 영역 서브모드에 따라 달라집니다.


- 문자 단위 및 줄 단위 영역의 경우, 텍스트가 그대로 평가됩니다.


- 블록 단위 영역의 경우, 줄별로 평가되며 출력의 첫 번째 줄만 사용합니다. 이를 통해 줄 단위 영역과 비교하여 다른 동작을 줄 수 있도록 줄별 실행이 가능합니다.

#### 매개변수 {#minioperators.default_evaluate_func-parameters}



<span class="help-syntax-special">{content}</span> `(table)` 다음 필드를 포함하는 테이블.

  - <span class="help-syntax-keys">\<lines\></span> `(table)` - 콘텐츠 줄 배열.

  - <span class="help-syntax-keys">\<submode\></span> `(string)` - 영역 서브모드. `'v'`, `'V'`, `'<C-v>'`(이스케이프됨) 중 하나.

---

### default_sort_func() {#minioperators.default_sort_func .help-syntax-right-anchor}

<p align="center">`MiniOperators.default_sort_func`(<span class="help-syntax-special">{content}</span>, <span class="help-syntax-special">{opts}</span>)</p>
기본 정렬 함수

영역 서브모드에 따라 텍스트를 정렬합니다.


- 문자 단위 영역의 경우, 구분자 패턴으로 분할하고 각 부분을 정렬한 후 구분자와 함께 다시 합칩니다. 실제 패턴은 `opts.split_patterns` 배열의 패턴을 기반으로 유추됩니다. 텍스트에 존재하는 요소 중 가장 먼저 나타나는 패턴을 우선적으로 사용합니다.
  예: 기본 `opts.split_patterns`로 "c, b; a" 줄을 정렬하면 쉼표로만 분할되므로 "b; a, c"가 됩니다.


- 줄 단위 및 블록 단위 영역의 경우 줄을 있는 그대로 정렬합니다.

참고:

- 정렬은 줄 배열에 대해 [table.sort()](https://neovim.io/doc/user/helptag.html?tag=table.sort\(\))로 수행되며, 공백이나 숫자를 특별하게 처리하지 않습니다. 더 복잡한 작업에는 [:sort](https://neovim.io/doc/user/helptag.html?tag=:sort)를 사용하세요.


- 패턴은 빈 문자열일 수 있으며, 이 경우 모든 문자를 부분으로 분할합니다.


- `split_patterns`의 패턴에 `%s*`를 추가하여 구분자에 공백을 포함시키세요.
  예: "_" 패턴을 사용한 "b _ a" 줄은 " a_b "(각 부분이 "b ", "_", " a"로 분할되기 때문)로 정렬되는 반면, "%s_%s" 패턴을 사용하면 "a _ b"("b", " _ ", "a"로 분할됨)가 됩니다.

#### 매개변수 {#minioperators.default_sort_func-parameters}



<span class="help-syntax-special">{content}</span> `(table)` 다음 필드를 포함하는 테이블.

  - <span class="help-syntax-keys">\<lines\></span> `(table)` - 콘텐츠 줄 배열.

  - <span class="help-syntax-keys">\<submode\></span> `(string)` - 영역 서브모드. `'v'`, `'V'`, `'<C-v>'`(이스케이프됨) 중 하나.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<compare_fun\></span> `(function)` - [table.sort()](https://neovim.io/doc/user/helptag.html?tag=table.sort\(\))와 호환되는 비교 함수. 기본값: `<`를 사용한 직접 비교.

  - <span class="help-syntax-keys">\<split_patterns\></span> `(table)` - 문자 단위 서브모드에 사용될 분할 Lua 패턴 배열. 순서가 중요합니다. 기본값: `{ '%s*,%s*', '%s*;%s*', '%s+', '' }`.
