---
title: "mini.diff 문서"
---

_이 문서는 'mini.nvim'의 `main` 브랜치에서 생성되었습니다._

<a name="mini.diff" href="mini-diff.qmd#mini.diff"><b>mini.diff</b></a> 디프 헝크(hunk) 작업

MIT 라이선스 Copyright (c) 2024 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:


- 버퍼 텍스트와 설정 가능한 참조 간의 차이점을 대화형으로 시각화합니다 (입력하는 동안 업데이트됨). 이는 추가, 변경 또는 삭제된 차이점 부분(헝크라고 함) 내에 있는지 여부를 줄 단위로 보여줌으로써 수행됩니다. 시각화는 사용자 정의 가능한 색상 기호나 줄 번호를 사용할 수 있습니다.


- 텍스트 영역 내부에 더 많은 헝크 세부 정보가 있는 특별한 토글 가능 오버레이 뷰. [MiniDiff.toggle\_overlay()](mini-diff.qmd#minidiff.toggle_overlay)를 참조하세요.


- 최신 상태를 유지하고 상호 작용을 정의하는 데 사용되는 참조 텍스트의 버퍼별 소스를 완전히 구성할 수 있습니다. 순서대로 연결을 시도하는 소스 배열일 수 있습니다. [MiniDiff-소스 사양](mini-diff.qmd#minidiff-source-specification)을 참조하세요. 기본적으로 Git 소스를 사용합니다. [MiniDiff.gen\_source.git()](mini-diff.qmd#minidiff.gen_source.git)을 참조하세요.


- 디프 헝크를 관리하기 위한 구성 가능한 매핑:

    - 영역 내의 헝크를 적용하거나 리셋합니다 (비주얼 선택 또는 점 반복 가능한 오퍼레이터 사용).

    - 오퍼레이터 대상으로 사용할 수 있는 "커서 아래의 헝크 범위" 텍스트 오브젝트.

    - 처음/이전/다음/마지막 헝크로 이동. [MiniDiff.goto\_hunk()](mini-diff.qmd#minidiff.goto_hunk)를 참조하세요.

하지 않는 것:


- (기본) Git 소스를 사용하여 헝크를 시각화하고 스테이징(적용)하는 것 외에 Git과 직접 작업하는 기능은 제공하지 않습니다. 특히 헝크 스테이징 취소는 지원되지 않습니다. [MiniDiff.gen\_source.git()](mini-diff.qmd#minidiff.gen_source.git)을 참조하세요.

세부 정보 소스:

- [MiniDiff-개요](mini-diff.qmd#minidiff-overview)

- [MiniDiff-소스 사양](mini-diff.qmd#minidiff-source-specification)

- [MiniDiff-헝크 사양](mini-diff.qmd#minidiff-hunk-specification)

- [MiniDiff-디프 요약](mini-diff.qmd#minidiff-diff-summary)

#### 설정 {#module-setup}


이 모듈은 `require('mini.diff').setup({})`으로 설정이 필요합니다 (`{}`를 `config` 테이블로 교체하세요). 이는 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniDiff`를 생성합니다 (예: `:lua MiniDiff.*`).

`config` 구조와 기본값은 [MiniDiff.config](mini-diff.qmd#minidiff.config)를 참조하세요.

`MiniDiff.config`와 동일한 구조를 가져야 하는 `vim.b.minidiff_config`를 통해 버퍼 로컬에서 런타임 설정 설정을 재정의할 수 있습니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

#### 비교 {#module-comparisons}



- [lewis6991/gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim):

    - 이 모듈의 주요 영감이 되었으므로 많은 유사점이 있습니다.

    - Git 헝크만 표시할 수 있는 반면, 이 모듈은 확장 가능한 디자인을 가지고 있습니다.

    - 헝크 외의 Git 작업 기능을 더 많이 제공합니다. 이 모듈은 (의도적으로) 그렇지 않습니다.

#### 하이라이트 그룹 {#module-highlightgroups}



- `MiniDiffSignAdd`        - "추가(add)" 헝크 줄 시각화.

- `MiniDiffSignChange`     - "변경(change)" 헝크 줄 시각화.

- `MiniDiffSignDelete`     - "삭제(delete)" 헝크 줄 시각화.

- `MiniDiffOverAdd`        - 오버레이에 표시된 추가된 버퍼 텍스트.

- `MiniDiffOverChange`     - 오버레이에 표시된 변경된 참조 텍스트.

- `MiniDiffOverChangeBuf`  - 오버레이에 표시된 변경된 버퍼 텍스트.

- `MiniDiffOverContext`    - 참조 오버레이에 표시된 변경 컨텍스트.

- `MiniDiffOverContextBuf` - 버퍼 오버레이에 표시된 변경 컨텍스트.

- `MiniDiffOverDelete`     - 오버레이에 표시된 삭제된 참조 텍스트.

하이라이트 그룹을 변경하려면 [nvim\_set\_hl()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_hl\(\))로 직접 설정하세요.

#### 비활성화 {#module-disabling}


[MiniDiff.disable()](mini-diff.qmd#minidiff.disable)에 의존하지 않고 기능을 일시적으로 비활성화하려면 `vim.g.minidiff_disable` (전역) 또는 `vim.b.minidiff_disable` (버퍼용)을 `true`로 설정하세요. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈 기능 비활성화를 위한 정확한 규칙 작성은 사용자의 몫으로 남겨둡니다. 일반적인 레시피는 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### 개요 {#minidiff-overview .help-syntax-right-anchor}

#### 디프와 헝크 {#minidiff-overview-diffsandhunks}


"디프(diff)"(difference의 줄임말)는 두 텍스트 문자열이 서로 어떻게 다른지 계산한 결과입니다. 이는 줄 단위로 수행됩니다. 즉, 목표는 두 파일에 공통적인 줄 시퀀스를 계산하고 그 사이에 흩어져 있는 서로 다른 줄 그룹("헝크"라고 함)을 계산하는 것입니다.

디프 계산은 일반적인 개념(단독으로 사용되거나 Git 등에서 사용됨)이지만, 이 모듈은 버퍼의 현재 텍스트와 해당 버퍼에 대해 특별히 최신 상태로 유지되는 일부 참조 텍스트 간의 차이점을 계산합니다. 예를 들어, 기본 참조 텍스트는 Git 인덱스의 파일 콘텐츠로 계산됩니다. 이는 `config.source`에서 사용자 정의할 수 있습니다 ([MiniDiff-소스 사양](mini-diff.qmd#minidiff-source-specification) 참조).

#### 헝크 사양 {#minidiff-overview-hunkspecification}


<a name="minidiff-hunk-specification" href="mini-diff.qmd#minidiff-hunk-specification"><b>MiniDiff-헝크 사양</b></a>

헝크는 서로 다른 연속된 두 줄 세트(버퍼 텍스트에서 하나, 참조에서 하나)를 설명합니다. 이 모듈에서 헝크는 다음 필드를 가진 테이블로 저장됩니다:


- <span class="help-syntax-keys">\<buf_start\></span> `(number)` - 헝크 버퍼 줄의 시작. 첫 번째 줄은 1입니다. 첫 번째 참조 줄이 삭제된 경우 0이 될 수 있습니다.


- <span class="help-syntax-keys">\<buf_count\></span> `(number)` - 연속된 버퍼 줄의 수. 참조 줄이 삭제된 경우 0이 될 수 있습니다.


- <span class="help-syntax-keys">\<ref_start\></span> `(number)` - 헝크 참조 줄의 시작. 첫 번째 줄은 1입니다. 첫 번째 참조 줄 앞에 줄이 추가된 경우 0이 될 수 있습니다.


- <span class="help-syntax-keys">\<ref_count\></span> `(number)` - 연속된 참조 줄의 수. 버퍼 줄이 추가된 경우 0이 될 수 있습니다.


- <span class="help-syntax-keys">\<type\></span> `(string)` - 헝크 유형. 다음 중 하나일 수 있습니다:

    - "add" - 버퍼에는 있지만 참조에는 없는 줄.

    - "change" - 버퍼와 참조 모두에 있는 줄.

    - "delete" - 버퍼에는 없지만 참조에는 있는 줄.

#### 수명 주기 {#minidiff-overview-lifecycle}



- 적절한(이미 활성화되지 않았고, 유효하며, 텍스트를 보여주는) 버퍼에 들어갈 때, 디프 처리를 위해 활성화를 시도합니다.

- 활성화하는 동안 소스 연결을 시도합니다. 이는 참조 텍스트를 최신 상태로 유지하는 방법을 설정해야 합니다.

- 텍스트가 변경될 때마다 디프 계산이 사용자 정의 가능한 지연 시간(기본값 200ms) 후에 디바운스(debounce) 방식으로 예약됩니다.

- 디프가 계산된 후 다음 작업을 수행합니다:

    - 구성 가능한 스타일에 따라 시각화를 업데이트합니다: 사인 열에 색상 텍스트를 배치하거나 줄 번호에 색상을 지정합니다. 두 스타일의 색상은 해당하는 `MiniDiffSign*` 하이라이트 그룹([mini.diff](mini-diff.qmd#mini.diff) 참조)에서 헝크 유형별로 정의되며, "sign" 스타일의 사인 텍스트는 [MiniDiff.config](mini-diff.qmd#minidiff.config)의 `view.signs`에서 구성할 수 있습니다.

    - 오버레이 뷰를 업데이트합니다(활성화된 경우).

    - `vim.b.minidiff_summary` 및 `vim.b.minidiff_summary_string` 버퍼 로컬 변수를 업데이트합니다. 이들은 예를 들어 상태라인에서 사용할 수 있습니다.

    - <a name="minidiff-update-event" href="mini-diff.qmd#minidiff-update-event"><b>MiniDiff-업데이트-이벤트</b></a> `MiniDiffUpdated` `User` 이벤트를 트리거합니다. 사용 예는 [MiniDiff-디프 요약](mini-diff.qmd#minidiff-diff-summary)을 참조하세요.

참고:

- 현재 버퍼를 리셋(비활성화 및 재활성화)하려면 [:edit](https://neovim.io/doc/user/helptag.html?tag=:edit)를 사용하세요.

- BOM 바이트로 작업하려면 'bomb'을 설정하고 'fileencodings'에 `ucs-bom`을 넣으세요.

#### 오버레이 {#minidiff-overview-overlay}


기본 시각화와 함께 "오버레이(overlay)"라는 특별한 뷰가 있습니다. 디프 세부 정보를 일시적으로 개괄하기 위한 것이며 [MiniDiff.toggle\_overlay()](mini-diff.qmd#minidiff.toggle_overlay)를 통해 수동으로 토글할 수 있지만, 텍스트가 변경됨에 따라 오버레이도 그에 맞춰 반응할 수 있습니다.

텍스트 영역 내부에 더 많은 디프 세부 정보를 보여줍니다:


- 추가된 버퍼 줄은 `MiniDiffOverAdd` 하이라이트 그룹으로 강조됩니다.


- 삭제된 참조 줄은 가상 줄(virtual lines)로 표시되며 `MiniDiffOverDelete` 하이라이트 그룹으로 강조됩니다.


- 버퍼/참조 줄 수가 동일한 "변경(change)" 헝크는 "단어 디프(word diff)"를 보여줍니다. 이는 보통 `options.linematch`가 활성화된 경우(기본값)에 해당합니다. 참조 줄은 버퍼 대응 줄 옆에 표시됩니다. 변경된 부분은 참조 및 버퍼 줄에서 `MiniDiffOverChange` 및 `MiniDiffOverChangeBuf`로 강조됩니다. 나머지 줄은 `MiniDiffOverContext` 및 `MiniDiffOverContextBuf` 하이라이트가 적용됩니다.

  버퍼/참조 줄 수가 일치하지 않는 변경은 `MiniDiffOverChange` 그룹으로 강조된 가상 줄로 참조 부분이 표시됩니다. 해당하는 버퍼 줄은 변경에 대한 컨텍스트로 취급되며 `MiniDiffOverContextBuf` 그룹으로 강조됩니다.

참고:

- 단어 디프는 0이 아닌 컨텍스트 너비를 가집니다. 즉, 변경된 문자가 충분히 가까우면 그 사이의 전체 범위도 색상이 지정됩니다. 이는 보통 시각적 노이즈를 줄여줍니다.

- 1행 위의 가상 줄(삭제되거나 변경된 줄 등)은 보이게 하려면 수동 스크롤([CTRL-Y](https://neovim.io/doc/user/helptag.html?tag=CTRL-Y))이 필요합니다.

#### 매핑 {#minidiff-overview-mappings}


이 모듈은 다음과 같은 디프 관련 일반 동작에 대한 매핑을 제공합니다:

- 헝크 적용 및 리셋.

- "커서 아래의 헝크 범위" 텍스트 오브젝트.

- 처음/이전/다음/마지막 헝크 범위로 이동.

예시:

- `vip` 다음에 `gh` / `gH`를 누르면 현재 단락 내부의 헝크를 적용/리셋합니다. 오퍼레이터 형태인 `ghip` / `gHip`으로도 동일한 작업을 수행할 수 있으며, 점 반복이 가능하다는 장점이 있습니다 ([single-repeat](https://neovim.io/doc/user/helptag.html?tag=single-repeat) 참조).

- `gh_` / `gH_`는 (전체 헝크가 아니더라도) 현재 줄을 적용/리셋합니다.

- `ghgh` / `gHgh`는 커서 아래의 헝크 범위를 적용/리셋합니다.

- `dgh`는 커서 아래의 헝크 범위를 삭제합니다.

- `[H` / `[h` / `]h` / `]H`는 커서를 현재 버퍼의 처음 / 이전 / 다음 / 마지막 헝크 범위로 이동시킵니다.

일부 기능에 대한 매핑은 수동으로 수행되는 것으로 가정합니다.
[MiniDiff.operator()](mini-diff.qmd#minidiff.operator)를 참조하세요.

#### 버퍼 로컬 변수 {#minidiff-overview-buffer-localvariables}


<a name="minidiff-diff-summary" href="mini-diff.qmd#minidiff-diff-summary"><b>MiniDiff-디프 요약</b></a>

활성화된 각 버퍼에는 현재 버퍼의 헝크 개요를 보여주기 위해 커스텀 상태라인에서 사용할 수 있는 다음과 같은 버퍼 로컬 변수가 있습니다:


- `vim.b.minidiff_summary`는 다음 필드를 가진 테이블입니다:

    - `source_name` - 활성 소스의 이름. 버퍼의 참조 텍스트가 (아직) 설정되지 않은 경우 유일하게 존재하는 필드입니다.

    - `n_ranges` - 헝크 범위(인접한 헝크의 시퀀스)의 수.

    - `add` - 추가된 줄 수.

    - `change` - 변경된 줄 수.

    - `delete` - 삭제된 줄 수.


- `vim.b.minidiff_summary_string`은 고정된 형식의 요약 문자열 표현입니다. 참조 텍스트가 (아직) 없는 경우 빈 문자열입니다. 그대로 사용되도록 의도되었습니다. 다른 형식을 사용하려면 `vim.b.minidiff_summary`를 사용하여 직접 구성하세요. 이를 수행하는 가장 좋은 방법은 [MiniDiff-업데이트-이벤트](mini-diff.qmd#minidiff-update-event) 내부에서 `vim.b.minidiff_summary_string`을 재정의하는 것입니다:

  ```lua
  local format_summary = function(data)
    local summary = vim.b[data.buf].minidiff_summary
    local t = {}
    if summary.add > 0 then table.insert(t, '+' .. summary.add) end
    if summary.change > 0 then table.insert(t, '~' .. summary.change) end
    if summary.delete > 0 then table.insert(t, '-' .. summary.delete) end
    vim.b[data.buf].minidiff_summary_string = table.concat(t, ' ')
  end
  local au_opts = { pattern = 'MiniDiffUpdated', callback = format_summary }
  vim.api.nvim_create_autocmd('User', au_opts)
  ```

---

### setup() {#minidiff.setup .help-syntax-right-anchor}

<p align="center">`MiniDiff.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minidiff.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniDiff.config](mini-diff.qmd#minidiff.config)를 참조하세요.

#### 사용법 {#minidiff.setup-usage}



  ```lua
  require('mini.diff').setup() -- 기본 설정 사용
  -- 또는
  require('mini.diff').setup({}) -- {}를 설정 테이블로 교체
  ```

---

### config {#minidiff.config .help-syntax-right-anchor}

<p align="center">`MiniDiff.config`</p>
#### 기본값 {#minidiff.config-defaults}



  ```lua
  MiniDiff.config = {
    -- 헝크 시각화 방식에 대한 옵션
    view = {
      -- 시각화 스타일. 가능한 값은 'sign' 및 'number'입니다.
      -- 기본값: 줄 번호가 활성화된 경우 'number', 그렇지 않으면 'sign'.
      style = vim.go.number and 'number' or 'sign',

      -- 'sign' 뷰에서 헝크에 사용되는 사인
      signs = { add = '▒', change = '▒', delete = '▒' },

      -- 사용된 시각화 extmarks의 우선순위
      priority = 199,
    },

    -- 참조 텍스트가 계산/업데이트되는 방식에 대한 소스
    -- 기본적으로 Git 인덱스의 내용을 사용합니다.
    source = nil,

    -- 비동기 프로세스를 정의하는 지연 시간 (ms)
    delay = {
      -- 텍스트 변경 후 업데이트 전 대기 시간
      text_change = 200,
    },

    -- 모듈 매핑. 비활성화하려면 `''`(빈 문자열)을 사용하세요.
    mappings = {
      -- 비주얼/오퍼레이터 영역 내의 헝크 적용
      apply = 'gh',

      -- 비주얼/오퍼레이터 영역 내의 헝크 리셋
      reset = 'gH',

      -- 오퍼레이터 내부에서 사용할 헝크 범위 텍스트 오브젝트
      -- 매핑이 apply 및 reset과 다른 경우 비주얼 모드에서도 작동합니다.
      textobject = 'gh',

      -- 해당 방향으로 헝크 범위 이동
      goto_first = '[H',
      goto_prev = '[h',
      goto_next = ']h',
      goto_last = ']H',
    },

    -- 다양한 옵션
    options = {
      -- 디프 알고리즘. `:h vim.diff()`를 참조하세요.
      algorithm = 'histogram',

      -- "들여쓰기 휴리스틱" 사용 여부. `:h vim.diff()`를 참조하세요.
      indent_heuristic = true,

      -- 줄을 맞추기 위한 2단계 디프의 양
      linematch = 60,

      -- 헝크 탐색 중 가장자리에 도달했을 때 랩어라운드(wrap around) 여부
      wrap_goto = false,
    },
  }
  ```

#### 뷰 {#minidiff.config-view}


`config.view`는 디프 헝크가 시각화되는 방식에 대한 설정을 포함합니다.
커스텀 사인을 사용하는 예시:

  ```lua
  require('mini.diff').setup({
    view = {
      style = 'sign',
      signs = { add = '+', change = '~', delete = '-' },
    },
  })
  ```

`view.style`은 시각화 스타일을 정의하는 문자열입니다. "sign"([사인 열](https://neovim.io/doc/user/helptag.html?tag=sign-column)의 색상 기호) 또는 "number"(색상 줄 번호) 중 하나일 수 있습니다.
기본값: ['number'](https://neovim.io/doc/user/helptag.html?tag='number') 옵션이 활성화된 경우 "number", 그렇지 않으면 "sign".
참고: "sign" 스타일에서는 ['signcolumn'](https://neovim.io/doc/user/helptag.html?tag='signcolumn')을 항상 표시하는 것이 좋습니다.

`view.signs`는 해당("add", "change", "delete") 헝크의 사인으로 사용되는 한 개 또는 두 개의 문자 문자열 테이블입니다.
기본값: 모든 헝크가 "▒" 문자를 사용하여 연속된 색상 줄을 생성합니다.

`view.priority`는 시각화 및 오버레이 [extmarks](https://neovim.io/doc/user/helptag.html?tag=extmarks)에 사용되는 우선순위 번호입니다.
기본값: 199. 이는 [vim.hl.priorities](https://neovim.io/doc/user/helptag.html?tag=vim.hl.priorities)의 `user`보다 하나 적습니다 (Neovim<0.11에서는 [vim.hl.priorities](https://neovim.io/doc/user/helptag.html?tag=vim.hl.priorities) 참조). 자동화된 extmarks보다는 높은 우선순위를 가지지만 사용자 활성화 extmarks보다는 낮습니다.

#### 소스 {#minidiff.config-source}


<a name="minidiff-소스-사양" href="mini-diff.qmd#minidiff-source-specification"><b>MiniDiff-소스 사양</b></a>

`config.source`는 단일 소스 또는 소스 배열 테이블입니다. 단일 소스는 특정 버퍼에서 참조 텍스트가 관리되는 방식을 정의합니다. 배열의 소스는 순서대로 연결을 시도하며, 연결되는 소스가 없으면 [MiniDiff.disable()](mini-diff.qmd#minidiff.disable)을 호출합니다.

단일 소스 테이블은 다음 필드를 가질 수 있습니다:


- <span class="help-syntax-keys">\<attach\></span> `(function)` - 특정 버퍼 내에서 참조 텍스트가 업데이트되는 시기와 방법을 정의하는 호출 가능 객체입니다. [MiniDiff.enable()](mini-diff.qmd#minidiff.enable) 내부에서 버퍼 식별자를 단일 인수로 사용하여 사용됩니다.

  버퍼의 참조 텍스트를 업데이트해야 할 때 [MiniDiff.set\_ref\_text()](mini-diff.qmd#minidiff.set_ref_text)를 호출하는 로직을 실행해야 합니다. [autocommand](https://neovim.io/doc/user/helptag.html?tag=autocommand)의 콜백이나 파일 감시자([watch-file](https://neovim.io/doc/user/helptag.html?tag=watch-file) 참조) 내부와 같이 사용합니다.

  예를 들어, 기본 Git 소스는 ".git/index" 파일이 변경되는 시점을 감시하고 참조 텍스트를 현재 파일에 대한 Git 인덱스의 텍스트로 계산합니다.

  연결에 실패했음을 나타내기 위해 `false`를 반환할 수 있습니다. (예를 들어 비동기 실행으로 인해) 연결 실패를 즉시 유추할 수 없는 경우, 적절한 인수와 함께 [MiniDiff.fail\_attach()](mini-diff.qmd#minidiff.fail_attach)를 명시적으로 호출해야 합니다. 이는 소스 배열을 적절하게 처리하는 데 중요합니다.

  기본값은 없으며 항상 제공되어야 합니다.


- <span class="help-syntax-keys">\<name\></span> `(string|nil)` - 소스 이름. 제공되지 않으면 문자열 `"unknown"`이 사용됩니다.


- <span class="help-syntax-keys">\<detach\></span> `(function|nil)` - 버퍼가 비활성화될 때 수행할 정리 작업이 포함된 호출 가능 객체입니다. [MiniDiff.disable()](mini-diff.qmd#minidiff.disable) 내부에서 버퍼 식별자를 단일 인수로 하여 호출됩니다.

  제공되지 않으면 해제(detaching) 중에 아무 작업도 수행되지 않습니다.


- <span class="help-syntax-keys">\<apply_hunks\></span> `(function|nil)` - 헝크가 적용되는 방식을 정의하는 호출 가능 객체입니다. 첫 번째 인수로 버퍼 식별자를, 두 번째 인수로 헝크 배열([MiniDiff-헝크 사양](mini-diff.qmd#minidiff-hunk-specification) 참조)을 사용하여 호출됩니다. 결국 [MiniDiff.set\_ref\_text()](mini-diff.qmd#minidiff.set_ref_text)를 명시적으로 호출하거나 해당 호출을 트리거하는 동작을 수행하여 참조 텍스트를 업데이트해야 합니다.

  예를 들어, 기본 Git 소스는 헝크를 기반으로 패치를 계산하고 파일의 Git 저장소 내에 적용합니다.

  제공되지 않으면 헝크 적용 시 에러가 발생합니다.

기본값: 단일 [MiniDiff.gen\_source.git()](mini-diff.qmd#minidiff.gen_source.git).

#### 지연 시간 {#minidiff.config-delay}


`config.delay`는 비동기 프로세스의 지연 시간에 대한 설정을 포함합니다.

`delay.text_change`는 최신 텍스트 변경 후 디프 및 시각화를 업데이트하기 전 대기할 시간(ms)을 정의하는 숫자입니다 (디바운스 방식).
기본값: 200.

#### 매핑 {#minidiff.config-mappings}


`config.mappings`는 [MiniDiff.setup()](mini-diff.qmd#minidiff.setup) 중에 매핑되는 키를 포함합니다.

`mappings.apply` 키는 비주얼/오퍼레이터 영역 내부의 헝크를 적용하는 데 사용될 수 있습니다. "헝크 적용"이 정확히 무엇을 의미하는지는 소스와 그 `apply_hunks()`에 따라 다릅니다. 예를 들어 기본 Git 소스에서는 헝크 스테이징을 의미합니다.

`mappings.reset` 키는 비주얼/오퍼레이터 영역 내부의 헝크를 리셋하는 데 사용될 수 있습니다. 리셋은 영역의 버퍼 텍스트를 해당하는 참조 텍스트로 교체하는 것을 의미합니다.

`mappings.textobject` 키는 오퍼레이터 대기 모드에서 오퍼레이터(예: [d](https://neovim.io/doc/user/helptag.html?tag=d), [y](https://neovim.io/doc/user/helptag.html?tag=y), 헝크 적용/리셋 등)의 대상으로 사용할 수 있는 "커서 아래의 헝크 범위" 텍스트 오브젝트를 정의합니다. 키가 `mappings.apply` 및 `mappings.reset`과 충돌하지 않는 경우 비주얼 모드에서도 설정됩니다.
"헝크 범위"는 인접한(연속적인) 헝크들이 동일한 헝크 범위의 일부로 간주된다는 의미로 사용됩니다.

`mappings.goto_first` / `mappings.goto_prev` / `mappings.goto_next` / `mappings.goto_last` 키는 현재 버퍼의 처음 / 이전 / 다음 / 마지막 헝크 범위로 이동하는 데 사용할 수 있습니다.

#### 옵션 {#minidiff.config-options}


`config.options`는 다양한 사용자 정의 옵션을 포함합니다.

`options.algorithm`은 사용할 디프 알고리즘을 정의하는 문자열입니다.
기본값: "histogram". 가능한 값은 [vim.diff()](https://neovim.io/doc/user/helptag.html?tag=vim.diff\(\))를 참조하세요.

`options.indent_heuristic`은 (가능한 한) 더 자연스럽게 정렬된 헝크를 위해 들여쓰기 휴리스틱을 사용할지 여부를 정의하는 불리언 값입니다.
기본값: `true`.

`options.linematch`는 더 잘 정렬되고 더 세분화된 헝크를 위해 2단계 디프가 실행되는 헝크 크기를 정의하는 숫자입니다.
기본값: 60. 자세한 내용은 [vim.diff()](https://neovim.io/doc/user/helptag.html?tag=vim.diff\(\)) 및 'diffopt'를 참조하세요.

`options.wrap_goto`는 헝크 탐색([MiniDiff.goto\_hunk()](mini-diff.qmd#minidiff.goto_hunk) 또는 `goto_*` 매핑 사용) 중 가장자리에 도달했을 때 랩어라운드할지 여부를 나타내는 불리언 값입니다. 예를 들어 커서가 마지막 헝크 뒤에 있는 경우 "다음"으로 이동하면 커서가 첫 번째 헝크에 놓입니다.
기본값: `false`.

---

### enable() {#minidiff.enable .help-syntax-right-anchor}

<p align="center">`MiniDiff.enable`(<span class="help-syntax-special">{buf_id}</span>)</p>
버퍼에서 디프 처리 활성화

#### 매개변수 {#minidiff.enable-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

---

### disable() {#minidiff.disable .help-syntax-right-anchor}

<p align="center">`MiniDiff.disable`(<span class="help-syntax-special">{buf_id}</span>)</p>
버퍼에서 디프 처리 비활성화

#### 매개변수 {#minidiff.disable-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

---

### toggle() {#minidiff.toggle .help-syntax-right-anchor}

<p align="center">`MiniDiff.toggle`(<span class="help-syntax-special">{buf_id}</span>)</p>
버퍼에서 디프 처리 토글

비활성화된 경우 활성화하고, 활성화된 경우 비활성화합니다.

#### 매개변수 {#minidiff.toggle-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

---

### toggle_overlay() {#minidiff.toggle_overlay .help-syntax-right-anchor}

<p align="center">`MiniDiff.toggle_overlay`(<span class="help-syntax-special">{buf_id}</span>)</p>
버퍼에서 오버레이 뷰 토글

#### 매개변수 {#minidiff.toggle_overlay-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

---

### export() {#minidiff.export .help-syntax-right-anchor}

<p align="center">`MiniDiff.export`(<span class="help-syntax-special">{format}</span>, <span class="help-syntax-special">{opts}</span>)</p>
헝크 내보내기

현재/모든 버퍼에서 헝크를 가져와 변환합니다. 사용 예시:

  ```lua
  -- 사용 가능한 모든 헝크에서 퀵픽스 목록 설정
  vim.fn.setqflist(MiniDiff.export('qf'))
  ```

#### 매개변수 {#minidiff.export-parameters}



<span class="help-syntax-special">{format}</span> `(string)` 출력 형식. 현재는 `'qf'` 값만 지원됩니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 어떤 버퍼에서 헝크를 사용할지 정의하는 범위.
    "all"(활성화된 모든 버퍼) 또는 "current" 중 하나.

#### 반환 {#minidiff.export-return}


`(table)` 내보내기 결과. `format`에 따라 다릅니다:

  - "qf"인 경우, [setqflist()](https://neovim.io/doc/user/helptag.html?tag=setqflist\(\)) 및 [setloclist()](https://neovim.io/doc/user/helptag.html?tag=setloclist\(\))와 호환되는 배열.

---

### get_buf_data() {#minidiff.get_buf_data .help-syntax-right-anchor}

<p align="center">`MiniDiff.get_buf_data`(<span class="help-syntax-special">{buf_id}</span>)</p>
버퍼 데이터 가져오기

#### 매개변수 {#minidiff.get_buf_data-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

#### 반환 {#minidiff.get_buf_data-return}


`(table|nil)` 버퍼 디프 데이터가 포함된 테이블 또는 버퍼가 활성화되지 않은 경우 `nil`.
  테이블에는 다음 필드가 있습니다:

  - <span class="help-syntax-keys">\<config\></span> `(table)` - 이 특정 버퍼에 사용된 설정.

  - <span class="help-syntax-keys">\<hunks\></span> `(table)` - 헝크 배열. [MiniDiff-헝크 사양](mini-diff.qmd#minidiff-hunk-specification)을 참조하세요.

  - <span class="help-syntax-keys">\<overlay\></span> `(boolean)` - 오버레이 뷰 표시 여부.

  - <span class="help-syntax-keys">\<ref_text\></span> `(string|nil)` - 참조 텍스트의 현재 값. 줄은 줄 바꿈 문자(`'\n'`)로 구분됩니다. 참조 텍스트가 아직 설정되지 않은 경우(예: 소스가 아직 반응하지 않은 경우) `nil`일 수 있습니다.

  - <span class="help-syntax-keys">\<summary\></span> `(table)` - 전체 디프 요약. [MiniDiff-디프 요약](mini-diff.qmd#minidiff-diff-summary)을 참조하세요.

---

### set_ref_text() {#minidiff.set_ref_text .help-syntax-right-anchor}

<p align="center">`MiniDiff.set_ref_text`(<span class="help-syntax-special">{buf_id}</span>, <span class="help-syntax-special">{text}</span>)</p>
버퍼에 대한 참조 텍스트 설정

참고: 대상 버퍼가 아직 활성화되지 않은 경우 [MiniDiff.enable()](mini-diff.qmd#minidiff.enable)을 호출합니다.

#### 매개변수 {#minidiff.set_ref_text-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

<span class="help-syntax-special">{text}</span> `(string|table)` 새로운 참조 텍스트. 줄 구분에 `\n`이 사용된 문자열 또는 줄 배열입니다. 현재 참조 텍스트를 해제하려면 빈 테이블을 사용하세요(헝크가 표시되지 않음). 기본값: `{}`.
  참고: 더 나은 디프를 위해 끝에 줄 바꿈 문자가 (이미 있지 않은 경우) 추가됩니다.

---

### gen_source {#minidiff.gen_source .help-syntax-right-anchor}

<p align="center">`MiniDiff.gen_source`</p>
내장 소스 생성

함수 요소를 가진 테이블입니다. 소스를 실제로 가져오려면 호출하세요.
예시:

  ```lua
  local diff = require('mini.diff')

  -- 단일 `save` 소스
  diff.setup({ source = diff.gen_source.save() })

  -- 다중 소스 (순서대로 연결 시도)
  diff.setup({ source = { diff.gen_source.git(), diff.gen_source.save() } })
  ```

---

### gen_source.git() {#minidiff.gen_source.git .help-syntax-right-anchor}

<p align="center">`MiniDiff.gen_source.git`()</p>
Git 소스

기본 소스입니다. Git 인덱스의 파일 텍스트를 참조로 사용합니다. 결과는 다음과 같습니다:

- "Add" 헝크는 현재 버퍼에는 있지만 인덱스에는 없는 텍스트를 나타냅니다.

- "Change" 헝크는 이미 인덱스에 있는 수정된 텍스트를 나타냅니다.

- "Delete" 헝크는 인덱스에서 삭제된 텍스트를 나타냅니다.

헝크를 적용하는 것은 스테이징(인덱스에 추가)을 의미합니다.
참고:

- Git 버전 2.38.0 이상이 필요합니다.

- 헝크 스테이징 취소 기능은 없습니다. 이를 위해서는 전체 Git 클라이언트를 사용하세요.

#### 반환 {#minidiff.gen_source.git-return}


`(table)` 소스. [MiniDiff-소스 사양](mini-diff.qmd#minidiff-source-specification)을 참조하세요.

---

### gen_source.none() {#minidiff.gen_source.none .help-syntax-right-anchor}

<p align="center">`MiniDiff.gen_source.none`()</p>
"아무것도 안 함" 소스

참조 텍스트를 설정하지 않고 버퍼를 활성화할 수 있습니다.
수동 [MiniDiff.set\_ref\_text()](mini-diff.qmd#minidiff.set_ref_text) 호출에 의존하려는 경우에 사용하세요.

#### 반환 {#minidiff.gen_source.none-return}


`(table)` 소스. [MiniDiff-소스 사양](mini-diff.qmd#minidiff-source-specification)을 참조하세요.

---

### gen_source.save() {#minidiff.gen_source.save .help-syntax-right-anchor}

<p align="center">`MiniDiff.gen_source.save`()</p>
최신 저장 소스

최신 저장 시점의 텍스트를 참조로 사용합니다. 결과적으로 최신 저장 이후의 차이점을 보여주는 디프가 표시됩니다.

#### 반환 {#minidiff.gen_source.save-return}


`(table)` 소스. [MiniDiff-소스 사양](mini-diff.qmd#minidiff-source-specification)을 참조하세요.

---

### do_hunks() {#minidiff.do_hunks .help-syntax-right-anchor}

<p align="center">`MiniDiff.do_hunks`(<span class="help-syntax-special">{buf_id}</span>, <span class="help-syntax-special">{action}</span>, <span class="help-syntax-special">{opts}</span>)</p>
영역 내 헝크에 대해 동작 수행

대상 영역 내부의 헝크(일부만 포함된 헝크 포함)를 계산하고 그에 대해 적용(apply)/리셋(reset)/얀크(yank) 작업을 수행합니다.

"yank" 동작은 대상 헝크의 모든 참조 줄을 지정된 레지스터([registers](https://neovim.io/doc/user/helptag.html?tag=registers) 중 하나여야 함)로 얀크합니다.

참고:

- 헝크가 영역 내부에 있는지 여부는 해당 버퍼 줄의 위치를 기반으로 계산됩니다.

- "change" 또는 "delete"가 대상 영역에 부분적으로만 걸쳐 있는 경우, 계산된 "교차(intersection)" 헝크에는 모든 참조 줄이 사용됩니다.

`config.mappings.apply` 및 `config.mappings.reset`에서 직접 사용됩니다. 보통 이 함수를 수동으로 사용할 필요는 없습니다. "yank" 매핑 설정 방법은 [MiniDiff.operator()](mini-diff.qmd#minidiff.operator)를 참조하세요.

#### 매개변수 {#minidiff.do_hunks-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number)` 대상 버퍼 식별자. 기본값: 0 (현재 버퍼).

<span class="help-syntax-special">{action}</span> `(string)` "apply", "reset", "yank" 중 하나.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<line_start\></span> `(number)` - 영역의 시작 줄. 기본값: 1.

  - <span class="help-syntax-keys">\<line_end\></span> `(number)` - 영역의 끝 줄. 기본값: 마지막 버퍼 줄.

  - <span class="help-syntax-keys">\<register\></span> `(string)` - 참조 줄을 얀크할 레지스터.
    기본값: [v:register](https://neovim.io/doc/user/helptag.html?tag=v:register).

---

### goto_hunk() {#minidiff.goto_hunk .help-syntax-right-anchor}

<p align="center">`MiniDiff.goto_hunk`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
현재 버퍼의 헝크 범위로 이동

#### 매개변수 {#minidiff.goto_hunk-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "prev", "next", "last" 중 하나.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 필드가 있는 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 전진 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<line_start\></span> `(number)` - "prev" 및 "next" 방향에 대해 시작할 줄 번호. 기본값: 커서 줄.

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 가장자리에서 랩어라운드 여부.
    기본값: 설정의 `options.wrap` 값.

---

### operator() {#minidiff.operator .help-syntax-right-anchor}

<p align="center">`MiniDiff.operator`(<span class="help-syntax-special">{mode}</span>)</p>
영역에 대해 동작 수행

마크로 정의된 영역에 대해 동작을 수행합니다. 매핑에서 사용됩니다.

커서 아래 헝크 범위의 참조 줄을 얀크하는 매핑 예시 (기본 'config.mappings.textobject'를 가정):

  ```lua
  local rhs = function() return MiniDiff.operator('yank') .. 'gh' end
  vim.keymap.set('n', 'ghy', rhs, { expr = true, remap = true })
  ```

#### 매개변수 {#minidiff.operator-parameters}



<span class="help-syntax-special">{mode}</span> `(string)` "apply", "reset", "yank" 중 하나 또는 [g@](https://neovim.io/doc/user/helptag.html?tag=g@)에서 사용되는 것들.

---

### textobject() {#minidiff.textobject .help-syntax-right-anchor}

<p align="center">`MiniDiff.textobject`()</p>
헝크 범위 텍스트 오브젝트 선택

임의의(반드시 동일할 필요는 없음) 헝크에 있는 커서 줄에 인접한 모든 연속 줄을 선택합니다 (커서 줄 자체가 헝크에 있는 경우).
기본 매핑에서 사용됩니다.

---

### fail_attach() {#minidiff.fail_attach .help-syntax-right-anchor}

<p align="center">`MiniDiff.fail_attach`(<span class="help-syntax-special">{buf_id}</span>)</p>
소스 연결 실패 표시

다음 소스 연결을 시도합니다. 없으면 [MiniDiff.disable()](mini-diff.qmd#minidiff.disable)을 호출합니다.

#### 매개변수 {#minidiff.fail_attach-parameters}



<span class="help-syntax-special">{buf_id}</span> `(integer)` 연결에 실패한 버퍼 식별자.
