---
title: "mini.visits 문서"
---

_이 문서는 'mini.nvim'의 `main` 브랜치에서 생성되었습니다._

<a name="mini.visits" href="mini-visits.qmd#mini.visits"><b>mini.visits</b></a> 파일 시스템 방문 추적 및 재사용

MIT 라이선스 Copyright (c) 2023 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:


- 프로젝트 디렉토리별로 파일 시스템 방문(파일 및 디렉토리 모두)을 지속적으로 추적합니다.
  방문 인덱스는 사람이 읽을 수 있고 편집 가능하도록 저장됩니다.


- 방문 인덱스는 작성될 때마다 관련 정보를 포함하도록 정규화됩니다.
  정확한 세부 정보는 사용자 정의할 수 있습니다. [MiniVisits.normalize\_index()](mini-visits.qmd#minivisits.normalize_index)를 참조하세요.


- 나중에 사용할 수 있도록 경로에 라벨을 지속적으로 추가하는 기능이 내장되어 있습니다.
  [MiniVisits.add\_label()](mini-visits.qmd#minivisits.add_label) 및 [MiniVisits.remove\_label()](mini-visits.qmd#minivisits.remove_label)을 참조하세요.


- 방문 데이터를 재사용하기 위한 내보낸 함수들:

    - 사용자 정의 필터 및 정렬(기본적으로 "견고한 frecency" 사용)을 사용하여 방문한 경로/라벨 목록을 표시합니다.
      선택기(picker)의 소스로 사용할 수 있습니다.
      [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths) 및 [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)를 참조하세요.
      [MiniVisits.gen\_filter](mini-visits.qmd#minivisits.gen_filter) 및 [MiniVisits.gen\_sort](mini-visits.qmd#minivisits.gen_sort)를 참조하세요.


    - [vim.ui.select()](https://neovim.io/doc/user/helptag.html?tag=vim.ui.select\(\))를 사용하여 방문한 경로/라벨을 선택합니다.
      [MiniVisits.select\_path()](mini-visits.qmd#minivisits.select_path) 및 [MiniVisits.select\_label()](mini-visits.qmd#minivisits.select_label)을 참조하세요.


    - 대상 방향("forward", "backward", "first", "last")으로 방문 경로를 반복합니다.
      [MiniVisits.iterate\_paths()](mini-visits.qmd#minivisits.iterate_paths)를 참조하세요.


- 모든 사용자 정보를 지속적으로 추적할 수 있도록 방문 인덱스를 수동으로 업데이트하는 내보낸 함수들.
  `*_index()` 함수들을 참조하세요.

참고:

- 모든 데이터는 빠른 작업을 위해 세션 내 Lua 변수에만 저장되며, 지속적인 사용을 위해 디스크의
  `config.store.path`에 저장됩니다.

- 대부분의 함수는 세션 내 데이터에 영향을 미치며, Neovim이 종료되기 직전이나 사용자가 요청할 때만
  디스크에 기록됩니다.

- 경로의 이름이 변경되거나 이동되는 것을 감지하지 못합니다 (이를 감지하는 일반적인 방법이 없기 때문입니다).
  일반적으로 변경 후 다음 디스크 기록 전(보통 현재 세션 종료 전)에 방문 인덱스에 대한 수동 개입이
  필요합니다. 그렇지 않으면 이전 경로를 삭제된 것으로 간주하고 인덱스에서 제거합니다.
  이를 위한 [MiniVisits.rename\_in\_index()](mini-visits.qmd#minivisits.rename_in_index) 헬퍼가 있습니다.
  [mini.files](mini-files.qmd#mini.files)로 이름 변경/이동을 수행하면 인덱스가 자동으로 업데이트됩니다.

더 자세한 정보 소스:

- [MiniVisits 개요](mini-visits.qmd#minivisits-overview)

- [MiniVisits 인덱스 사양](mini-visits.qmd#minivisits-index-specification)

- [MiniVisits 예제](mini-visits.qmd#minivisits-examples)

#### 설정 {#module-setup}


이 모듈은 `require('mini.visits').setup({})`을 통한 설정이 필요합니다
(`{}`를 사용자의 `config` 테이블로 교체하세요). 스크립팅이나 수동으로 사용할 수 있는
전역 Lua 테이블 `MiniVisits`를 생성합니다 (예: `:lua MiniVisits.*`).

`config` 구조 및 기본값은 [MiniVisits.config](mini-visits.qmd#minivisits.config)를 참조하세요.

`vim.b.minivisits_config`를 사용하여 버퍼별로 런타임 설정 설정을 재정의할 수 있으며,
이는 `MiniVisits.config`와 동일한 구조를 가져야 합니다. 자세한 내용은
[mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

#### 비교 {#module-comparisons}



- [nvim-telescope/telescope-frecency.nvim](https://github.com/nvim-telescope/telescope-frecency.nvim):

    - 실제 방문 타임스탬프의 배열을 저장하는 반면, 이 모듈은 총 횟수와 최신 방문 타임스탬프만
      추적합니다. 이는 사용/저장되는 데이터의 양과 기본 "frecency" 정렬의 복잡성 사이의
      다른 트레이드오프로 설계된 것입니다.

    - 기본적으로 세션당 한 번만 버퍼를 추적하는 반면, 이 모듈은 의미 있는 버퍼 진입 때마다
      추적합니다. 이는 더 관련성 있는 세션 내 정렬로 이어집니다.

    - Firefox 주소 표시줄의 원래 frecency 알고리즘을 구현하는 반면, 이 모듈은 자체적인
      "견고한 frecency" 접근 방식을 사용합니다.

    - 주로 'nvim-telescope/telescope.nvim'과 함께 작동하도록 설계된 반면, 이 모듈은 경로를 나열하고
      [vim.ui.select()](https://neovim.io/doc/user/helptag.html?tag=vim.ui.select\(\))로 선택하는 일반적인 함수를 제공합니다.

    - 사용자 정의 데이터(라벨 등)의 사용을 허용하지 않는 반면, 이 모듈은 허용합니다.


- [ThePrimeagen/harpoon](https://github.com/ThePrimeagen/harpoon):

    - 일반적인 라벨링과는 약간 다른 개념을 가지고 있으며, 순서가 지정된 스택에 경로를 추가하는 것과
      더 비슷합니다. 이 모듈은 작업 및/또는 선호도에 따라 자동화할 수 있는 기능과 함께,
      순서를 암시하지 않는 보다 일반적인 라벨링을 구현합니다.

    - 마크를 경로 내의 위치로 구현하는 반면, 이 모듈은 경로를 라벨링합니다.

    - 모든 의미 있는 변경 후에 디스크에 데이터를 기록하는 반면, 이 모듈은 더 보수적이며
      Neovim이 종료되거나 요청할 때만 기록합니다.

    - 터미널 라벨링을 지원하는 반면, 이 모듈은 경로에만 집중합니다.

    - 마크를 관리하기 위한 전용 UI가 있는 반면, 이 모듈은 설계상 UI를 제공하지 않습니다.
      경로에서 라벨을 추가하고 제거하는 함수가 있습니다.

    - 방문한 경로를 추적하고 재사용하는 기능을 제공하지 않는 반면, 이 모듈은 제공합니다.

#### 비활성화 {#module-disabling}


자동 추적을 비활성화하려면 `vim.g.minivisits_disable` (전역) 또는
`vim.b.minivisits_disable` (버퍼별)을 `true`로 설정하세요. 다양한
시나리오와 사용자 정의 의도를 고려하여, 모듈 기능을 비활성화하기 위한 정확한 규칙을
작성하는 것은 사용자의 몫으로 남겨둡니다. 일반적인 방법은
[mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### 개요 {#minivisits-overview .help-syntax-right-anchor}

#### 방문 추적 {#minivisits-overview-trackingvisits}


파일 시스템 방문(디렉토리 및 파일 모두) 추적은 두 단계로 수행됩니다:

- 모든 전용 이벤트(`config.track.event`, 기본적으로 [BufEnter](https://neovim.io/doc/user/helptag.html?tag=BufEnter))에서 일정 시간
  (`config.track.delay` 밀리초, 기본값 1000) 후에 실제로 방문을 등록하기 위해 타이머를
  시작(또는 재시작)합니다. 여러 단계(예: [:bnext](https://neovim.io/doc/user/helptag.html?tag=:bnext) / [:bprevious](https://neovim.io/doc/user/helptag.html?tag=:bprevious) 시리즈)를 통해
  대상 버퍼로 탐색할 수 있도록 즉시 등록되지 않습니다.


- 전용 이벤트가 트리거되지 않고 지연 시간이 지나면(사용자가 특정 버퍼에 "안착"했음을 의미),
  다음 조건이 모두 충족되는 경우 [MiniVisits.register\_visit()](mini-visits.qmd#minivisits.register_visit)이 호출됩니다:

    - 모듈이 비활성화되지 않았습니다 ([mini.visits](mini-visits.qmd#mini.visits)의 "비활성화" 섹션 참조).

    - 버퍼가 비어 있지 않은 이름을 가진 일반 버퍼입니다 (방문 경로로 사용됨).

    - 방문 경로가 마지막으로 추적된 경로와 같지 않습니다. 이는 도움말, 터미널 등과 같은
      비정상 버퍼에 일시적으로 진입할 때 방문 횟수가 인위적으로 증가하는 것을 방지하기 위함입니다.

방문은 [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)에 대해 자동 등록되며 방문 횟수와 최신 방문 시간이 증가합니다.
자세한 내용은 [MiniVisits 인덱스 사양](mini-visits.qmd#minivisits-index-specification)을 참조하세요.

참고:

- 모든 데이터는 빠른 작업을 위해 세션 내 Lua 변수에만 저장되며, 지속적인 사용을 위해 디스크의
  `config.store.path`에 저장됩니다. Neovim이 종료되기 전에 자동으로 디스크에 기록됩니다
  (`config.store.autowrite`가 설정된 경우).


- 추적은 빈 문자열을 `track.event`로 제공하여 비활성화할 수 있습니다.
  그러면 사용자가 [MiniVisits.register\_visit()](mini-visits.qmd#minivisits.register_visit)을 적절하게 호출해야 합니다.

#### 방문 재사용 {#minivisits-overview-reusingvisits}


방문 데이터는 최소한 다음과 같은 방법으로 재사용할 수 있습니다:


- 방문한 경로 목록을 가져와서( [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths) 참조) 방문 기록을
  시각화/선택/탐색하는 데 사용합니다.


- 방문한 경로 중 하나를 선택하여 엽니다( [MiniVisits.select\_path()](mini-visits.qmd#minivisits.select_path) 참조).


- 방문 기록을 따라 이동합니다( [MiniVisits.iterate\_paths()](mini-visits.qmd#minivisits.iterate_paths) 참조).


- 라벨을 활용합니다. 모든 방문에 하나 이상의 라벨(예: "core", "tmp" 등)을 추가할 수 있습니다.
  이러한 라벨은 방문(특정 디렉토리에 대해 등록된 경로)에 바인딩되며 영구적으로 저장됩니다.
  라벨을 사용하여 사용자가 특히 관심을 갖는 파일 및/또는 디렉토리 그룹을 수동으로 생성할 수 있습니다.
  라벨을 사용하는 유일한 옳은 방법은 없습니다. 영감을 얻으려면 [MiniVisits-예제](mini-visits.qmd#minivisits-examples)를 참조하세요.


- 사용자 정의 데이터 활용. `_index()` 함수 세트를 사용하여 방문 인덱스를 수동으로 조작할 수 있습니다.
  인덱스 내부의 모든 "저장 가능한"(즉, 함수나 메타테이블이 아닌) 사용자 데이터는 디스크에 저장되므로
  사용자가 원하는 모든 종류의 워크플로우를 만드는 데 사용할 수 있습니다.

실제 구성 및 워크플로우 예제는 [MiniVisits-예제](mini-visits.qmd#minivisits-examples)를 참조하세요.

---

### 인덱스 사양 {#minivisits-index-specification .help-syntax-right-anchor}

#### 구조 {#minivisits-index-specification-structure}


방문 인덱스는 두 수준의 중첩된 테이블에 실제 데이터를 포함하는 테이블입니다.

첫 번째 수준의 키는 방문이 등록된 프로젝트 디렉토리(일명 "cwd")의 경로입니다.

두 번째 수준의 키는 실제 방문 경로입니다. 해당 값은 다음 요구 사항을 따라야 하는 방문 데이터를 가진 테이블입니다:

- <span class="help-syntax-keys">\<count\></span> 필드가 있어야 하며 숫자여야 합니다. 특정 cwd 하에서 이 경로를 방문한 횟수를 나타냅니다.

- <span class="help-syntax-keys">\<latest\></span> 필드가 있어야 하며 숫자여야 합니다. 특정 cwd 하에서 경로를 마지막으로 방문한 시간을 나타냅니다.
  기본적으로 [os.time()](https://neovim.io/doc/user/helptag.html?tag=os.time\(\))으로 계산됩니다(초 단위).

- <span class="help-syntax-keys">\<labels\></span> 필드는 없을 수도 있습니다. 있는 경우 문자열 라벨을 키로 하고 `true`를 값으로 하는 테이블이어야 합니다.
  특정 cwd 하에서의 경로 라벨을 나타냅니다.

참고:

- 모든 경로는 절대 경로입니다.

- 방문 경로가 반드시 해당 cwd의 일부일 필요는 없습니다.

- `count`와 `latest`는 정수, 소수, 음수 등 어떤 숫자라도 될 수 있습니다.

인덱스 데이터의 예:

  ```lua
  {
    ['/home/user/project_1'] = {
      ['home/user/project_1/file'] = { count = 3, latest = 1699796000 },
      ['home/user/project_1/subdir'] = {
        count = 10, latest = 1699797000, labels = { core = true },
      },
    },
    ['/home/user/project_2'] = {
      ['home/user/project_1/file'] = {
        count = 0, latest = 0, labels = { other = true },
      },
      ['home/user/project_2/README'] = { count = 1, latest = 1699798000 },
    },
  }
  ```

#### 저장소 {#minivisits-index-specification-storage}


디스크에 저장될 때 방문 인덱스는 방문 인덱스 테이블을 반환하는 Lua 코드가 포함된 파일입니다.
유효한 Lua 코드( [dofile()](https://neovim.io/doc/user/helptag.html?tag=dofile\(\))로 실행됨)가 포함되어 있는 한 손으로 편집할 수 있습니다.

참고:

- 저장소는 둘 이상의 병렬 Neovim 프로세스를 실제로 지원하지 않는 방식으로 구현되었습니다.
  즉, 동일한 방문 인덱스 저장 경로를 가진 둘 이상의 동시 Neovim 프로세스가 있는 경우,
  마지막으로 기록하는 프로세스가 방문 기록을 보존하고 다른 프로세스는 보존하지 않습니다.

#### 정규화 {#minivisits-index-specification-normalization}


방문 인덱스에 주로 관련 데이터가 포함되도록 정규화됩니다:
[MiniVisits.write\_index()](mini-visits.qmd#minivisits.write_index) 내부에서 자동으로 수행되거나
[MiniVisits.normalize\_index()](mini-visits.qmd#minivisits.normalize_index)를 통해 수행됩니다.

정규화가 실제로 수행하는 작업은 `config.store.normalize`에서 구성할 수 있습니다.

기본 정규화 방식은 [MiniVisits.gen\_normalize.default()](mini-visits.qmd#minivisits.gen_normalize.default)를 참조하세요.

---

### 예제 {#minivisits-examples .help-syntax-right-anchor}

이 모듈은 파일 시스템 방문 작업을 위한 유연한 프레임워크를 제공합니다.
워크플로우를 구성하는 방법의 정확한 선택은 사용자에게 달려 있습니다.
다음은 서로 결합할 수 있는 영감을 주는 몇 가지 예제입니다.

#### 다른 정렬 사용 {#minivisits-examples-usedifferentsorting}


[MiniVisits.gen\_sort.default()](mini-visits.qmd#minivisits.gen_sort.default)의 기본 정렬을 사용하면 최신성(recency) 또는 빈도(frequency) 중
어느 쪽을 더 선호할지 유연하게 조정할 수 있습니다. 다음은 세 가지 정렬 유형과 두 가지 범위
(모든 방문 및 현재 cwd에 대해서만)를 결합한 키맵 세트를 만드는 예제입니다:

  ```lua
  local make_select_path = function(select_global, recency_weight)
    local visits = require('mini.visits')
    local sort = visits.gen_sort.default({ recency_weight = recency_weight })
    local select_opts = { sort = sort }
    return function()
      local cwd = select_global and '' or vim.fn.getcwd()
      visits.select_path(cwd, select_opts)
    end
  end

  local map = function(lhs, desc, ...)
    vim.keymap.set('n', lhs, make_select_path(...), { desc = desc })
  end

  -- LHS와 설명을 원하는 대로 조정하세요
  map('<Leader>vr', '최근 방문 선택 (전체)',   true,  1)
  map('<Leader>vR', '최근 방문 선택 (cwd)',    false, 1)
  map('<Leader>vy', 'Frecent 방문 선택 (전체)', true,  0.5)
  map('<Leader>vY', 'Frecent 방문 선택 (cwd)',  false, 0.5)
  map('<Leader>vf', '자주 방문한 경로 선택 (전체)', true,  0)
  map('<Leader>vF', '자주 방문한 경로 선택 (cwd)',  false, 0)
  ```

참고: [mini.pick](mini-pick.qmd#mini.pick)을 사용하는 경우 [MiniExtra.pickers.visit\_paths()](mini-extra.qmd#miniextra.pickers.visit_paths)를 고려하세요.

#### 수동 라벨 사용 {#minivisits-examples-usemanuallabels}


라벨은 연관된 경로 그룹을 만드는 강력한 도구입니다.
일반적인 워크플로우는 다음과 같습니다:

- [MiniVisits.add\_label()](mini-visits.qmd#minivisits.add_label)로 라벨 추가 (실제 라벨을 묻는 메시지가 표시됨).

- [MiniVisits.remove\_label()](mini-visits.qmd#minivisits.remove_label)로 라벨 제거 (실제 라벨을 묻는 메시지가 표시됨).

- 라벨링된 그룹을 사용해야 할 때 [MiniVisits.select\_label()](mini-visits.qmd#minivisits.select_label)을 호출하면,
  선택된 라벨이 있는 경로 중에서 선택하기 위해 [MiniVisits.select\_path()](mini-visits.qmd#minivisits.select_path)를 호출합니다.
  참고: [mini.pick](mini-pick.qmd#mini.pick)을 사용하는 경우 [MiniExtra.pickers.visit\_labels()](mini-extra.qmd#miniextra.pickers.visit_labels)를 고려하세요.

이 워크플로우를 더 원활하게 만들기 위한 키맵 예제입니다:

  ```lua
  local map_vis = function(keys, call, desc)
    local rhs = '<Cmd>lua MiniVisits.' .. call .. '<CR>'
    vim.keymap.set('n', '<Leader>' .. keys, rhs, { desc = desc })
  end

  map_vis('vv', 'add_label()',          '라벨 추가')
  map_vis('vV', 'remove_label()',       '라벨 제거')
  map_vis('vl', 'select_label("", "")', '라벨 선택 (전체)')
  map_vis('vL', 'select_label()',       '라벨 선택 (cwd)')
  ```

#### 고정 라벨 사용 {#minivisits-examples-usefixedlabels}


모든 프로젝트 작업을 하는 동안 일반적으로 핵심 활동이 집중되는 소수의 파일이 있습니다.
특수 고정 라벨(예: "core")을 추가/제거하고 전체 및 현재 cwd에 대해 해당 라벨이 있는 경로를
선택하는 매핑을 만들어 이를 더 쉽게 만들 수 있습니다. 예제:

  ```lua
  -- 생성 및 선택
  local map_vis = function(keys, call, desc)
    local rhs = '<Cmd>lua MiniVisits.' .. call .. '<CR>'
    vim.keymap.set('n', '<Leader>' .. keys, rhs, { desc = desc })
  end

  map_vis('vv', 'add_label("core")',                     'core에 추가')
  map_vis('vV', 'remove_label("core")',                  'core에서 제거')
  map_vis('vc', 'select_path("", { filter = "core" })',  'core 선택 (전체)')
  map_vis('vC', 'select_path(nil, { filter = "core" })', 'core 선택 (cwd)')

  -- 최신성을 기반으로 반복
  local sort_latest = MiniVisits.gen_sort.default({ recency_weight = 1 })
  local map_iterate_core = function(lhs, direction, desc)
    local opts = { filter = 'core', sort = sort_latest, wrap = true }
    local rhs = function()
      MiniVisits.iterate_paths(direction, vim.fn.getcwd(), opts)
    end
    vim.keymap.set('n', lhs, rhs, { desc = desc })
  end

  map_iterate_core('[{', 'last',     'Core 라벨 (가장 오래전)')
  map_iterate_core('[[', 'forward',  'Core 라벨 (이전)')
  map_iterate_core(']]', 'backward', 'Core 라벨 (이후)')
  map_iterate_core(']}', 'first',    'Core 라벨 (최신)')
  ```

#### 자동 라벨 사용 {#minivisits-examples-useautomatedlabels}


버전 제어 시스템(예: Git)을 사용할 때는 일반적으로 작업 중인 파일을 그룹화하는
식별자인 브랜치 이름이 이미 있습니다. 다음은 브랜치 이름과 동일한 라벨을
추가/제거하는 키맵 예제입니다:

  ```lua
  local map_branch = function(keys, action, desc)
    local rhs = function()
      local branch = vim.fn.system('git rev-parse --abbrev-ref HEAD')
      if vim.v.shell_error ~= 0 then return nil end
      branch = vim.trim(branch)
      require('mini.visits')[action](branch)
    end
    vim.keymap.set('n', '<Leader>' .. keys, rhs, { desc = desc })
  end

  map_branch('vb', 'add_label',    '브랜치 라벨 추가')
  map_branch('vB', 'remove_label', '브랜치 라벨 제거')
  ```

---

### setup() {#minivisits.setup .help-syntax-right-anchor}

<p align="center">`MiniVisits.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minivisits.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniVisits.config](mini-visits.qmd#minivisits.config)를 참조하세요.

#### 사용법 {#minivisits.setup-usage}



  ```lua
  require('mini.visits').setup() -- 기본 설정 사용
  -- 또는
  require('mini.visits').setup({}) -- {}를 사용자의 설정 테이블로 교체
  ```

---

### config {#minivisits.config .help-syntax-right-anchor}

<p align="center">`MiniVisits.config`</p>
#### 기본값 {#minivisits.config-defaults}



  ```lua
  MiniVisits.config = {
    -- 방문 인덱스가 경로 목록으로 변환되는 방법
    list = {
      -- 포함할 경로에 대한 서술어(기본적으로 전체 포함)
      filter = nil,

      -- 방문 데이터를 기반으로 경로 정렬(기본적으로 견고한 frecency)
      sort = nil,
    },

    -- 오류가 아닌 피드백 표시를 비활성화할지 여부
    silent = false,

    -- 방문 인덱스가 저장되는 방법
    store = {
      -- Neovim이 종료되기 전에 모든 방문을 기록할지 여부
      autowrite = true,

      -- 작성된 인덱스가 관련성이 있는지 확인하는 함수
      normalize = nil,

      -- 방문 인덱스를 저장할 경로
      path = vim.fn.stdpath('data') .. '/mini-visits-index',
    },

    -- 방문 추적 방법
    track = {
      -- 이 이벤트에서 방문 등록 타이머 시작
      -- 이를 자동으로 수행하지 않으려면 빈 문자열(`''`)을 제공하세요
      event = 'BufEnter',

      -- 방문을 등록하기 위한 이벤트 후의 디바운스 지연 시간
      delay = 1000,
    },
  }
  ```

#### List {#minivisits.config-list}


<a name="minivisits.config.list" href="mini-visits.qmd#minivisits.config.list"><b>MiniVisits.config.list</b></a>

`config.list`는 방문 인덱스가 기본적으로 경로 목록으로 변환되는 방식을 정의합니다.

`list.filter`는 경로 데이터를 받아 이 경로가 목록에 있어야 하는 경우 `true`를 반환해야 하는
호출 가능한 객체입니다.
기본값: [MiniVisits.gen\_filter.default()](mini-visits.qmd#minivisits.gen_filter.default)의 출력.

경로 데이터는 최소한 다음 필드를 포함하는 테이블입니다:

- <span class="help-syntax-keys">\<path\></span> `(string)` - 방문의 절대 경로.

- <span class="help-syntax-keys">\<count\></span> `(number)` - 방문 횟수.

- <span class="help-syntax-keys">\<latest\></span> `(number)` - 최신 방문의 타임스탬프.

- <span class="help-syntax-keys">\<labels\></span> `(table|nil)` - 라벨 테이블(`true` 값을 가진 문자열 키 포함).

참고:

- `count`와 `latest`는 (이론적으로) 어떤 숫자라도 될 수 있습니다. 하지만 내장된 추적은
  양의 정수 `count`와 [os.time()](https://neovim.io/doc/user/helptag.html?tag=os.time\(\))에서 오는 `latest`를 결과로 생성합니다.

- 사용자가 인덱스 항목으로 설정한 경우 다른 항목이 있을 수 있습니다.

`list.sort`는 경로 데이터 배열을 받아 정렬된 경로 데이터 배열(또는 적어도 각 테이블에
<span class="help-syntax-keys">\<path\></span> 필드가 포함된 테이블)을 반환해야 하는 호출 가능한 객체입니다.
기본값: [MiniVisits.gen\_sort.default()](mini-visits.qmd#minivisits.gen_sort.default)의 출력.
단일 경로 데이터 항목은 `list.filter`와 동일한 구조를 가진 테이블입니다.

참고로 `list.sort`는 필터링, 정렬 또는 입력과 무관한 경로를 반환하는 데 모두 사용될 수 있습니다.

#### Silent {#minivisits.config-silent}


`config.silent`는 오류가 아닌 피드백(라벨 추가/제거 등)을 표시할지 여부를 제어하는 부울 값입니다.
기본값: `false`.

#### Store {#minivisits.config-store}


`config.store`는 여러 세션에서 영구 데이터를 활성화하기 위해 방문 인덱스가 디스크에
저장되는 방식을 정의합니다.

`store.autowrite`는 [VimLeavePre](https://neovim.io/doc/user/helptag.html?tag=VimLeavePre) 이벤트 시 디스크에 방문 데이터를 기록할지 여부를 제어하는
부울 값입니다. 기본값: `true`.

`store.normalize`는 방문 인덱스( [MiniVisits 인덱스 사양](mini-visits.qmd#minivisits-index-specification) 참조)를 입력으로 받아
"정규화된" 방문 인덱스를 출력으로 반환해야 하는 호출 가능한 객체입니다.
이는 방문 인덱스가 최신 상태이고 관련 데이터만 포함하도록 하는 데 사용됩니다.
예를 들어, 오래되고 관련 없는 방문을 "잊어버리는" 방법 등을 제어합니다.
기본값: [MiniVisits.gen\_normalize.default()](mini-visits.qmd#minivisits.gen_normalize.default)의 출력.

`store.path`는 방문 인덱스가 작성되는 경로입니다. 자세한 내용은 [MiniVisits 인덱스 사양](mini-visits.qmd#minivisits-index-specification)의
"저장소" 섹션을 참조하세요.
참고: 명시적으로 설정되지 않은 경로( [VimLeavePre](https://neovim.io/doc/user/helptag.html?tag=VimLeavePre)의 경로 포함)에 대한 쓰기를
비활성화하려면 빈 문자열로 설정하세요.
기본값: [\$XDG\_DATA\_HOME](https://neovim.io/doc/user/helptag.html?tag=$XDG_DATA_HOME) 내부의 "mini-visits-index" 파일.

#### Track {#minivisits.config-track}


`config.track`은 방문이 추적되는 방식(인덱스 항목 자동 업데이트)을 정의합니다.
자세한 내용은 [MiniVisits 개요](mini-visits.qmd#minivisits-overview)의 "방문 추적" 섹션을 참조하세요.

`track.event`는 추적을 트리거하는 올바른 Neovim [<span class="help-syntax-special">{event}</span>](https://neovim.io/doc/user/helptag.html?tag={event})입니다.
참고: 자동 추적을 비활성화하려면 빈 문자열로 설정하세요.
기본값: [BufEnter](https://neovim.io/doc/user/helptag.html?tag=BufEnter).

`track.delay`는 이벤트가 트리거되고 방문이 자동으로 등록된 후의 밀리초 단위 지연 시간입니다.
기본값: 1000 (중간 버퍼를 추적하지 않고 버퍼 간 탐색을 허용하기 위함).

---

### register_visit() {#minivisits.register_visit .help-syntax-right-anchor}

<p align="center">`MiniVisits.register_visit`(<span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>)</p>
방문 등록

단계:

- 경로-cwd 쌍에 대한 항목이 있는지 확인합니다.

- 방문 `count`에 1을 더합니다.

- `latest` 방문 시간을 현재 시간과 동일하게 설정합니다.

#### 매개변수 {#minivisits.register_visit-parameters}



<span class="help-syntax-special">{path}</span> `(string|nil)` 방문 경로. 기본값: 일반적인 경우 현재 버퍼의 경로,
  그렇지 않으면 오류.

<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

---

### add_path() {#minivisits.add_path .help-syntax-right-anchor}

<p align="center">`MiniVisits.add_path`(<span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>)</p>
인덱스에 경로 추가

경로-cwd 쌍에 대한 하나 이상의 항목이 있는지 확인합니다. 항목이 이미 존재하는 경우
아무 작업도 수행하지 않습니다. 존재하지 않는 경우 `count`와 `latest`를 모두 0으로
설정하여 생성합니다.

#### 매개변수 {#minivisits.add_path-parameters}



<span class="help-syntax-special">{path}</span> `(string|nil)` 방문 경로. `cwd`에 대해 "방문한 모든 경로"를 의미하도록
  빈 문자열일 수 있습니다. 기본값: 일반적인 경우 현재 버퍼의 경로, 그렇지 않으면 오류.

<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). "방문한 모든 cwd"를
  의미하도록 빈 문자열일 수 있습니다. 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

---

### add_label() {#minivisits.add_label .help-syntax-right-anchor}

<p align="center">`MiniVisits.add_label`(<span class="help-syntax-special">{label}</span>, <span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>)</p>
경로에 라벨 추가

단계:

- 경로-cwd 쌍에 대한 항목이 있는지 확인합니다.

- 항목에 라벨을 추가합니다.

#### 매개변수 {#minivisits.add_label-parameters}



<span class="help-syntax-special">{label}</span> `(string|nil)` 라벨 문자열. 기본값: `nil` (사용자에게 요청).

<span class="help-syntax-special">{path}</span> `(string|nil)` 방문 경로. `cwd`에 대해 "방문한 모든 경로"를 의미하도록
  빈 문자열일 수 있습니다. 기본값: 일반적인 경우 현재 버퍼의 경로, 그렇지 않으면 오류.

<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). "방문한 모든 cwd"를
  의미하도록 빈 문자열일 수 있습니다. 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

---

### remove_path() {#minivisits.remove_path .help-syntax-right-anchor}

<p align="center">`MiniVisits.remove_path`(<span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>)</p>
경로 제거

인덱스에서 경로-cwd 쌍에 대한 하나 이상의 항목을 삭제합니다. 항목이 이미 없으면
아무 작업도 수행하지 않습니다.

참고:

- 세션 내 Lua 변수에만 영향을 미칩니다. 영구적으로 유지하려면
  [MiniVisits.write\_index()](mini-visits.qmd#minivisits.write_index)를 호출하세요.

#### 매개변수 {#minivisits.remove_path-parameters}



<span class="help-syntax-special">{path}</span> `(string|nil)` 방문 경로. `cwd`에 대해 "방문한 모든 경로"를 의미하도록
  빈 문자열일 수 있습니다. 기본값: 일반적인 경우 현재 버퍼의 경로, 그렇지 않으면 오류.

<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). "방문한 모든 cwd"를
  의미하도록 빈 문자열일 수 있습니다. 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

---

### remove_label() {#minivisits.remove_label .help-syntax-right-anchor}

<p align="center">`MiniVisits.remove_label`(<span class="help-syntax-special">{label}</span>, <span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>)</p>
경로에서 라벨 제거

단계:

- 하나 이상의 인덱스 항목에서 라벨을 제거합니다.

- 항목의 마지막 라벨인 경우 `labels` 키를 제거합니다.

#### 매개변수 {#minivisits.remove_label-parameters}



<span class="help-syntax-special">{label}</span> `(string|nil)` 라벨 문자열. 기본값: `nil` (사용자에게 요청).

<span class="help-syntax-special">{path}</span> `(string|nil)` 방문 경로. `cwd`에 대해 "방문한 모든 경로"를 의미하도록
  빈 문자열일 수 있습니다. 기본값: 일반적인 경우 현재 버퍼의 경로, 그렇지 않으면 오류.

<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). "방문한 모든 cwd"를
  의미하도록 빈 문자열일 수 있습니다. 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

---

### list_paths() {#minivisits.list_paths .help-syntax-right-anchor}

<p align="center">`MiniVisits.list_paths`(<span class="help-syntax-special">{cwd}</span>, <span class="help-syntax-special">{opts}</span>)</p>
방문 경로 나열

특정 cwd의 방문 인덱스를 방문한 경로의 정렬된 목록으로 변환합니다.
사용자 정의 필터링 및 정렬을 지원합니다.

예제:

  ```lua
  -- 가장 최근 방문 순으로 정렬된 경로 가져오기
  local sort_recent = MiniVisits.gen_sort.default({ recency_weight = 1 })
  MiniVisits.list_paths(nil, { sort = sort_recent })

  -- 모든 cwd에서 가장 빈번하게 방문한 순으로 정렬된 경로 가져오기
  local sort_frequent = MiniVisits.gen_sort.default({ recency_weight = 0 })
  MiniVisits.list_paths('', { sort = sort_frequent })

  -- 숨김 파일을 제외한 경로 가져오기
  local is_not_hidden = function(path_data)
    return not vim.startswith(vim.fn.fnamemodify(path_data.path, ':t'), '.')
  end
  MiniVisits.list_paths(nil, { filter = is_not_hidden })
  ```

#### 매개변수 {#minivisits.list_paths-parameters}



<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). "방문한 모든 cwd"를
  의미하도록 빈 문자열일 수 있습니다. 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<filter\></span> `(function)` - 경로를 필터링하는 서술어. 사용 방법에 대한 자세한 내용은
    [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.
    기본값: 기본값으로 [MiniVisits.gen\_filter.default()](mini-visits.qmd#minivisits.gen_filter.default)를 사용하는
    `config.list.filter` 값.

  - <span class="help-syntax-keys">\<sort\></span> `(function)` - 경로 데이터 정렬기. 사용 방법에 대한 자세한 내용은
    [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.
    기본값: 기본값으로 `config.list.sort` 또는 [MiniVisits.gen\_sort.default()](mini-visits.qmd#minivisits.gen_sort.default)를
    사용하는 값.

#### 반환 {#minivisits.list_paths-return}


`(table)` 방문한 경로의 배열.

---

### list_labels() {#minivisits.list_labels .help-syntax-right-anchor}

<p align="center">`MiniVisits.list_labels`(<span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>, <span class="help-syntax-special">{opts}</span>)</p>
방문 라벨 나열

특정 경로-cwd 쌍의 방문 인덱스를 정렬된 라벨 목록으로 변환합니다.
경로에 대한 사용자 정의 필터링을 지원합니다. 결과는 가장 빈번한 라벨부터 정렬됩니다.

예제:

  ```lua
  -- 현재 경로-cwd 쌍에 대한 라벨 가져오기
  MiniVisits.list_labels()

  -- 모든 cwd에서 현재 경로에 대한 라벨 가져오기
  MiniVisits.list_labels(nil, '')

  -- 숨김 파일을 제외한 모든 사용 가능한 라벨 가져오기
  local is_not_hidden = function(path_data)
    return not vim.startswith(vim.fn.fnamemodify(path_data.path, ':t'), '.')
  end
  MiniVisits.list_labels('', '', { filter = is_not_hidden })
  ```

#### 매개변수 {#minivisits.list_labels-parameters}



<span class="help-syntax-special">{path}</span> `(string|nil)` 방문 경로. `cwd`에 대해 "방문한 모든 경로"를 의미하도록
  빈 문자열일 수 있습니다. 기본값: 일반적인 경우 현재 버퍼의 경로, 그렇지 않으면 오류.

<span class="help-syntax-special">{cwd}</span> `(string|nil)` 방문 cwd (프로젝트 디렉토리). "방문한 모든 cwd"를
  의미하도록 빈 문자열일 수 있습니다. 기본값: [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory).

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<filter\></span> `(function)` - 경로를 필터링하는 서술어. 사용 방법에 대한 자세한 내용은
    [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.
    기본값: 기본값으로 [MiniVisits.gen\_filter.default()](mini-visits.qmd#minivisits.gen_filter.default)를 사용하는
    `config.list.filter` 값.

  - <span class="help-syntax-keys">\<sort\></span> `(function)` - 경로 데이터 정렬기. 사용 방법에 대한 자세한 내용은
    [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.
    기본값: 기본값으로 `config.list.sort` 또는 [MiniVisits.gen\_sort.default()](mini-visits.qmd#minivisits.gen_sort.default)를
    사용하는 값.

#### 반환 {#minivisits.list_labels-return}


`(table)` 사용 가능한 라벨의 배열.

---

### select_path() {#minivisits.select_path .help-syntax-right-anchor}

<p align="center">`MiniVisits.select_path`(<span class="help-syntax-special">{cwd}</span>, <span class="help-syntax-special">{opts}</span>)</p>
방문 경로 선택

[MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)의 출력과 함께 [vim.ui.select()](https://neovim.io/doc/user/helptag.html?tag=vim.ui.select\(\))를 사용하고
선택한 항목에서 [:edit](https://neovim.io/doc/user/helptag.html?tag=:edit)를 호출합니다.

참고: [mini.pick](mini-pick.qmd#mini.pick)을 사용하는 경우 [MiniExtra.pickers.visit\_labels()](mini-extra.qmd#miniextra.pickers.visit_labels)
및 [MiniExtra.pickers.visit\_paths()](mini-extra.qmd#miniextra.pickers.visit_paths)를 고려하세요.

예제:


- 모든 방문 경로에서 선택: `MiniVisits.select_path('')`


- 현재 디렉토리 아래의 경로 중에서 가장 최근 방문 순으로 선택:

    ```lua
    local sort_recent = MiniVisits.gen_sort.default({ recency_weight = 1 })
    MiniVisits.select_path(nil, { sort = sort_recent })
    ```

#### 매개변수 {#minivisits.select_path-parameters}



<span class="help-syntax-special">{cwd}</span> [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.

<span class="help-syntax-special">{opts}</span> [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.

---

### select_label() {#minivisits.select_label .help-syntax-right-anchor}

<p align="center">`MiniVisits.select_label`(<span class="help-syntax-special">{path}</span>, <span class="help-syntax-special">{cwd}</span>, <span class="help-syntax-special">{opts}</span>)</p>
방문 라벨 선택

[MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)의 출력과 함께 [vim.ui.select()](https://neovim.io/doc/user/helptag.html?tag=vim.ui.select\(\))를 사용하고
선택한 라벨이 있는 대상 경로를 가져오기 위해 [MiniVisits.select\_path()](mini-visits.qmd#minivisits.select_path)를 호출합니다.

참고: [mini.pick](mini-pick.qmd#mini.pick)을 사용하는 경우 [MiniExtra.pickers.visit\_labels()](mini-extra.qmd#miniextra.pickers.visit_labels)를 고려하세요.

예제:


- 현재 경로의 라벨 중에서 선택: `MiniVisits.select_label()`


- 모든 방문한 라벨 중에서 선택: `MiniVisits.select_label('', '')`


- 현재 프로젝트 라벨 중에서 선택하고 (선택 후) 경로를 가장 최근 순으로 정렬:

    ```lua
    local sort_recent = MiniVisits.gen_sort.default({ recency_weight = 1 })
    MiniVisits.select_label('', nil, { sort = sort_recent })
    ```

#### 매개변수 {#minivisits.select_label-parameters}



<span class="help-syntax-special">{path}</span> [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)로 전달됩니다.

<span class="help-syntax-special">{cwd}</span> [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)로 전달됩니다.

<span class="help-syntax-special">{opts}</span> [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels) 및
 (라벨을 선택한 후) [MiniVisits.select\_path()](mini-visits.qmd#minivisits.select_path)로 모두 전달됩니다.

---

### iterate_paths() {#minivisits.iterate_paths .help-syntax-right-anchor}

<p align="center">`MiniVisits.iterate_paths`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{cwd}</span>, <span class="help-syntax-special">{opts}</span>)</p>
방문 경로 반복

단계:

- [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)를 사용하여 대상 경로의 정렬된 배열을 계산합니다.

- 현재 버퍼의 경로를 기반으로 배열 내부의 현재 인덱스를 식별합니다.

- 전용 방향으로 배열을 일정 횟수만큼 반복합니다:

    - "first" 방향 - 인덱스 0부터 정방향으로 시작 (단일 첫 번째 반복이 첫 번째 경로로 연결됨).

    - "backward" 방향 - 현재 인덱스부터 역방향으로 시작.

    - "forward" 방향 - 현재 인덱스부터 정방향으로 시작.

    - "last" 방향 - 마지막 다음 인덱스부터 역방향으로 시작 (단일 첫 번째 반복이 마지막 경로로 연결됨).

참고:

- 주로 매핑으로 사용되도록 설계되었습니다. `MiniVisits-예제`를 참조하세요.

- 현재 버퍼의 경로가 `MiniVisits.list_paths()`의 출력에 없는 경우,
  첫 번째 반복이 (정방향으로 반복하는 경우) 첫 번째 항목에 안착하거나
  (역방향으로 반복하는 경우) 마지막 항목에 안착하도록 시작 인덱스가 유추됩니다.

- 이 함수를 통한 탐색은 추적되지 않습니다 ([MiniVisits-개요](mini-visits.qmd#minivisits-overview) 참조).
  이는 기본 경로 목록에 영향을 주지 않고 연속적으로 적용할 수 있도록 하기 위함입니다.

기본 파일 배열이 `{ "file1", "file2", "file3" }`이라고 가정한 예:


- `MiniVisits("first")`는 "file1"에 집중하게 됩니다.

- "file3"에서 `MiniVisits("backward", { n_times = 2 })`는 "file1"로 이어집니다.

- "file1"에서 `MiniVisits("forward", { n_times = 10 })`은 "file3"으로 이어집니다.

- `MiniVisits("last", { n_times = 4, wrap = true })`는 "file3"으로 이어집니다.

#### 매개변수 {#minivisits.iterate_paths-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나.

<span class="help-syntax-special">{cwd}</span> [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<filter\></span> `(function)` - [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.

  - <span class="help-syntax-keys">\<sort\></span> `(function)` - [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 특정 방향으로 이동할 단계 수.
    기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 목록 가장자리를 넘을 때 감싸기(wrap) 여부. 기본값: `false`.

---

### get_index() {#minivisits.get_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.get_index`()</p>
활성 방문 인덱스 가져오기

#### 반환 {#minivisits.get_index-return}


`(table)` 현재 활성 방문 인덱스 테이블의 복사본.

---

### set_index() {#minivisits.set_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.set_index`(<span class="help-syntax-special">{index}</span>)</p>
활성 방문 인덱스 설정

#### 매개변수 {#minivisits.set_index-parameters}



<span class="help-syntax-special">{index}</span> `(table)` 방문 인덱스 테이블.

---

### reset_index() {#minivisits.reset_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.reset_index`()</p>
활성 방문 인덱스 초기화

현재 활성 방문 인덱스를 [MiniVisits.read\_index()](mini-visits.qmd#minivisits.read_index)의 출력으로 설정합니다.
인덱스 읽기에 실패하면 아무 작업도 수행하지 않습니다.

---

### normalize_index() {#minivisits.normalize_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.normalize_index`(<span class="help-syntax-special">{index}</span>)</p>
방문 인덱스 정규화

입력 인덱스 개체에 `config.store.normalize` (기본적으로 [MiniVisits.gen\_normalize.default()](mini-visits.qmd#minivisits.gen_normalize.default))를
적용하고 출력을 반환합니다(인덱스 개체의 정의에 맞는 경우.
[MiniVisits 인덱스 사양](mini-visits.qmd#minivisits-index-specification) 참조).

#### 매개변수 {#minivisits.normalize_index-parameters}



<span class="help-syntax-special">{index}</span> `(table|nil)` 인덱스 개체. 기본값: 현재 인덱스의 복사본.

#### 반환 {#minivisits.normalize_index-return}


`(table)` 정규화된 인덱스 개체.

---

### read_index() {#minivisits.read_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.read_index`(<span class="help-syntax-special">{store_path}</span>)</p>
디스크에서 방문 인덱스 읽기

#### 매개변수 {#minivisits.read_index-parameters}



<span class="help-syntax-special">{store_path}</span> `(string|nil)` 방문 인덱스 데이터가 포함된 디스크 상의 경로.
  기본값: `config.store.path`.
  참고:

  - 경로가 빈 문자열이거나 파일을 읽을 수 없는 경우 `nil`을 반환할 수 있습니다.

  - 파일은 일반 Lua 파일처럼 [dofile()](https://neovim.io/doc/user/helptag.html?tag=dofile\(\))로 소스화됩니다.

#### 반환 {#minivisits.read_index-return}


`(table|nil)` 파일 소스의 출력.

---

### write_index() {#minivisits.write_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.write_index`(<span class="help-syntax-special">{store_path}</span>, <span class="help-syntax-special">{index}</span>)</p>
디스크에 방문 인덱스 기록

단계:

- [MiniVisits.normalize\_index()](mini-visits.qmd#minivisits.normalize_index)를 사용하여 인덱스를 정규화합니다.

- 경로가 유효한지 확인합니다(모든 상위 디렉토리가 생성되었는지 등).

- [MiniVisits.read\_index()](mini-visits.qmd#minivisits.read_index)로 읽을 수 있도록 인덱스 개체를 경로에 기록합니다.

#### 매개변수 {#minivisits.write_index-parameters}



<span class="help-syntax-special">{store_path}</span> `(string|nil)` 방문 인덱스 데이터를 기록할 디스크 상의 경로.
  기본값: `config.store.path`. 참고: 빈 문자열인 경우 아무것도 기록되지 않습니다.

<span class="help-syntax-special">{index}</span> `(table|nil)` 디스크에 기록할 인덱스 개체.
  기본값: 현재 세션 인덱스.

---

### rename_in_index() {#minivisits.rename_in_index .help-syntax-right-anchor}

<p align="center">`MiniVisits.rename_in_index`(<span class="help-syntax-special">{path_from}</span>, <span class="help-syntax-special">{path_to}</span>, <span class="help-syntax-special">{index}</span>)</p>
인덱스 내 경로 이름 변경

방문 데이터를 보존하기 위해 경로 이름 변경/이동에 반응하는 헬퍼입니다.
파일 및 디렉토리 경로 모두에 작동합니다.

참고:

- 현재 인덱스를 업데이트하지 않고 수정된 인덱스 개체를 반환합니다.
  현재 인덱스로 만들려면 [MiniVisits.set\_index()](mini-visits.qmd#minivisits.set_index)를 사용하세요.

- 전체 경로만 사용하세요.

- 디렉토리 경로에 `/`를 추가하지 마세요. 파일과 동일한 형식을 사용하세요.

`path_from` 및 `path_to`가 이름 변경/이동 전후의 전체 경로를 포함하는 변수라고
가정할 때, 현재 인덱스를 업데이트하는 예제입니다:

  ```lua
  local new_index = MiniVisits.rename_in_index(path_from, path_to)
  MiniVisits.set_index(new_index)
  ```

#### 매개변수 {#minivisits.rename_in_index-parameters}



<span class="help-syntax-special">{path_from}</span> `(string)` 이름을 변경할 전체 경로.

<span class="help-syntax-special">{path_to}</span> `(string)` 대체할 전체 경로.

<span class="help-syntax-special">{index}</span> `(table|nil)` 이름 변경을 수행할 인덱스 개체.
  기본값: 현재 세션 인덱스.

#### 반환 {#minivisits.rename_in_index-return}


`(table)` 경로 이름이 변경된 인덱스 개체.

---

### gen_filter {#minivisits.gen_filter .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_filter`</p>
필터 함수 생성

이것은 함수 요소가 있는 테이블입니다. 실제로 사양을 가져오려면 호출하세요.

---

### gen_filter.default() {#minivisits.gen_filter.default .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_filter.default`()</p>
기본 필터

항상 `true`를 반환하여 실제 필터링을 수행하지 않습니다.

#### 반환 {#minivisits.gen_filter.default-return}


`(function)` 방문 필터 함수. 자세한 내용은 [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.

---

### gen_filter.this_session() {#minivisits.gen_filter.this_session .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_filter.this_session`()</p>
현재 세션의 방문 필터링

#### 반환 {#minivisits.gen_filter.this_session-return}


`(function)` 방문 필터 함수. 자세한 내용은 [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.

---

### gen_sort {#minivisits.gen_sort .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_sort`</p>
정렬 함수 생성

이것은 함수 요소가 있는 테이블입니다. 실제로 사양을 가져오려면 호출하세요.

---

### gen_sort.default() {#minivisits.gen_sort.default .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_sort.default`(<span class="help-syntax-special">{opts}</span>)</p>
기본 정렬

"견고한 frecency" 접근 방식을 사용하여 경로를 정렬합니다. 순위 연산에 의존합니다:
특정 기준 번호를 바탕으로 모든 항목에 1(최고)부터 항목 수(최악) 사이의 숫자를 할당합니다.
동점은 "평균 순위" 접근 방식으로 처리됩니다. 기준 번호가 동일한 각 요소에는 해당 요소들 간의
평균 순위가 할당됩니다. 이 방식을 통해 총 순위 합계는 경로 수에만 의존하게 됩니다.

알고리즘 개요입니다:

- 빈도(`count` 값)를 기준으로 경로 순위 지정: 가장 빈번한 것부터 빈도가 낮은 것 순으로.

- 최신성(`latest` 값)을 기준으로 경로 순위 지정: 가장 최근 것부터 오래된 것 순으로.

- 이전 단계의 순위를 가중치와 결합:
  `score = (1 - w) * rank_frequency + w * rank_recency`, 여기서 `w`는 "최신성 가중치"입니다.
  이 가중치가 작을수록 최신성이 결과에 미치는 영향이 줄어듭니다.

예제:

- 기본 최신성 가중치 0.5는 "견고한 frecency" 정렬을 결과로 생성합니다: 빈도와 최신성을 모두 결합합니다.
  실제 값이 결과에 직접적인 영향을 주지 않고 순서만 중요하기 때문에 이를 "견고한 frecency"라고 부릅니다.
  예를 들어, 매우 빈번한 파일의 `count = 100`이고 다른 모든 파일의 `count = 5`인 경우,
  해당 파일이 매우 최근의 것이 아닌 한 결과를 대폭 지배하지는 않습니다.


- 최신성 가중치가 1이면 "가장 최근 것부터 가장 오래된 것 순으로" 정렬됩니다.


- 최신성 가중치가 0이면 "가장 빈번한 것부터 빈도가 가장 낮은 것 순으로" 정렬됩니다.

#### 매개변수 {#minivisits.gen_sort.default-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<recency_weight\></span> `(number)` - 최신성 가중치를 위한 0과 1 사이의 숫자.
    기본값: 0.5.

#### 반환 {#minivisits.gen_sort.default-return}


`(function)` 방문 정렬 함수. 자세한 내용은 [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.

---

### gen_sort.z() {#minivisits.gen_sort.z .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_sort.z`()</p>
Z 정렬

https://github.com/rupa/z 와 같이 정렬합니다.

#### 반환 {#minivisits.gen_sort.z-return}


`(function)` 방문 정렬 함수. 자세한 내용은 [MiniVisits.config.list](mini-visits.qmd#minivisits.config.list)를 참조하세요.

---

### gen_normalize {#minivisits.gen_normalize .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_normalize`</p>
정규화 함수 생성

이것은 함수 요소가 있는 테이블입니다. 실제로 사양을 가져오려면 호출하세요.

---

### gen_normalize.default() {#minivisits.gen_normalize.default .help-syntax-right-anchor}

<p align="center">`MiniVisits.gen_normalize.default`(<span class="help-syntax-special">{opts}</span>)</p>
기본 정규화 함수 생성

단계:

- 방문 가지치기(Prune), 즉 오래된 방문 제거:

    - `count` 방문 횟수가 가지치기 임계값 미만인 경우, 특정 cwd에서 해당 방문 항목을 제거합니다
      (다른 cwd에는 여전히 존재할 수 있음).

    - 첫 번째 수준(cwd) 또는 두 번째 수준(경로) 키가 디스크 상의 실제 경로를 나타내지 않는 경우,
      관련된 값 전체를 제거합니다.

    - 참고: 방문에 라벨이 있는 경우 자동으로 가지치기되지 않습니다.


- 방문 감쇠(Decay), 즉 방문을 더 오래된 것으로 만들 수 있습니다. 이는 전체 유용성에 중요한 부분입니다:
  가지치기와 함께 사용하면 오래전에 방문하여 관련 없는 경로를 자동으로 제거하는 결과를 낳습니다.

  감쇠는 총 `count` 값의 합계가 감쇠 임계값을 초과하는 경우 cwd별로 수행됩니다.
  각 `count`에 동일한 계수를 곱하여 새로운 `count` 총합이 더 작은 목표 값과 같아지도록 하여 수행됩니다.
  참고: 소수점 이하 두 자리까지만 보존되므로 합계가 정확하지 않을 수 있습니다.


- 가지치기를 한 번 더 수행하여 감쇠 후 오래된 경로가 없는지 확인합니다.

#### 매개변수 {#minivisits.gen_normalize.default-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<decay_threshold\></span> `(number)` - 감쇠 임계값. 기본값: 1000.

  - <span class="help-syntax-keys">\<decay_target\></span> `(number)` - 감쇠 목표. 기본값: 800.

  - <span class="help-syntax-keys">\<prune_threshold\></span> `(number)` - 가지치기 임계값. 기본값: 0.5.

  - <span class="help-syntax-keys">\<prune_paths\></span> `(boolean)` - 오래된 경로를 가지치기할지 여부. 기본값: `true`.

#### 반환 {#minivisits.gen_normalize.default-return}


`(function)` 방문 인덱스 정규화 함수. [MiniVisits.config](mini-visits.qmd#minivisits.config)의 "Store"를 참조하세요.
