---
title: "mini.basics 문서"
---

_'mini.nvim'의 `main` 브랜치에서 생성됨_

<a name="mini.basics" href="mini-basics.qmd#mini.basics"><b>mini.basics</b></a> 일반적인 설정 프리셋

MIT 라이선스 Copyright (c) 2023 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

설치하고, 'init.lua'를 생성하고, `require('mini.basics').setup()`을 추가하면 준비가 끝납니다.

기능:

- 일반적인 옵션들을 위한 프리셋. 옵션이 이전에 수동으로 설정되지 않은 경우에만 변경합니다. 자세한 내용은 [MiniBasics.config.options](mini-basics.qmd#minibasics.config.options)를 참조하십시오.


- 일반적인 매핑들을 위한 프리셋. 매핑이 이전에 수동으로 생성되지 않은 경우에만 추가합니다. 자세한 내용은 [MiniBasics.config.mappings](mini-basics.qmd#minibasics.config.mappings).


- 일반적인 자동 명령(autocommands)들을 위한 프리셋. 자세한 내용은 [MiniBasics.config.autocommands](mini-basics.qmd#minibasics.config.autocommands).


- 하위 호환성을 최우선으로 합니다. 이미 존재하는 동작을 변경하기 위한 모든 결정은 신중하게 이루어집니다.

참고:

- 이 모듈의 주요 목표는 비교적 새로운 Neovim 사용자에게 더 나은 "기본 설치 상태에서의 사용(works out of the box)" 경험을 제공하는 동시에 공부할 수 있는 관련 옵션/매핑/자동 명령을 문서화하여 제공하는 것입니다. 이는 부분적으로 Neovim 사용자 간의 설문 조사를 기반으로 하며 부분적으로는 개인적인 선호도에서 비롯됩니다.

  하지만 숙련된 사용자들도 유용한 것을 찾을 수 있을 것입니다.

  그래도 사용된 옵션/매핑/자동 명령에 대해 읽어보고 필요한지 결정하는 것이 권장됩니다. 그렇게 하는 주된 방법은 Neovim의 도움말 페이지(도움말 파일에 링크됨)와 이 모듈의 소스 코드(더 쉬운 이해를 위해 철저하게 문서화됨)를 읽는 것입니다.

#### 설정 {#module-setup}


이 모듈은 `require('mini.basics').setup({})`을 통한 설정이 필요합니다 (`{}`를 `config` 테이블로 교체). 스크립팅에 사용하거나 수동으로 (`:lua MiniBasics.*` 사용) 사용할 수 있는 전역 Lua 테이블 `MiniBasics`가 생성됩니다.

사용 가능한 구성 설정은 [MiniBasics.config](mini-basics.qmd#minibasics.config)를 참조하십시오.

모듈이 에러가 아닌 피드백을 표시하지 않도록 하려면 `config.silent = true`로 설정하십시오.

#### 비교 {#module-comparisons}



- [tpope/vim-sensible](https://github.com/tpope/vim-sensible):

    - 'tpope/vim-sensible'의 대부분은 이미 Neovim의 기본 옵션으로 통합되었습니다 ([nvim-defaults](https://neovim.io/doc/user/helptag.html?tag=nvim-defaults) 참조). 이 모듈은 훨씬 더 광범위한 영향을 미칩니다.

- [tpope/vim-unimpaired](https://github.com/tpope/vim-unimpaired):

    - 'tpope/vim-unimpaired'에는 `yo` 접두사를 사용하여 옵션을 토글하는 매핑이 있습니다. 이 모듈은 `\` 접두사를 사용하여 유사한 기능을 구현합니다 ([MiniBasics.config.mappings](mini-basics.qmd#minibasics.config.mappings) 참조).

---

### setup() {#minibasics.setup .help-syntax-right-anchor}

<p align="center">`MiniBasics.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minibasics.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 구성 테이블. [MiniBasics.config](mini-basics.qmd#minibasics.config)를 참조하십시오.

#### 사용법 {#minibasics.setup-usage}



  ```lua
  require('mini.basics').setup() -- 기본 설정 사용
  -- 또는
  require('mini.basics').setup({}) -- {}를 사용자 구성 테이블로 교체
  ```

---

### config {#minibasics.config .help-syntax-right-anchor}

<p align="center">`MiniBasics.config`</p>
#### 기본값 {#minibasics.config-defaults}



  ```lua
  MiniBasics.config = {
    -- 옵션. 필드를 `false`로 설정하면 비활성화됩니다.
    options = {
      -- 기본 옵션 ('number', 'ignorecase' 등 다수)
      basic = true,

      -- 추가 UI 기능 ('winblend', 'listchars', 'pumheight' 등)
      extra_ui = false,

      -- 창 테두리 프리셋 ('single', 'double' 등)
      -- 기본값 'auto'는 'winborder' 옵션에서 유추합니다.
      win_borders = 'auto',
    },

    -- 매핑. 필드를 `false`로 설정하면 비활성화됩니다.
    mappings = {
      -- 기본 매핑 (더 나은 'jk', Ctrl+S로 저장 등)
      basic = true,

      -- 일반 옵션을 토글하는 매핑의 접두사 ('wrap', 'spell' 등).
      -- 이러한 매핑을 생성하지 않으려면 빈 문자열을 입력하십시오.
      option_toggle_prefix = [[\]],

      -- <C-hjkl>로 창 이동, <C-arrow>로 크기 조정
      windows = false,

      -- Insert, Command, Terminal 모드에서 <M-hjkl>로 커서 이동
      move_with_alt = false,
    },

    -- 자동 명령. 필드를 `false`로 설정하면 비활성화됩니다.
    autocommands = {
      -- 기본 자동 명령 (yank 시 강조 표시, 터미널에서 Insert 시작 등)
      basic = true,

      -- 줄 단위 및 블록 단위 Visual 모드에서만 'relativenumber' 설정
      relnum_in_visual_mode = false,
    },

    -- 에러가 아닌 피드백 표시 비활성화 여부
    silent = false,
  }
  ```

#### 옵션 {#minibasics.config-options}


<a name="minibasics.config.options" href="mini-basics.qmd#minibasics.config.options"><b>MiniBasics.config.options</b></a>

사용 예시:

  ```lua
  require('mini.basics').setup({
    options = {
      basic = true,
      extra_ui = true,
      win_borders = 'double',
    }
  })
  ```

##### options.basic {#minibasics.config-options-options.basic}


`config.options.basic`은 상당히 일반적으로 사용되는 값으로 특정 옵션을 설정합니다 (사용 가능한 Neovim 사전 설정, 공개 dotfile 및 설문 조사를 기반으로 판단).
옵션은 이전에 수동으로 설정되지 않은 경우에만 변경됩니다.
정확한 변경 사항은 소스 코드('lua/mini/basics.lua')를 참조하십시오.

영향을 받는 옵션 목록은 다음과 같습니다 (커서를 올려놓고 [CTRL-]](https://neovim.io/doc/user/helptag.html?tag=CTRL-]))를 누르십시오):

- 일반(General):

    - [<span class="help-syntax-keys">\<Leader\></span>](https://neovim.io/doc/user/helptag.html?tag=<Leader>) 키를 [<span class="help-syntax-keys">\<Space\></span>](https://neovim.io/doc/user/helptag.html?tag=<Space>)로 설정합니다. 이 이후에 모든 Leader 매핑을 수행해야 합니다 (그렇지 않으면 기본 <span class="help-syntax-keys">\<Leader\></span>로 생성됩니다).

    - `:filetype plugin indent on` 실행 ([:filetype-overview](https://neovim.io/doc/user/helptag.html?tag=:filetype-overview) 참조)

    - ['backup'](https://neovim.io/doc/user/helptag.html?tag='backup')

    - ['mouse'](https://neovim.io/doc/user/helptag.html?tag='mouse')

    - ['undofile'](https://neovim.io/doc/user/helptag.html?tag='undofile')

    - ['writebackup'](https://neovim.io/doc/user/helptag.html?tag='writebackup')

- 외관(Appearance)

    - ['breakindent'](https://neovim.io/doc/user/helptag.html?tag='breakindent')

    - ['cursorline'](https://neovim.io/doc/user/helptag.html?tag='cursorline')

    - ['fillchars'](https://neovim.io/doc/user/helptag.html?tag='fillchars')

    - ['linebreak'](https://neovim.io/doc/user/helptag.html?tag='linebreak')

    - ['number'](https://neovim.io/doc/user/helptag.html?tag='number')

    - ['ruler'](https://neovim.io/doc/user/helptag.html?tag='ruler')

    - ['showmode'](https://neovim.io/doc/user/helptag.html?tag='showmode')

    - ['signcolumn'](https://neovim.io/doc/user/helptag.html?tag='signcolumn')

    - ['shortmess'](https://neovim.io/doc/user/helptag.html?tag='shortmess')

    - ['splitbelow'](https://neovim.io/doc/user/helptag.html?tag='splitbelow')

    - ['splitkeep'](https://neovim.io/doc/user/helptag.html?tag='splitkeep')

    - ['splitright'](https://neovim.io/doc/user/helptag.html?tag='splitright')

    - ['termguicolors'](https://neovim.io/doc/user/helptag.html?tag='termguicolors') (Neovim<0.10에서; 이후 버전은 자동으로 활성화됨)

    - ['wrap'](https://neovim.io/doc/user/helptag.html?tag='wrap')

- 편집(Editing)

    - ['completeopt'](https://neovim.io/doc/user/helptag.html?tag='completeopt')

    - ['formatoptions'](https://neovim.io/doc/user/helptag.html?tag='formatoptions')

    - ['ignorecase'](https://neovim.io/doc/user/helptag.html?tag='ignorecase')

    - ['incsearch'](https://neovim.io/doc/user/helptag.html?tag='incsearch')

    - ['infercase'](https://neovim.io/doc/user/helptag.html?tag='infercase')

    - ['smartcase'](https://neovim.io/doc/user/helptag.html?tag='smartcase')

    - ['smartindent'](https://neovim.io/doc/user/helptag.html?tag='smartindent')

    - ['virtualedit'](https://neovim.io/doc/user/helptag.html?tag='virtualedit')

##### options.extra_ui {#minibasics.config-options-options.extra_ui}


`config.options.extra_ui`는 일반적인 선호도와 일치하지 않을 수 있지만 시도해 볼 가치가 있는 시각적 외관을 위한 특정 옵션을 설정합니다.
옵션은 이전에 수동으로 설정되지 않은 경우에만 변경됩니다.
정확한 변경 사항은 소스 코드('lua/mini/basics.lua')를 참조하십시오.

영향을 받는 옵션 목록:

- ['list'](https://neovim.io/doc/user/helptag.html?tag='list')

- ['listchars'](https://neovim.io/doc/user/helptag.html?tag='listchars')

- ['pumblend'](https://neovim.io/doc/user/helptag.html?tag='pumblend')

- ['pumheight'](https://neovim.io/doc/user/helptag.html?tag='pumheight')

- ['winblend'](https://neovim.io/doc/user/helptag.html?tag='winblend')

- `:syntax on` 실행 ([:syntax-on](https://neovim.io/doc/user/helptag.html?tag=:syntax-on) 참조)

##### options.win_borders {#minibasics.config-options-options.win_borders}


`config.options.win_borders`는 창 테두리(`vert`, `horiz`, `msgsep` 등)에 대해 일관된 문자 세트를 갖도록 ['fillchars'](https://neovim.io/doc/user/helptag.html?tag='fillchars')를 업데이트합니다.

사용 가능한 값:

- `'auto'` - ['winborder'](https://neovim.io/doc/user/helptag.html?tag='winborder')에서 유추합니다. Neovim<0.11에서는 아무 작업도 수행하지 않습니다.

- `'bold'` - 굵은 선.

- `'dot'` - 모든 셀에 점 표시.

- `'double'` - 이중 선.

- `'single'` - 단일 선.

- `'solid'` - 기호 없이 배경만 표시.

#### 매핑(Mappings) {#minibasics.config-mappings}


<a name="minibasics.config.mappings" href="mini-basics.qmd#minibasics.config.mappings"><b>MiniBasics.config.mappings</b></a>

사용 예시:

  ```lua
  require('mini.basics').setup({
    mappings = {
      basic = true,
      option_toggle_prefix = [[\]],
      windows = true,
      move_with_alt = true,
    }
  })
  ```

일부 매핑을 다르게 설정하거나 전혀 설정하지 않으려면 [MiniBasics.setup()](mini-basics.qmd#minibasics.setup) 호출 후에 설정하거나 삭제하십시오.

##### mappings.basic {#minibasics.config-mappings-mappings.basic}


`config.mappings.basic`은 일반적으로 매핑되는 특정 작업에 대한 매핑을 생성합니다 (사용 가능한 Neovim 사전 설정 및 공개 dotfile을 기반으로 판단).

일부 매핑은 내장 매핑을 재정의하여 동작을 개선하거나 그다지 유용하지 않은 기본 동작을 재정의합니다.
매핑이 이전에 수동으로 생성되지 않은 경우에만 추가합니다.

생성된 매핑 표는 다음과 같습니다 :

 ```
 |키     |      모드       |                   설명                        |
 |-------|-----------------|-----------------------------------------------|
 | j     | Normal, Visual  | [count] 없이 가시적인 줄을 따라 아래로 이동   |
 | k     | Normal, Visual  | [count] 없이 가시적인 줄을 따라 위로 이동     |
 | go    | Normal          | 커서 다음에 [count]개의 빈 줄 추가            |
 | gO    | Normal          | 커서 이전에 [count]개의 빈 줄 추가            |
 | gy    | Normal, Visual  | 시스템 클립보드로 복사                        |
 | gp    | Normal, Visual  | 시스템 클립보드에서 붙여넣기                  |
 | gV    | Normal          | 마지막으로 변경되거나 yank된 텍스트 시각적 선택|
 | g/    | Visual          | 현재 시각적 선택 영역 내부에서 검색           |
 | *     | Visual          | 현재 시각적 선택 영역을 정방향 검색           |
 | #     | Visual          | 현재 시각적 선택 영역을 역방향 검색           |
 | <C-s> | Normal, Visual, | 저장하고 Normal 모드로 이동                   |
 |       |     Insert      |                                               |
 ```

참고:

- [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])의 의미는 해당 문서를 참조하십시오.

- Neovim>=0.10에서는 `#` 및 `*`에 대한 매핑이 생성되지 않습니다. 향상된 버전이 내장되어 있기 때문입니다. [v\_star-default](https://neovim.io/doc/user/helptag.html?tag=v_star-default) 및 [v\_#-default](https://neovim.io/doc/user/helptag.html?tag=v_#-default)를 참조하십시오.

- Neovim>=0.11에는 빈 줄 추가를 위한 [[<span class="help-syntax-keys">\<Space\></span>](https://neovim.io/doc/user/helptag.html?tag=[<Space>) / []<span class="help-syntax-keys">\<Space\></span>](https://neovim.io/doc/user/helptag.html?tag=]<span class="help-syntax-keys">\<Space\></span>)가 있습니다.
  `gO` 및 `go` 매핑은 여전히 생성되는데, 이는 유사한 목적의 [O](https://neovim.io/doc/user/helptag.html?tag=O) 및 [o](https://neovim.io/doc/user/helptag.html?tag=o) 키와 더 잘 일치하기 때문입니다 (가끔 [gO](https://neovim.io/doc/user/helptag.html?tag=gO)와 충돌하기도 함).

##### mappings.option_toggle_prefix {#minibasics.config-mappings-mappings.option_toggle_prefix}


`config.mappings.option_toggle_prefix`는 일반 옵션을 토글하는 매핑을 생성하는 데 사용되는 접두사를 정의합니다. 결과 매핑은 `<접두사> + <접미사>`가 됩니다. 예를 들어, 기본값을 사용하면 `\w`는 ['wrap'](https://neovim.io/doc/user/helptag.html?tag='wrap')을 토글합니다.

접두사에 대한 다른 실행 가능한 선택지는 다음과 같습니다:

- `,` (토글할 여러 값을 위한 기억법으로).

- `|` (동일한 기억법으로).

- `yo` ('tpope/vim-unimpaired'에서 사용됨)

- `<Leader>t`(`t`는 "toggle")와 같이 [<span class="help-syntax-keys">\<Leader\></span>](https://neovim.io/doc/user/helptag.html?tag=<Leader>) 키를 포함하는 것. 참고:
  접두사에 `<Leader>` 키가 포함된 경우 [MiniBasics.setup()](mini-basics.qmd#minibasics.setup) 호출 전에 설정해야 합니다 (기본 `basic` 필드인 [MiniBasics.config.options](mini-basics.qmd#minibasics.config.options)에서 수행되는 방식임).

토글 후, `require('mini.basics').setup()` 이전에 모듈이 묵음 처리되지 않은 경우 현재 옵션 값에 대한 피드백이 제공됩니다 ([mini.basics](mini-basics.qmd#mini.basics)의 "Silencing" 섹션 참조).

매핑이 이전에 수동으로 생성되지 않은 경우에만 추가합니다.

생성된 토글 매핑의 접미사 목록은 다음과 같습니다 (모두 Normal 모드):


- `b` - ['background'](https://neovim.io/doc/user/helptag.html?tag='background').

- `c` - ['cursorline'](https://neovim.io/doc/user/helptag.html?tag='cursorline').

- `C` - ['cursorcolumn'](https://neovim.io/doc/user/helptag.html?tag='cursorcolumn').

- `d` - 진단(diagnostic) ([vim.diagnostic](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic) 함수를 통해).

- `h` - ['hlsearch'](https://neovim.io/doc/user/helptag.html?tag='hlsearch') (정확히는 [v:hlsearch](https://neovim.io/doc/user/helptag.html?tag=v:hlsearch)).

- `i` - ['ignorecase'](https://neovim.io/doc/user/helptag.html?tag='ignorecase').

- `l` - ['list'](https://neovim.io/doc/user/helptag.html?tag='list').

- `n` - ['number'](https://neovim.io/doc/user/helptag.html?tag='number').

- `r` - ['relativenumber'](https://neovim.io/doc/user/helptag.html?tag='relativenumber').

- `s` - ['spell'](https://neovim.io/doc/user/helptag.html?tag='spell').

- `w` - ['wrap'](https://neovim.io/doc/user/helptag.html?tag='wrap').

##### mappings.windows {#minibasics.config-mappings-mappings.windows}


`config.mappings.windows`는 더 쉬운 창 조작을 위한 매핑을 생성합니다.

매핑이 이전에 수동으로 생성되지 않은 경우에만 추가합니다.

생성된 Normal 모드 매핑 목록은 다음과 같습니다 (모두 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])를 따름):

- 창 이동:

    - `<C-h>` - 왼쪽 창으로 포커스 이동 ([CTRL-W\_H](https://neovim.io/doc/user/helptag.html?tag=CTRL-W_H) 참조).

    - `<C-j>` - 아래 창으로 포커스 이동 ([CTRL-W\_J](https://neovim.io/doc/user/helptag.html?tag=CTRL-W_J) 참조).

    - `<C-k>` - 위 창으로 포커스 이동 ([CTRL-W\_K](https://neovim.io/doc/user/helptag.html?tag=CTRL-W_K) 참조).

    - `<C-l>` - 오른쪽 창으로 포커스 이동 ([CTRL-W\_L](https://neovim.io/doc/user/helptag.html?tag=CTRL-W_L) 참조).

- 창 크기 조정 (모두 화살표 키 사용; [:resize](https://neovim.io/doc/user/helptag.html?tag=:resize) 변형; [[count]](https://neovim.io/doc/user/helptag.html?tag=[count]) 따름):

    - `<C-left>`  - 창 너비 감소.

    - `<C-down>`  - 창 높이 감소.

    - `<C-up>`    - 창 높이 증가.

    - `<C-right>` - 창 너비 증가.

##### mappings.move_with_alt {#minibasics.config-mappings-mappings.move_with_alt}


`config.mappings.move_with_alt`는 Insert, Command 및 Terminal 모드에서 더 일관된 커서 이동을 위한 매핑을 생성합니다. 예를 들어, 자동 쌍(autopair) 플러그인(예: [mini.pairs](mini-pairs.qmd#mini.pairs))과 조합하여 삽입된 쌍의 오른쪽 바깥으로 이동하는 데 유용합니다 (어떤 쌍이든 상관없음).

매핑이 이전에 수동으로 생성되지 않은 경우에만 추가합니다.

생성된 매핑 목록은 다음과 같습니다 (`<M-x>`는 `Alt`/`Meta` + `x`를 의미):

- `<M-h>` - 커서를 왼쪽으로 이동.  모드: Insert, Terminal, Command.

- `<M-j>` - 커서를 아래로 이동.  모드: Insert, Terminal.

- `<M-k>` - 커서를 위로 이동.    모드: Insert, Terminal.

- `<M-l>` - 커서를 오른쪽으로 이동. 모드: Insert, Terminal, Command.

#### 자동 명령(Autocommands) {#minibasics.config-autocommands}


<a name="minibasics.config.autocommands" href="mini-basics.qmd#minibasics.config.autocommands"><b>MiniBasics.config.autocommands</b></a>

사용 예시:

  ```lua
  require('mini.basics').setup({
    autocommands = {
      basic = true,
      relnum_in_visual_mode = true,
    }
  })
  ```

##### autocommands.basic {#minibasics.config-autocommands-autocommands.basic}


`config.autocommands.basic`은 몇 가지 일반적인 자동 명령을 생성합니다:


- 터미널을 열 때 insert 모드를 시작합니다 ([:startinsert](https://neovim.io/doc/user/helptag.html?tag=:startinsert) 및 [TermOpen](https://neovim.io/doc/user/helptag.html?tag=TermOpen) 참조).

- yank 된 텍스트를 잠시 동안 강조 표시합니다 ([vim.hl.on\_yank()](https://neovim.io/doc/user/helptag.html?tag=vim.hl.on_yank\(\)) 참조;
  Neovim<0.11에서는 [vim.hl.on\_yank()](https://neovim.io/doc/user/helptag.html?tag=vim.hl.on_yank\(\)) 및 [TextYankPost](https://neovim.io/doc/user/helptag.html?tag=TextYankPost) 참조).

##### autocommands.relnum_in_visual_mode {#minibasics.config-autocommands-autocommands.relnum_in_visual_mode}


`config.autocommands.relnum_in_visual_mode`는 줄 단위 및 블록 단위 Visual 모드에서 ['relativenumber'](https://neovim.io/doc/user/helptag.html?tag='relativenumber')를 활성화하고 그 외에는 비활성화하는 자동 명령을 생성합니다. [ModeChanged](https://neovim.io/doc/user/helptag.html?tag=ModeChanged)를 참조하십시오.

---

### toggle_diagnostic() {#minibasics.toggle_diagnostic .help-syntax-right-anchor}

<p align="center">`MiniBasics.toggle_diagnostic`()</p>
현재 버퍼에 대한 진단 토글

이는 버퍼마다 [vim.diagnostic](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic) 함수를 사용합니다.

#### 반환값 {#minibasics.toggle_diagnostic-return}


`(string)` 새 상태에 대한 문자열 표시기. [:set](https://neovim.io/doc/user/helptag.html?tag=:set) `{option}?`이 표시하는 것과 유사합니다.
