---
title: "mini.deps 문서"
---

_ 'mini.nvim'의 'main' 브랜치에서 생성됨 _

<a name="mini.deps" href="mini-deps.qmd#mini.deps"><b>mini.deps</b></a> 플러그인 관리자

MIT 라이선스 Copyright (c) 2024 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:


- Git과 내장 [packages](https://neovim.io/doc/user/helptag.html?tag=packages)를 사용하여 다음 작업으로 플러그인을 관리합니다:

    - 현재 세션에 플러그인을 추가하고, 없는 경우 다운로드합니다. [MiniDeps.add()](mini-deps.qmd#minideps.add)를 참고하세요.

    - 확인 여부와 상관없이, 새로운 데이터의 병렬 다운로드 여부와 상관없이 업데이트합니다.
      [MiniDeps.update()](mini-deps.qmd#minideps.update)를 참고하세요.

    - 확인 여부와 상관없이 사용하지 않는 플러그인을 삭제합니다. [MiniDeps.clean()](mini-deps.qmd#minideps.clean)를 참고하세요.

    - 스냅샷을 가져오기 / 설정 / 저장 / 로드합니다. `MiniDeps.snap_*()` 함수들을 참고하세요.

    모든 주요 작업은 Lua 함수와 사용자 명령어([MiniDeps-commands](mini-deps.qmd#minideps-commands) 참고)로 모두 제공됩니다.


- 최소한이지만 유연한 플러그인 [사양](mini-deps.qmd#minideps-plugin-specification):

    - 플러그인 소스.

    - 대상 플러그인 디렉토리 이름.

    - 체크아웃 대상: 브랜치, 커밋, 태그 등.

    - 체크아웃하지 않고 업데이트를 추적할 모니터 브랜치.

    - 대상 플러그인 전에 설정할 의존성.

    - 플러그인이 생성/변경되기 전후에 호출할 훅.


- 2단계 시작을 구현하는 헬퍼: [MiniDeps.now()](mini-deps.qmd#minideps.now) 및 [MiniDeps.later()](mini-deps.qmd#minideps.later).
  이것들을 사용하여 기본적인 지연 로딩을 구현하는 방법은 [MiniDeps-overview](mini-deps.qmd#minideps-overview)를 참고하세요.

하지 않는 기능:


- Git 없이 개발된 플러그인 관리. 권장되는 방법은 별도의 패키지를 만드는 것입니다 ([packages](https://neovim.io/doc/user/helptag.html?tag=packages) 참고).


- 현재 세션에서 플러그인의 기능을 완전히 제거하거나 업데이트하는 방법을 제공하지 않습니다. 이것은 부분적으로는 가능하지만, 플러그인이 추적할 수 없는 부작용(자동 명령, 매핑 등)을 가질 수 있기 때문에 (아직은) 완전히 수행할 수 없습니다.
  권장되는 방법은 Nvim을 재시작하는 것입니다.

상세 정보를 위한 출처:

- [MiniDeps-overview](mini-deps.qmd#minideps-overview)

- [MiniDeps-plugin-specification](mini-deps.qmd#minideps-plugin-specification)

- [MiniDeps-commands](mini-deps.qmd#minideps-commands)

#### 의존성 {#module-dependencies}


이 플러그인의 대부분의 기능은 `git` CLI 도구에 의존합니다.
설치 방법에 대한 자세한 내용은 https://git-scm.com/ 을 참고하세요.
Git에 대한 실질적인 지식은 필수적이지 않지만 도움이 됩니다.

#### 설정 {#module-setup}


이 모듈은 `require('mini.deps').setup({})`으로 설정이 필요합니다 (`{}`를 `config` 테이블로 교체하세요). 스크립팅이나 수동으로 (`:lua MiniDeps.*`) 사용할 수 있는 전역 Lua 테이블 `MiniDeps`가 생성됩니다.

`config` 구조와 기본값은 [MiniDeps.config](mini-deps.qmd#minideps.config)를 참고하세요.

`vim.b.minideps_config` 내부의 버퍼에 로컬로 런타임 설정을 재정의할 수 있으며, 이는 `MiniDeps.config`와 동일한 구조를 가져야 합니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참고하세요.

#### 비교 {#module-comparisons}



- [folke/lazy.nvim](https://github.com/folke/lazy.nvim):

    - 더 기능이 풍부하고 복잡합니다.

    - 전용 함수를 사용하여 플러그인을 추가하는 테이블 사양을 사용하는 반면, 이 모듈은 직접 함수 호출 방식([MiniDeps.add()](mini-deps.qmd#minideps.add) 호출로 플러그인 사용 가능 보장)을 사용합니다.

    - 기본적으로 버전 태그를 사용하는 반면, 이 모듈은 브랜치를 추적하도록 더 설계되었습니다. 태그 사용도 가능합니다 ([MiniDeps-overview](mini-deps.qmd#minideps-overview) 참고).


- [savq/paq-nvim](https://github.com/savq/paq-nvim):

    - 전반적으로 이 모듈보다 기능이 적습니다 (의도된 설계).

    - `setup()` 호출 내부에서 어떤 플러그인을 설치할지 정의하기 위해 플러그인 사양 배열을 사용합니다. 실제로 설치하려면 별도의 `:PaqInstall` 호출이 필요합니다. 이 모듈은 첫 로드 시 설치를 보장합니다.


- [junegunn/vim-plug](https://github.com/junegunn/vim-plug):

    - Vimscript로 작성된 반면, 이 모듈은 Lua로 작성되었습니다.

    - 'savq/paq-nvim'과 유사한 플러그인 정의 및 설치 방식을 사용합니다.

    - 기본적인 지연 로딩이 내장되어 있지만, 이 모듈은 그렇지 않습니다 (의도된 설계).

#### 하이라이트 그룹 {#module-highlightgroups}


하이라이트 그룹은 기본 [MiniDeps.update()](mini-deps.qmd#minideps.update) 및 [MiniDeps.clean()](mini-deps.qmd#minideps.clean) 이후의 확인 버퍼 내부에서 사용됩니다.


- `MiniDepsChangeAdded`   - 업데이트 중 추가된 변경 사항 (커밋).

- `MiniDepsChangeRemoved` - 업데이트 중 제거된 변경 사항 (커밋).

- `MiniDepsHint`          - 각종 힌트.

- `MiniDepsInfo`          - 각종 정보.

- `MiniDepsMsgBreaking`   - (conventional commit) 주요 변경 사항(breaking change) 메시지.

- `MiniDepsPlaceholder`   - 유용한 정보가 없을 때의 자리 표시자.

- `MiniDepsTitle`         - 각종 제목.

- `MiniDepsTitleError`    - 업데이트 중 플러그인에 오류가 발생했을 때의 제목.

- `MiniDepsTitleSame`     - 업데이트할 변경 사항이 없을 때의 제목.

- `MiniDepsTitleUpdate`   - 업데이트할 변경 사항이 있을 때의 제목.

하이라이트 그룹을 변경하려면 [nvim\_set\_hl()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_hl\(\))을 사용하여 직접 설정하세요.

---

### 개요 {#minideps-overview .help-syntax-right-anchor}

#### 디렉토리 구조 {#minideps-overview-directorystructure}


이 모듈은 현재 세션에서 플러그인을 사용할 수 있도록 내장 [packages](https://neovim.io/doc/user/helptag.html?tag=packages)를 사용합니다.
`config.path.package` 디렉토리 내부의 "pack/deps" 패키지와 작동합니다.

기본적으로 [MiniDeps.add()](mini-deps.qmd#minideps.add)로 요청 시 로드되는 선택적 플러그인을 설치하기 위해 "opt" 하위 디렉토리가 사용됩니다.
"start" 하위 디렉토리의 필수 플러그인은 초기 설치 후 수동으로 이동한 경우에만 지원됩니다. 무엇을 하고 있는지 잘 아는 경우에만 사용하세요.

#### 플러그인 추가 {#minideps-overview-addplugin}


현재 세션에 플러그인을 추가하려면 [MiniDeps.add()](mini-deps.qmd#minideps.add)를 사용하세요. 플러그인의 URL 소스를 문자열로 제공하거나 일반적으로 [플러그인 사양](mini-deps.qmd#minideps-plugin-specification)을 제공하세요. 플러그인이 "pack/deps" 패키지에 없는 경우, 다른 작업을 처리하기 전에 생성(일명 설치)됩니다.

플러그인을 추가하는 권장 방법은 [init.lua](https://neovim.io/doc/user/helptag.html?tag=init.lua) 파일에서 [MiniDeps.add()](mini-deps.qmd#minideps.add)를 호출하는 것입니다 ([MiniDeps.setup()](mini-deps.qmd#minideps.setup)이 먼저 호출되었는지 확인하세요):

  ```lua
  local add = MiniDeps.add

  -- 현재 세션에 추가 (없으면 설치)
  add({
    source = 'neovim/nvim-lspconfig',
    -- 대상 플러그인 근처에 의존성 제공
    depends = { 'williamboman/mason.nvim' },
  })

  add({
    source = 'nvim-treesitter/nvim-treesitter',
    -- 'main'에서 업데이트를 모니터링하면서 'master' 사용
    checkout = 'master',
    monitor = 'main',
    -- 매 체크아웃 후 작업 수행
    hooks = { post_checkout = function() vim.cmd('TSUpdate') end },
  })
  -- 추가된 플러그인에 의존하는 코드를 즉시 실행 가능
  require('nvim-treesitter.configs').setup({
    ensure_installed = { 'lua', 'vimdoc' },
    highlight = { enable = true },
  })
  ```

참고:

- 성능을 높이기 위해 `add()`는 디스크에 존재 여부만 보장하고 그 외에는 아무것도 하지 않습니다. 특히 `opts.checkout` 상태를 보장하지 않습니다.
  플러그인 상태를 명시적으로 업데이트하거나 수정하세요 (이후 섹션 참고).

#### 지연 로딩 {#minideps-overview-lazyloading}


모든 지연 로딩은 적절한 시점에 [MiniDeps.add()](mini-deps.qmd#minideps.add)를 호출하여 수동으로 수행되는 것으로 가정합니다. 이 모듈은 특수한 안전한 2단계 로딩을 구현하는 헬퍼를 제공합니다:

- [MiniDeps.now()](mini-deps.qmd#minideps.now)는 즉시 코드를 안전하게 실행합니다. 초기 화면 그리기에 필요한 UI가 있는 플러그인을 로드하는 데 사용하세요.

- [MiniDeps.later()](mini-deps.qmd#minideps.later)는 나중에 코드가 안전하게 실행되도록 예약하며 순서를 유지합니다. 정확한 타이밍이 필요하지 않은 다른 모든 작업에 (주의해서) 사용하세요. 다음 이벤트 루프 중 하나에서 곧 실행될 것입니다.

  ```lua
  local now, later = MiniDeps.now, MiniDeps.later

  -- 즉시 안전하게 실행
  now(function() vim.cmd('colorscheme miniwinter') end)
  now(function() require('mini.statusline').setup() end)

  -- 나중에 안전하게 실행
  later(function() require('mini.pick').setup() end)
  ```

#### 업데이트 {#minideps-overview-update}


현재 세션의 플러그인을 소스의 새로운 데이터로 업데이트하려면 [:DepsUpdate](mini-deps.qmd#depsupdate)를 사용하세요. 업데이트를 다운로드하고(멀티 코어 활용) 확인 버퍼를 표시합니다. 업데이트를 완료하려면 상단의 지침을 따르세요.

참고: 이것은 디스크의 플러그인을 업데이트하며 현재 세션에는 영향을 주지 않을 가능성이 큽니다. 제대로 로드하려면 Nvim을 재시작하세요.

#### 수정 {#minideps-overview-modify}


플러그인 사양을 변경하려면 (다른 `checkout` 설정 등):

- 해당 [MiniDeps.add()](mini-deps.qmd#minideps.add) 호출을 업데이트하세요.

- `:DepsUpdateOffline <plugin_name>`을 실행하세요.

- 변경 사항을 검토하고 확인하세요.

- Nvim을 재시작하세요.

참고: 이전에 `add()`가 단일 소스 문자열을 사용했다면, 인수를 `{ source = '<이전_인수>', checkout = '<상태>'}`로 변환해야 합니다.

#### 스냅샷 {#minideps-overview-snapshots}


현재 세션의 모든 플러그인 상태를 스냅샷 파일에 저장하려면 [:DepsSnapSave](mini-deps.qmd#depssnapsave)를 사용하세요 (`config.path.snapshot` 참고).

스냅샷을 로드하려면 [:DepsSnapLoad](mini-deps.qmd#depssnapload)를 사용하세요. 확인 없이 디스크의 상태를 변경합니다. 스냅샷 파일과 현재 세션 모두에 있는 플러그인이 영향을 받습니다. 효과를 보려면 Nvim을 재시작하세요.

참고: 스냅샷을 로드해도 [MiniDeps.add()](mini-deps.qmd#minideps.add) 호출 내부에 정의된 플러그인 사양은 변경되지 않습니다. 즉, 다음 업데이트 시 플러그인 상태가 변경될 수 있습니다. 영구적으로 만들려면 대상 상태에서 플러그인을 수동으로 동결하세요.

#### 동결 {#minideps-overview-freeze}


플러그인 사양을 수정하여 `checkout`이 정적 대상을 가리키도록 하세요: 태그, 상태(커밋 해시) 또는 'HEAD'(현재 상태로 동결).

동결된 플러그인은 업데이트를 받지 않습니다. [:DepsUpdate](mini-deps.qmd#depsupdate) 후 확인 버퍼에 표시될 `monitor` 브랜치를 "구독"하여 소스의 새로운 변경 사항을 모니터링할 수 있습니다.

예시: `checkout = 'v0.10.0'`을 사용하여 플러그인을 "v0.10.0" 태그로 동결하고, `monitor`(보통 기본값) 브랜치의 로그에서 새로운 버전을 모니터링합니다.

#### 롤백 {#minideps-overview-rollback}


불운한 업데이트 후 롤백하려면:

- 최신 작동 상태의 식별자를 가져옵니다:

    - [:DepsShowLog](mini-deps.qmd#depsshowlog)를 사용하여 업데이트 로그를 보고, 플러그인 이름을 찾은 다음 "State before:"로 나열된 식별자를 복사합니다.

    - 이전에 저장된 스냅샷 파일에서 플러그인 이름을 찾고 그 옆의 식별자를 복사합니다.

- 적절한 브랜치를 모니터링하면서 해당 상태에서 플러그인을 동결합니다. 업데이트를 재개하려면 [MiniDeps.add()](mini-deps.qmd#minideps.add) 호출의 이전 모양으로 되돌립니다.

#### 삭제 {#minideps-overview-remove}



- 대상 플러그인이 현재 세션에 등록되어 있지 않은지 확인하세요. 보통 해당 [MiniDeps.add()](mini-deps.qmd#minideps.add) 호출을 제거하는 것을 의미합니다.

- [:DepsClean](mini-deps.qmd#depsclean)을 실행하세요. 디스크에서 삭제될 플러그인 목록이 포함된 확인 버퍼를 표시합니다. 삭제를 완료하려면 상단의 지침을 따르세요.

또는 "pack/deps" 패키지에서 플러그인 디렉토리를 수동으로 삭제하세요.

---

### 플러그인 사양 {#minideps-plugin-specification .help-syntax-right-anchor}

각 플러그인 의존성은 사양(일명 "spec")을 기반으로 관리됩니다.
몇 가지 예시는 [MiniDeps-overview](mini-deps.qmd#minideps-overview)를 참고하세요.

사양은 다음과 같이 추론되는 단일 문자열일 수 있습니다:

- "/"를 포함하지 않는 경우 플러그인 <span class="help-syntax-keys">\<name\></span>.

- 그렇지 않은 경우 플러그 <span class="help-syntax-keys">\<source\></span>.

기본적으로 사양은 다음 필드를 갖는 테이블입니다:


- <span class="help-syntax-keys">\<source\></span> `(string|nil)` - 생성 또는 업데이트 중에 사용되는 플러그인 소스의 URI 필드입니다. `git clone`이 허용하는 무엇이든 가능합니다.
  기본값: 설치 중에 설정된 소스에 의존하도록 `nil`.
  참고:

    - 플러그인 생성에는 필수적이지만 나중에는 생략할 수 있습니다.

    - 가장 흔한 경우로, "user/repo" 형식의 URI(유효한 문자가 포함된 경우)는 "https://github.com/user/repo"로 변환됩니다.


- <span class="help-syntax-keys">\<name\></span> `(string|nil)` - 플러그인 소스를 저장할 디렉토리 기본 이름입니다.
  `config.path.package`의 "pack/deps/opt" 하위 디렉토리에 저장됩니다.
  기본값: <span class="help-syntax-keys">\<source\></span>가 있는 경우 그 기본 이름이며, 그렇지 않으면 명시적으로 제공되어야 합니다.


- <span class="help-syntax-keys">\<checkout\></span> `(string|nil)` - 업데이트 중 상태를 설정하는 데 사용되는 체크아웃 대상입니다.
  `git checkout`이 지원하는 무엇이든(브랜치, 커밋, 태그 등) 가능합니다.
  기본값: 기본 브랜치(보통 "main" 또는 "master")의 경우 `nil`.


- <span class="help-syntax-keys">\<monitor\></span> `(string|nil)` - `checkout`과 다른 대상에서 새로운 변경 사항을 추적하는 데 사용되는 모니터 브랜치입니다. 존재하는 Git 브랜치 이름이어야 합니다.
  기본값: 기본 브랜치(보통 "main" 또는 "master")의 경우 `nil`.


- <span class="help-syntax-keys">\<depends\></span> `(table|nil)` - 대상 전에 추가할 플러그인 사양(문자열 또는 테이블)의 배열입니다.
  기본값: 의존성이 없는 경우 `nil`.


- <span class="help-syntax-keys">\<hooks\></span> `(table|nil)` - 특정 이벤트 발생 시 호출할 수 있는 훅 테이블입니다.
  가능한 훅 이름:

    - <span class="help-syntax-keys">\<pre_install\></span>   - 플러그인 디렉토리를 생성하기 전.

    - <span class="help-syntax-keys">\<post_install\></span>  - 플러그인 디렉토리를 생성한 후 ([:packadd](https://neovim.io/doc/user/helptag.html?tag=:packadd) 전).

    - <span class="help-syntax-keys">\<pre_checkout\></span>  - 기존 플러그인을 변경하기 전.

    - <span class="help-syntax-keys">\<post_checkout\></span> - 기존 플러그인을 변경한 후.
  각 훅은 다음 테이블을 인수로 하여 실행됩니다:

    - <span class="help-syntax-keys">\<path\></span> (`string`)   - 플러그인 디렉토리의 절대 경로 (디스크에 아직 존재하지 않을 수 있음).

    - <span class="help-syntax-keys">\<source\></span> (`string`) - 사양에서 해석된 <span class="help-syntax-keys">\<source\></span>.

    - <span class="help-syntax-keys">\<name\></span> (`string`)   - 사양에서 해석된 <span class="help-syntax-keys">\<name\></span>.
  기본값: 훅이 없는 경우 `nil`.

---

### 명령어 {#minideps-commands .help-syntax-right-anchor}

참고: 대부분의 명령에는 의존하는 Lua 함수 대안이 있습니다.
[:DepsAdd](mini-deps.qmd#depsadd)가 [MiniDeps.add()](mini-deps.qmd#minideps.add)를 사용하는 식입니다.

#### :DepsAdd {#minideps-commands-depsadd}


<a name="depsadd" href="mini-deps.qmd#depsadd"><b>:DepsAdd</b></a>에 `user/repo` 인수를 사용하면 https://github.com/user/repo 플러그인을 현재 세션에서 사용할 수 있게 합니다 (없는 경우 생성도 함).
`:DepsAdd name`은 이미 설치된 플러그인 `name`을 현재 세션에 추가합니다.
[MiniDeps-plugin-specification](mini-deps.qmd#minideps-plugin-specification)과 호환되는 단일 문자열만 허용합니다.
모든 세션에 플러그인을 추가하려면 [init.lua](https://neovim.io/doc/user/helptag.html?tag=init.lua)에 [MiniDeps.add()](mini-deps.qmd#minideps.add)를 넣으세요.

#### :DepsUpdate {#minideps-commands-depsupdate}


<a name="depsupdate" href="mini-deps.qmd#depsupdate"><b>:DepsUpdate</b></a>는 플러그인을 세션 사양과 동기화하고 소스의 새로운 변경 사항으로 업데이트합니다. 검토하고 (선택적으로) 적용할 예정인 업데이트에 대한 정보와 함께 별도의 [tabpage](https://neovim.io/doc/user/helptag.html?tag=tabpage)에 확인 버퍼를 표시합니다. 자세한 내용은 [MiniDeps.update()](mini-deps.qmd#minideps.update)를 참고하세요.

`:DepsUpdate name`은 플러그인 `name`을 업데이트합니다. 이름은 몇 개든 허용됩니다.

`:DepsUpdate!` 및 `:DepsUpdate! name`은 확인 없이 업데이트합니다.
나중에 로그 파일([:DepsShowLog](mini-deps.qmd#depsshowlog))에서 수행된 작업을 확인할 수 있습니다.

#### :DepsUpdateOffline {#minideps-commands-depsupdateoffline}


<a name="depsupdateoffline" href="mini-deps.qmd#depsupdateoffline"><b>:DepsUpdateOffline</b></a>은 [:DepsUpdate](mini-deps.qmd#depsupdate)와 동일하지만 소스에서 새로운 업데이트를 다운로드하지 않습니다. 불필요한 다운로드 없이 코드와 디스크의 플러그인 사양만 동기화하는 데 유용합니다.

#### :DepsShowLog {#minideps-commands-depsshowlog}


<a name="depsshowlog" href="mini-deps.qmd#depsshowlog"><b>:DepsShowLog</b></a>는 검토할 로그 파일을 엽니다.

#### :DepsClean {#minideps-commands-depsclean}


<a name="depsclean" href="mini-deps.qmd#depsclean"><b>:DepsClean</b></a>은 현재 세션에 추가되지 않은 플러그인을 디스크에서 삭제합니다. 검토하고 (선택적으로) 적용할 예정인 삭제에 대한 정보와 함께 별도의 [tabpage](https://neovim.io/doc/user/helptag.html?tag=tabpage)에 확인 버퍼를 표시합니다. 자세한 내용은 [MiniDeps.clean()](mini-deps.qmd#minideps.clean)을 참고하세요.

`:DepsClean!`은 확인 없이 플러그인을 삭제합니다.

#### :DepsSnapSave {#minideps-commands-depssnapsave}


<a name="depssnapsave" href="mini-deps.qmd#depssnapsave"><b>:DepsSnapSave</b></a>는 기본 위치([MiniDeps.config](mini-deps.qmd#minideps.config) 참고)에 스냅샷 파일을 생성합니다.
`:DepsSnapSave path`는 `path`에 스냅샷 파일을 생성합니다.

#### :DepsSnapLoad {#minideps-commands-depssnapload}


<a name="depssnapload" href="mini-deps.qmd#depssnapload"><b>:DepsSnapLoad</b></a>는 기본 위치([MiniDeps.config](mini-deps.qmd#minideps.config) 참고)에서 스냅샷 파일을 로드합니다.
`:DepsSnapLoad path`는 `path`에서 스냅샷 파일을 로드합니다.

---

### setup() {#minideps.setup .help-syntax-right-anchor}

<p align="center">`MiniDeps.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

이 함수를 호출하면 [MiniDeps-commands](mini-deps.qmd#minideps-commands)에 설명된 사용자 명령어가 생성됩니다.

#### 매개변수 {#minideps.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniDeps.config](mini-deps.qmd#minideps.config)를 참고하세요.

#### 사용법 {#minideps.setup-usage}



  ```lua
  require('mini.deps').setup() -- 기본 설정 사용
  -- 또는
  require('mini.deps').setup({}) -- {}를 설정 테이블로 교체
  ```

---

### config {#minideps.config .help-syntax-right-anchor}

<p align="center">`MiniDeps.config`</p>
#### 기본값 {#minideps.config-defaults}



  ```lua
  MiniDeps.config = {
    -- CLI 작업 매개변수
    job = {
      -- 사용할 병렬 스레드 수. 기본값: 전체 가용 리소스의 80%.
      n_threads = nil,

      -- 강제 종료 전 각 작업의 타임아웃 (ms 단위)
      timeout = 30000,
    },

    -- 데이터 저장 위치를 설명하는 경로
    path = {
      -- 내장 패키지 디렉토리.
      -- 모든 플러그인은 실제로 'pack/deps' 하위 디렉토리에 저장됩니다.
      package = vim.fn.stdpath('data') .. '/site',

      -- 스냅샷의 기본 파일 경로
      snapshot = vim.fn.stdpath('config') .. '/mini-deps-snap',

      -- 로그 파일
      log = vim.fn.stdpath('log') .. '/mini-deps.log'
    },

    -- 오류가 아닌 피드백 표시를 비활성화할지 여부
    silent = false,
  }
  ```

#### 작업 {#minideps.config-job}


`config.job`은 CLI 작업이 실행되는 방식을 정의합니다.

`job.n_threads`는 필요할 때 사용되는 최대 병렬 작업 수입니다.
기본값: 전체 가용 리소스의 80%.

`job.timeout`은 작업 시작부터 강제 종료까지의 기간(ms 단위)입니다.
기본값: 30000.

#### 경로 {#minideps.config-paths}


`config.path`는 이 모듈에서 사용되는 주요 경로를 정의합니다.

`path.package`는 "pack/deps" 패키지가 저장되는 경로가 포함된 문자열입니다
([MiniDeps-overview](mini-deps.qmd#minideps-overview) 참고).
기본값: "data" 표준 경로([stdpath()](https://neovim.io/doc/user/helptag.html?tag=stdpath\(\)) 참고)의 "site" 하위 디렉토리.

`path.snapshot`은 스냅샷의 기본 경로가 포함된 문자열입니다.
[:DepsSnapSave](mini-deps.qmd#depssnapsave) 및 [:DepsSnapLoad](mini-deps.qmd#depssnapload)를 참고하세요.
기본값: "config" 표준 경로([stdpath()](https://neovim.io/doc/user/helptag.html?tag=stdpath\(\)) 참고)의 "mini-deps-snap" 파일.

`path.log`는 모듈에서 수행한 작업 로그가 포함된 경로의 문자열입니다.
특히 업데이트 후 수행된 모든 변경 사항이 포함됩니다.
기본값: "log" 표준 경로([stdpath()](https://neovim.io/doc/user/helptag.html?tag=stdpath\(\)) 참고)의 "mini-deps.log" 파일.

#### 자동 모드 {#minideps.config-silent}


`config.silent`는 오류가 아닌 피드백을 억제할지 여부를 제어하는 불리언입니다.
기본값: `false`.

---

### add() {#minideps.add .help-syntax-right-anchor}

<p align="center">`MiniDeps.add`(<span class="help-syntax-special">{spec}</span>, <span class="help-syntax-special">{opts}</span>)</p>
현재 세션에 플러그인 추가


- 의존성을 단일 사양 배열로 확장하여 사양을 처리합니다.

- 없는 의존성을 (병렬로) 설치하여 디스크에 플러그인과 그 의존성이 있는지 확인합니다:

    - `opts.hooks.pre_install`을 실행합니다.

    - `git clone`을 사용하여 소스 URI에서 "pack/deps/opt"로 플러그인을 클론합니다.

    - `opts.checkout`에 따라 상태를 설정합니다.

    - `opts.hooks.post_install`을 실행합니다.

- 현재 세션에 사양을 등록합니다.

- 현재 세션에서 플러그인을 사용할 수 있는지 확인합니다 ([:packadd](https://neovim.io/doc/user/helptag.html?tag=:packadd) 참고).

- 시작 중이 아니고 필요한 경우, 모든 "after/plugin/" 스크립트를 소싱합니다.

참고:

- 플러그인의 존재 여부는 "pack/deps" 패키지 내부의 디렉토리 이름과 동일한 이름으로 확인됩니다 ([MiniDeps-overview](mini-deps.qmd#minideps-overview) 참고).

- 성능을 높이기 위해 이 함수는 디스크에 존재 여부만 보장하고 그 외에는 아무것도 하지 않습니다. 특히 `opts.checkout` 상태를 보장하지 않습니다.
  [MiniDeps.update()](mini-deps.qmd#minideps.update) 또는 [:DepsUpdateOffline](mini-deps.qmd#depsupdateoffline)을 명시적으로 사용하세요.

- 플러그인을 여러 번 추가하면 세션 사양이 업데이트됩니다.

#### 매개변수 {#minideps.add-parameters}



<span class="help-syntax-special">{spec}</span> `(table|string)` 플러그인 사양. [플러그인 사양](mini-deps.qmd#minideps-plugin-specification)을 참고하세요.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<bang\></span> `(boolean)` - 일반 [:packadd](https://neovim.io/doc/user/helptag.html?tag=:packadd) 대신 `:packadd!`를 사용할지 여부.

---

### update() {#minideps.update .help-syntax-right-anchor}

<p align="center">`MiniDeps.update`(<span class="help-syntax-special">{names}</span>, <span class="help-syntax-special">{opts}</span>)</p>
플러그인 업데이트


- 사양을 디스크의 플러그인 상태와 동기화합니다 (`source` 설정 등).

- 업데이트를 다운로드하기 전에 데이터를 추론합니다.

- 오프라인이 아닌 경우, 업데이트를 (병렬로) 다운로드합니다.

- 업데이트를 다운로드한 후 데이터를 추론합니다.

- 업데이트가 강제된 경우, 로그 파일(`config.path.log`에 위치; 검토하려면 [:DepsShowLog](mini-deps.qmd#depsshowlog) 사용)을 업데이트하면서 모든 변경 사항을 즉시 적용합니다.
  그렇지 않으면 진행 방법에 대한 지침과 함께 확인 버퍼를 표시합니다.

#### 매개변수 {#minideps.update-parameters}



<span class="help-syntax-special">{names}</span> `(table|nil)` 업데이트할 플러그인 이름 배열.
 기본값: 현재 세션의 모든 플러그인 ([MiniDeps.get\_session()](mini-deps.qmd#minideps.get_session) 참고).

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<force\></span> `(boolean)` - 확인 없이 업데이트를 강제할지 여부.
    기본값: `false`.

  - <span class="help-syntax-keys">\<offline\></span> `(boolean)` - 소스에서 업데이트 다운로드를 건너뛸지 여부.
    기본값: `false`.

---

### clean() {#minideps.clean .help-syntax-right-anchor}

<p align="center">`MiniDeps.clean`(<span class="help-syntax-special">{opts}</span>)</p>
플러그인 삭제


- 없는 플러그인 계산: 현재 세션에 등록되지 않았지만([MiniDeps.get\_session()](mini-deps.qmd#minideps.get_session) 참고) 전용 "pack/deps" 패키지(`config.path.package` 내부)의 디스크에 존재하는 플러그인.

- 삭제가 강제된 경우, 디스크에서 모든 없는 플러그인을 삭제합니다.
  그렇지 않으면 진행 방법에 대한 지침과 함께 확인 버퍼를 표시합니다.

#### 매개변수 {#minideps.clean-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<force\></span> `(boolean)` - 확인 없이 삭제를 강제할지 여부.
    기본값: `false`.

---

### snap_get() {#minideps.snap_get .help-syntax-right-anchor}

<p align="center">`MiniDeps.snap_get`()</p>
스냅샷 계산

#### 반환값 {#minideps.snap_get-return}


`(table)` 스냅샷 테이블: 플러그인 이름이 키이고 상태가 값입니다.
  현재 세션의 모든 플러그인이 처리됩니다.

---

### snap_set() {#minideps.snap_set .help-syntax-right-anchor}

<p align="center">`MiniDeps.snap_set`(<span class="help-syntax-special">{snap}</span>)</p>
스냅샷 적용

참고:

- 스냅샷에서 상태를 체크아웃해도 세션 플러그인 사양(특히 `checkout` 필드)은 업데이트되지 않습니다. 즉, 다음 [MiniDeps.update()](mini-deps.qmd#minideps.update) 호출 시 이 함수의 결과가 무시될 수 있습니다.
  변경 사항을 영구적으로 만들려면 `checkout` 사양 필드를 스냅샷의 상태로 설정하세요.

#### 매개변수 {#minideps.snap_set-parameters}



<span class="help-syntax-special">{snap}</span> `(table)` 스냅샷 테이블: 플러그인 이름이 키이고 상태가 값입니다.
  현재 세션의 플러그인만 처리됩니다.

---

### snap_save() {#minideps.snap_save .help-syntax-right-anchor}

<p align="center">`MiniDeps.snap_save`(<span class="help-syntax-special">{path}</span>)</p>
스냅샷 저장

#### 매개변수 {#minideps.snap_save-parameters}



<span class="help-syntax-special">{path}</span> `(string|nil)` [MiniDeps.snap\_get()](mini-deps.qmd#minideps.snap_get)으로 계산된 스냅샷을 기록할 디스크의 유효한 경로입니다.
  기본값: `config.path.snapshot`.

---

### snap_load() {#minideps.snap_load .help-syntax-right-anchor}

<p align="center">`MiniDeps.snap_load`(<span class="help-syntax-special">{path}</span>)</p>
스냅샷 파일 로드

[MiniDeps.snap\_set()](mini-deps.qmd#minideps.snap_set)의 참고 사항이 여기에도 적용됩니다.

#### 매개변수 {#minideps.snap_load-parameters}



<span class="help-syntax-special">{path}</span> `(string|nil)` 스냅샷을 읽어올 디스크의 유효한 경로입니다.
  기본값: `config.path.snapshot`.

---

### get_session() {#minideps.get_session .help-syntax-right-anchor}

<p align="center">`MiniDeps.get_session`()</p>
세션 가져오기

플러그인은 다음 중 하나에 해당하면 현재 세션에 등록됩니다:

- [MiniDeps.add()](mini-deps.qmd#minideps.add)로 추가된 경우 (호출 순서 유지).

- "start" 플러그인이며 'runtimpath'에 있는 경우.

#### 반환값 {#minideps.get_session-return}


`(table)` 현재 세션에 등록된 모든 플러그인의 사양이 포함된 배열.

---

### now() {#minideps.now .help-syntax-right-anchor}

<p align="center">`MiniDeps.now`(<span class="help-syntax-special">{f}</span>)</p>
함수 즉시 실행

함수를 즉시 안전하게 실행합니다. 오류는 나중에 대기 중인 모든 함수([MiniDeps.later()](mini-deps.qmd#minideps.later) 포함)가 실행된 후 [vim.notify()](https://neovim.io/doc/user/helptag.html?tag=vim.notify\(\))로 표시되므로, 파일의 다음 코드 실행을 방해하지 않습니다.

시작 시 플러그인을 즉시 로드하기 위해 2단계 설정 실행 중 첫 번째 단계로 사용되는 것으로 가정합니다. [MiniDeps-overview](mini-deps.qmd#minideps-overview)를 참고하세요.

#### 매개변수 {#minideps.now-parameters}



<span class="help-syntax-special">{f}</span> `(function)` 실행할 호출 가능한 객체.

---

### later() {#minideps.later .help-syntax-right-anchor}

<p align="center">`MiniDeps.later`(<span class="help-syntax-special">{f}</span>)</p>
함수 나중에 실행

파일의 다음 코드 실행을 방해하지 않고 나중에 안전하게 실행되도록 함수를 대기열에 추가합니다. 대기 중인 모든 함수는 추가된 순서대로 실행되는 것이 보장됩니다.
오류는 모든 대기 중인 함수가 실행된 후 [vim.notify()](https://neovim.io/doc/user/helptag.html?tag=vim.notify\(\))로 표시됩니다.

시작 후 플러그인을 "지연" 로드하기 위해 2단계 설정 실행 중 두 번째 단계로 사용되는 것으로 가정합니다. [MiniDeps-overview](mini-deps.qmd#minideps-overview)를 참고하세요.

#### 매개변수 {#minideps.later-parameters}



<span class="help-syntax-special">{f}</span> `(function)` 실행할 호출 가능한 객체.
