---
title: "mini.bracketed 문서"
---

_'mini.nvim'의 `main` 브랜치에서 생성됨_

<a name="mini.bracketed" href="mini-bracketed.qmd#mini.bracketed"><b>mini.bracketed</b></a> 대괄호를 사용하여 앞/뒤로 이동하기

MIT 라이선스 Copyright (c) 2023 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:

- 특정 대상으로 앞/뒤로 이동할 수 있는 설정 가능한 Lua 함수들.
  각 함수는 다음과 같이 사용자 정의할 수 있습니다:

    - 방향. "forward"(앞으로), "backward"(뒤로), "first"(첫 번째부터 시작하여 앞으로), "last"(마지막부터 시작하여 뒤로) 중 하나입니다.

    - 이동 횟수.

    - 끝에서 되돌아갈지 여부 (마지막에서 앞으로 이동하면 첫 번째로 이동).

    - 기타 대상별 옵션들.


- 대괄호를 사용하는 매핑들. 설정 가능한 대상 접미사를 사용하여 생성되며 선택적으로 비활성화할 수 있습니다.

  각 매핑은 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])를 지원합니다. 매핑은 Normal 모드에서 생성됩니다. 현재 버퍼에서 커서를 이동하는 대상의 경우 Visual 및 Operator-pending (점 반복 지원) 모드도 지원됩니다.

  단일 대상에 대해 `lower-suffix`(소문자 접미사)와 `upper-suffix`(대문자 접미사)를 사용하여 다음과 같은 매핑이 생성됩니다:

    - `[` + `upper-suffix` : 첫 번째로 이동.

    - `[` + `lower-suffix` : 뒤로 이동.

    - `]` + `lower-suffix` : 앞으로 이동.

    - `]` + `upper-suffix` : 마지막으로 이동.


- 지원되는 대상들 (자세한 내용은 해당 Lua 함수에 대한 도움말 참조):


| `대상` | `매핑` | `Lua 함수` |
|---|---|---:|
| 버퍼 | `[B` `[b` `]b` `]B` | [MiniBracketed.buffer()](mini-bracketed.qmd#minibracketed.buffer) |
| 주석 블록 | `[C` `[c` `]c` `]C` | [MiniBracketed.comment()](mini-bracketed.qmd#minibracketed.comment) |
| 충돌 마커 | `[X` `[x` `]x` `]X` | [MiniBracketed.conflict()](mini-bracketed.qmd#minibracketed.conflict) |
| 진단(Diagnostic) | `[D` `[d` `]d` `]D` | [MiniBracketed.diagnostic()](mini-bracketed.qmd#minibracketed.diagnostic) |
| 디스크의 파일 | `[F` `[f` `]f` `]F` | [MiniBracketed.file()](mini-bracketed.qmd#minibracketed.file) |
| 들여쓰기 변경 | `[I` `[i` `]i` `]I` | [MiniBracketed.indent()](mini-bracketed.qmd#minibracketed.indent) |
| 현재 버퍼 내 점프 | `[J` `[j` `]j` `]J` | [MiniBracketed.jump()](mini-bracketed.qmd#minibracketed.jump) |
| [location-list](https://neovim.io/doc/user/helptag.html?tag=location-list)의 위치 | `[L` `[l` `]l` `]L` | [MiniBracketed.location()](mini-bracketed.qmd#minibracketed.location) |
| 오래된 파일(Old files) | `[O` `[o` `]o` `]O` | [MiniBracketed.oldfile()](mini-bracketed.qmd#minibracketed.oldfile) |
| [Quickfix](https://neovim.io/doc/user/helptag.html?tag=Quickfix)의 퀵픽스 항목 | `[Q` `[q` `]q` `]Q` | [MiniBracketed.quickfix()](mini-bracketed.qmd#minibracketed.quickfix) |
| Tree-sitter 노드 및 부모 | `[T` `[t` `]t` `]T` | [MiniBracketed.treesitter()](mini-bracketed.qmd#minibracketed.treesitter) |
| 선형 히스토리에서의 실행 취소(Undo) | `[U` `[u` `]u` `]U` | [MiniBracketed.undo()](mini-bracketed.qmd#minibracketed.undo) |
| 현재 탭의 창(Window) | `[W` `[w` `]w` `]W` | [MiniBracketed.window()](mini-bracketed.qmd#minibracketed.window) |
| 붙여넣기 영역에 대한 Yank 항목 | `[Y` `[y` `]y` `]Y` | [MiniBracketed.yank()](mini-bracketed.qmd#minibracketed.yank) |

참고:

- `undo` 대상은 [u](https://neovim.io/doc/user/helptag.html?tag=u) 및 [CTRL-R](https://neovim.io/doc/user/helptag.html?tag=CTRL-R) 키를 다시 매핑하여 각각 실행 취소 및 다시 실행 후에 실행 취소 상태를 등록합니다. 사용자 설정과 충돌하는 경우 `undo` 대상을 비활성화하거나 [MiniBracketed.setup()](mini-bracketed.qmd#minibracketed.setup) 호출 후에 다시 매핑을 수행하십시오. `undo` 대상을 사용하려면 실행 취소/다시 실행 키가 동작 후에 [MiniBracketed.register\_undo\_state()](mini-bracketed.qmd#minibracketed.register_undo_state)를 호출하도록 다시 매핑하십시오.

#### 설정 {#module-setup}


이 모듈은 `require('mini.bracketed').setup({})`을 통한 설정이 필요합니다 (`{}`를 `config` 테이블로 교체). 스크립팅에 사용하거나 수동으로 (`:lua MiniBracketed.*` 사용) 사용할 수 있는 전역 Lua 테이블 `MiniBracketed`가 생성됩니다.

사용 가능한 구성 설정은 [MiniBracketed.config](mini-bracketed.qmd#minibracketed.config)를 참조하십시오.

런타임 구성 설정(예: 대상 옵션)을 `vim.b.minibracketed_config` 내부의 버퍼에 국부적으로 재정의할 수 있으며, 이는 `MiniBracketed.config`와 동일한 구조를 가져야 합니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하십시오.

#### 비교 {#module-comparisons}



- [tpope/vim-unimpaired](https://github.com/tpope/vim-unimpaired):

    - 설정 없이 주로 내장 명령(예: [:bprevious](https://neovim.io/doc/user/helptag.html?tag=:bprevious) 등)을 통해 버퍼, 충돌, 파일, 위치 및 퀵픽스 대상을 지원합니다.

    - 인자 목록(argument list) 및 태그의 파일을 지원합니다. 이 모듈은 지원하지 않습니다.

    - 이 모듈의 대부분의 다른 대상(주석, 들여쓰기 등)은 지원하지 않습니다.

- [mini.indentscope](mini-indentscope.qmd#mini.indentscope):

    - 대상 [MiniBracketed.indent()](mini-bracketed.qmd#minibracketed.indent) 대상은 "첫 번째" 및 "마지막" 들여쓰기 변경으로 이동할 수 있습니다. 또한 더 작은 들여쓰기가 있는 줄뿐만 아니라 더 크거나 다른 들여쓰기가 있는 줄로도 이동할 수 있습니다.

    - 'mini.indentscope'의 매핑은 경계 근처의 빈 줄을 처리하는 방법이나 커서 위치에서 들여쓰기를 계산할지 여부와 같이 들여쓰기 범위를 계산하는 데 더 많은 유연성을 제공합니다.

#### 비활성화 {#module-disabling}


비활성화하려면 `vim.g.minibracketed_disable`(전역) 또는 `vim.b.minibracketed_disable`(버퍼용)을 `true`로 설정하십시오. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈 기능 비활성화를 위한 정확한 규칙 작성은 사용자의 몫으로 남겨둡니다. 일반적인 레시피는 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하십시오.

---

### setup() {#minibracketed.setup .help-syntax-right-anchor}

<p align="center">`MiniBracketed.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minibracketed.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 구성 테이블. [MiniBracketed.config](mini-bracketed.qmd#minibracketed.config)를 참조하십시오.

#### 사용법 {#minibracketed.setup-usage}



  ```lua
  require('mini.bracketed').setup() -- 기본 설정 사용
  -- 또는
  require('mini.bracketed').setup({}) -- {}를 사용자 구성 테이블로 교체
  ```

---

### config {#minibracketed.config .help-syntax-right-anchor}

<p align="center">`MiniBracketed.config`</p>
#### 기본값 {#minibracketed.config-defaults}



  ```lua
  MiniBracketed.config = {
    -- 첫 번째 레벨 요소는 대상의 동작을 설명하는 테이블입니다:
    --
    -- - <suffix> - 단일 문자 접미사. 매핑에서 `[` / `]` 뒤에 사용됩니다.
    --   예를 들어, `b`를 사용하면 `[B`, `[b`, `]b`, `]B` 매핑이 생성됩니다.
    --   매핑을 생성하지 않으려면 빈 문자열 `''`을 제공하십시오.
    --
    -- - <options> - 대상 옵션을 재정의하는 테이블입니다.
    --
    -- 자세한 내용은 `:h MiniBracketed.config`를 참조하십시오.

    buffer     = { suffix = 'b', options = {} },
    comment    = { suffix = 'c', options = {} },
    conflict   = { suffix = 'x', options = {} },
    diagnostic = { suffix = 'd', options = {} },
    file       = { suffix = 'f', options = {} },
    indent     = { suffix = 'i', options = {} },
    jump       = { suffix = 'j', options = {} },
    location   = { suffix = 'l', options = {} },
    oldfile    = { suffix = 'o', options = {} },
    quickfix   = { suffix = 'q', options = {} },
    treesitter = { suffix = 't', options = {} },
    undo       = { suffix = 'u', options = {} },
    window     = { suffix = 'w', options = {} },
    yank       = { suffix = 'y', options = {} },
  }
  ```

#### 옵션 {#minibracketed.config-options}


각 항목은 동일한 이름의 대상을 구성하며 매핑 접미사 및 대상 옵션을 구성하는 데이터를 가질 수 있습니다.

구성 예시:

  ```lua
  require('mini.bracketed').setup({
    -- 'tpope/vim-unimpaired'에서와 같이 충돌 마커를 위해 [N, [n, ]n, ]N 매핑
    conflict = { suffix = 'n' },

    -- 진단 이동 시 에러만 대상으로 함
    diagnostic = { options = { severity = vim.diagnostic.severity.ERROR } },

    -- `indent` 대상에 대한 매핑 생성 비활성화 (예를 들어,
    -- |mini.indentscope|의 매핑을 선호하는 경우)
    indent = { suffix = '' },

    -- `window` 대상에 대한 매핑을 사용자 정의 매핑을 위해 비활성화
    window = { suffix = '' },
  })

  -- 사용자 정의 `window` 매핑 생성
  local map = vim.keymap.set
  map('n', '<Leader>wH', "<Cmd>lua MiniBracketed.window('first')<CR>")
  map('n', '<Leader>wh', "<Cmd>lua MiniBracketed.window('backward')<CR>")
  map('n', '<Leader>wl', "<Cmd>lua MiniBracketed.window('forward')<CR>")
  map('n', '<Leader>wL', "<Cmd>lua MiniBracketed.window('last')<CR>")
  ```

##### 접미사(Suffix) {#minibracketed.config-options-suffix}


`suffix` 키는 대상 매핑을 생성하는 데 사용됩니다.

해당 대상에 대한 매핑 생성을 비활성화하려면 빈 문자열을 입력하십시오.
전혀 다른 매핑(예: [<span class="help-syntax-keys">\<Leader\></span>](https://neovim.io/doc/user/helptag.html?tag=<Leader>) 사용)을 생성하려면 대상 함수를 수동으로 사용하십시오.

단일 대상에 대해 `lower-suffix`(소문자 접미사)와 `upper-suffix`(대문자 접미사)를 사용하여 다음과 같은 매핑이 생성됩니다:

- `[` + `upper-suffix` : 첫 번째로 이동.

- `[` + `lower-suffix` : 뒤로 이동.

- `]` + `lower-suffix` : 앞으로 이동.

- `]` + `upper-suffix` : 마지막으로 이동.

문자가 아닌 것이 제공되면 앞/뒤 매핑만 생성됩니다.

##### 옵션(Options) {#minibracketed.config-options-options}


`options` 키는 해당 Lua 함수에 `opts`로 직접 전달됩니다.

---

### buffer() {#minibracketed.buffer .help-syntax-right-anchor}

<p align="center">`MiniBracketed.buffer`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
나열된 버퍼

다음/이전 나열된 버퍼로 이동합니다. 번호순으로 정렬됩니다 ([bufnr()](https://neovim.io/doc/user/helptag.html?tag=bufnr\(\)) 참조).

"forward" 방향은 번호가 증가하고, "backward"는 감소합니다.

#### 매개변수 {#minibracketed.buffer-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### comment() {#minibracketed.comment .help-syntax-right-anchor}

<p align="center">`MiniBracketed.comment`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
주석 블록

다음/이전 주석 블록으로 이동합니다. 'commentstring'을 사용하는 줄 단위 주석만 인식됩니다.

"forward" 방향은 줄 번호가 증가하고, "backward"는 감소합니다.

#### 매개변수 {#minibracketed.comment-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

  - <span class="help-syntax-keys">\<add_to_jumplist\></span> (`boolean`) - 현재 위치를 점프 목록에 추가할지 여부.
    기본값: `false`.

  - <span class="help-syntax-keys">\<block_side\></span> `(string)` - 주석 블록의 어느 쪽을 사용할지. "near"(기본값; 가장 가까운 쪽), "start"(첫 번째 줄 사용), "end"(마지막 줄 사용), "both"(첫 번째 및 마지막 줄 모두 사용) 중 하나입니다.

---

### conflict() {#minibracketed.conflict .help-syntax-right-anchor}

<p align="center">`MiniBracketed.conflict`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Git 충돌 마커

Git 충돌 마커를 포함하는 다음/이전 줄로 이동합니다. 즉, "<<<<<<< ", ">>>>>>> "로 시작하거나 "======="인 줄입니다.

"forward" 방향은 줄 번호가 증가하고, "backward"는 감소합니다.

참고:

- Operator-pending 모드에서 이 대상을 사용하면 병합 충돌을 해결하는 다음과 같은 접근 방식이 가능합니다:

    - 커서를 `=======` 줄에 놓습니다.

    - 다음 중 하나를 실행합니다: `d]x[xdd` (위쪽 선택) 또는
      `d[x]xdd` (아래쪽 선택).

#### 매개변수 {#minibracketed.conflict-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

  - <span class="help-syntax-keys">\<add_to_jumplist\></span> (`boolean`) - 현재 위치를 점프 목록에 추가할지 여부.
    기본값: `false`.

---

### diagnostic() {#minibracketed.diagnostic .help-syntax-right-anchor}

<p align="center">`MiniBracketed.diagnostic`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
진단(Diagnostic)

다음/이전 진단으로 이동합니다. 이는 모듈의 다른 메서드와 일치하는 인터페이스와 동작을 가진 내장 [vim.diagnostic.jump()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.jump\(\)) (Neovim<0.11에서는 [vim.diagnostic.goto\_next()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.goto_next\(\)) 및 [vim.diagnostic.goto\_prev()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.goto_prev\(\)))와 거의 유사합니다.

"forward" 방향은 줄 번호가 증가하고, "backward"는 감소합니다.

참고:

- `severity` 옵션을 사용하여 "다음/이전 에러로 이동"과 같은 매핑에 이 대상을 사용할 수 있습니다. 다음과 유사한 코드를 사용하십시오:

  ```lua
  local severity_error = vim.diagnostic.severity.ERROR
  -- 사용자 정의 매핑 내부에서 사용하십시오
  MiniBracketed.diagnostic('forward', { severity = severity_error })
  MiniBracketed.diagnostic('backward', { severity = severity_error })
  ```

#### 매개변수 {#minibracketed.diagnostic-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

  - <span class="help-syntax-keys">\<float\></span> `(boolean|table)` - 이동 후 플로팅 창을 제어합니다.
    사용 가능한 값은 [vim.diagnostic.goto\_next()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.goto_next\(\))를 참조하십시오.

  - <span class="help-syntax-keys">\<severity\></span> `(string|table)` - 사용할 심각도(severity).
    사용 가능한 값은 [diagnostic-severity](https://neovim.io/doc/user/helptag.html?tag=diagnostic-severity)를 참조하십시오.

---

### file() {#minibracketed.file .help-syntax-right-anchor}

<p align="center">`MiniBracketed.file`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
디스크의 파일

알파벳순으로 디스크의 다음/이전 파일로 이동합니다. 파일은 현재 버퍼의 파일 디렉토리(또는 버퍼에 읽기 가능한 파일이 없는 경우 현재 작업 디렉토리)에서 가져옵니다. 첫 번째 레벨의 파일만 사용되며, 즉 하위 디렉토리 내부로는 들어가지 않습니다.

"forward" 방향은 알파벳 순방향으로, "backward"는 역방향으로 이동합니다.

#### 매개변수 {#minibracketed.file-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### indent() {#minibracketed.indent .help-syntax-right-anchor}

<p align="center">`MiniBracketed.indent`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
들여쓰기 변경

다른 들여쓰기가 있는 다음/이전 줄로 이동합니다 ([indent()](https://neovim.io/doc/user/helptag.html?tag=indent\(\)) 참조).
들여쓰기가 더 작거나, 크거나, 다른 줄로 이동하는 데 사용할 수 있습니다.

참고:

- 성능상의 이유로 "first" 및 "last" 방향은 대부분의 다른 대상과 다르게 작동합니다. 기본적으로 매우 큰 `n_times` 옵션을 가진 "backward" 및 "forward"와 같습니다.

- 비슷한 이유로 `wrap`은 지원되지 않습니다.

- 빈 줄은 이동 방향에 있는 인접한 빈 줄이 아닌 줄에서 들여쓰기를 상속합니다.

"forward" 방향은 줄 번호가 증가하고, "backward"는 감소합니다.

#### 매개변수 {#minibracketed.indent-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<add_to_jumplist\></span> (`boolean`) - 현재 위치를 점프 목록에 추가할지 여부.
    기본값: `false`.

  - <span class="help-syntax-keys">\<change_type\></span> `(string)` - 어떤 유형의 들여쓰기 변경을 사용할지.
    "less"(기본값; 더 작은 들여쓰기), "more"(더 큰 들여쓰기), "diff"(다른 들여쓰기) 중 하나입니다.

---

### jump() {#minibracketed.jump .help-syntax-right-anchor}

<p align="center">`MiniBracketed.jump`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
현재 버퍼 내 점프

현재 버퍼 내에 있는 [jumplist](https://neovim.io/doc/user/helptag.html?tag=jumplist)의 다음/이전 점프로 이동합니다.

참고:

- 구현상의 문제로 Visual 모드 매핑은 없습니다.

"forward" 방향은 점프 번호가 증가하고, "backward"는 감소합니다.

#### 매개변수 {#minibracketed.jump-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### location() {#minibracketed.location .help-syntax-right-anchor}

<p align="center">`MiniBracketed.location`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
위치 목록(Location list)의 위치

[location-list](https://neovim.io/doc/user/helptag.html?tag=location-list)의 다음/이전 위치로 이동합니다. [:lfirst](https://neovim.io/doc/user/helptag.html?tag=:lfirst), [:lprevious](https://neovim.io/doc/user/helptag.html?tag=:lprevious), [:lnext](https://neovim.io/doc/user/helptag.html?tag=:lnext), [:llast](https://neovim.io/doc/user/helptag.html?tag=:llast)와 유사하지만 끝에서 되돌아가는 기능과 "first"/"last" 방향에 대한 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])를 지원합니다.

"forward" 방향은 위치 번호가 증가하고, "backward"는 감소합니다.

#### 매개변수 {#minibracketed.location-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### oldfile() {#minibracketed.oldfile .help-syntax-right-anchor}

<p align="center">`MiniBracketed.oldfile`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
이전 및 현재 세션의 오래된 파일

이전 세션([v:oldfiles](https://neovim.io/doc/user/helptag.html?tag=v:oldfiles) 참조) 또는 현재 세션([MiniBracketed.setup()](mini-bracketed.qmd#minibracketed.setup) 호출 후 자동으로 업데이트됨)에서 읽기 가능한 더 오래된/최신 파일로 이동합니다.

"forward" 방향은 더 최근 파일로, "backward"는 더 오래된 파일로 이동합니다.

참고:

- 현재 세션에서는 읽기 가능한 파일에 대해 일반 버퍼(['buftype'](https://neovim.io/doc/user/helptag.html?tag='buftype') 참조)만 추적합니다.

- 이 대상을 이동할 때는 새 파일이 추적되지 않습니다. 이 대상이 아닌 방식(예: [MiniBracketed.buffer()](mini-bracketed.qmd#minibracketed.buffer))으로 버퍼 변경이 완료된 후에만 마지막으로 이동한 버퍼와 새 버퍼의 최근성을 업데이트합니다.

#### 매개변수 {#minibracketed.oldfile-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### quickfix() {#minibracketed.quickfix .help-syntax-right-anchor}

<p align="center">`MiniBracketed.quickfix`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
퀵픽스 목록의 퀵픽스

[quickfix](https://neovim.io/doc/user/helptag.html?tag=quickfix) 목록의 다음/이전 항목으로 이동합니다. [:cfirst](https://neovim.io/doc/user/helptag.html?tag=:cfirst), [:cprevious](https://neovim.io/doc/user/helptag.html?tag=:cprevious), [:cnext](https://neovim.io/doc/user/helptag.html?tag=:cnext), [:clast](https://neovim.io/doc/user/helptag.html?tag=:clast)와 유사하지만 끝에서 되돌아가는 기능과 "first"/"last" 방향에 대한 [[count]](https://neovim.io/doc/user/helptag.html?tag=[count])를 지원합니다.

"forward" 방향은 위치 번호가 증가하고, "backward"는 감소합니다.

#### 매개변수 {#minibracketed.quickfix-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### treesitter() {#minibracketed.treesitter .help-syntax-right-anchor}

<p align="center">`MiniBracketed.treesitter`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Tree-sitter 노드

현재 tree-sitter 노드 및 그 부모(루트 제외)의 끝/시작으로 이동합니다.

참고:

- 현재 버퍼에 로드된 tree-sitter 파서가 필요합니다.

- 성능상의 이유로 "first" 및 "last" 방향은 대부분의 다른 대상과 다르게 작동합니다. 기본적으로 매우 큰 `n_times` 옵션을 가진 "backward" 및 "forward"와 같습니다.

- 비슷한 이유로 `wrap`은 지원되지 않습니다.

"forward" 방향은 커서를 노드의 끝으로, "backward"는 노드의 시작으로 이동합니다.

#### 매개변수 {#minibracketed.treesitter-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<add_to_jumplist\></span> (`boolean`) - 현재 위치를 점프 목록에 추가할지 여부.
    기본값: `false`.

---

### undo() {#minibracketed.undo .help-syntax-right-anchor}

<p align="center">`MiniBracketed.undo`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
추적된 선형 히스토리를 따른 실행 취소(Undo)

요약:

- [u](https://neovim.io/doc/user/helptag.html?tag=u) 및 [CTRL-R](https://neovim.io/doc/user/helptag.html?tag=CTRL-R) 키를 평소처럼 사용할 수 있지만(다시 매핑되었음에도 불구하고), 실행될 때마다 이 모듈의 선형 실행 취소 히스토리에 새로운 상태가 기록됩니다.

- 이 대상을 이동하면 선형 실행 취소 히스토리를 따라 실제 나타난 순서대로 실행 취소 상태가 나타납니다.

- 내장 메서드와의 큰 차이점 중 하나는 추적된 선형 히스토리가 실행 취소 상태를 반복할 수 있다는 것입니다(연속적이지는 않음).

Neovim의 실행 취소 히스토리 관리 기본 방식은 브랜치(가지)를 통한 것입니다([undo-branches](https://neovim.io/doc/user/helptag.html?tag=undo-branches) 참조). 기본적으로 여러 변경 사항을 실행 취소한 다음 새로운 변경 사항을 만들면 새로운 실행 취소 브랜치가 생성되는 동시에 보통(['undolevels'](https://neovim.io/doc/user/helptag.html?tag='undolevels') 참조) 다른 브랜치에 이전 버퍼 상태를 저장하는 것을 의미합니다. 실행 취소 상태 생성 시간별로 탐색하는 명령(예: [:earlier](https://neovim.io/doc/user/helptag.html?tag=:earlier) 및 [:later](https://neovim.io/doc/user/helptag.html?tag=:later))이 있지만, 이들을 순환하는 직관적인 방법은 없습니다. 기존 [g-](https://neovim.io/doc/user/helptag.html?tag=g-) 및 [g+](https://neovim.io/doc/user/helptag.html?tag=g+)는 생성 시간을 기반으로 실행 취소 상태를 순환하는데, 이는 많이 편집된 버퍼에서 종종 매우 빠르게 혼란스러워집니다.

이 `undo()` 대상은 실제 상태가 나타난 순서대로 선형 실행 취소 히스토리를 순환하는 방법을 제공합니다. 새로운 실행 취소 상태가 발생할 때와 [MiniBracketed.register\_undo\_state()](mini-bracketed.qmd#minibracketed.register_undo_state)가 호출될 때마다 등록함으로써 이를 수행합니다. 더 "기본(out of the box)"적인 경험을 제공하기 위해 [u](https://neovim.io/doc/user/helptag.html?tag=u) 및 [CTRL-R](https://neovim.io/doc/user/helptag.html?tag=CTRL-R)은 실행 취소/다시 실행을 수행한 후 이를 호출하도록 다시 매핑됩니다.

예시:

이 대상을 이동하는 것과 내장 기능을 사용하는 것의 차이점을 더 명확하게 보여주기 위한 예시입니다:


- 새 버퍼([:new](https://neovim.io/doc/user/helptag.html?tag=:new))에서 실행 취소 히스토리를 생성합니다:

    - `one two three` 텍스트를 입력합니다.

    - `daw`로 첫 번째 단어를 삭제하고 `u`로 변경 사항을 취소합니다.

    - `daw`로 두 번째 단어를 삭제하고 `u`로 변경 사항을 취소합니다.

    - `daw`로 세 번째 단어를 삭제하고 `u`로 변경 사항을 취소합니다.


- 이제 다음 중 하나를 시도해 보십시오 (각각 별도의 새 버퍼에서 이전 단계를 수행한 후):

    - `u`를 누릅니다. 빈 버퍼로 돌아갑니다. `<C-R>`을 두 번 누르면 최신 변경 사항(`one two`)으로 이동합니다. 이 두 키로는 다른 상태(예: `two three` 또는 `one three`)로 이동할 방법이 없습니다.


    - `g-`를 누릅니다. 빈 버퍼로 이동합니다. `g+`를 4번 누릅니다. 생성된 순서대로 사용 가능한 모든 실행 취소 상태를 순환합니다.


    - 마지막으로 `[u`를 누릅니다. 이전에 사용자가 방문했던 상태인 `one two`로 돌아갑니다. 다시 `[u`를 누르면 `one two three`가 복원됩니다. `]U`를 사용하여 마지막으로 방문한 실행 취소 상태로 이동합니다.

#### 매개변수 {#minibracketed.undo-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### register_undo_state() {#minibracketed.register_undo_state .help-syntax-right-anchor}

<p align="center">`MiniBracketed.register_undo_state`()</p>
실행 취소 대상을 위한 상태 등록

이 함수를 사용하여 현재 실행 취소 상태를 이 모듈의 선형 실행 취소 히스토리에 추가하십시오. [MiniBracketed.setup()](mini-bracketed.qmd#minibracketed.setup)에서 [u](https://neovim.io/doc/user/helptag.html?tag=u) 및 [CTRL-R](https://neovim.io/doc/user/helptag.html?tag=CTRL-R) 키가 새 상태를 선형 실행 취소 히스토리에 추가하도록 다시 매핑하는 데 사용됩니다.

---

### window() {#minibracketed.window .help-syntax-right-anchor}

<p align="center">`MiniBracketed.window`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
일반 창(Window)

다음/이전 일반 창으로 이동합니다. 번호순으로 정렬됩니다 ([winnr()](https://neovim.io/doc/user/helptag.html?tag=winnr\(\)) 참조).

"forward" 방향은 창 번호가 증가하고, "backward"는 감소합니다.

일반(플로팅이 아닌) 창만 사용됩니다.

#### 매개변수 {#minibracketed.window-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

---

### yank() {#minibracketed.yank .help-syntax-right-anchor}

<p align="center">`MiniBracketed.yank`(<span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
"최근 붙여넣기 영역"을 yank 히스토리 항목으로 교체

[MiniBracketed.setup()](mini-bracketed.qmd#minibracketed.setup)이 호출된 후, 모든 yank/삭제/변경 작업마다(기술적으로는 [TextYankPost](https://neovim.io/doc/user/helptag.html?tag=TextYankPost) 이벤트가 트리거될 때마다) 작업 대상이 yank 히스토리에 추가됩니다. 이 대상을 이동하면 최근 붙여넣기 작업 영역이 yank 히스토리의 항목으로 교체됩니다.

기본적으로 텍스트 붙여넣기(예: [p](https://neovim.io/doc/user/helptag.html?tag=p) 또는 [P](https://neovim.io/doc/user/helptag.html?tag=P)) 직후에 호출할 때 가장 잘 작동합니다.

"최근 붙여넣기 영역"을 더 잘 감지하려면 나중에 설명할 [MiniBracketed.register\_put\_region()](mini-bracketed.qmd#minibracketed.register_put_region)을 사용하십시오.

"forward" 방향은 더 최신 yank 히스토리 항목으로, "backward"는 더 오래된 항목으로 이동합니다.

예시:


- `one two three`를 입력합니다.

- `yiw`로 각 단어를 yank 합니다.

- 새 줄을 만들고 `p`를 누릅니다. `three`가 붙여넣어집니다.

- `[y`를 누릅니다. 최근 `three`가 `two`로 바뀝니다.

#### 최근 붙여넣기 영역 {#minibracketed.yank-latestputregion}


"최근 붙여넣기 영역"은 다음과 같습니다 (우선순위 내림차순):

- 이 대상의 최근 이동 영역.

- 사용자가 [MiniBracketed.register\_put\_region()](mini-bracketed.qmd#minibracketed.register_put_region)으로 등록한 영역.

- ['[](https://neovim.io/doc/user/helptag.html?tag='[) 및 [']](https://neovim.io/doc/user/helptag.html?tag=']) 마크에서 가져온 영역.

사용자의 경우 사용할 영역을 관리하기 위해 다음과 같은 접근 방식이 있습니다:

- 아무것도 하지 않음. 이 경우 `[` / `]` 마크 사이의 영역이 첫 번째 `yank` 이동에 항상 사용됩니다.
  가능은 하지만 여러 단점이 있습니다. 마크가 설정되지 않은 경우 최근 yank 되거나 변경된 영역 또는 전체 버퍼를 사용합니다.
  최근 붙여넣기 작업 후에만 이 대상을 이동하는 것을 기억한다면 예상대로 작동할 것입니다.


- 일반적인 붙여넣기 작업이 [MiniBracketed.register\_put\_region()](mini-bracketed.qmd#minibracketed.register_put_region)을 사용하도록 다시 매핑합니다.
  그 후에는 매핑된 붙여넣기 작업의 영역만 첫 번째 이동에 사용됩니다. 사용자 정의 매핑 예시 ([:map-expression](https://neovim.io/doc/user/helptag.html?tag=:map-expression) 사용 유의):

    ```lua
    local put_keys = { 'p', 'P' }
    for _, lhs in ipairs(put_keys) do
      local rhs = 'v:lua.MiniBracketed.register_put_region("' .. lhs .. '")'
      vim.keymap.set({ 'n', 'x' }, lhs, rhs, { expr = true })
    end
    ```

#### 매개변수 {#minibracketed.yank-parameters}



<span class="help-syntax-special">{direction}</span> `(string)` "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 다음과 같은 필드를 가진 테이블:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 이동 횟수. 기본값: [v:count1](https://neovim.io/doc/user/helptag.html?tag=v:count1).

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - 끝에서 되돌아갈지 여부. 기본값: `true`.

  - <span class="help-syntax-keys">\<operators\></span> `(table)` - 이동을 위해 yank 항목을 사용해야 하는 연산자 이름("c", "d" 또는 "y") 배열입니다. 예를 들어, [y](https://neovim.io/doc/user/helptag.html?tag=y)를 사용한 실제 yank 작업의 결과 항목으로만 이동하려면 `{ "y" }`를 사용하십시오.
    기본값: `{ 'c', 'd', 'y' }`.

---

### register_put_region() {#minibracketed.register_put_region .help-syntax-right-anchor}

<p align="center">`MiniBracketed.register_put_region`(<span class="help-syntax-special">{put_key}</span>)</p>
"최근 붙여넣기 영역" 등록

이 함수는 붙여넣기 레지스터가 관련성이 생기고([v:register](https://neovim.io/doc/user/helptag.html?tag=v:register)가 적절히 설정됨) 붙여넣기 작업이 일어나기 전(['[](https://neovim.io/doc/user/helptag.html?tag='[) 및 [']](https://neovim.io/doc/user/helptag.html?tag=']) 마크가 관련성이 생기기 전)에 호출되어야 합니다.

사용자용 표현식 매핑(expression mapping, [:map-expression](https://neovim.io/doc/user/helptag.html?tag=:map-expression) 참조)에서 사용하도록 설계되었습니다.
매핑 예시는 [MiniBracketed.yank()](mini-bracketed.qmd#minibracketed.yank)를 참조하십시오.

#### 매개변수 {#minibracketed.register_put_region-parameters}



<span class="help-syntax-special">{put_key}</span> `(string)` 다시 매핑할 붙여넣기 키입니다.

#### 반환값 {#minibracketed.register_put_region-return}


`(string)` 표현식 매핑 내부에서 더 나은 사용을 위해 `put_key`를 반환합니다.

---

### advance() {#minibracketed.advance .help-syntax-right-anchor}

<p align="center">`MiniBracketed.advance`(<span class="help-syntax-special">{iterator}</span>, <span class="help-syntax-special">{direction}</span>, <span class="help-syntax-special">{opts}</span>)</p>
반복자(iterator) 이동

이 모듈에서 모든 forward/backward/first/last 이동을 수행하는 주요 함수입니다. 기본 아이디어는 반복자(현재 상태와 다음/이전 상태로 가는 방법에 대한 정보를 포함하는 객체)를 가져와서 필요하거나 허용될 때까지 특정 방향으로 이동하는 것입니다.

참고:

- "first" 및 "last" 방향은 초기 상태를 `start_edge` 및 `end_edge`로 미리 설정한 "forward" 및 "backward"의 편의용 래퍼입니다.

- 반복자의 `next()` 및 `prev()` 메서드는 입력으로 `nil`을 처리할 수 있어야 합니다.

- 이 함수는 새로운 상태만 반환하며 `iterator.state`를 수정하지 않습니다.

#### 매개변수 {#minibracketed.advance-parameters}



<span class="help-syntax-special">{iterator}</span> `(table)` 테이블:

  - 메서드:

      - <span class="help-syntax-keys">\<next\></span> - 상태가 주어지면 순방향 상태를 반환합니다 (wrap 없음).

      - <span class="help-syntax-keys">\<prev\></span> - 상태가 주어지면 역방향 상태를 반환합니다 (wrap 없음).

  - 필드:

      - <span class="help-syntax-keys">\<state\></span> - 현재 상태를 설명하는 객체.

      - <span class="help-syntax-keys">\<start_edge\></span> (선택 사항) - 첫 번째 상태를 설명하는 `forward(start_edge)`가 있는 객체. `nil`인 경우 앞으로 되돌아가거나 "first" 방향을 사용할 수 없습니다.

      - <span class="help-syntax-keys">\<end_edge\></span> (선택 사항) - 마지막 상태를 설명하는 `backward(end_edge)`가 있는 객체. `nil`인 경우 뒤로 되돌아가거나 "last" 방향을 사용할 수 없습니다.

<span class="help-syntax-special">{direction}</span> `(string)` 방향. "first", "backward", "forward", "last" 중 하나입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 다음과 같은 키를 가진 옵션:

  - <span class="help-syntax-keys">\<n_times\></span> `(number)` - 입력 방향으로 이동할 횟수.
    기본값: `v:count1`.

  - <span class="help-syntax-keys">\<wrap\></span> `(boolean)` - `next()` 또는 `prev()`가 `nil`을 반환할 때 끝에서 되돌아갈지 여부. 기본값: `true`.

#### 반환값 {#minibracketed.advance-return}


`(any)` 결과 상태. `nil`인 경우 유효한 결과 상태에 도달할 수 없습니다.
