---
title: "mini.hipatterns 문서"
---

_Generated from the `main` branch of 'mini.nvim'_

<a name="mini.hipatterns" href="mini-hipatterns.qmd#mini.hipatterns"><b>mini.hipatterns</b></a> 텍스트 패턴 강조

MIT License Copyright (c) 2023 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:

- 설정 가능한 패턴과 하이라이트 그룹(문자열 또는 호출 가능 객체)으로 텍스트를 강조합니다.


- 설정 가능한 디바운스 지연 시간과 함께 비동기적으로 하이라이트가 업데이트됩니다.


- 버퍼 내의 매치 항목을 가져오는 함수 ( [MiniHipatterns.get\_matches()](mini-hipatterns.qmd#minihipatterns.get_matches) 참고).

공통 구성 예제는 [MiniHipatterns-examples](mini-hipatterns.qmd#minihipatterns-examples)를 참고하십시오.

참고:

- 기본적으로는 어떤 하이라이터도 정의되어 있지 않습니다. 시각적인 효과를 보려면 `config.highlighters`에 추가하십시오.


- 가끔(특히 동일한 줄 번호에서 버퍼 업데이트가 빈번할 때) 하이라이트가 최신 상태가 아니거나 적용되어야 할 때 적용되지 않을 수 있습니다. 이는 텍스트 변경에 반응하는 업데이트( [nvim\_buf\_attach()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_attach\(\))의 `on_lines`를 통한)의 비동기적 특성 때문입니다. 최신 상태로 유지하려면 다음 중 하나를 사용하십시오:

    - 창 스크롤 (예: [CTRL-E](https://neovim.io/doc/user/helptag.html?tag=CTRL-E) / [CTRL-Y](https://neovim.io/doc/user/helptag.html?tag=CTRL-Y)). 이를 통해 창 보기 내부의 하이라이트가 최신 상태임을 보장합니다.

    - 버퍼 숨기기 및 표시.

    - `:edit` 실행 ( [MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)으로 하이라이트를 활성화한 경우).

    - [MiniHipatterns.update()](mini-hipatterns.qmd#minihipatterns.update) 수동 호출.


- Insert 모드에서 강조된 패턴 근처에서 입력할 때 깜빡임이 발생한다면, [mini.completion](mini-completion.qmd#mini.completion)의 `delay` 설정이나 내장된 completion을 사용하기 때문일 수 있습니다.
  'mini.completion'에서 더 나은 경험을 하려면 `delay.completion`이 이 모듈의 `delay.text_change`보다 작아야 합니다 (기본값으로 설정되어 있습니다).
  이유는 (현재로서는 해결할 수 없는) Neovim의 내장 completion 구현의 한계 때문입니다.

#### 설정 {#module-setup}


하이라이트 설정은 두 가지 방법으로 할 수 있습니다:

- `require('mini.hipatterns').enable()`을 통해 각 버퍼에 대해 수동으로 설정합니다. 이는 언로드될 때까지(현재 파일에 대해 `:edit`을 호출하는 경우도 포함) 특정 버퍼에서만 하이라이트를 활성화합니다.


- `require('mini.hipatterns').setup({})`을 통해 전역적으로 설정합니다 ( `{}`를 설정 테이블로 교체하십시오). 이는 "일반" 버퍼('buftype' 참고)에서 하이라이트를 자동으로 활성화합니다. 다른 버퍼에서 수동으로 활성화하려면 [MiniHipatterns.enable()](mini-hipatterns.qmd#minihipatterns.enable)을 사용하십시오.
  또한 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블인 `MiniHipatterns`를 생성합니다 ( `:lua MiniHipatterns.*` 참고).

설정 구조와 기본값은 [MiniHipatterns.config](mini-hipatterns.qmd#minihipatterns.config)를 참고하십시오.

`vim.b.minihipatterns_config` 내에서 버퍼 로컬로 런타임 설정(하이라이터 및 지연 시간 등)을 재정의할 수 있으며, `MiniHipatterns.config`와 동일한 구조를 가져야 합니다.
자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참고하십시오.

#### 비교 {#module-comparisons}



- [folke/todo-comments](https://github.com/folke/todo-comments):

    - "TODO", "NOTE", "FIXME"와 같은 패턴에 특화되어 있는 반면, 이 모듈은 모든 Lua 패턴 및 계산 가능한 하이라이트 그룹과 함께 작동할 수 있습니다.

    - 텍스트 하이라이트 외의 기능(사인 배치, "telescope.nvim" 확장 등)이 있지만, 이 모듈은 텍스트 하이라이트에만 집중합니다.

- [folke/paint.nvim](https://github.com/folke/paint.nvim):

    - 이 모듈과 거의 비슷하지만, 계산된 패턴 및 하이라이트 그룹, 비동기 지연 등 기능이 약간 적습니다.

- [NvChad/nvim-colorizer.lua](https://github.com/NvChad/nvim-colorizer.lua):

    - 색상 하이라이트에 특화되어 있는 반면, 이 모듈은 모든 Lua 패턴 및 계산 가능한 하이라이트 그룹과 함께 작동할 수 있습니다.

    - 하이라이트할 수 있는 더 많은 내장 색상 공간이 있는 반면, 이 모듈은 기본적으로 16진수 색상 하이라이트만 제공합니다
      ( [MiniHipatterns.gen\_highlighter.hex\_color()](mini-hipatterns.qmd#minihipatterns.gen_highlighter.hex_color) 참고). 다른 유형도 구현이 가능합니다.

- [uga-rosa/ccc.nvim](https://github.com/uga-rosa/ccc.nvim):

    - 색상 하이라이트 이상의 기능이 있으며, 'NvChad/nvim-colorizer.lua'와 같은 방식으로 이 모듈과 비교됩니다.

#### 하이라이트 그룹 {#module-highlightgroups}



- `MiniHipatternsFixme` - `FIXME` 스타일의 패턴에 사용하기를 권장하는 그룹.

- `MiniHipatternsHack` - `HACK` 스타일의 패턴에 사용하기를 권장하는 그룹.

- `MiniHipatternsTodo` - `TODO` 스타일의 패턴에 사용하기를 권장하는 그룹.

- `MiniHipatternsNote` - `NOTE` 스타일의 패턴에 사용하기를 권장하는 그룹.

하이라이트 그룹을 변경하려면 [nvim\_set\_hl()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_hl\(\))로 직접 설정하십시오.

#### 비활성화 {#module-disabling}


이 모듈은 세 가지 방법으로 비활성화할 수 있습니다:

- 전역적으로: `vim.g.minihipatterns_disable`를 `true`로 설정합니다.

- 버퍼에 대해 영구적으로 로컬로: `vim.b.minihipatterns_disable`를 `true`로 설정합니다.

- 버퍼에 대해 일시적으로 로컬로 ( [MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)으로 설정된 경우 다음 자동 활성화 이벤트 전까지): [MiniHipatterns.disable()](mini-hipatterns.qmd#minihipatterns.disable)을 호출합니다.

시나리오와 사용자 정의 의도가 매우 다양하기 때문에 모듈 기능을 비활성화하기 위한 정확한 규칙을 작성하는 것은 사용자의 몫입니다. 일반적인 방법은 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참고하십시오.

---

### 예제 {#minihipatterns-examples .help-syntax-right-anchor}

#### 일반적인 구성 예제 {#minihipatterns-examples-commonconfigurationexamples}



- 다양한 주의 수준을 전달하는 데 사용되는 특별한 단어:

  ```lua
  require('mini.hipatterns').setup({
    highlighters = {
      fixme = { pattern = 'FIXME', group = 'MiniHipatternsFixme' },
      hack  = { pattern = 'HACK',  group = 'MiniHipatternsHack'  },
      todo  = { pattern = 'TODO',  group = 'MiniHipatternsTodo'  },
      note  = { pattern = 'NOTE',  group = 'MiniHipatternsNote'  },
    }
  })
  ```


- 패턴이 독립된 단어로 나타날 때만 매치하려면 프론티어 패턴 `%f`를 사용하십시오. 예를 들어 `'TODO'` 패턴 대신 `'%f[%w]()TODO()%f[%W]'`를 사용합니다. 이 경우 `'TODOING'`이나 `'MYTODO'`는 매치되지 않지만 `'TODO'`와 `'TODO:'`는 매치됩니다.


- 16진수 색상(예: `#rrggbb`) 하이라이트:

  ```lua
  local hipatterns = require('mini.hipatterns')
  hipatterns.setup({
    highlighters = {
      hex_color = hipatterns.gen_highlighter.hex_color(),
    }
  })
  ```

  입력 옵션의 `style` 필드를 사용하여 16진수 색상의 어느 부분이 강조되는지 사용자 정의할 수 있습니다. [MiniHipatterns.gen\_highlighter.hex\_color()](mini-hipatterns.qmd#minihipatterns.gen_highlighter.hex_color)를 참고하십시오.


- 색상이 지정된 단어:

  ```lua
  local words = { red = '#ff0000', green = '#00ff00', blue = '#0000ff' }
  local word_color_group = function(_, match)
    local hex = words[match]
    if hex == nil then return nil end
    return MiniHipatterns.compute_hex_color_group(hex, 'bg')
  end

  local hipatterns = require('mini.hipatterns')
  hipatterns.setup({
    highlighters = {
      word_color = { pattern = '%S+', group = word_color_group },
    },
  })
  ```


- 후행 공백 (더 구체적인 [mini.trailspace](mini-trailspace.qmd#mini.trailspace)를 사용하고 싶지 않은 경우):

  ```lua
  { pattern = '%f[%s]%s*$', group = 'Error' }
  ```


- 특정 민감한 정보 검열:

  ```lua
  local censor_extmark_opts = function(_, match, _)
    local mask = string.rep('x', vim.fn.strchars(match))
    return {
      virt_text = { { mask, 'Comment' } }, virt_text_pos = 'overlay',
      priority = 200, right_gravity = false,
    }
  end

  require('mini.hipatterns').setup({
    highlighters = {
      censor = {
        pattern = 'password: ()%S+()',
        group = '',
        extmark_opts = censor_extmark_opts,
      },
    },
  })
  ```


- 특정 파일 형식에서만 활성화합니다. 적어도 다음과 같은 방법이 있습니다:

    - (권장) filetype-plugin에서 `vim.b.minihipatterns_config`를 사용합니다. 기본적으로 설정 디렉토리 ( [\$XDG\_CONFIG\_HOME](https://neovim.io/doc/user/helptag.html?tag=$XDG_CONFIG_HOME) 참고)에 "after/ftplugin/<span class="help-syntax-keys">\<filetype\></span>.lua" 파일을 만들고 파일 형식에 특화된 하이라이터로 `vim.b.minihipatterns_config`를 정의합니다.

      이는 `require('mini.hipatterns').setup()` 호출을 가정합니다.

      예를 들어 Lua 파일의 EmmyLua 주석에서 키워드를 강조하려면 다음 내용으로 "after/ftplugin/lua.lua"를 생성하십시오:

        ```lua
        vim.b.minihipatterns_config = {
          highlighters = {
            emmylua = { pattern = '^%s*%-%-%-()@%w+()', group = 'Special' }
          }
        }
        ```


    - 조건과 함께 호출 가능한 `pattern`을 사용합니다. 예:

      ```lua
      require('mini.hipatterns').setup({
        highlighters = {
          emmylua = {
            pattern = function(buf_id)
              if vim.bo[buf_id].filetype ~= 'lua' then return nil end
              return '^%s*%-%-%-()@%w+()'
            end,
            group = 'Special',
          },
        },
      })
      ```


- 특정 파일 형식에서만 비활성화합니다. [MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)으로 활성화하고 비활성화하려는 버퍼에 대해 버퍼 로컬 변수인 `vim.b.minihipatterns_disable`를 `true`로 설정하십시오. 더 많은 예제는 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참고하십시오.

---

### setup() {#minihipatterns.setup .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minihipatterns.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniHipatterns.config](mini-hipatterns.qmd#minihipatterns.config) 참고.

#### 사용법 {#minihipatterns.setup-usage}



  ```lua
  require('mini.hipatterns').setup({}) -- {}를 설정 테이블로 교체하십시오
                                       -- `highlighters` 필드가 필요합니다
  ```

---

### config {#minihipatterns.config .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.config`</p>
#### 기본값 {#minihipatterns.config-defaults}



  ```lua
  MiniHipatterns.config = {
    -- 하이라이터가 포함된 테이블 (자세한 내용은 |MiniHipatterns.config| 참고).
    -- 기본적으로는 아무것도 정의되어 있지 않습니다. 시각적인 효과를 위해 수동으로 추가하십시오.
    highlighters = {},

    -- 비동기 하이라이트 프로세스를 정의하는 지연 시간(ms)
    delay = {
      -- 텍스트가 변경될 때마다 업데이트를 기다리는 시간
      text_change = 200,

      -- 창 스크롤 후 업데이트를 기다리는 시간
      scroll = 50,
    },
  }
  ```

#### 하이라이터 {#minihipatterns.config-highlighters}


`highlighters` 테이블은 매치 시작 부분에 [extmark](https://neovim.io/doc/user/helptag.html?tag=extmark)를 배치하여 강조할 패턴을 정의합니다. 명시적으로 명명된 필드가 있을 수도 있고 없을 수도 있지만, 버퍼 로컬 설정으로 `vim.b.minihipatterns_config`를 적절하게 사용하려면 필드 이름을 지정하는 것이 권장되며 필수입니다. 기본적으로는 사용자의 정의를 기다리는 빈 상태입니다.

각 항목은 다음 필드를 포함하는 테이블로 단일 하이라이터를 정의합니다:

- <span class="help-syntax-keys">\<pattern\></span> `(string|function|table)` - 강조할 Lua 패턴. 문자열, 문자열을 반환하는 호출 가능 객체 또는 이들의 배열일 수 있습니다.
  문자열인 경우:

    - 시작과 끝에 `()`를 배치하여 하위 매치를 구분할 수 있습니다. 괄호로 감싸지 마십시오 ( `number expected, got string` 오류가 발생함). 예: `xx()abcd()xx`는 앞뒤에 `xx`가 있는 경우에만 `abcd`를 매치합니다.

  호출 가능한 경우:

    - 활성화된 모든 버퍼에 대해 버퍼 식별자를 입력으로 하여 호출됩니다. 단일 문자열 패턴 또는 `nil`(해당 하이라이터가 해당 버퍼에서 작동하지 않음을 의미)을 반환해야 합니다.

  배열인 경우:

    - 각 요소는 매치되며 동일한 하이라이트 그룹으로 강조됩니다.

    참고: 매칭은 겹치는 (하위) 매칭을 생성하지 않습니다 ( [cpo-c](https://neovim.io/doc/user/helptag.html?tag=cpo-c)의 작동 방식과 유사). 예를 들어 `xxxxxxx` 줄의 경우:

    - 패턴 `xxx`는 1-3, 4-6 열을 매치합니다.

    - 패턴 `()xx()x`는 1-2, 3-4, 5-6 열을 매치합니다.

    - 패턴 `x()xx()`는 2-3, 5-6 열을 매치합니다.

    - 패턴 `x()x()x`는 2-2, 4-4, 6-6 열을 매치합니다.


- <span class="help-syntax-keys">\<group\></span> `(string|function)` - 사용할 하이라이트 그룹의 이름. 문자열이거나 문자열을 반환하는 호출 가능 객체일 수 있습니다.
  호출 가능한 경우:

    - 모든 패턴 매치에 대해 다음 인수를 사용하여 호출됩니다:

        - `buf_id` - 버퍼 식별자.

        - `match` - 강조할 문자열 패턴 매치.

        - `data` - 매치에 대한 정보가 포함된 추가 테이블.
          최소한 다음과 같은 필드를 갖습니다:

            - <span class="help-syntax-keys">\<full_match\></span> - 전체 패턴 매치가 포함된 문자열.

            - <span class="help-syntax-keys">\<line\></span> - 매치 줄 번호 (1부터 시작).

            - <span class="help-syntax-keys">\<from_col\></span> - 매치 시작 바이트 열 (1부터 시작).

            - <span class="help-syntax-keys">\<to_col\></span> - 매치 종료 바이트 열 (1부터 시작, 포함).


    - `nil`을 반환할 수 있으며, 이는 해당 매치가 강조되지 않음을 의미합니다.


- <span class="help-syntax-keys">\<extmark_opts\></span> `(table|function|nil)` - [nvim\_buf\_set\_extmark()](https://neovim.io/doc/user/helptag.html?tag=nvim_buf_set_extmark\(\))를 위한 선택적 추가 옵션. 호출 가능한 경우 호출 가능한 <span class="help-syntax-keys">\<group\></span>과 동일한 방식으로 호출되며( `data`에는 <span class="help-syntax-keys">\<group\></span> 값을 갖는 `hl_group` 키도 포함됨), extmark를 위한 모든 옵션( `end_row`, `end_col`, `hl_group` 및 `priority` 포함)이 포함된 테이블을 반환해야 합니다.

예제는 "일반적인 사용 사례" 섹션을 참고하십시오.

#### 지연 시간 {#minihipatterns.config-delay}


`delay`는 비동기 하이라이트 프로세스에 사용되는 밀리초 단위의 지연 시간을 정의하는 테이블입니다.

`delay.text_change`는 하이라이트 업데이트를 누적하여(디바운스 방식) 지연시키는 데 사용됩니다. 값이 작을수록 응답은 빠르지만 업데이트가 더 빈번해집니다. 값이 클수록 응답은 느려지지만 업데이트 빈도는 낮아집니다.

`delay.scroll`은 스크롤하는 동안 현재 창 보기에서 하이라이트 업데이트를 지연시키는 데 사용됩니다 ( [WinScrolled](https://neovim.io/doc/user/helptag.html?tag=WinScrolled) 이벤트 참고). 이러한 업데이트는 스크롤 후 최신 하이라이트를 보장하기 위해 존재합니다.

---

### enable() {#minihipatterns.enable .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.enable`(<span class="help-syntax-special">{buf_id}</span>, <span class="help-syntax-special">{config}</span>)</p>
버퍼에서 하이라이트 활성화

참고:

- 기본 설정으로는 어떤 하이라이터도 없기 때문에 아무것도 강조하지 않습니다.


- 버퍼 하이라이트는 버퍼가 메모리에서 언로드되거나 이 버퍼에 대해 [MiniHipatterns.disable()](mini-hipatterns.qmd#minihipatterns.disable)이 호출될 때까지 활성화됩니다.


- `:edit`은 버퍼를 닫고 여는 것과 거의 같기 때문에 이를 비활성화합니다. `:edit` 후에도 하이라이트가 유지되도록 하려면 [MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)을 호출하십시오.

#### 매개변수 {#minihipatterns.enable-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number|nil)` 하이라이트를 활성화할 버퍼 식별자.
  기본값: 현재 버퍼의 경우 0.

<span class="help-syntax-special">{config}</span> `(table|nil)` 선택적 버퍼 로컬 설정. [MiniHipatterns.config](mini-hipatterns.qmd#minihipatterns.config)와 동일한 구조를 가져야 합니다. 값은 다음 순서로 가져옵니다:

  - 이 `config` 인수로부터 (제공된 경우).

  - `vim.b.minihipatterns_config`의 버퍼 로컬 설정으로부터 (존재하는 경우).

  - 전역 설정으로부터 ( [MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)이 호출된 경우).

  - 기본값으로부터.

---

### disable() {#minihipatterns.disable .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.disable`(<span class="help-syntax-special">{buf_id}</span>)</p>
버퍼에서 하이라이트 비활성화

[MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)이 호출된 경우 효과는 다음 자동 활성화 이벤트 전까지만 지속된다는 점에 주의하십시오. 버퍼에서 하이라이트를 영구적으로 비활성화하려면 `vim.b.minihipatterns_disable`를 `true`로 설정하십시오.

#### 매개변수 {#minihipatterns.disable-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number|nil)` 하이라이트를 활성화할 버퍼 식별자.
  기본값: 현재 버퍼의 경우 0.

---

### toggle() {#minihipatterns.toggle .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.toggle`(<span class="help-syntax-special">{buf_id}</span>, <span class="help-syntax-special">{config}</span>)</p>
버퍼에서 하이라이트 토글

활성화된 경우 [MiniHipatterns.disable()](mini-hipatterns.qmd#minihipatterns.disable)을 호출하고, 그렇지 않으면 [MiniHipatterns.enable()](mini-hipatterns.qmd#minihipatterns.enable)을 호출합니다.

#### 매개변수 {#minihipatterns.toggle-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number|nil)` 하이라이트를 활성화할 버퍼 식별자.
  기본값: 현재 버퍼의 경우 0.

<span class="help-syntax-special">{config}</span> `(table|nil)` [MiniHipatterns.enable()](mini-hipatterns.qmd#minihipatterns.enable)로 전달됩니다.

---

### update() {#minihipatterns.update .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.update`(<span class="help-syntax-special">{buf_id}</span>, <span class="help-syntax-special">{from_line}</span>, <span class="help-syntax-special">{to_line}</span>)</p>
범위 내의 하이라이트 업데이트

하이라이트가 활성화된 버퍼에서만 작동합니다. 지연 없이 즉시 효과가 나타납니다.

#### 매개변수 {#minihipatterns.update-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number|nil)` 하이라이트를 활성화할 버퍼 식별자.
  기본값: 현재 버퍼의 경우 0.

<span class="help-syntax-special">{from_line}</span> `(number|nil)` 업데이트를 시작할 줄 (1부터 시작).

<span class="help-syntax-special">{to_line}</span> `(number|nil)` 업데이트를 종료할 줄 (1부터 시작, 포함).

---

### get_enabled_buffers() {#minihipatterns.get_enabled_buffers .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.get_enabled_buffers`()</p>
활성화된 버퍼의 배열 가져오기

#### 반환값 {#minihipatterns.get_enabled_buffers-return}


`(table)` 하이라이트가 활성화된 버퍼 식별자의 배열.

---

### get_matches() {#minihipatterns.get_matches .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.get_matches`(<span class="help-syntax-special">{buf_id}</span>, <span class="help-syntax-special">{highlighters}</span>)</p>
버퍼 매치 항목 가져오기

#### 매개변수 {#minihipatterns.get_matches-parameters}



<span class="help-syntax-special">{buf_id}</span> `(number|nil)` 매치 항목을 반환할 버퍼 식별자.
  기본값: 현재 버퍼의 경우 `nil`.

<span class="help-syntax-special">{highlighters}</span> `(table|nil)` 매치 항목을 반환할 하이라이터 식별자 배열 ( [MiniHipatterns.config](mini-hipatterns.qmd#minihipatterns.config)의 `highlighters` 필드와 동일).
  기본값: 사용 가능한 모든 하이라이터 (문자열 표현에 따라 정렬됨).

#### 반환값 {#minihipatterns.get_matches-return}


`(table)` 다음 필드를 포함하는 테이블인 버퍼 매치 배열:

  - <span class="help-syntax-keys">\<bufnr\></span> `(number)` - 매치의 버퍼 식별자.

  - <span class="help-syntax-keys">\<highlighter\></span> `(any)` - 매치를 생성한 하이라이터 식별자.

  - <span class="help-syntax-keys">\<lnum\></span> `(number)` - 매치 시작 줄 번호 (1부터 시작).

  - <span class="help-syntax-keys">\<col\></span> `(number)` - 매치 시작 열 번호 (1부터 시작).

  - <span class="help-syntax-keys">\<end_lnum\></span> `(number|nil)` - 매치 종료 줄 번호 (1부터 시작).

  - <span class="help-syntax-keys">\<end_col\></span> `(number|nil)` - 매치 종료 다음 열 번호 (종료 제외 영역 구현, 1부터 시작).

  - <span class="help-syntax-keys">\<hl_group\></span> `(string|nil)` - 매치의 하이라이트 그룹 이름.

  매치는 먼저 제공된 `highlighters`에 의해 정렬된 다음, 매치 시작 줄과 열에 의해 정렬됩니다.

---

### gen_highlighter {#minihipatterns.gen_highlighter .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.gen_highlighter`</p>
내장 하이라이터 생성

함수 요소를 포함하는 테이블입니다. 실제로 하이라이터를 가져오려면 호출하십시오.

---

### gen_highlighter.hex_color() {#minihipatterns.gen_highlighter.hex_color .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.gen_highlighter.hex_color`(<span class="help-syntax-special">{opts}</span>)</p>
16진수 색상 문자열 강조

`#rrggbb` 형식의 색상 16진수 문자열을 매치하고 매치된 색상을 표시하는 `opts.style`에 따라 강조합니다.

하이라이트 그룹은 [MiniHipatterns.compute\_hex\_color\_group()](mini-hipatterns.qmd#minihipatterns.compute_hex_color_group)을 사용하여 계산되므로 모든 사용 시 주의 사항이 여기에 적용됩니다.

#### 매개변수 {#minihipatterns.gen_highlighter.hex_color-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<style\></span> `(string)` - 다음 중 하나:

      - `'full'` - 전체 16진수 문자열의 배경을 해당 색상으로 강조합니다. 기본값.

      - `'#'` - `#`의 배경만 강조합니다.

      - `'line'` - 해당 색상으로 밑줄을 강조합니다.

      - `'inline'` - <span class="help-syntax-keys">\<inline_text\></span>의 텍스트를 강조합니다.
        참고: Neovim>=0.10이 필요합니다.

  - <span class="help-syntax-keys">\<priority\></span> `(number)` - 하이라이트 우선순위. 기본값: 200.

  - <span class="help-syntax-keys">\<filter\></span> `(function)` - 하이라이트가 발생할 버퍼를 필터링하는 데 사용되는 호출 가능 객체입니다. 버퍼 식별자를 입력으로 받고 해당 버퍼 내부를 강조하지 않으려면 `false` 또는 `nil`을 반환해야 합니다.

  - <span class="help-syntax-keys">\<inline_text\></span> `(string)` - <span class="help-syntax-keys">\<style\></span>이 "inline"인 경우 매치 오른쪽에 배치되고 색상으로 강조될 문자열입니다. 기본값: "█".

#### 반환값 {#minihipatterns.gen_highlighter.hex_color-return}


`(table)` `config.highlighters`의 일부로 사용할 준비가 된 하이라이터 테이블입니다. `pattern`과 `group` 모두 호출 가능합니다.

#### 사용법 {#minihipatterns.gen_highlighter.hex_color-usage}



  ```lua
  local hipatterns = require('mini.hipatterns')
  hipatterns.setup({
    highlighters = {
      hex_color = hipatterns.gen_highlighter.hex_color(),
    }
  })
  ```

---

### compute_hex_color_group() {#minihipatterns.compute_hex_color_group .help-syntax-right-anchor}

<p align="center">`MiniHipatterns.compute_hex_color_group`(<span class="help-syntax-special">{hex_color}</span>, <span class="help-syntax-special">{style}</span>)</p>
16진수 색상 문자열을 강조하기 위한 그룹 계산 및 생성

참고:

- 이 기능은 ['termguicolors'](https://neovim.io/doc/user/helptag.html?tag='termguicolors')가 활성화된 경우에만 제대로 작동합니다.


- 성능을 높이기 위해 `hex_color`와 `style` 조합별로 하이라이트 그룹을 캐시합니다. 색상 구성표 변경 시에도 이러한 그룹이 유지되도록 하려면 [MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)을 호출해야 합니다.

#### 매개변수 {#minihipatterns.compute_hex_color_group-parameters}



<span class="help-syntax-special">{hex_color}</span> `(string)` `#rrggbb` 형식의 16진수 색상 문자열.

<span class="help-syntax-special">{style|nil}</span> `(string)` 다음 중 하나:

  - `'bg'` - 배경을 `hex_color`로 강조하고 전경을 검은색 또는 흰색(더 잘 보이는 것)으로 강조합니다. 기본값.

  - `'fg'` - 전경을 `hex_color`로 강조합니다.

  - `'line'` - 밑줄을 `hex_color`로 강조합니다.

#### 반환값 {#minihipatterns.compute_hex_color_group-return}


`(string)` `hex_color`를 표시하기에 적합하게 생성된 하이라이트 그룹의 이름.
