---
title: "mini.sessions 문서"
---

_ 'mini.nvim'의 `main` 브랜치에서 생성됨 _

<a name="mini.sessions" href="mini-sessions.qmd#mini.sessions"><b>mini.sessions</b></a> 세션 관리

MIT 라이선스 Copyright (c) 2021 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

세션을 읽고, 쓰고, 삭제합니다. [:mksession](https://neovim.io/doc/user/helptag.html?tag=:mksession)을 사용하므로 'sessionoptions'가 완전히 존중됩니다. 이는 [mhinz/vim-startify](https://github.com/mhinz/vim-startify) 세션 관리의 Lua 대체제로 설계되었습니다 (기존 세션과 호환됨). 설정된 디렉토리의 전역(global) 세션과 현재 디렉토리의 로컬(local) 세션을 모두 지원합니다.

주요 디자인 아이디어:

- 세션은 읽을 수 있는 파일([:mksession](https://neovim.io/doc/user/helptag.html?tag=:mksession)의 결과물)로 표현됩니다. 두 가지 종류의 세션이 있습니다:

    - 전역(Global): 설정된 디렉토리 내의 모든 파일.

    - 로컬(Local): 현재 작업 디렉토리([getcwd()](https://neovim.io/doc/user/helptag.html?tag=getcwd\(\))) 내의 설정된 파일.


- 모든 세션 파일은 `MiniSessions.setup()` 도중과 관련 동작(`read`, `delete`, `select`) 도중에 감지되며, 파일 이름이 세션 이름(확장자 포함 가능)으로 사용됩니다.


- 새로운 세션의 자동 생성은 지원하지 않습니다. [MiniSessions.write()](mini-sessions.qmd#minisessions.write)를 수동으로 사용하세요.


- 감지된 세션에 대한 정보는 별도의 테이블([MiniSessions.detected](mini-sessions.qmd#minisessions.detected))에 저장되며 이 테이블에서만 작동합니다. 즉, 정보가 변경되어도 다음 감지 전까지는 효과가 없습니다. 혼란을 피하기 위해 세션 파일을 읽고 쓰는 데 [:mksession](https://neovim.io/doc/user/helptag.html?tag=:mksession) / [:source](https://neovim.io/doc/user/helptag.html?tag=:source)를 직접 사용하지 마세요.

주요 기능:

- Neovim이 다른 무언가를 보여줄 의도 없이 실행된 경우, 기본 세션(감지된 경우 로컬, 그렇지 않으면 가장 최근에 작성된 전역 세션)을 자동으로 읽습니다(Autoread).


- 세션을 벗어나기 전에(Neovim 종료 또는 다른 세션 읽기) 현재 읽은 세션을 자동으로 저장합니다(Autowrite).


- 모든 동작에 대해 설정 가능한 심각도 레벨을 지원합니다.

#### 설정 {#module-setup}


이 모듈은 `require('mini.sessions').setup({})`을 통한 설정이 필요합니다 (`{}`를 원하는 `config` 테이블로 교체하세요). 이를 통해 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniSessions`가 생성됩니다 ( `:lua MiniSessions.*` 사용).

사용 가능한 설정값은 [MiniSessions.config](mini-sessions.qmd#minisessions.config)를 참조하세요.

이 모듈은 버퍼 로컬 설정의 이점이 없으므로 `vim.b.minisessions_config`를 사용해도 효과가 없습니다.

#### 비활성화 {#module-disabling}


핵심 기능을 비활성화하려면 `vim.g.minisessions_disable`(전역) 또는 `vim.b.minisessions_disable`(버퍼용)을 `true`로 설정하세요. 다양한 시나리오와 커스터마이징 의도를 고려할 때, 모듈 기능을 비활성화하기 위한 정확한 규칙을 작성하는 것은 사용자의 몫입니다. 일반적인 방법은 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### setup() {#minisessions.setup .help-syntax-right-anchor}

<p align="center">`MiniSessions.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minisessions.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블입니다. [MiniSessions.config](mini-sessions.qmd#minisessions.config)를 참조하세요.

#### 사용법 {#minisessions.setup-usage}



  ```lua
  require('mini.sessions').setup() -- 기본 설정 사용
  -- 또는
  require('mini.sessions').setup({}) -- {}를 원하는 설정 테이블로 교체
  ```

---

### config {#minisessions.config .help-syntax-right-anchor}

<p align="center">`MiniSessions.config`</p>
#### 기본값 {#minisessions.config-defaults}



  ```lua
  MiniSessions.config = {
    -- 파일 인자 없이 Neovim을 열었을 때 기본 세션을 읽을지 여부
    autoread = false,

    -- 현재 읽은 세션을 벗어나기 전에 자동으로 저장할지 여부
    autowrite = true,

    -- 전역 세션이 저장되는 디렉토리 (비활성화하려면 `''` 사용)
    directory = --<|stdpath()|에서 가져온 사용자 데이터 디렉토리의 "session" 하위 디렉토리>,

    -- 로컬 세션을 위한 파일 (비활성화하려면 `''` 사용)
    file = 'Session.vim',

    -- 잠재적으로 해로울 수 있는 동작을 강제할지 여부 (기능에 따라 의미가 다름)
    force = { read = false, write = true, delete = false },

    -- 동작에 대한 후크(Hook) 함수. 기본값 `nil`은 '아무것도 하지 않음'을 의미합니다.
    -- 활성 세션 데이터를 인자로 하는 테이블을 받습니다.
    hooks = {
      -- 성공적인 동작 전
      pre = { read = nil, write = nil, delete = nil },
      -- 성공적인 동작 후
      post = { read = nil, write = nil, delete = nil },
    },

    -- 동작 후 세션 경로를 출력할지 여부
    verbose = { read = false, write = true, delete = true },
  }
  ```

---

### detected {#minisessions.detected .help-syntax-right-anchor}

<p align="center">`MiniSessions.detected`</p>
감지된 세션 테이블입니다. 키는 세션 이름을 나타냅니다. 값은 현재 다음과 같은 필드(변경될 수 있음)를 가진 세션 정보 테이블입니다:

- <span class="help-syntax-keys">\<modify_time\></span> `(number)` 세션 파일의 수정 시간( [getftime()](https://neovim.io/doc/user/helptag.html?tag=getftime\(\)) 참조).

- <span class="help-syntax-keys">\<name\></span> `(string)` 세션 이름 (테이블 키와 동일해야 함).

- <span class="help-syntax-keys">\<path\></span> `(string)` 세션 파일의 전체 경로.

- <span class="help-syntax-keys">\<type\></span> `(string)` 세션 유형 ('global' 또는 'local').

---

### read() {#minisessions.read .help-syntax-right-anchor}

<p align="center">`MiniSessions.read`(<span class="help-syntax-special">{session_name}</span>, <span class="help-syntax-special">{opts}</span>)</p>
감지된 세션 읽기

수행 동작:

- 활성 세션이 있고 [MiniSessions.config](mini-sessions.qmd#minisessions.config)에서 `autowrite`가 `true`인 경우, [MiniSessions.write()](mini-sessions.qmd#minisessions.write)를 사용하여 저장합니다.

- [:bwipeout](https://neovim.io/doc/user/helptag.html?tag=:bwipeout)을 사용하여 현재의 모든 버퍼를 삭제합니다. 이는 대상 세션에서 버퍼를 올바르게 복구하는 데 필요합니다. `force`가 `true`가 아니면, 저장되지 않은 버퍼가 있는지 미리 확인하고 있으면 중단합니다.

- 제공된 이름의 세션 파일을 불러옵니다(source).

#### 매개변수 {#minisessions.read-parameters}



<span class="help-syntax-special">{session_name}</span> `(string|nil)` 읽을 감지된 세션 파일의 이름입니다. 기본값:
  `nil` (기본 세션 사용: 감지된 경우 로컬 세션, 그렇지 않으면 최신 세션( [MiniSessions.get\_latest()](mini-sessions.qmd#minisessions.get_latest) 참조)).

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션 테이블입니다. 현재 허용되는 키:

  - <span class="help-syntax-keys">\<force\></span> (저장되지 않은 버퍼를 삭제할지 여부; 기본값:
    `MiniSessions.config.force.read`).

  - <span class="help-syntax-keys">\<verbose\></span> (동작 후 세션 경로를 출력할지 여부; 기본값
    `MiniSessions.config.verbose.read`).

  - <span class="help-syntax-keys">\<hooks\></span> (성공적인 읽기 전후에 세션 데이터를 인자로 실행될 <span class="help-syntax-keys">\<pre\></span> 및 <span class="help-syntax-keys">\<post\></span> 함수 후크 테이블; `MiniSessions.config.hooks.pre.read` 및 `MiniSessions.config.hooks.post.read`를 재정의함).

---

### write() {#minisessions.write .help-syntax-right-anchor}

<p align="center">`MiniSessions.write`(<span class="help-syntax-special">{session_name}</span>, <span class="help-syntax-special">{opts}</span>)</p>
세션 쓰기(저장)

수행 동작:

- 제공된 세션 이름의 파일이 이미 존재하는지 확인합니다. 존재하고 `force`가 `true`가 아니면 중단합니다.

- [:mksession](https://neovim.io/doc/user/helptag.html?tag=:mksession)을 사용하여 `session_name`이라는 파일로 세션을 저장합니다. 디렉토리는 세션 유형에 따라 결정됩니다:

    - `session_name`이 `nil`이고 현재 읽은 세션이 있는 경우 [v:this\_session](https://neovim.io/doc/user/helptag.html?tag=v:this_session) 위치에 저장합니다.

    - `session_name`이 `MiniSessions.config.file`과 같으면(로컬 세션) 현재 작업 디렉토리([getcwd()](https://neovim.io/doc/user/helptag.html?tag=getcwd\(\)))에 저장합니다.

    - 그 외의 경우(전역 세션) `MiniSessions.config.directory`에 저장합니다.

- [MiniSessions.detected](mini-sessions.qmd#minisessions.detected)를 업데이트합니다.

#### 매개변수 {#minisessions.write-parameters}



<span class="help-syntax-special">{session_name}</span> `(string|nil)` 저장할 세션 파일의 이름입니다. 기본값: `nil` (현재 읽은 세션 사용([v:this\_session](https://neovim.io/doc/user/helptag.html?tag=v:this_session))).

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션 테이블입니다. 현재 허용되는 키:

  - <span class="help-syntax-keys">\<force\></span> (세션 파일의 존재 여부를 무시할지 여부; 기본값:
    `MiniSessions.config.force.write`).

  - <span class="help-syntax-keys">\<verbose\></span> (동작 후 세션 경로를 출력할지 여부; 기본값
    `MiniSessions.config.verbose.write`).

  - <span class="help-syntax-keys">\<hooks\></span> (성공적인 저장 전후에 세션 데이터를 인자로 실행될 <span class="help-syntax-keys">\<pre\></span> 및 <span class="help-syntax-keys">\<post\></span> 함수 후크 테이블; `MiniSessions.config.hooks.pre.write` 및 `MiniSessions.config.hooks.post.write`를 재정의함).

---

### delete() {#minisessions.delete .help-syntax-right-anchor}

<p align="center">`MiniSessions.delete`(<span class="help-syntax-special">{session_name}</span>, <span class="help-syntax-special">{opts}</span>)</p>
감지된 세션 삭제

수행 동작:

- 세션 이름이 현재 세션인지 확인합니다. 현재 세션이고 `force`가 `true`가 아니면 중단합니다.

- 세션을 삭제합니다.

- [MiniSessions.detected](mini-sessions.qmd#minisessions.detected)를 업데이트합니다.

#### 매개변수 {#minisessions.delete-parameters}



<span class="help-syntax-special">{session_name}</span> `(string|nil)` 삭제할 감지된 세션 파일의 이름입니다. 기본값:
  `nil` (현재 읽은 세션의 이름([v:this\_session](https://neovim.io/doc/user/helptag.html?tag=v:this_session)) 사용).

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션 테이블입니다. 현재 허용되는 키:

  - <span class="help-syntax-keys">\<force\></span> (현재 세션의 삭제를 허용할지 여부; 기본값:
    `MiniSessions.config.force.delete`).

  - <span class="help-syntax-keys">\<verbose\></span> (동작 후 세션 경로를 출력할지 여부; 기본값
    `MiniSessions.config.verbose.delete`).

  - <span class="help-syntax-keys">\<hooks\></span> (성공적인 삭제 전후에 세션 데이터를 인자로 실행될 <span class="help-syntax-keys">\<pre\></span> 및 <span class="help-syntax-keys">\<post\></span> 함수 후크 테이블; `MiniSessions.config.hooks.pre.delete` 및 `MiniSessions.config.hooks.post.delete`를 재정의함).

---

### select() {#minisessions.select .help-syntax-right-anchor}

<p align="center">`MiniSessions.select`(<span class="help-syntax-special">{action}</span>, <span class="help-syntax-special">{opts}</span>)</p>
대화형으로 세션을 선택하고 동작 수행

참고: [vim.ui.select()](https://neovim.io/doc/user/helptag.html?tag=vim.ui.select\(\)) 함수를 사용합니다. 더 사용자 친화적인 경험을 위해 이 함수를 재정의하세요 (예: [MiniPick.ui\_select()](mini-pick.qmd#minipick.ui_select) 참조).

#### 매개변수 {#minisessions.select-parameters}



<span class="help-syntax-special">{action}</span> `(string|nil)` 수행할 동작입니다. "read" (기본값), "write", "delete" 중 하나여야 합니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 지정된 동작에 대한 옵션입니다.

---

### get_latest() {#minisessions.get_latest .help-syntax-right-anchor}

<p align="center">`MiniSessions.get_latest`()</p>
가장 최근에 감지된 세션의 이름 가져오기

[getftime()](https://neovim.io/doc/user/helptag.html?tag=getftime\(\))으로 확인했을 때 수정 시간이 가장 최근인 세션입니다.

#### 반환 {#minisessions.get_latest-return}


`(string|nil)` 가장 최근 세션의 이름 또는 세션이 없는 경우 `nil`.
