---
title: "mini.jump2d 문서"
---

_'mini.nvim'의 `main` 브랜치에서 생성됨_

<a name="mini.jump2d" href="mini-jump2d.qmd#mini.jump2d"><b>mini.jump2d</b></a> 현재 보이는 줄 내에서 점프

MIT 라이선스 Copyright (c) 2022 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

반복적인 레이블 필터링을 통해 현재 보이는 줄 내에서 점프합니다.

기능:

- 하나만 남을 때까지 가능한 점프 지점들을 반복적으로 필터링하여 점프합니다. 필터링은 점프 지점에 표시되는 레이블 문자를 입력하여 수행됩니다.


- 사용자 정의 가능 ([MiniJump2d.config](mini-jump2d.qmd#minijump2d.config) 참조):

    - 기본 제공되는 방식 외에 가능한 점프 지점을 계산하는 방법을 설정할 수 있습니다.

    - 반복 필터링 중에 점프 지점에 레이블을 지정하는 데 사용되는 문자를 설정할 수 있습니다.

    - 시각 효과: 몇 단계 앞까지 보여줄지, 점프 지점이 있는 줄을 어둡게 처리할지 등을 설정할 수 있습니다.

    - 점프 중 특정 이벤트에서 실행될 액션 훅(hook)을 설정할 수 있습니다.

    - 허용되는 창: 현재 창 및/또는 현재 창이 아닌 창을 설정할 수 있습니다.

    - 허용되는 줄: 빈 줄이나 접힌 줄을 처리할지, 커서 줄 앞/현재/뒤 줄을 처리할지 등을 설정할 수 있습니다. 예: 사용자는 현재 창의 커서 줄 또는 그 이후에서만 단어 시작 지점을 찾도록 구성할 수 있으며, 점프 후 특정 작업을 수행하는 'j' 및 'k' 레이블을 사용할 수 있습니다.


- 비주얼 모드 및 연산자 대기(Operator-pending, dot-repeat 지원) 모드에서 작동합니다.


- 점프 지점을 계산하는 사전 구성된 방식 제공 ([MiniJump2d.builtin\_opts](mini-jump2d.qmd#minijump2d.builtin_opts) 참조):

    - 줄의 시작 부분.

    - 단어의 시작 부분.

    - 사용자 입력으로부터 받은 단일 문자.

    - 사용자 입력으로부터 받은 가변 길이 쿼리.


- 멀티바이트 문자를 지원합니다.

점프 수행 방식 개요:

- 원하는 위치("지점")를 응시합니다. 현재 보이는 줄 내에서 커서를 놓을 수 있는 위치여야 합니다.


- 점프를 시작합니다. 사용자 정의 키 바인딩을 사용하거나 [MiniJump2d.start()](mini-jump2d.qmd#minijump2d.start)를 호출하여 시작합니다 (사용자 정의 옵션 허용). 그러면 가능한 모든 점프 지점이 레이블(기본적으로 "a"에서 "z"까지의 문자)과 함께 하이라이트됩니다. 자세한 내용은 [MiniJump2d.start()](mini-jump2d.qmd#minijump2d.start) 및 [MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)를 참조하세요.


- 원하는 위치 위에 나타난 문자를 입력합니다. 레이블이 유일하다면 점프가 수행됩니다. 유일하지 않다면, 해당 레이블 문자를 가진 지점들로 필터링됩니다.


- 가능한 점프 지점이 하나만 남을 때까지 이전 단계를 반복하거나, <span class="help-syntax-keys">\<CR\></span>을 입력하여 첫 번째 사용 가능한 점프 지점으로 점프합니다. 다른 것을 입력하면 커서를 이동하지 않고 점프를 중단합니다.

#### 설정 {#module-setup}


이 모듈은 `require('mini.jump2d').setup({})`을 통한 설정이 필요합니다 (`{}`를 사용자 `config` 테이블로 대체). 그러면 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniJump2d`가 생성됩니다 (예: `:lua MiniJump2d.*`).

사용 가능한 설정 옵션은 [MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)를 참조하세요.

`MiniJump2d.config`와 동일한 구조를 가진 `vim.b.minijump2d_config`를 사용하여 버퍼별로 런타임 설정을 재정의할 수 있습니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

모듈이 에러가 아닌 피드백을 표시하지 않게 하려면 `config.silent = true`로 설정하세요.

#### 사용 예시 {#module-exampleusage}



- 현재 창의 커서 줄 또는 그 이후만 사용하도록 기본 점프 방식 수정:

  ```lua
  require('mini.jump2d').setup({
    allowed_lines = { cursor_before = false },
    allowed_windows = { not_current = false },
  })
  ```


- [MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)와 [MiniJump2d.builtin\_opts.line\_start](mini-jump2d.qmd#minijump2d.builtin_opts.line_start)에 제공된 옵션 조합을 사용하여 줄 시작 지점으로 점프:

  ```vim
  :lua MiniJump2d.start(MiniJump2d.builtin_opts.line_start)
  ```


- 명령 실행 후 입력한 단일 문자로 점프:

  ```vim
  :lua MiniJump2d.start(MiniJump2d.builtin_opts.single_character)
  ```


- 더 많은 예시는 [MiniJump2d.start()](mini-jump2d.qmd#minijump2d.start) 및 [MiniJump2d.builtin\_opts](mini-jump2d.qmd#minijump2d.builtin_opts)를 참조하세요.

#### 비교 {#module-comparisons}



- [phaazon/hop.nvim](https://github.com/phaazon/hop.nvim):

    - 둘 다 빠르고 사용자 정의 및 확장이 가능합니다 (사용자가 점프 지점을 정의하는 고유한 방법을 작성할 수 있음).

    - 'hop.nvim'은 모든 단계를 한 번에 시각화합니다. 반면 이 모듈은 설정 가능한 단계 수만큼 앞서 보여줄 수 있습니다.

    - 둘 다 점프 유형(단어 시작, 줄 시작, 한 문자 또는 사용자 입력 기반 쿼리)을 지정하는 여러 내장 방식을 제공합니다. 'hop.nvim'은 많은 전용 Neovim 명령어를 내보내는 방식으로 수행하는 반면, 이 모듈은 사전 구성된 기본 옵션을 제공하고 나머지는 Lua 코드로 사용자 정의할 수 있게 합니다 ([MiniJump2d.builtin\_opts](mini-jump2d.qmd#minijump2d.builtin_opts) 참조).

    - 'hop.nvim'은 레이블("힌트"라고 함)을 다르게 계산합니다. 이 모듈은 의도적으로 점프 지점 간의 우선순위를 두지 않지만, 'hop.nvim'은 약간 편향된 방식으로 키 시퀀스를 생성하는 특수 알고리즘을 사용합니다: 일부 시퀀스는 다른 시퀀스보다 의도적으로 짧게 만들어 평균 키 입력을 줄입니다. 이들은 커서 근처에 배치되며(기본값) 다르게 하이라이트됩니다. 시퀀스의 최종 순서는 커서와의 거리를 기반으로 합니다.

    - 'mini.jump2d'는 점프 지점을 계산하는 독자적인 기본 알고리즘을 가지고 있습니다. [MiniJump2d.default\_spotter()](mini-jump2d.qmd#minijump2d.default_spotter)를 참조하세요.

#### 하이라이트 그룹 {#module-highlightgroups}



- `MiniJump2dSpot` - 점프 지점의 다음 단계 하이라이트. 기본적으로 시각적으로 너무 부담스럽지 않으면서 대비가 가장 높은 레이블을 사용합니다: 어두운 배경에는 검은색 바탕에 흰색, 밝은 배경에는 흰색 바탕에 검은색. 마음에 들지 않는다면 다음 대안들을 시도해 보세요:

    ```lua
    -- 배경색 반전 (대부분의 컬러 스킴에서 매우 잘 보임)
    vim.api.nvim_set_hl(0, 'MiniJump2dSpot', { reverse = true })

    -- 굵게 기울임꼴
    vim.api.nvim_set_hl(0, 'MiniJump2dSpot', { bold = true, italic = true })

    -- 빨간색 물결 밑줄
    vim.api.nvim_set_hl(0, 'MiniJump2dSpot', { sp = 'Red', undercurl = true })
    ```


- `MiniJump2dSpotUnique` - 유일한 레이블을 가진 경우의 점프 지점 다음 단계 하이라이트. 기본적으로 `MiniJump2dSpot`에 연결됩니다.


- `MiniJump2dSpotAhead` - 점프 지점의 이후 단계 하이라이트. 기본적으로 `MiniJump2dSpot`과 유사하지만 대비와 가시성이 낮습니다.


- `MiniJump2dDim` - 점프 지점이 하나 이상 있는 줄의 하이라이트. 점프 지점 레이블이 더 잘 보이도록 밝지 않게 설정하세요. 기본적으로 `Comment` 하이라이트 그룹에 연결됩니다.

하이라이트 그룹을 변경하려면 [nvim\_set\_hl()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_hl\(\))을 사용하여 직접 설정하세요.

#### 비활성화 {#module-disabling}


비활성화하려면 `vim.g.minijump2d_disable`(전역) 또는 `vim.b.minijump2d_disable`(버퍼별)을 `true`로 설정하세요. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈 기능 비활성화에 대한 정확한 규칙을 작성하는 것은 사용자의 몫으로 남겨둡니다. 일반적인 방법은 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### setup() {#minijump2d.setup .help-syntax-right-anchor}

<p align="center">`MiniJump2d.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minijump2d.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)를 참조하세요.

#### 사용법 {#minijump2d.setup-usage}



  ```lua
  require('mini.jump2d').setup() -- 기본 설정 사용
  -- 또는
  require('mini.jump2d').setup({}) -- {}를 사용자 설정 테이블로 대체
  ```

---

### config {#minijump2d.config .help-syntax-right-anchor}

<p align="center">`MiniJump2d.config`</p>
#### 기본값 {#minijump2d.config-defaults}



  ```lua
  MiniJump2d.config = {
    -- 특정 줄에 대한 점프 지점(바이트 인덱스)을 생성하는 함수.
    -- 자세한 정보는 |MiniJump2d.start()|를 참조하세요.
    -- `nil`(기본값)인 경우 |MiniJump2d.default_spotter()|를 사용합니다.
    spotter = nil,

    -- 점프 지점의 레이블에 사용되는 문자 (제공된 순서대로)
    labels = 'abcdefghijklmnopqrstuvwxyz',

    -- 시각 효과 옵션
    view = {
      -- 점프 지점이 하나 이상 있는 줄을 어둡게 처리할지 여부
      dim = false,

      -- 몇 단계 앞까지 보여줄지. 모든 단계를 보려면 큰 숫자로 설정하세요.
      n_steps_ahead = 0,
    },

    -- 점프 지점 계산에 사용되는 줄
    allowed_lines = {
      blank = true, -- 빈 줄 (`true`여도 스포터에게 전달되지 않음)
      cursor_before = true, -- 커서 줄 이전 줄들
      cursor_at = true, -- 커서 줄
      cursor_after = true, -- 커서 줄 이후 줄들
      fold = true, -- 접기 시작 부분 (`true`여도 스포터에게 전달되지 않음)
    },

    -- 현재 탭페이지에서 보이는 줄에 사용되는 창
    allowed_windows = {
      current = true,
      not_current = true,
    },

    -- 특정 이벤트에서 실행될 함수
    hooks = {
      before_start = nil, -- 점프 시작 전
      after_jump = nil, -- 점프가 실제로 완료된 후
    },

    -- 모듈 매핑. 비활성화하려면 `''`(빈 문자열)을 사용하세요.
    mappings = {
      start_jumping = '<CR>',
    },

    -- 에러가 아닌 피드백을 표시하지 않을지 여부
    -- 이는 사용자 입력이 필요할 때 대기 시간 후에 표시되는 (정보용) 도움말 메시지에도 영향을 줍니다.
    silent = false,
  }
  ```

#### 스포터(Spotter) 함수 {#minijump2d.config-spotterfunction}


가능한 점프 지점의 실제 계산은 스포터 함수를 통해 수행됩니다. 다음 인수를 가져야 합니다:

- `line_num`: 버퍼 내의 줄 번호.

- `args`: 추가 인수가 포함된 테이블:

    - <span class="help-syntax-special">{win_id}</span> - 입력 줄 번호가 속한 창의 식별자.

    - <span class="help-syntax-special">{win_id_init}</span> - `MiniJump2d.start()`가 호출되었을 때 현재 창이었던 창의 식별자.

출력은 해당 창의 특정 줄에 대해 가능한 점프 지점으로 간주되어야 하는 바이트 인덱스 위치 목록이어야 합니다. 참고: 시각화 정렬을 위해 이 목록은 오름차순으로 정렬되어야 합니다 (필수는 아님).

참고: 스포터 함수는 항상 `win_id` 창이 "임시 현재 창"인 상태에서 호출됩니다 ([nvim\_win\_call()](https://neovim.io/doc/user/helptag.html?tag=nvim_win_call\(\)) 참조). 이를 통해 현재 창에서만 작동하는 내장 Vimscript 함수를 사용할 수 있습니다.

#### 뷰(View) {#minijump2d.config-view}


`view.n_steps_ahead` 옵션은 현재 필요한 레이블과 함께 몇 단계 앞까지 보여줄지 제어합니다. 이러한 미래 단계는 다른(덜 보이는) 하이라이트 그룹("MiniJump2dSpotAhead")으로 표시됩니다. 보통 이는 점프 지점이 많이 생성되지 않는 스포터(예: [MiniJump2d.builtin\_opts.word\_start](mini-jump2d.qmd#minijump2d.builtin_opts.word_start))와 함께 사용하는 것이 좋습니다. 기본값은 시각적 노이즈를 줄이기 위해 아무것도 앞서 보여주지 않는 0입니다.

`view.dim` 옵션은 점프 지점이 하나 이상 있는 줄을 어둡게 처리할지 여부를 제어합니다. 줄 전체에 "MiniJump2dDim" 하이라이트 그룹을 적용하여 수행됩니다.

#### 허용되는 줄 {#minijump2d.config-allowedlines}


`allowed_lines` 옵션은 가능한 점프 지점을 계산하는 데 사용될 줄을 제어합니다:

- `blank` 또는 `fold`가 `true`인 경우, 빈 줄의 첫 번째 열([prevnonblank()](https://neovim.io/doc/user/helptag.html?tag=prevnonblank\(\))에 의해 결정됨) 또는 접힌 줄의 첫 번째 열([foldclosed()](https://neovim.io/doc/user/helptag.html?tag=foldclosed\(\))에 의해 결정됨)로 점프할 수 있습니다. 그렇지 않으면 건너뜁니다. 이러한 줄은 옵션이 `true`이더라도 스포터 함수에 의해 처리되지 않습니다.

- `cursor_before`, (`cursor_at`, `cursor_after`)가 `true`인 경우, 처리되는 모든 창의 커서 줄 이전(현재, 이후) 줄들이 스포터 함수로 전달됩니다. 그렇지 않으면 전달되지 않습니다. 이를 통해 점프 "방향"을 제어할 수 있습니다.

#### 훅(Hooks) {#minijump2d.config-hooks}


다음 훅 함수들을 사용하여 점프 경험을 더 세밀하게 조정할 수 있습니다:

- `before_start` - 점프가 시작될 때 가장 먼저 호출됩니다. 사용자 입력을 요청하고 그에 따라 스포터 함수를 업데이트하는 등의 용도로 사용할 수 있습니다.

- `after_jump` - 점프가 실제로 완료된 후 호출됩니다. 후속 조정(커서를 첫 번째 비공백 문자로 이동하는 등)을 수행하는 데 유용합니다.

---

### start() {#minijump2d.start .help-syntax-right-anchor}

<p align="center">`MiniJump2d.start`(<span class="help-syntax-special">{opts}</span>)</p>
점프 시작

가능한 점프 지점을 계산하고 시각화한 후 반복 필터링을 기다립니다.

#### 가능한 점프 지점의 첫 계산 {#minijump2d.start-firstcomputationofpossiblejumpspots}



- 허용되는 창(`allowed_windows` 옵션으로 제어)을 보이는 줄에 따라 위에서 아래로 처리합니다. 각 줄이 허용되는지(`allowed_lines` 옵션으로 제어) 확인합니다. 허용되지 않으면 아무 작업도 수행하지 않습니다. 허용되고 `spotter`에 의해 처리되어야 한다면 처리합니다.

- 각 적절한 줄에 대해 `spotter` 옵션의 스포터 함수를 적용하고 출력을 병합합니다. 즉, 점프 지점의 최종 순서는 "창 ID" - "줄 번호" - "스포터 출력의 위치" 튜플 내의 사전식 순서와 일치합니다.

- 가능한 각 점프에 대해 레이블을 계산합니다. 점프 지점을 필터링하는 데 사용되는 `labels` 옵션의 단일 문자입니다. 각 레이블 문자는 여러 "연속적인" 점프 지점을 지정하는 데 두 번 이상 사용될 수 있습니다. 이는 점프 지점 간의 우선순위가 없다는 가정 하에 최적의 방식으로 수행됩니다. 기본적으로 "반복 필터링의 각 단계에서 모든 레이블을 최대한 균등하게 사용함"을 의미합니다.

#### 시각화 {#minijump2d.start-visualization}


가능한 각 점프 지점의 현재 레이블이 해당 위치에 표시되어 아래에 있는 모든 내용을 덮어씁니다.

#### 반복 필터링 {#minijump2d.start-iterativefiltering}


가능한 점프 지점의 레이블은 최대한 균등하게 사용되도록 계산됩니다.

예시:

- `labels` 옵션이 `abc`인 경우, 10개의 가능한 점프에 대한 초기 레이블은 "aaaabbbccc"입니다. 10개의 지점을 3개의 기호로 "코딩"해야 하므로, 필터링을 위해 최소 2개의 기호는 3단계가 필요합니다. 현재 구현에서는 항상 "첫 번째 것들"이 해당됩니다.

- `a`를 입력하면 첫 4개의 점프 지점이 필터링되고 레이블이 "aabc"로 다시 계산됩니다.

- 다시 `a`를 입력하면 첫 2개의 지점이 필터링되고 레이블이 "ab"로 다시 계산됩니다.

- `a` 또는 `b`를 입력하면 단일 지점이 필터링되어 점프가 수행됩니다.

기본 26개 레이블을 사용하면 대부분의 실제 사례에서 기본 스포터 함수로 2단계면 충분합니다. 여러 창을 사용하는 경우 드물게 3단계가 필요할 수 있습니다.

#### 매개변수 {#minijump2d.start-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 전역 및 버퍼 로컬 값을 재정의하는 점프 설정. [MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)와 동일한 구조이며 <span class="help-syntax-keys">\<mappings\></span> 필드는 없습니다. 추가 허용 필드는 다음과 같습니다:

  - <span class="help-syntax-keys">\<hl_group\></span> - 첫 번째 단계의 하이라이트 그룹.
    기본값: `"MiniJump2dSpot"`.

  - <span class="help-syntax-keys">\<hl_group_ahead\></span> - 두 번째 및 이후 단계의 하이라이트 그룹.
    기본값: `"MiniJump2dSpotAhead"`.

  - <span class="help-syntax-keys">\<hl_group_dim\></span> - 사용된 줄을 어둡게 하는 하이라이트 그룹.
    기본값: `"MiniJump2dDim"`.

  - <span class="help-syntax-keys">\<hl_group_unique\></span> - 유일한 다음 단계에 대한 하이라이트 그룹.
    기본값: `"MiniJump2dSpotUnique"`.

#### 사용법 {#minijump2d.start-usage}



  ```lua
  -- 기본 점프 시작
  MiniJump2d.start()

  -- 단어 시작 부분으로 점프
  MiniJump2d.start(MiniJump2d.builtin_opts.word_start)

  -- 사용자 입력 단일 문자로 점프 (문자 하나 입력이 뒤따름)
  MiniJump2d.start(MiniJump2d.builtin_opts.single_character)

  -- 현재 창의 커서 줄에 있는 문장 부호 그룹의 첫 번째 문자로 점프하고 `Search`로 시각화
  MiniJump2d.start({
    spotter = MiniJump2d.gen_spotter.pattern('%p+'),
    allowed_lines = { cursor_before = false, cursor_after = false },
    allowed_windows = { not_current = false },
    hl_group = 'Search'
  })
  ```

#### 참고 {#minijump2d.start-seealso}


[MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)

---

### stop() {#minijump2d.stop .help-syntax-right-anchor}

<p align="center">`MiniJump2d.stop`()</p>
점프 중단

---

### gen_spotter {#minijump2d.gen_spotter .help-syntax-right-anchor}

<p align="center">`MiniJump2d.gen_spotter`</p>
스포터 생성

함수 요소를 가진 테이블입니다. 실제로 스포터를 가져오려면 호출하세요.

---

### gen_spotter.pattern() {#minijump2d.gen_spotter.pattern .help-syntax-right-anchor}

<p align="center">`MiniJump2d.gen_spotter.pattern`(<span class="help-syntax-special">{pattern}</span>, <span class="help-syntax-special">{side}</span>)</p>
Lua 패턴용 스포터 생성

#### 매개변수 {#minijump2d.gen_spotter.pattern-parameters}



<span class="help-syntax-special">{pattern}</span> `(string|nil)` Lua 패턴. 기본값: `'[^%s%p]+'`로 "공백이 아니고 문장 부호가 아닌 문자 그룹"(기본적으로 멀티바이트 문자에서 작동하는 "영숫자 문자 그룹")과 매치됩니다.

<span class="help-syntax-special">{side}</span> `(string|nil)` 패턴 매치의 어느 쪽을 점프 지점으로 간주할지 설정합니다. 'start'(매치 시작 부분, 기본값), 'end'(매치의 마지막 부분 포함), 또는 'none'(일반 `()` 매칭 그룹을 사용하여 패턴 내에서 수동으로 지점 지정) 중 하나여야 합니다.

#### 반환값 {#minijump2d.gen_spotter.pattern-return}


`(function)` 스포터 함수.

#### 사용법 {#minijump2d.gen_spotter.pattern-usage}



  ```lua
  -- 모든 문장 부호와 매치
  MiniJump2d.gen_spotter.pattern('%p')

  -- 줄 시작 부분에서 첫 번째 비공백 문자와 매치
  MiniJump2d.gen_spotter.pattern('^%s*%S', 'end')

  -- 마지막 단어의 시작 부분과 매치
  MiniJump2d.gen_spotter.pattern('[^%s%p]+[%s%p]-$', 'start')

  -- 다른 문자가 뒤따르는 문자와 매치 (패턴 내 수동 매칭 예시)
  MiniJump2d.gen_spotter.pattern('%a()%a', 'none')
  ```

---

### gen_spotter.vimpattern() {#minijump2d.gen_spotter.vimpattern .help-syntax-right-anchor}

<p align="center">`MiniJump2d.gen_spotter.vimpattern`(<span class="help-syntax-special">{pattern}</span>)</p>
Vimscript 패턴용 스포터 생성

#### 매개변수 {#minijump2d.gen_spotter.vimpattern-parameters}



<span class="help-syntax-special">{pattern}</span> `(string|nil)` Vimscript [패턴(pattern)](https://neovim.io/doc/user/helptag.html?tag=pattern). 기본값: `\k\+`로 "키워드 문자"( 'iskeyword' 참조) 그룹과 매치됩니다.

#### 반환값 {#minijump2d.gen_spotter.vimpattern-return}


`(function)` 스포터 함수.

#### 사용법 {#minijump2d.gen_spotter.vimpattern-usage}



  ```lua
  -- 키워드의 시작 부분과 매치
  MiniJump2d.gen_spotter.vimpattern('\\k\\+')

  -- 키워드의 마지막 부분과 매치
  MiniJump2d.gen_spotter.vimpattern('\\k*\\zs\\k')
  ```

---

### gen_spotter.union() {#minijump2d.gen_spotter.union .help-syntax-right-anchor}

<p align="center">`MiniJump2d.gen_spotter.union`(<span class="help-syntax-special">{...}</span>)</p>
스포터들의 합집합 생성

#### 매개변수 {#minijump2d.gen_spotter.union-parameters}



<span class="help-syntax-special">{...}</span> `(any)` 각 인수는 유효한 스포터여야 합니다.
  자세한 내용은 [MiniJump2d.config](mini-jump2d.qmd#minijump2d.config)를 참조하세요.

#### 반환값 {#minijump2d.gen_spotter.union-return}


`(function)` 스포터들의 합집합을 생성하는 스포터.

#### 사용법 {#minijump2d.gen_spotter.union-usage}



  ```lua
  -- 비공백 문자 그룹의 시작과 끝과 매치:
  local nonblank_start = MiniJump2d.gen_spotter.pattern('%S+', 'start')
  local nonblank_end = MiniJump2d.gen_spotter.pattern('%S+', 'end')
  local spotter = MiniJump2d.gen_spotter.union(nonblank_start, nonblank_end)
  ```

---

### default_spotter() {#minijump2d.default_spotter .help-syntax-right-anchor}

<p align="center">`MiniJump2d.default_spotter`</p>
기본 스포터 함수

다음 중 하나에 해당하면 점프가 가능합니다:

- 비공백 문자 그룹의 시작 또는 끝.

- 문장 부호가 앞뒤에 붙은 영숫자 문자 (snake_case 이름에 유용).

- 대문자 그룹의 시작 부분 (camelCase 이름에 유용). 보통 Lua 패턴의 한계로 인해 라틴 알파벳만 인식됩니다.

이러한 규칙들은 다음 두 가지 의도 사이의 균형을 맞추기 위해 도출되었습니다:

- 가능한 많은 유용한 점프 지점을 허용합니다.

- 레이블이 지정된 점프 지점을 쉽게 구별할 수 있게 합니다.

보통 목적지까지 2~3번의 키 입력이 필요합니다.

---

### builtin_opts {#minijump2d.builtin_opts .help-syntax-right-anchor}

<p align="center">`MiniJump2d.builtin_opts`</p>
[MiniJump2d.start()](mini-jump2d.qmd#minijump2d.start)를 위한 내장 `opts` 값 테이블

테이블의 각 요소는 `MiniJump2d.start()`를 위한 하나 이상의 옵션을 정의하는 테이블입니다. 어떤 옵션을 정의하는지 보려면 도움말 설명을 읽으세요 (예: [MiniJump2d.builtin\_opts.line\_start](mini-jump2d.qmd#minijump2d.builtin_opts.line_start)).

#### 사용법 {#minijump2d.builtin_opts-usage}



  ```lua
  -- `MiniJump2d.builtin_opts.line_start`를 예시로 사용:
  -- 명령어
  :lua MiniJump2d.start(MiniJump2d.builtin_opts.line_start)

  -- 사용자 정의 매핑
  vim.keymap.set(
    'n', '<CR>',
    '<Cmd>lua MiniJump2d.start(MiniJump2d.builtin_opts.line_start)<CR>'
  )

  -- `MiniJump2d.setup()` 내부에서 사용 (정의된 모든 옵션을 사용해야 함)
  local jump2d = require('mini.jump2d')
  local jump_line_start = jump2d.builtin_opts.line_start
  jump2d.setup({
    spotter = jump_line_start.spotter,
    hooks = { after_jump = jump_line_start.hooks.after_jump }
  })
  ```

---

### builtin_opts.default {#minijump2d.builtin_opts.default .help-syntax-right-anchor}

<p align="center">`MiniJump2d.builtin_opts.default`</p>
[MiniJump2d.default\_spotter()](mini-jump2d.qmd#minijump2d.default_spotter)를 사용하여 점프

`spotter`를 정의합니다.

---

### builtin_opts.line_start {#minijump2d.builtin_opts.line_start .help-syntax-right-anchor}

<p align="center">`MiniJump2d.builtin_opts.line_start`</p>
줄 시작 부분으로 점프

`spotter` 및 `hooks.after_jump`를 정의합니다.

---

### builtin_opts.word_start {#minijump2d.builtin_opts.word_start .help-syntax-right-anchor}

<p align="center">`MiniJump2d.builtin_opts.word_start`</p>
단어 시작 부분으로 점프

단어 시작을 계산할 때 'iskeyword'를 존중합니다.

`spotter`를 정의합니다.

---

### builtin_opts.single_character {#minijump2d.builtin_opts.single_character .help-syntax-right-anchor}

<p align="center">`MiniJump2d.builtin_opts.single_character`</p>
사용자 입력으로부터 받은 단일 문자로 점프

`spotter`, `allowed_lines.blank`, `allowed_lines.fold`, `hooks.before_start`를 정의합니다.

---

### builtin_opts.query {#minijump2d.builtin_opts.query .help-syntax-right-anchor}

<p align="center">`MiniJump2d.builtin_opts.query`</p>
사용자 입력으로부터 받은 쿼리로 점프

`spotter`, `allowed_lines.blank`, `allowed_lines.fold`, `hooks.before_start`를 정의합니다.
