---
title: "mini.extra 문서"
---

_ 'mini.nvim'의 `main` 브랜치에서 생성됨 _

<a name="mini.extra" href="mini-extra.qmd#mini.extra"><b>mini.extra</b></a> 추가적인 'mini.nvim' 기능

MIT 라이선스 Copyright (c) 2023 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

다른 'mini.nvim' 모듈에 직접 포함하기에는 필수적이지 않지만 유용한 추가 기능들입니다.

주요 기능:


- [mini.pick](mini-pick.qmd#mini.pick)을 위한 다양한 피커:

    - 내장 진단([MiniExtra.pickers.diagnostic()](mini-extra.qmd#miniextra.pickers.diagnostic)).

    - 파일 탐색기([MiniExtra.pickers.explorer()](mini-extra.qmd#miniextra.pickers.explorer)).

    - Git 브랜치/커밋/파일/헌크([MiniExtra.pickers.git\_hunks()](mini-extra.qmd#miniextra.pickers.git_hunks) 등).

    - 명령/검색/입력 기록([MiniExtra.pickers.history()](mini-extra.qmd#miniextra.pickers.history)).

    - LSP 참조/심볼/기타([MiniExtra.pickers.lsp()](mini-extra.qmd#miniextra.pickers.lsp)).

    - Tree-sitter 노드([MiniExtra.pickers.treesitter()](mini-extra.qmd#miniextra.pickers.treesitter)).

    - 그리고 더 많은 기능들.
  자세한 내용은 [MiniExtra.pickers](mini-extra.qmd#miniextra.pickers)를 참조하세요.


- [mini.ai](mini-ai.qmd#mini.ai)를 위한 다양한 텍스트 오브젝트 사양. [MiniExtra.gen\_ai\_spec](mini-extra.qmd#miniextra.gen_ai_spec)을 참조하세요.


- [mini.hipatterns](mini-hipatterns.qmd#mini.hipatterns)를 위한 다양한 하이라이터. [MiniExtra.gen\_highlighter](mini-extra.qmd#miniextra.gen_highlighter)를 참조하세요.

참고:

- 이 모듈은 특정 기능에 필요한 'mini.nvim' 모듈(예: 피커의 경우 'mini.pick')만 요구합니다.

#### 설정 {#module-setup}


이 모듈은 `require('mini.extra').setup({})`을 통한 설정이 필요합니다 (`{}`를 원하는 `config` 테이블로 교체하세요). 이를 통해 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniExtra`가 생성됩니다 ( `:lua MiniExtra.*` 사용).

사용 가능한 설정값은 [MiniExtra.config](mini-extra.qmd#miniextra.config)를 참조하세요.

이 모듈에는 런타임 옵션이 없으므로 `vim.b.miniextra_config`를 사용해도 효과가 없습니다.

#### 비교 {#module-comparisons}



- [nvim-telescope/telescope.nvim](https://github.com/nvim-telescope/telescope.nvim):

    - [MiniExtra.pickers](mini-extra.qmd#miniextra.pickers)를 사용하면 'mini.pick'은 내장 피커 측면에서 상당히 대등한 수준입니다.


- [ibhagwan/fzf-lua](https://github.com/ibhagwan/fzf-lua):

    - 'nvim-telescope/telescope.nvim'과 동일합니다.

---

### setup() {#miniextra.setup .help-syntax-right-anchor}

<p align="center">`MiniExtra.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#miniextra.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블입니다. [MiniExtra.config](mini-extra.qmd#miniextra.config)를 참조하세요.

#### 사용법 {#miniextra.setup-usage}



  ```lua
  require('mini.extra').setup() -- 기본 설정 사용
  -- 또는
  require('mini.extra').setup({}) -- {}를 원하는 설정 테이블로 교체
  ```

---

### config {#miniextra.config .help-syntax-right-anchor}

<p align="center">`MiniExtra.config`</p>
#### 기본값 {#miniextra.config-defaults}



  ```lua
  MiniExtra.config = {}
  ```

---

### gen_ai_spec {#miniextra.gen_ai_spec .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_ai_spec`</p>
[mini.ai](mini-ai.qmd#mini.ai) 텍스트 오브젝트 사양 생성기

함수 요소를 가진 테이블입니다. 사양을 얻으려면 호출하세요.

[MiniAi.setup()](mini-ai.qmd#miniai.setup)의 일부로 사용되도록 설계되었습니다. 예시:

  ```lua
  local gen_ai_spec = require('mini.extra').gen_ai_spec
  require('mini.ai').setup({
    custom_textobjects = {
      B = gen_ai_spec.buffer(),
      D = gen_ai_spec.diagnostic(),
      I = gen_ai_spec.indent(),
      L = gen_ai_spec.line(),
      N = gen_ai_spec.number(),
    },
  })
  ```

---

### gen_ai_spec.buffer() {#miniextra.gen_ai_spec.buffer .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_ai_spec.buffer`()</p>
현재 버퍼 텍스트 오브젝트

참고:

- `a` 텍스트 오브젝트는 버퍼의 모든 줄을 선택합니다.

- `i` 텍스트 오브젝트는 시작과 끝의 빈 줄을 제외한 모든 줄을 선택합니다.

#### 반환 {#miniextra.gen_ai_spec.buffer-return}


`(function)` [MiniAi-텍스트 오브젝트 사양](mini-ai.qmd#miniai-textobject-specification)을 구현하는 함수입니다.

---

### gen_ai_spec.diagnostic() {#miniextra.gen_ai_spec.diagnostic .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_ai_spec.diagnostic`(<span class="help-syntax-special">{severity}</span>)</p>
현재 버퍼 진단(diagnostic) 텍스트 오브젝트

참고:

- `a`와 `i` 텍스트 오브젝트 모두 현재 버퍼에 대한 [vim.diagnostic.get()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.get\(\)) 출력을 반환합니다. 이는 [MiniAi-텍스트 오브젝트 사양](mini-ai.qmd#miniai-textobject-specification)에 맞게 수정되었습니다.

#### 매개변수 {#miniextra.gen_ai_spec.diagnostic-parameters}



<span class="help-syntax-special">{severity}</span> `(any)` 사용할 심각도(severity)입니다. [vim.diagnostic.get()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.get\(\))으로 전달됩니다.
  기본값: `nil` (모든 진단 항목 사용).

#### 반환 {#miniextra.gen_ai_spec.diagnostic-return}


`(function)` [MiniAi-텍스트 오브젝트 사양](mini-ai.qmd#miniai-textobject-specification)을 구현하는 함수입니다.

---

### gen_ai_spec.indent() {#miniextra.gen_ai_spec.indent .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_ai_spec.indent`()</p>
현재 버퍼 들여쓰기 범위(indent scope) 텍스트 오브젝트

들여쓰기 범위는 다음 속성을 가진 연속된 줄의 집합입니다:

- 첫 번째 줄 위와 마지막 줄 아래는 비어 있지 않은 줄입니다. 이를 경계(border)라고 부릅니다.

- 집합 내에 적어도 하나의 비어 있지 않은 줄이 있습니다.

- 경계 사이의 모든 비어 있지 않은 줄은 어느 경계보다도 엄격하게 더 큰 들여쓰기(['tabstop'](https://neovim.io/doc/user/helptag.html?tag='tabstop')을 존중하는 시각적 앞쪽 공백)를 가집니다.

참고:

- `a` 텍스트 오브젝트는 경계를 포함한 범위를 선택합니다.

- `i` 텍스트 오브젝트는 범위를 문자 단위(charwise)로 선택합니다.

- [MiniIndentscope.textobject()](mini-indentscope.qmd#miniindentscope.textobject)와의 차이점:

    - 이 텍스트 오브젝트는 `i` 텍스트 오브젝트의 위아래 빈 줄을 항상 그 일부로 취급하지만, 'mini.indentscope'는 이를 설정할 수 있습니다.

    - 이 텍스트 오브젝트는 감싸고 있지 않은(non-covering) 범위를 선택할 수 있지만, 'mini.indentscope'는 (설계상) 불가능합니다.

    - 이 텍스트 오브젝트 범위 계산은 위에서 아래로만 수행되며 'mini.indentscope'처럼 양방향으로 수행되지 않습니다.
      이는 대부분의 일반적인 시나리오에서 작동하며, 하단 경계의 들여쓰기가 상단보다 클 것으로 예상되는 경우에만 작동하지 않습니다.

#### 반환 {#miniextra.gen_ai_spec.indent-return}


`(function)` [MiniAi-텍스트 오브젝트 사양](mini-ai.qmd#miniai-textobject-specification)을 구현하는 함수입니다.
  버퍼의 모든 들여쓰기 범위를 시작 줄 번호에 따라 오름차순으로 정렬된 지역 배열로 반환합니다.

---

### gen_ai_spec.line() {#miniextra.gen_ai_spec.line .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_ai_spec.line`()</p>
현재 줄 텍스트 오브젝트

참고:

- `a` 텍스트 오브젝트는 전체 줄을 선택합니다.

- `i` 텍스트 오브젝트는 시작 들여쓰기 이후의 줄 내용을 선택합니다.

#### 반환 {#miniextra.gen_ai_spec.line-return}


`(function)` [MiniAi-텍스트 오브젝트 사양](mini-ai.qmd#miniai-textobject-specification)을 구현하는 함수입니다.

---

### gen_ai_spec.number() {#miniextra.gen_ai_spec.number .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_ai_spec.number`()</p>
숫자 텍스트 오브젝트

참고:

- `a` 텍스트 오브젝트는 앞에 "-"가 붙을 수 있고 뒤에 소수점 부분(점과 숫자)이 붙을 수 있는 전체 숫자를 선택합니다.

- `i` 텍스트 오브젝트는 연속된 숫자를 선택합니다.

#### 반환 {#miniextra.gen_ai_spec.number-return}


`(function)` [MiniAi-텍스트 오브젝트 사양](mini-ai.qmd#miniai-textobject-specification)을 구현하는 함수입니다.

---

### gen_highlighter {#miniextra.gen_highlighter .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_highlighter`</p>
[mini.hipatterns](mini-hipatterns.qmd#mini.hipatterns) 하이라이터 생성기

함수 요소를 가진 테이블입니다. 사양을 얻으려면 호출하세요.

[MiniHipatterns.setup()](mini-hipatterns.qmd#minihipatterns.setup)의 일부로 사용되도록 설계되었습니다. 예시:

  ```lua
  local hi_words = require('mini.extra').gen_highlighter.words
  require('mini.hipatterns').setup({
    highlighters = {
      todo = hi_words({ 'TODO', 'Todo', 'todo' }, 'MiniHipatternsTodo'),
    },
  })
  ```

---

### gen_highlighter.words() {#miniextra.gen_highlighter.words .help-syntax-right-anchor}

<p align="center">`MiniExtra.gen_highlighter.words`(<span class="help-syntax-special">{words}</span>, <span class="help-syntax-special">{group}</span>, <span class="help-syntax-special">{extmark_opts}</span>)</p>
단어 하이라이트

참고:

- 단어는 영숫자(라틴 문자 또는 숫자)로 시작하고 끝나야 합니다.

- 단어는 전체가 일치할 때만 하이라이트되며, 더 큰 단어의 일부인 경우는 제외됩니다. 즉, 단어 앞뒤에 영숫자가 없어야 합니다.

#### 매개변수 {#miniextra.gen_highlighter.words-parameters}



<span class="help-syntax-special">{words}</span> `(table)` 하이라이트할 단어 배열입니다. Lua 패턴이 아닌 리터럴로 매칭됩니다.

<span class="help-syntax-special">{group}</span> `(string|function)` 하이라이터의 `group` 필드입니다.
  [MiniHipatterns.config](mini-hipatterns.qmd#minihipatterns.config)를 참조하세요.

<span class="help-syntax-special">{extmark_opts}</span> `(any)` 하이라이터의 `extmark_opts` 필드입니다.
  [MiniHipatterns.config](mini-hipatterns.qmd#minihipatterns.config)를 참조하세요.

---

### pickers {#miniextra.pickers .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers`</p>
[mini.pick](mini-pick.qmd#mini.pick) 피커

'mini.pick' 피커(필수 의존성)를 포함하는 테이블입니다.
참고:

- 모든 피커는 동일한 시그니처를 가집니다:

    - <span class="help-syntax-keys">\<local_opts\></span> - 피커 로컬 옵션을 포함하는 선택적 테이블입니다.

    - <span class="help-syntax-keys">\<opts\></span> - [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 선택적 옵션 테이블입니다.

- [MiniExtra.setup()](mini-extra.qmd#miniextra.setup) 또는 [MiniPick.setup()](mini-pick.qmd#minipick.setup) 중 하나만 호출해도 [MiniPick.registry](mini-pick.qmd#minipick.registry)에 자동으로 등록됩니다.

- 별도의 언급이 없는 한 모든 피커는 [MiniPick-source.preview](mini-pick.qmd#minipick-source.preview), [MiniPick-source.choose](mini-pick.qmd#minipick-source.choose),
  [MiniPick-source.choose\_marked](mini-pick.qmd#minipick-source.choose_marked)의 기본 버전을 사용합니다.
  표시되는 텍스트와 [MiniPick-source.show](mini-pick.qmd#minipick-source.show)는 선택된 항목에 맞춰집니다.

사용 예시:

- Lua 코드: `MiniExtra.pickers.buf_lines()`.

- [:Pick](mini-pick.qmd#pick) 명령 사용: `:Pick buf_lines scope='current'`
  참고: 이를 위해서는 [MiniExtra.setup()](mini-extra.qmd#miniextra.setup) 호출이 필요합니다.

---

### pickers.buf_lines() {#miniextra.pickers.buf_lines .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.buf_lines`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
버퍼 줄(lines) 피커

버퍼의 줄 중에서 선택합니다. 참고:

- 현재 로드되지 않은 모든 대상 버퍼를 로드합니다.

#### 매개변수 {#miniextra.pickers.buf_lines-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - "all" (나열된 일반 버퍼들) 또는 "current" 중 하나입니다.
    기본값: "all".

  - <span class="help-syntax-keys">\<preserve_order\></span> `(boolean)` - 쿼리 중에 원래 순서를 유지할지 여부입니다. 기본값: `false`.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.buf_lines-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.colorschemes() {#miniextra.pickers.colorschemes .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.colorschemes`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
컬러 스킴(color scheme) 피커

컬러 스킴을 선택하고 적용합니다. 미리보기는 항목의 컬러 스킴을 일시적으로 적용하고 선택된 하이라이트 그룹이 어떻게 보이는지 보여줍니다.
취소하면 피커 시작 전의 컬러 스킴으로 돌아갑니다:

- [mini.colors](mini-colors.qmd#mini.colors)가 사용 가능한 경우 [MiniColors-colorscheme:apply()](mini-colors.qmd#minicolors-colorschemeapply)를 사용합니다.

- [g:colors\_name](https://neovim.io/doc/user/helptag.html?tag=g:colors_name)이 사용 가능한 경우 [:colorscheme](https://neovim.io/doc/user/helptag.html?tag=:colorscheme)을 사용합니다.

#### 매개변수 {#miniextra.pickers.colorschemes-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<names\></span> `(table)` - 선택할 컬러 스킴 이름 배열입니다.
    기본값: 사용 가능한 모든 컬러 스킴.

  - <span class="help-syntax-keys">\<preview_hl_groups\></span> `(table)` - 미리보기 창에 표시할 하이라이트 그룹 배열입니다. 기본값: 정의된 모든 하이라이트 그룹을 알파벳 순으로 표시.


<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.colorschemes-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.commands() {#miniextra.pickers.commands .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.commands`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 명령 피커

Neovim 내장 명령([Ex-commands](https://neovim.io/doc/user/helptag.html?tag=Ex-commands)) 및 [사용자 정의 명령](https://neovim.io/doc/user/helptag.html?tag=user-commands) 중에서 선택합니다.
참고:

- 미리보기는 명령에 대한 정보(가능한 경우)를 보여줍니다.

- 선택하면 명령을 직접 실행하거나(인자가 필요 없다고 판단되는 경우), 명령줄에 해당 명령을 입력합니다.

#### 매개변수 {#miniextra.pickers.commands-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  현재는 사용되지 않습니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.commands-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.diagnostic() {#miniextra.pickers.diagnostic .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.diagnostic`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
내장 진단 피커

[vim.diagnostic.get()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.get\(\))을 사용하여 [vim.diagnostic](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic)에서 진단 항목을 선택합니다.

#### 매개변수 {#miniextra.pickers.diagnostic-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<get_opts\></span> `(table)` - [vim.diagnostic.get()](https://neovim.io/doc/user/helptag.html?tag=vim.diagnostic.get\(\))을 위한 옵션입니다. 심각도나 네임스페이스를 제한하는 데 사용할 수 있습니다. 기본값: `{}`.

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - "all" (사용 가능한 전체) 또는 "current" (버퍼) 중 하나입니다.
    기본값: "all".

  - <span class="help-syntax-keys">\<sort_by\></span> `(string)` - 정렬 우선순위입니다. "severity", "path", "none" 중 하나입니다.
    기본값: "severity".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.diagnostic-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.explorer() {#miniextra.pickers.explorer .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.explorer`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
파일 탐색기 피커

파일 시스템을 탐색하고 파일을 엽니다.
참고:

- 디렉토리를 선택하면 그 안으로 이동하여 피커의 항목과 현재 작업 디렉토리를 변경합니다.

- 쿼리와 미리보기는 평소와 같이 작동합니다 ( `move_next`/`move_prev`만 사용할 수 있는 것은 아님).

- 미리보기는 모든 항목에 대해 작동합니다.

예시:


- `MiniExtra.pickers.explorer()`

- `:Pick explorer cwd='..'` - 부모 디렉토리에서 탐색기를 엽니다.

#### 매개변수 {#miniextra.pickers.explorer-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<cwd\></span> `(string)` - 탐색을 시작할 초기 디렉토리입니다. 유효한 디렉토리 경로여야 합니다. 기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)).

  - <span class="help-syntax-keys">\<filter\></span> `(function)` - 표시할 항목을 필터링하는 호출 가능한 서술부(predicate)입니다. 모든 항목에 대해 호출되며, 표시해야 하는 경우 `true`를 반환해야 합니다. 각 항목은 다음 필드를 가진 테이블입니다:

      - <span class="help-syntax-keys">\<fs_type\></span> `(string)` - 경로 유형입니다. "directory" 또는 "file" 중 하나입니다.

      - <span class="help-syntax-keys">\<path\></span> `(string)` - 항목 경로입니다.

      - <span class="help-syntax-keys">\<text\></span> `(string)` - 표시되는 텍스트(경로의 기본 이름).

  - <span class="help-syntax-keys">\<sort\></span> `(function)` - 호출 가능한 항목 정렬기입니다. 항목 배열(위에 설명된 구조를 가진 각 요소)과 함께 호출되며 정렬된 항목 배열을 반환해야 합니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.explorer-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.git_branches() {#miniextra.pickers.git_branches .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.git_branches`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Git 브랜치 피커

`git branch`를 사용하여 Git 브랜치 중에서 선택합니다.
참고:

- 실행 가능한 `git`이 필요합니다.

- 대상 경로가 Git 저장소의 일부여야 합니다.

- 탐색 및 내비게이션 목적으로 제공됩니다. Git 작업을 수행하는 것은 전용 Git 클라이언트를 사용하는 것이 좋으며, 별도의 기능 추가 계획은 없습니다.

- 선택 시 브랜치의 이력이 포함된 스크래치 버퍼를 엽니다.

예시:


- `MiniExtra.pickers.git_branches({ scope = 'local' })` - [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory) 부모 Git 저장소의 로컬 브랜치.

- `:Pick git_branches path='%'` - 현재 파일 부모 Git 저장소의 모든 브랜치.

#### 매개변수 {#miniextra.pickers.git_branches-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<path\></span> `(string|nil)` - Git 작업을 위한 대상 경로(필요한 경우)입니다. 항목을 구성할 Git 저장소를 찾는 데에도 사용됩니다.
    기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)를 포함하는 Git 저장소의 루트).

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 브랜치 범위입니다. "all", "local", "remotes" 중 하나입니다.
    기본값: "all".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.git_branches-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.git_commits() {#miniextra.pickers.git_commits .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.git_commits`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Git 커밋 피커

`git log`를 사용하여 Git 커밋 중에서 선택합니다.
참고:

- 실행 가능한 `git`이 필요합니다.

- 대상 경로가 Git 저장소의 일부여야 합니다.

- 탐색 및 내비게이션 목적으로 제공됩니다. Git 작업을 수행하는 것은 전용 Git 클라이언트를 사용하는 것이 좋으며, 별도의 기능 추가 계획은 없습니다.

- 선택 시 커밋의 diff가 포함된 스크래치 버퍼를 엽니다.

예시:


- `MiniExtra.pickers.git_commits()` - [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)의 부모 Git 저장소에 있는 모든 커밋.

- `MiniExtra.pickers.git_commits({ path = 'subdir' })` - 'subdir' 하위 디렉토리의 파일에 영향을 주는 커밋들.

- `:Pick git_commits path='%'` 현재 파일에 영향을 주는 커밋들.

#### 매개변수 {#miniextra.pickers.git_commits-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<path\></span> `(string|nil)` - Git 작업을 위한 대상 경로(필요한 경우)입니다. 항목을 구성할 Git 저장소를 찾는 데에도 사용됩니다.
    기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)를 포함하는 Git 저장소의 루트).

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.git_commits-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.git_files() {#miniextra.pickers.git_files .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.git_files`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Git 파일 피커

`git ls-files`를 사용하여 Git 파일 중에서 선택합니다.
참고:

- 실행 가능한 `git`이 필요합니다.

- 대상 경로가 Git 저장소의 일부여야 합니다.

- 탐색 및 내비게이션 목적으로 제공됩니다. Git 작업을 수행하는 것은 전용 Git 클라이언트를 사용하는 것이 좋으며, 별도의 기능 추가 계획은 없습니다.

예시:


- `MiniExtra.pickers.git_files({ scope = 'ignored' })` - [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)의 부모 Git 저장소에서 무시된 파일들.

- `:Pick git_files path='subdir' scope='modified'` - Git에서 무시된 'subdir' 하위 디렉토리의 파일들.

#### 매개변수 {#miniextra.pickers.git_files-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<path\></span> `(string|nil)` - Git 작업을 위한 대상 경로(필요한 경우)입니다. 항목을 구성할 Git 저장소를 찾는 데에도 사용됩니다.
    기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)를 포함하는 Git 저장소의 루트).

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 파일 범위입니다. 다음 중 하나입니다:

      - "tracked"   (`--cached`   Git 플래그).

      - "modified"  (`--modified` Git 플래그).

      - "untracked" (`--others`   Git 플래그).

      - "ignored"   (`--ignored`  Git 플래그).

      - "deleted"   (`--deleted`  Git 플래그).
    기본값: "tracked".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.git_files-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.git_hunks() {#miniextra.pickers.git_hunks .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.git_hunks`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Git 헌크(hunks) 피커

`git diff`를 사용하여 Git 헌크 중에서 선택합니다.
참고:

- 실행 가능한 `git`이 필요합니다.

- 대상 경로가 Git 저장소의 일부여야 합니다.

- 탐색 및 내비게이션 목적으로 제공됩니다. Git 작업을 수행하는 것은 전용 Git 클라이언트를 사용하는 것이 좋으며, 별도의 기능 추가 계획은 없습니다.

- 선택 시 헌크의 첫 번째 변경 사항으로 이동합니다.

예시:


- `MiniExtra.pickers.git_hunks({ scope = 'staged' })` - [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)의 부모 Git 저장소에서 스테이징된(staged) 헌크들.

- `:Pick git_hunks path='%' n_context=0` - 현재 파일에서 컨텍스트 없이 계산된 헌크들.

#### 매개변수 {#miniextra.pickers.git_hunks-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<n_context\></span> `(number)` - 헌크 미리보기에 표시할 컨텍스트 줄 수입니다.
    기본값: 3.

  - <span class="help-syntax-keys">\<path\></span> `(string|nil)` - Git 작업을 위한 대상 경로(필요한 경우)입니다. 항목을 구성할 Git 저장소를 찾는 데에도 사용됩니다.
    기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)를 포함하는 Git 저장소의 루트).

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 헌크 범위입니다. "unstaged" 또는 "staged" 중 하나입니다.
    기본값: "unstaged".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.git_hunks-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.hipatterns() {#miniextra.pickers.hipatterns .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.hipatterns`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
'mini.hipatterns' 매치 피커

[MiniHipatterns.get\_matches()](mini-hipatterns.qmd#minihipatterns.get_matches)를 사용하여 [mini.hipatterns](mini-hipatterns.qmd#mini.hipatterns) 매치 중에서 선택합니다.
참고:

- 'mini.hipatterns'가 필요합니다.

- 하이라이터 식별자는 해당 하이라이트 그룹으로 하이라이트됩니다.

#### 매개변수 {#miniextra.pickers.hipatterns-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - "all" ('mini.hipatterns'가 활성화된 버퍼들) 또는 "current" (버퍼) 중 하나입니다. 기본값: "all".

  - <span class="help-syntax-keys">\<highlighters\></span> `(table|nil)` - 매치를 찾을 하이라이터입니다.
    [MiniHipatterns.get\_matches()](mini-hipatterns.qmd#minihipatterns.get_matches)로 전달됩니다. 기본값: `nil`.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.hipatterns-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.history() {#miniextra.pickers.history .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.history`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 기록(history) 피커

[:history](https://neovim.io/doc/user/helptag.html?tag=:history) 출력에서 선택합니다. `<C-e>`를 사용하여 명령줄에서 현재 매치를 편집할 수 있습니다.

참고:

- 미리보기가 없습니다.

- 선택 시 동작은 범위(scope)에 따라 다릅니다:

    - "cmd" / ":" 범위의 경우, 명령이 실행됩니다.

    - "search" / "/" / "?" 범위의 경우, 검색이 다시 수행됩니다.

    - 다른 범위의 경우 아무 작업도 수행되지 않습니다 (하지만 선택된 항목은 여전히 반환됨).

- `<C-e>`는 "cmd" / ":" / "search" / "/" / "?" 범위에서만 작동합니다.

예시:


- 명령 기록: `MiniExtra.pickers.history({ scope = ':' })`

- 검색 기록: `:Pick history scope='/'`

#### 매개변수 {#miniextra.pickers.history-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - [:history](https://neovim.io/doc/user/helptag.html?tag=:history) 명령의 허용되는 모든 {name} 플래그입니다.
    참고: 단어 줄임표는 허용되지 않습니다. 기본값: "all".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.history-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.hl_groups() {#miniextra.pickers.hl_groups .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.hl_groups`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
하이라이트 그룹 피커

하이라이트 그룹을 선택하고 미리 봅니다.
참고:

- 항목 줄은 그것이 나타내는 것과 동일한 하이라이트 그룹으로 색칠됩니다.

- 미리보기는 하이라이트 정의를 보여줍니다 ( [:highlight](https://neovim.io/doc/user/helptag.html?tag=:highlight)와 <span class="help-syntax-special">{group-name}</span> 사용 시와 동일).

- 선택하면 업데이트 및 적용을 위해 하이라이트 정의를 명령줄에 배치합니다.

#### 매개변수 {#miniextra.pickers.hl_groups-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  현재는 사용되지 않습니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.hl_groups-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.keymaps() {#miniextra.pickers.keymaps .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.keymaps`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 키맵 피커

Neovim 키맵에 대한 데이터를 선택하고 미리 봅니다.
참고:

- 항목 줄에는 키맵 모드, 버퍼 로컬 여부, 왼쪽 키 시퀀스, 추론된 설명에 대한 데이터가 포함됩니다.

- 미리보기는 키맵 데이터 또는 콜백 소스(존재하고 접근 가능한 경우)를 보여줍니다.

- 선택하면 키맵의 왼쪽 키 시퀀스를 누르는 것과 동일한 동작을 수행합니다.

#### 매개변수 {#miniextra.pickers.keymaps-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<mode\></span> `(string)` - 표시할 모드입니다. "all" 또는 [nvim\_set\_keymap()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_keymap\(\))을 위한 적절한 모드 중 하나입니다. 기본값: "all".

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 범위입니다. "all", "global", "buf" 중 하나입니다.
    기본값: "all".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.keymaps-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.list() {#miniextra.pickers.list .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.list`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 리스트 피커

다음 Neovim 리스트의 요소를 선택하고 탐색합니다:

- [quickfix](https://neovim.io/doc/user/helptag.html?tag=quickfix) 리스트.

- 현재 창의 [location-list](https://neovim.io/doc/user/helptag.html?tag=location-list).

- [jumplist](https://neovim.io/doc/user/helptag.html?tag=jumplist).

- [changelist](https://neovim.io/doc/user/helptag.html?tag=changelist).

참고: 명시적인 `scope`가 필요합니다.

예시:


- `MiniExtra.pickers.list({ scope = 'quickfix' })` - quickfix 리스트.

- `:Pick list scope='jump'` - 점프 리스트.

#### 매개변수 {#miniextra.pickers.list-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 리스트 유형입니다. "quickfix", "location", "jump", "change" 중 하나입니다. 기본값: `nil` (명시적 범위 지정 필요).

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.list-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.lsp() {#miniextra.pickers.lsp .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.lsp`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
LSP 피커

LSP 메서드를 사용하여 선택하고 탐색합니다.
참고:

- 지원되는 목록 중 하나에서 명시적인 범위(scope)를 지정해야 합니다:

    - "declaration".

    - "definition".

    - "document_symbol".

    - "implementation".

    - "references".

    - "type_definition".

    - "workspace_symbol".

    - "workspace_symbol_live" - "workspace_symbol"과 동일하지만 피커의 프롬프트를 LSP 서버 쿼리로 취급하여 실시간 피드백을 제공합니다. [MiniPick.builtin.grep\_live()](mini-pick.qmd#minipick.builtin.grep_live)와 [MiniPick.builtin.grep()](mini-pick.qmd#minipick.builtin.grep)의 관계와 유사합니다. 일반 매칭을 사용하려면 [MiniPick-actions-refine](mini-pick.qmd#minipick-actions-refine)을 활성화하세요.

- [vim.lsp.LocationOpts.OnList](https://neovim.io/doc/user/helptag.html?tag=vim.lsp.LocationOpts.OnList)를 지원하는 `vim.lsp.buf` 메서드에 의존합니다. 특히, LSP 서버가 단일 위치가 아닌 위치 목록을 반환하는 경우에만 피커가 시작됨을 의미합니다.

- `vim.lsp.buf` 메서드의 비동기 특성으로 인해 아무것도 반환하지 않습니다.

- "document_symbol", "workspace_symbol", "workspace_symbol_live" 범위에서 추가 아이콘과 하이라이트를 표시하려면 [mini.icons](mini-icons.qmd#mini.icons) 설정이 필요합니다.

예시:


- `MiniExtra.pickers.lsp({ scope = 'references' })` - 커서 아래 심볼의 참조(references).

- `:Pick lsp scope='document_symbol'` - 현재 파일의 심볼들.

#### 매개변수 {#miniextra.pickers.lsp-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 사용할 LSP 메서드입니다. 지원되는 메서드 중 하나여야 합니다 (위에 목록 참조). 기본값: `nil` (명시적 범위 지정 필요).

  - <span class="help-syntax-keys">\<symbol_query\></span> `(string)` - `"workspace_symbol"` 범위를 위한 쿼리입니다.
    기본값: (LSP 사양에 따라) 모든 심볼을 위한 빈 문자열.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.lsp-return}


`(nil)` 아무것도 반환하지 않습니다.

---

### pickers.manpages() {#miniextra.pickers.manpages .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.manpages`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
매뉴얼 페이지(Man pages)

매뉴얼 페이지([ft-man-plugin](https://neovim.io/doc/user/helptag.html?tag=ft-man-plugin)에 설명된 것과 동일)를 선택합니다.
참고:

- 항목을 미리 보고 선택하기 위해 [:Man](https://neovim.io/doc/user/helptag.html?tag=:Man) 명령에 의존합니다.

- 대상 창에 페이지를 표시합니다. 분할 창을 사용하려면 [MiniPick-actions-choose](mini-pick.qmd#minipick-actions-choose)를 사용하세요.

#### 매개변수 {#miniextra.pickers.manpages-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  현재는 사용되지 않습니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.manpages-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.marks() {#miniextra.pickers.marks .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.marks`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 마크(marks) 피커

Neovim [마크](https://neovim.io/doc/user/helptag.html?tag=mark)의 위치를 선택하고 미리 봅니다.

#### 매개변수 {#miniextra.pickers.marks-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 범위입니다. "all", "global", "buf" 중 하나입니다.
    기본값: "all".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.marks-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.oldfiles() {#miniextra.pickers.oldfiles .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.oldfiles`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
이전 파일(old files) 피커

읽기 가능한 파일을 나타내는 [v:oldfiles](https://neovim.io/doc/user/helptag.html?tag=v:oldfiles) 항목 중에서 선택합니다.

#### 매개변수 {#miniextra.pickers.oldfiles-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<current_dir\></span> `(boolean)` - 현재 작업 디렉토리와 그 하위 디렉토리의 파일만 반환할지 여부입니다. 기본값: `false`.

  - <span class="help-syntax-keys">\<preserve_order\></span> `(boolean)` - 쿼리 중에 원래 순서를 유지할지 여부입니다. 기본값: `false`.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.oldfiles-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.options() {#miniextra.pickers.options .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.options`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 옵션 피커

Neovim 옵션에 대한 데이터를 선택하고 미리 봅니다.
참고:

- 항목 줄은 설정 여부에 따라 색상이 지정됩니다 (설정되지 않은 경우 어둡게 표시).

- 미리보기는 대상 창에서의 옵션 값과 일반 정보를 보여줍니다.

- 선택하면 업데이트 및 적용을 위해 옵션 이름을 명령줄에 배치합니다.

#### 매개변수 {#miniextra.pickers.options-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<scope\></span> `(string)` - 표시할 옵션입니다. "all", "global", "win", "buf" 중 하나입니다.
    기본값: "all".

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.options-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.registers() {#miniextra.pickers.registers .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.registers`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 레지스터 피커

Neovim [레지스터](https://neovim.io/doc/user/helptag.html?tag=registers)에서 선택합니다.
참고:

- 미리보기가 없습니다 (모든 정보가 항목의 텍스트에 포함됨).

- 선택하면 레지스터의 내용을 붙여넣습니다: 입력 모드에서는 [i\_CTRL-R](https://neovim.io/doc/user/helptag.html?tag=i_CTRL-R), 명령줄 모드에서는 [c\_CTRL-R](https://neovim.io/doc/user/helptag.html?tag=c_CTRL-R), 그 외의 경우에는 [P](https://neovim.io/doc/user/helptag.html?tag=P)를 사용합니다.
  표현식 레지스터 [quote=](https://neovim.io/doc/user/helptag.html?tag=quote=)는 (존재하는 경우) 다시 평가되어 붙여넣어집니다.

#### 매개변수 {#miniextra.pickers.registers-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  현재는 사용되지 않습니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.registers-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.spellsuggest() {#miniextra.pickers.spellsuggest .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.spellsuggest`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Neovim 맞춤법 제안(spell suggestions) 피커

맞춤법 제안을 선택하고 적용합니다.
참고:

- 미리보기를 사용할 수 없습니다.

- 선택하면 현재 단어([<span class="help-syntax-keys">\<cword\></span>](https://neovim.io/doc/user/helptag.html?tag=<cword>))를 제안된 단어로 교체합니다.

#### 매개변수 {#miniextra.pickers.spellsuggest-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<n_suggestions\></span> `(number)` - 맞춤법 제안의 개수입니다. 기본값: 25.


<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.spellsuggest-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.treesitter() {#miniextra.pickers.treesitter .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.treesitter`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
Tree-sitter 노드 피커

현재 버퍼의 [treesitter](https://neovim.io/doc/user/helptag.html?tag=treesitter) 노드를 선택하고 탐색합니다.
참고:

- 현재 버퍼에 활성화된 tree-sitter 파서가 필요합니다.

#### 매개변수 {#miniextra.pickers.treesitter-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  현재는 사용되지 않습니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.treesitter-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.visit_paths() {#miniextra.pickers.visit_paths .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.visit_paths`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
'mini.visits' 방문 경로 피커

[MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)를 사용하여 [mini.visits](mini-visits.qmd#mini.visits)에서 경로를 선택합니다.
참고:

- 'mini.visits'가 필요합니다.

예시:


- `MiniExtra.pickers.visit_paths()` - [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)에 등록되고 "최신 빈도수(robust frecency)" 순으로 정렬된 방문 기록.

- `:Pick visit_paths cwd='' recency_weight=1 filter='core'` - "core" 레이블이 있는 모든 방문 기록을 최신 순으로 정렬.

#### 매개변수 {#miniextra.pickers.visit_paths-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<cwd\></span> `(string)` - [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.
    기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)에 등록된 경로를 가져옴).

  - <span class="help-syntax-keys">\<filter\></span> `(function|string)` - [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.
    기본값: `nil` (모든 경로 사용).

  - <span class="help-syntax-keys">\<preserve_order\></span> `(boolean)` - 쿼리 중에 원래 순서를 유지할지 여부입니다. 기본값: `false`.

  - <span class="help-syntax-keys">\<recency_weight\></span> `(number)` - [MiniVisits.gen\_sort.default()](mini-visits.qmd#minivisits.gen_sort.default)로 전달됩니다.
    기본값: 0.5 ("최신 빈도수(robust frecency)" 정렬 사용).

  - <span class="help-syntax-keys">\<sort\></span> `(function)` - [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다.
    기본값: `nil` ("최신 빈도수" 사용).
    참고: 제공된 경우 `recency_weight`보다 우선합니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.visit_paths-return}


`(any)` 호출된 피커의 출력입니다.

---

### pickers.visit_labels() {#miniextra.pickers.visit_labels .help-syntax-right-anchor}

<p align="center">`MiniExtra.pickers.visit_labels`(<span class="help-syntax-special">{local_opts}</span>, <span class="help-syntax-special">{opts}</span>)</p>
'mini.visits' 방문 레이블 피커

[MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels) 및 [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)를 사용하여 [mini.visits](mini-visits.qmd#mini.visits)에서 레이블을 선택합니다.
참고:

- 'mini.visits'가 필요합니다.

- 미리보기는 미리 본 레이블을 가진 방문 경로로 필터링하여 보여줍니다.

- 선택하면 본질적으로 선택된 레이블을 가진 경로에 대해 [MiniExtra.pickers.visit\_paths()](mini-extra.qmd#miniextra.pickers.visit_paths)를 시작합니다.

예시:


- `MiniExtra.pickers.visit_labels()` - [현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)에 등록된 방문 기록의 레이블.

- `:Pick visit_labels cwd=''` - 모든 방문 기록의 레이블.

#### 매개변수 {#miniextra.pickers.visit_labels-parameters}



<span class="help-syntax-special">{local_opts}</span> `(table|nil)` 이 특정 피커의 동작을 정의하는 옵션입니다.
  가능한 필드:

  - <span class="help-syntax-keys">\<cwd\></span> `(string)` - [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)로 전달됩니다.
    기본값: `nil` ([현재 디렉토리](https://neovim.io/doc/user/helptag.html?tag=current-directory)에 등록된 방문 기록에서 레이블을 가져옴).

  - <span class="help-syntax-keys">\<filter\></span> `(function|string)` - [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)로 전달됩니다.
    기본값: `nil` (모든 방문 기록 사용).

  - <span class="help-syntax-keys">\<path\></span> `(string)` - [MiniVisits.list\_labels()](mini-visits.qmd#minivisits.list_labels)로 전달됩니다.
    기본값: `""` (대상 `cwd`에 대한 모든 방문 기록에서 레이블을 가져옴).

  - <span class="help-syntax-keys">\<sort\></span> `(function)` - 미리보기 및 선택을 위해 [MiniVisits.list\_paths()](mini-visits.qmd#minivisits.list_paths)로 전달됩니다. 기본값: `nil` ("최신 빈도수" 사용).

<span class="help-syntax-special">{opts}</span> `(table|nil)` [MiniPick.start()](mini-pick.qmd#minipick.start)로 전달되는 옵션입니다.

#### 반환 {#miniextra.pickers.visit_labels-return}


`(...)` 선택된 경로입니다.
