---
title: "mini.animate 문서"
---

_'mini.nvim'의 `main` 브랜치에서 생성됨_

<a name="mini.animate" href="mini-animate.qmd#mini.animate"><b>mini.animate</b></a> 일반적인 Neovim 동작 애니메이션화

MIT 라이선스 Copyright (c) 2022 Evgeni Chasnovski

---

### 모듈 {#module .help-syntax-right-anchor}

기능:

- `require('mini.animate').setup()` 한 번으로 즉시 사용 가능합니다.
  별도의 매핑이나 명령어가 필요하지 않습니다.


- 사용자 정의 가능한 경로를 보여줌으로써 동일 버퍼 내의 커서 이동을 애니메이션화합니다.
  자세한 내용은 [MiniAnimate.config.cursor](mini-animate.qmd#minianimate.config.cursor)를 참조하세요.


- 일련의 서브스크롤("부드러운 스크롤")로 스크롤을 애니메이션화합니다.
  자세한 내용은 [MiniAnimate.config.scroll](mini-animate.qmd#minianimate.config.scroll)을 참조하세요.


- 모든 창의 크기를 점진적으로 변경하여 창 크기 조정을 애니메이션화합니다.
  자세한 내용은 [MiniAnimate.config.resize](mini-animate.qmd#minianimate.config.resize)를 참조하세요.


- 시각적으로 업데이트되는 플로팅 창으로 창 열기/닫기를 애니메이션화합니다.
  자세한 내용은 [MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 및 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close)를 참조하세요.


- 모든 동작에 대한 타이밍을 독립적으로 설정할 수 있습니다.
  자세한 내용은 [MiniAnimate-timing](mini-animate.qmd#minianimate-timing)을 참조하세요.


- 동작 애니메이션을 독립적으로 활성화/비활성화할 수 있습니다.


- 모든 애니메이션은 비동기/논블로킹이며, 애니메이션 완료 후 동작을 수행하는 데 사용할 수 있는 특정 이벤트를 트리거합니다.


- 자체 애니메이션을 수행하는 데 사용할 수 있는 [MiniAnimate.animate()](mini-animate.qmd#minianimate.animate) 함수를 제공합니다.

참고:

- 커서 이동은 화면 가로지르는 이동이 아니라 동일 창 및 버퍼 내부에서의 이동만 애니메이션화됩니다.


- 스크롤 및 크기 조정 애니메이션은 "부수 효과"와 함께 수행됩니다. 즉, 실제로 애니메이션 대상의 상태(각각 창 보기 및 크기)를 변경합니다. 이는 애니메이션의 비동기적 특성(특정 매핑 조정 등)을 고려하기 위해 추가 작업이 필요할 수 있다는 단점이 있습니다. 자세한 내용은 [MiniAnimate.config.scroll](mini-animate.qmd#minianimate.config.scroll) 및 [MiniAnimate.config.resize](mini-animate.qmd#minianimate.config.resize)를 참조하세요.

#### 설정 {#module-setup}


이 모듈은 `require('mini.animate').setup({})`으로 설정이 필요합니다 (`{}`를 사용자 `config` 테이블로 교체하세요). 이는 스크립팅이나 수동으로 사용할 수 있는 전역 Lua 테이블 `MiniAnimate`를 생성합니다 (`:lua MiniAnimate.*`로 사용 가능).

사용 가능한 설정은 [MiniAnimate.config](mini-animate.qmd#minianimate.config)를 참조하세요.

런타임 설정(예: `config.modifiers`)을 `vim.b.minianimate_config`를 사용하여 버퍼별로 재정의할 수 있으며, 이는 `MiniAnimate.config`와 동일한 구조여야 합니다. 자세한 내용은 [mini.nvim-buffer-local-config](mini-nvim.qmd#mini.nvim-buffer-local-config)를 참조하세요.

#### 비교 {#module-comparisons}



- [Neovide](https://neovide.dev/):

    - Neovide는 애니메이션을 더 세밀하게 제어할 수 있는 독립형 GUI입니다. 반면 'mini.animate'는 터미널 에뮬레이터 내부에서 작동합니다 (애니메이션에 대한 픽셀 단위 제어 부족과 같은 터미널의 모든 한계를 포함함).

    - Neovide는 화면을 가로지르는 커서 이동을 애니메이션화하지만, 'mini.animate'는 동일 버퍼 내에서의 이동을 애니메이션화합니다.

    - Neovide는 동작당 고정된 수의 애니메이션 효과를 갖지만, 'mini.animate'는 완전히 사용자 정의 가능합니다.

    - 'mini.animate'는 창 열기/닫기 애니메이션을 구현하지만 Neovide는 구현하지 않습니다.

- [edluffy/specs.nvim](https://github.com/edluffy/specs.nvim):

    - 'mini.animate'는 사용자 정의 가능한 경로 함수(extmark 사용)를 통해 커서 이동 시각화에 접근하는 반면, 'specs.nvim'은 자체 시각 효과(쉐이딩 및 플로팅 창 크기 조정) 내에서 사용자 정의할 수 있습니다.

- [karb94/neoscroll.nvim](https://github.com/karb94/neoscroll.nvim):

    - 스크롤 애니메이션은 전용 매핑 내부에서만 트리거됩니다. 'mini.animate'는 창 보기 변경으로 인한 모든 스크롤을 애니메이션화합니다.

- [anuvyklack/windows.nvim](https://github.com/anuvyklack/windows.nvim):

    - 크기 조정 애니메이션은 사용자 정의 명령어 및 매핑 내에서만 수행되는 반면, 'mini.animate'는 'winheight' / 'winwidth' 및 'winminheight' / 'winminwidth' 값이 적절할 경우 모든 크기 조정을 애니메이션화합니다.

#### 하이라이트 그룹 {#module-highlightgroups}



- `MiniAnimateCursor` - 애니메이션 이동 중 커서 하이라이트.

- `MiniAnimateNormalFloat` - `open` 및 `close` 애니메이션을 위한 플로팅 창 하이라이트.

하이라이트 그룹을 변경하려면 [nvim\_set\_hl()](https://neovim.io/doc/user/helptag.html?tag=nvim_set_hl\(\))을 사용하여 직접 설정하세요.

#### 비활성화 {#module-disabling}


비활성화하려면 `vim.g.minianimate_disable`(전역) 또는 `vim.b.minianimate_disable`(버퍼별)을 `true`로 설정하세요. 다양한 시나리오와 사용자 정의 의도를 고려하여 모듈 기능 비활성화를 위한 정확한 규칙 작성은 사용자의 몫으로 남겨둡니다. 일반적인 방법은 [mini.nvim-disabling-recipes](mini-nvim.qmd#mini.nvim-disabling-recipes)를 참조하세요.

---

### setup() {#minianimate.setup .help-syntax-right-anchor}

<p align="center">`MiniAnimate.setup`(<span class="help-syntax-special">{config}</span>)</p>
모듈 설정

#### 매개변수 {#minianimate.setup-parameters}



<span class="help-syntax-special">{config}</span> `(table|nil)` 모듈 설정 테이블. [MiniAnimate.config](mini-animate.qmd#minianimate.config)를 참조하세요.

#### 사용법 {#minianimate.setup-usage}



  ```lua
  require('mini.animate').setup() -- 기본 설정 사용
  -- 또는
  require('mini.animate').setup({}) -- {}를 사용자 설정 테이블로 교체
  ```

---

### config {#minianimate.config .help-syntax-right-anchor}

<p align="center">`MiniAnimate.config`</p>
#### 기본값 {#minianimate.config-defaults}



  ```lua
  MiniAnimate.config = {
    -- 커서 경로
    cursor = {
      -- 이 애니메이션 활성화 여부
      enable = true,

      -- 애니메이션 타이밍 (시간에 따른 단계 진행 방식)
      timing = --<함수: 선형 애니메이션, 총 250ms>,

      -- 시각화된 커서 이동을 위한 경로 생성기
      path = --<함수: 1000자 이하의 최단 직선 경로 구현>,
    },

    -- 세로 스크롤
    scroll = {
      -- 이 애니메이션 활성화 여부
      enable = true,

      -- 애니메이션 타이밍 (시간에 따른 단계 진행 방식)
      timing = --<함수: 선형 애니메이션, 총 250ms>,

      -- 총 스크롤을 기반으로 한 서브스크롤 생성기
      subscroll = --<함수: 최대 60단계의 균등 스크롤 구현>,
    },

    -- 창 크기 조정
    resize = {
      -- 이 애니메이션 활성화 여부
      enable = true,

      -- 애니메이션 타이밍 (시간에 따른 단계 진행 방식)
      timing = --<함수: 선형 애니메이션, 총 250ms>,

      -- 크기 조정 애니메이션의 모든 단계를 위한 서브리사이즈 생성기
      subresize = --<함수: 균등 선형 단계 구현>,
    },

    -- 창 열기
    open = {
      -- 이 애니메이션 활성화 여부
      enable = true,

      -- 애니메이션 타이밍 (시간에 따른 단계 진행 방식)
      timing = --<함수: 선형 애니메이션, 총 250ms>,

      -- 특정 창을 시각화하는 플로팅 창 설정 생성기
      winconfig = --<함수: 25단계 동안 정적 창 구현>,

      -- 플로팅 창을 위한 'winblend'(창 투명도) 생성기
      winblend = --<함수: 80에서 100까지 균등 선형 단계 구현>,
    },

    -- 창 닫기
    close = {
      -- 이 애니메이션 활성화 여부
      enable = true,

      -- 애니메이션 타이밍 (시간에 따른 단계 진행 방식)
      timing = --<함수: 선형 애니메이션, 총 250ms>,

      -- 특정 창을 시각화하는 플로팅 창 설정 생성기
      winconfig = --<함수: 25단계 동안 정적 창 구현>,

      -- 플로팅 창을 위한 'winblend'(창 투명도) 생성기
      winblend = --<함수: 80에서 100까지 균등 선형 단계 구현>,
    },
  }
  ```

#### 일반 {#minianimate.config-general}



- <a name="minianimate-timing" href="mini-animate.qmd#minianimate-timing"><b>MiniAnimate-timing</b></a> 모든 애니메이션은 논블로킹 방식으로 스케줄링된 일련의 특정 동작입니다. 이들은 `timing` 옵션에 의해 제어되는 시간 단계 순서대로 실행됩니다. 이는 다음 단계 번호와 총 단계 번호가 주어지면 대기 시간(ms 단위)을 반환하는 콜러블입니다. 내장 타이밍 함수는 [MiniAnimate.gen\_timing](mini-animate.qmd#minianimate.gen_timing)을 참조하세요. 애니메이션 프로세스에 대한 자세한 내용은 [MiniAnimate.animate()](mini-animate.qmd#minianimate.animate)를 참조하세요.


- 모든 애니메이션은 `enable` 옵션을 `true`/`false`로 설정하여 독립적으로 활성화/비활성화할 수 있습니다.


- <a name="minianimate-done-event" href="mini-animate.qmd#minianimate-done-event"><b>MiniAnimate-done-event</b></a> 모든 애니메이션은 완료 시 사용자 정의 [User](https://neovim.io/doc/user/helptag.html?tag=User) 이벤트를 트리거합니다. 이름은 `MiniAnimateDoneXxx`이며, `Xxx`는 대문자로 시작하는 지원되는 애니메이션 동작 이름(예: `MiniAnimateDoneCursor`)으로 대체됩니다. 특정 애니메이션이 완료된 후 일부 동작을 예약하는 데 사용하세요. 또는 [MiniAnimate.execute\_after()](mini-animate.qmd#minianimate.execute_after)를 사용할 수 있습니다(매핑에서 주로 선호됨).


- 각 애니메이션에는 특정 애니메이션이 수행되는 방식을 정의하는 기본 단계 생성기가 있습니다. 이들은 모두 입력 데이터를 받아 단계 데이터 배열을 반환하는 콜러블입니다. 해당 배열의 길이에 따라 애니메이션 단계 수가 결정됩니다. `nil` 또는 빈 테이블이 출력되면 애니메이션이 수행되지 않습니다.

#### 커서 {#minianimate.config-cursor}


<a name="minianimate.config.cursor" href="mini-animate.qmd#minianimate.config.cursor"><b>MiniAnimate.config.cursor</b></a>

이 애니메이션은 동일 창 및 버퍼 내부의 각 커서 이동에 대해 트리거됩니다. 시각화 단계는 특정 위치에 단일 extmark(참조 [extmarks](https://neovim.io/doc/user/helptag.html?tag=extmarks))를 배치하는 것으로 구성됩니다. 이 extmark는 단일 공백을 포함하며 `MiniAnimateCursor` 하이라이트 그룹으로 강조됩니다.

extmark의 정확한 위치와 개수는 `path` 옵션에 의해 제어됩니다. 이는 `destination` 인수(`(line, col)` 좌표의 2D 정수 포인트)를 받아 extmark가 배치될 `(0, 0)`에 대한 상대적 위치 배열을 반환하는 콜러블입니다. 예:

- 입력 `(2, -3)`은 커서가 앞으로 2행, 뒤로 3열 점프했음을 의미합니다.

- 출력 `{ {0, 0 }, { 0, -1 }, { 0, -2 }, { 0, -3 }, { 1, -3 } }`은 경로가 먼저 초기 행을 따라 시각화된 다음 최종 열을 따라 시각화됨을 의미합니다.

내장 경로 생성기는 [MiniAnimate.gen\_path](mini-animate.qmd#minianimate.gen_path)를 참조하세요.

참고:

- 입력 `destination` 값은 폴딩을 무시하고 계산됩니다. 이는 두 커서 위치 사이의 거리를 더 잘 시각화하기 위한 설계입니다.

- extmark를 배치할 수 없는 위치를 생성하는 경로 생성기의 출력은 애니메이션 중에 무시됩니다. 해당 단계는 시각화되지 않습니다.

설정 예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    cursor = {
      -- 선형 이징을 사용하여 200밀리초 동안 애니메이션화
      timing = animate.gen_timing.linear({ duration = 200, unit = 'total' }),

      -- 모든 커서 이동에 대해 최단 직선으로 애니메이션화
      path = animate.gen_path.line({
        predicate = function() return true end,
      }),
    }
  })
  ```

애니메이션이 완료되면 `MiniAnimateDoneCursor` 이벤트가 트리거됩니다.

#### 스크롤 {#minianimate.config-scroll}


<a name="minianimate.config.scroll" href="mini-animate.qmd#minianimate.config.scroll"><b>MiniAnimate.config.scroll</b></a>

이 애니메이션은 현재 창의 각 세로 스크롤에 대해 트리거됩니다. 시각화 단계는 작은 서브스크롤을 수행하여 최종적으로 필요한 총 스크롤이 되도록 구성됩니다.

정확한 서브스크롤 값과 개수는 `subscroll` 옵션에 의해 제어됩니다. 이는 `total_scroll` 인수(단일 비음수 정수)를 받아 각 단계에서 스크롤해야 할 행 수를 나타내는 비음수 정수 배열을 반환하는 콜러블입니다. 모든 서브스크롤 값의 합은 입력된 `total_scroll`과 같아야 합니다.
예:

- 입력 `5`는 총 스크롤이 5행으로 구성됨을 의미합니다 (위 또는 아래, 방향은 중요하지 않음).

- 출력 `{ 1, 1, 1, 1, 1 }`은 5개의 균등한 서브스크롤이 있음을 의미합니다.

내장 서브스크롤 생성기는 [MiniAnimate.gen\_subscroll](mini-animate.qmd#minianimate.gen_subscroll)을 참조하세요.

참고:

- `total_scroll` 입력 값은 폴딩을 고려하여 계산됩니다.

- 스크롤 애니메이션은 본질적으로 정밀하게 예약된 논블로킹 서브스크롤이므로, 다음과 같은 두 가지 중요한 연관된 결과가 있습니다.

    - 애니메이션 중에 다른 스크롤이 시도되면 현재 보이는 창 보기를 기준으로 수행됩니다. 예: 사용자가 [CTRL-D](https://neovim.io/doc/user/helptag.html?tag=CTRL-D)를 누른 다음 애니메이션이 절반쯤 진행되었을 때 [CTRL-U](https://neovim.io/doc/user/helptag.html?tag=CTRL-U)를 누르면 창에 이전 보기의 'scroll' 절반 위쪽이 표시되지 않습니다. 이는 특히 마우스 휠 스크롤에 영향을 미칩니다. 휠을 한 번 돌릴 때마다 'mousescroll'에 정의된 행 수만큼 새로운 스크롤이 발생하기 때문입니다. 취향에 맞게 조정하세요.

    - 동일한 명령어에서 여러 상대 스크롤 명령어를 사용하는 것이 중단됩니다. 대상 창 보기에 도달한 후 동작을 예약하려면 [MiniAnimate.execute\_after()](mini-animate.qmd#minianimate.execute_after)를 사용하세요.
      예: 유용한 `nnoremap n nzvzz` 매핑([n](https://neovim.io/doc/user/helptag.html?tag=n), [zv](https://neovim.io/doc/user/helptag.html?tag=zv), [zz](https://neovim.io/doc/user/helptag.html?tag=zz)의 연속 적용)은 다음과 같이 표현되어야 합니다.

        ```lua
        '<Cmd>lua vim.cmd("normal! n"); ' ..
          'MiniAnimate.execute_after("scroll", "normal! zvzz")<CR>'
        ```


- 기본 타이밍은 높은 키 반복 속도로 인해 키를 누르고 있는 상태(예: 'wrap'이 활성화된 상태에서 `j` 또는 `k`를 누름)에서 스크롤하는 것과 충돌할 수 있습니다. 현재 스크롤의 첫 번째 단계가 끝나기 전에 다음 스크롤이 수행되기 때문입니다. 그렇게 스크롤하지 않거나 단계 지속 시간의 최대값이 반복되는 키 사이의 시간보다 낮도록 타이밍을 설정하여 이를 해결하세요. `function(_, n) return math.min(250/n, 10) end`와 같이 타이밍을 설정하거나 고정된 단계 지속 시간의 타이밍을 사용하세요.

설정 예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    scroll = {
      -- 선형 이징을 사용하여 200밀리초 동안 애니메이션화
      timing = animate.gen_timing.linear({ duration = 200, unit = 'total' }),

      -- 균등하게 애니메이션화하되 기본 60단계 대신 최대 120단계 사용
      subscroll = animate.gen_subscroll.equal({ max_output_steps = 120 }),
    }
  })
  ```

애니메이션이 완료되면 `MiniAnimateDoneScroll` 이벤트가 트리거됩니다.

#### 크기 조정 {#minianimate.config-resize}


<a name="minianimate.config.resize" href="mini-animate.qmd#minianimate.config.resize"><b>MiniAnimate.config.resize</b></a>

이 애니메이션은 동일한 창들의 레이아웃을 유지하면서 창 크기가 조정될 때 트리거됩니다. 예를 들어, 창이 열리거나 닫힐 때 또는 [CTRL-W\_K](https://neovim.io/doc/user/helptag.html?tag=CTRL-W_K)와 같은 작업 후에는 트리거되지 않습니다. 시각화 단계는 모든 가시 창에 특정 크기를 설정하는 것으로 구성됩니다(마지막 단계는 "진짜" 최종 크기입니다).

정확한 창 단계 크기와 개수는 `subresize` 옵션에 의해 제어됩니다. 이는 `sizes_from` 및 `sizes_to` 인수(둘 다 창 ID를 키로, 차원 테이블을 값으로 갖는 테이블)를 받아 동일한 형태의 데이터 배열을 반환하는 콜러블입니다.
예:

- 입력:

  ```lua
  -- 이전
  { [1000] = {width = 7, height = 5}, [1001] = {width = 7, height = 10} }
  -- 이후
  { [1000] = {width = 9, height = 5}, [1001] = {width = 5, height = 10} }
  -- 창 1000의 너비가 창 1001을 희생하여 2만큼 증가했음을 의미함
  ```


- 다음 출력은 균등한 크기 조정을 보여줍니다.

  ```lua
  {
    { [1000] = {width = 8, height = 5}, [1001] = {width = 6, height = 10} },
    { [1000] = {width = 9, height = 5}, [1001] = {width = 5, height = 10} },
  }
  ```

내장 서브리사이즈 생성기는 [MiniAnimate.gen\_subresize](mini-animate.qmd#minianimate.gen_subresize)를 참조하세요.

참고:


- 크기 조정 애니메이션은 본질적으로 정밀하게 예약된 논블로킹 서브리사이즈이므로, 다음과 같은 두 가지 중요한 연관된 결과가 있습니다.

    - 애니메이션 중에 다른 크기 조정이 시도되면 현재 보이는 창 크기를 기준으로 수행됩니다. 이는 상대적인 크기 조정에 영향을 줄 수 있습니다.

    - 동일한 명령어에서 여러 상대적 크기 조정 명령어를 사용하는 것이 중단됩니다. 대상 창 크기에 도달한 후 동작을 예약하려면 [MiniAnimate.execute\_after()](mini-animate.qmd#minianimate.execute_after)를 사용하세요.

설정 예시:

  ```lua
  local is_many_wins = function(sizes_from, sizes_to)
    return vim.tbl_count(sizes_from) >= 3
  end
  local animate = require('mini.animate')
  animate.setup({
    resize = {
      -- 선형 이징을 사용하여 200밀리초 동안 애니메이션화
      timing = animate.gen_timing.linear({ duration = 200, unit = 'total' }),

      -- 창이 3개 이상인 경우에만 애니메이션화
      subresize = animate.gen_subscroll.equal({ predicate = is_many_wins }),
    }
  })
  ```

애니메이션이 완료되면 `MiniAnimateDoneResize` 이벤트가 트리거됩니다.

#### 창 열기/닫기 {#minianimate.config-windowopenclose}


<a name="minianimate.config.open" href="mini-animate.qmd#minianimate.config.open"><b>MiniAnimate.config.open</b></a>
<a name="minianimate.config.close" href="mini-animate.qmd#minianimate.config.close"><b>MiniAnimate.config.close</b></a>

이 애니메이션들은 일반(비플로팅) 창이 열리거나 닫힐 때 유사하게 트리거됩니다. 시각화 단계는 사용자 정의 가능한 설정과 투명도를 가진 빈 플로팅 창을 그리는 것으로 구성됩니다.

정확한 창 시각화 특성은 `winconfig` 및 `winblend` 옵션에 의해 제어됩니다.

`winconfig` 옵션은 창 ID([window-ID](https://neovim.io/doc/user/helptag.html?tag=window-ID))를 입력으로 받아 플로팅 창 설정 배열([nvim\_open\_win()](https://neovim.io/doc/user/helptag.html?tag=nvim_open_win\(\))의 `config` 인수와 동일)을 반환하는 콜러블입니다. 그 길이에 따라 애니메이션 단계 수가 결정됩니다.
예:

- 다음 출력은 두 단계의 애니메이션을 생성하며, 두 번째 단계는 첫 번째 단계의 왼쪽 상단 1/4 크기입니다.

  ```lua
  {
    {
      row      = 0,        col    = 0,
      width    = 10,       height = 10,
      relative = 'editor', anchor = 'NW',   focusable = false,
      zindex   = 1,        border = 'none', style  = 'minimal',
    },
    {
      row      = 0,        col    = 0,
      width    = 5,        height = 5,
      relative = 'editor', anchor = 'NW',   focusable = false,
      zindex   = 1,        border = 'none', style  = 'minimal',
    },
  }
  ```

`winblend` 옵션은 `timing` 옵션과 유사합니다. 현재 및 총 단계 번호가 주어지면 플로팅 창의 'winblend' 옵션 값을 반환하는 콜러블입니다. 단계 전이 아니라 현재 단계를 위해 호출되므로 0부터 시작한다는 점에 유의하세요 (반면 `timing`은 단계 전에 호출됨).
예:

- 함수 `function(s, n) return 80 + 20 * s / n end`는 `winblend` 값을 80에서 100으로 선형적으로 변화시킵니다.

내장 창 설정 생성기는 [MiniAnimate.gen\_winconfig](mini-animate.qmd#minianimate.gen_winconfig)를 참조하세요.
내장 창 투명도 생성기는 [MiniAnimate.gen\_winblend](mini-animate.qmd#minianimate.gen_winblend)를 참조하세요.

설정 예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    open = {
      -- 선형 이징을 사용하여 400밀리초 동안 애니메이션화
      timing = animate.gen_timing.linear({ duration = 400, unit = 'total' }),

      -- 기본 정적 창 대신 가장 가까운 가장자리에서 닦아내는 효과로 애니메이션화
      winconfig = animate.gen_winconfig.wipe({ direction = 'from_edge' }),

      -- 더 큰 창을 더 투명하게 만듦
      winblend = animate.gen_winblend.linear({ from = 80, to = 100 }),
    },

    close = {
      -- 선형 이징을 사용하여 400밀리초 동안 애니메이션화
      timing = animate.gen_timing.linear({ duration = 400, unit = 'total' }),

      -- 기본 정적 창 대신 가장 가까운 가장자리로 닦아내는 효과로 애니메이션화
      winconfig = animate.gen_winconfig.wipe({ direction = 'to_edge' }),

      -- 더 큰 창을 더 투명하게 만듦
      winblend = animate.gen_winblend.linear({ from = 100, to = 80 }),
    },
  })
  ```

애니메이션이 완료되면 `open` 애니메이션의 경우 `MiniAnimateDoneOpen`, `close` 애니메이션의 경우 `MiniAnimateDoneClose` 이벤트가 각각 트리거됩니다.

---

### is_active() {#minianimate.is_active .help-syntax-right-anchor}

<p align="center">`MiniAnimate.is_active`(<span class="help-syntax-special">{animation_type}</span>)</p>
애니메이션 활성 상태 확인

#### 매개변수 {#minianimate.is_active-parameters}



<span class="help-syntax-special">{animation_type}</span> `(string)` 지원되는 애니메이션 유형 중 하나
  ([MiniAnimate.config](mini-animate.qmd#minianimate.config)의 항목, 예: `'cursor'` 등).

#### 반환 {#minianimate.is_active-return}


`(boolean)` 애니메이션이 현재 활성 상태인지 여부.

---

### execute_after() {#minianimate.execute_after .help-syntax-right-anchor}

<p align="center">`MiniAnimate.execute_after`(<span class="help-syntax-special">{animation_type}</span>, <span class="help-syntax-special">{action}</span>)</p>
애니메이션 완료 후 동작 실행

애니메이션이 활성 상태가 아니면 동작을 즉시 실행합니다 ([MiniAnimate.is\_active()](mini-animate.qmd#minianimate.is_active)로 확인). 그렇지 않으면 애니메이션이 완료될 때까지 실행을 예약합니다 (해당 "완료 이벤트" 시점, [MiniAnimate-done-event](mini-animate.qmd#minianimate-done-event) 참조).

주로 매핑 내부에서 사용하도록 설계되었습니다.

예시:

유용한 `nnoremap n nzvzz` 매핑([n](https://neovim.io/doc/user/helptag.html?tag=n), [zv](https://neovim.io/doc/user/helptag.html?tag=zv), [zz](https://neovim.io/doc/user/helptag.html?tag=zz)의 연속 적용)은 다음과 같이 표현되어야 합니다.

  ```lua
  '<Cmd>lua vim.cmd("normal! n"); ' ..
    'MiniAnimate.execute_after("scroll", "normal! zvzz")<CR>'
  ```

#### 매개변수 {#minianimate.execute_after-parameters}



<span class="help-syntax-special">{animation_type}</span> `(string)` 지원되는 애니메이션 유형 중 하나
  ([MiniAnimate.is\_active()](mini-animate.qmd#minianimate.is_active)에서와 동일).

<span class="help-syntax-special">{action}</span> `(string|function)` 실행할 동작. 문자열인 경우 명령어로 실행됩니다 ([vim.cmd()](https://neovim.io/doc/user/helptag.html?tag=vim.cmd\(\)) 사용).

---

### animate() {#minianimate.animate .help-syntax-right-anchor}

<p align="center">`MiniAnimate.animate`(<span class="help-syntax-special">{step_action}</span>, <span class="help-syntax-special">{step_timing}</span>, <span class="help-syntax-special">{opts}</span>)</p>
동작 애니메이션화

이는 다음 알고리즘의 비동기 실행과 동일합니다.

- 이 함수 호출 직후 `step_action(0)`을 호출합니다. 동작이 `false` 또는 `nil`을 반환하면 중지합니다.

- `step_timing(1)` 밀리초 동안 대기합니다.

- `step_action(1)`을 호출합니다. `false` 또는 `nil`을 반환하면 중지합니다.

- `step_timing(2)` 밀리초 동안 대기합니다.

- `step_action(2)`을 호출합니다. `false` 또는 `nil`을 반환하면 중지합니다.

- ...

참고:

- 애니메이션은 동작 오류가 발생하거나 최대 단계 수에 도달한 경우에도 중지됩니다.

- 비동기 실행은 [uv.new\_timer()](https://neovim.io/doc/user/helptag.html?tag=uv.new_timer\(\))를 통해 수행됩니다. 반복 값으로 정수 부분만 허용합니다. 이는 다음과 같은 몇 가지 함의가 있습니다.

    - `step_timing()`의 출력값은 총 실행 시간을 유지하기 위해 누적됩니다.

    - 1ms 미만의 대기 시간은 동작이 즉시 실행됨을 의미합니다.

#### 매개변수 {#minianimate.animate-parameters}



<span class="help-syntax-special">{step_action}</span> `(function|table)` `step`(현재 단계를 나타내는 정수 0, 1, 2 등)을 받아 동작을 실행하는 콜러블입니다. 반환 값은 애니메이션 중지 시점을 정의합니다. `false` 및 `nil`(명시적 반환이 없는 경우와 동일) 값은 애니메이션 타이머를 중지하고, 그 외의 값은 계속합니다.

<span class="help-syntax-special">{step_timing}</span> `(function|table)` `step`(다음 단계를 나타내는 정수 1, 2 등)을 받아 이 단계 동작을 실행하기 전까지 대기할 밀리초를 반환하는 콜러블입니다.

<span class="help-syntax-special">{opts}</span> `(table|nil)` 옵션. 가능한 필드:

  - <span class="help-syntax-keys">\<max_steps\></span> - 실행 가능한 최대 단계 값. 기본값: 10000000.

---

### gen_timing {#minianimate.gen_timing .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing`</p>
애니메이션 타이밍 생성

각 필드는 적절한 인수를 제공하여 추가로 사용자 정의할 수 있는 진행 방식 제품군에 대응합니다.

이는 함수 요소가 있는 테이블입니다. 타이밍 함수를 실제로 가져오려면 호출하세요.

예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    cursor = {
      timing = animate.gen_timing.linear({ duration = 100, unit = 'total' })
    },
  })
  ```

#### 같이 보기 {#minianimate.gen_timing-seealso}


'mini.indentscope'의 유사한 개념은 [MiniIndentscope.gen\_animation](mini-indentscope.qmd#miniindentscope.gen_animation)을 참조하세요.

---

### gen_timing.none() {#minianimate.gen_timing.none .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing.none`()</p>
애니메이션 없는 타이밍 생성

최종 결과를 즉시 보여줍니다. 애니메이션을 비활성화하려면 보통 `config`의 `enable` 필드를 사용하는 것이 좋습니다.

---

### gen_timing.linear() {#minianimate.gen_timing.linear .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing.linear`(<span class="help-syntax-special">{opts}</span>)</p>
선형 진행 타이밍 생성

#### 매개변수 {#minianimate.gen_timing.linear-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 진행을 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<easing\></span> `(string)` - 진행의 하위 유형. "in"(속도 0에서 가속), "out"(속도 0으로 감속), "in-out"(기본값, 절반까지 가속 후 감속) 중 하나.

  - <span class="help-syntax-keys">\<duration\></span> `(number)` - 단위의 지속 시간(ms 단위). 기본값: 20.

  - <span class="help-syntax-keys">\<unit\></span> `(string)` - `opts.duration`이 제어하는 단위. "step"(기본값, 단계의 평균 지속 시간이 `opts.duration`이 되도록 보장) 또는 "total"(범위에 관계없이 고정된 총 지속 시간을 보장) 중 하나.

#### 반환 {#minianimate.gen_timing.linear-return}


`(function)` 타이밍 함수 ([MiniAnimate-timing](mini-animate.qmd#minianimate-timing) 참조).

---

### gen_timing.quadratic() {#minianimate.gen_timing.quadratic .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing.quadratic`(<span class="help-syntax-special">{opts}</span>)</p>
2차 진행 타이밍 생성

#### 매개변수 {#minianimate.gen_timing.quadratic-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 진행을 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<easing\></span> `(string)` - 진행의 하위 유형. "in"(속도 0에서 가속), "out"(속도 0으로 감속), "in-out"(기본값, 절반까지 가속 후 감속) 중 하나.

  - <span class="help-syntax-keys">\<duration\></span> `(number)` - 단위의 지속 시간(ms 단위). 기본값: 20.

  - <span class="help-syntax-keys">\<unit\></span> `(string)` - `opts.duration`이 제어하는 단위. "step"(기본값, 단계의 평균 지속 시간이 `opts.duration`이 되도록 보장) 또는 "total"(범위에 관계없이 고정된 총 지속 시간을 보장) 중 하나.

#### 반환 {#minianimate.gen_timing.quadratic-return}


`(function)` 타이밍 함수 ([MiniAnimate-timing](mini-animate.qmd#minianimate-timing) 참조).

---

### gen_timing.cubic() {#minianimate.gen_timing.cubic .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing.cubic`(<span class="help-syntax-special">{opts}</span>)</p>
3차 진행 타이밍 생성

#### 매개변수 {#minianimate.gen_timing.cubic-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 진행을 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<easing\></span> `(string)` - 진행의 하위 유형. "in"(속도 0에서 가속), "out"(속도 0으로 감속), "in-out"(기본값, 절반까지 가속 후 감속) 중 하나.

  - <span class="help-syntax-keys">\<duration\></span> `(number)` - 단위의 지속 시간(ms 단위). 기본값: 20.

  - <span class="help-syntax-keys">\<unit\></span> `(string)` - `opts.duration`이 제어하는 단위. "step"(기본값, 단계의 평균 지속 시간이 `opts.duration`이 되도록 보장) 또는 "total"(범위에 관계없이 고정된 총 지속 시간을 보장) 중 하나.

#### 반환 {#minianimate.gen_timing.cubic-return}


`(function)` 타이밍 함수 ([MiniAnimate-timing](mini-animate.qmd#minianimate-timing) 참조).

---

### gen_timing.quartic() {#minianimate.gen_timing.quartic .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing.quartic`(<span class="help-syntax-special">{opts}</span>)</p>
4차 진행 타이밍 생성

#### 매개변수 {#minianimate.gen_timing.quartic-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 진행을 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<easing\></span> `(string)` - 진행의 하위 유형. "in"(속도 0에서 가속), "out"(속도 0으로 감속), "in-out"(기본값, 절반까지 가속 후 감속) 중 하나.

  - <span class="help-syntax-keys">\<duration\></span> `(number)` - 단위의 지속 시간(ms 단위). 기본값: 20.

  - <span class="help-syntax-keys">\<unit\></span> `(string)` - `opts.duration`이 제어하는 단위. "step"(기본값, 단계의 평균 지속 시간이 `opts.duration`이 되도록 보장) 또는 "total"(범위에 관계없이 고정된 총 지속 시간을 보장) 중 하나.

#### 반환 {#minianimate.gen_timing.quartic-return}


`(function)` 타이밍 함수 ([MiniAnimate-timing](mini-animate.qmd#minianimate-timing) 참조).

---

### gen_timing.exponential() {#minianimate.gen_timing.exponential .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_timing.exponential`(<span class="help-syntax-special">{opts}</span>)</p>
지수 진행 타이밍 생성

#### 매개변수 {#minianimate.gen_timing.exponential-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 진행을 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<easing\></span> `(string)` - 진행의 하위 유형. "in"(속도 0에서 가속), "out"(속도 0으로 감속), "in-out"(기본값, 절반까지 가속 후 감속) 중 하나.

  - <span class="help-syntax-keys">\<duration\></span> `(number)` - 단위의 지속 시간(ms 단위). 기본값: 20.

  - <span class="help-syntax-keys">\<unit\></span> `(string)` - `opts.duration`이 제어하는 단위. "step"(기본값, 단계의 평균 지속 시간이 `opts.duration`이 되도록 보장) 또는 "total"(범위에 관계없이 고정된 총 지속 시간을 보장) 중 하나.

#### 반환 {#minianimate.gen_timing.exponential-return}


`(function)` 타이밍 함수 ([MiniAnimate-timing](mini-animate.qmd#minianimate-timing) 참조).

---

### gen_path {#minianimate.gen_path .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_path`</p>
커서 애니메이션 경로 생성

자세한 내용은 [MiniAnimate.config.cursor](mini-animate.qmd#minianimate.config.cursor)를 참조하세요.

이는 함수 요소가 있는 테이블입니다. 생성기를 실제로 가져오려면 호출하세요.

예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    cursor = {
      -- 최단 직선 대신 행-열 각도로 애니메이션화
      path = animate.gen_path.angle(),
    }
  })
  ```

---

### gen_path.line() {#minianimate.gen_path.line .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_path.line`(<span class="help-syntax-special">{opts}</span>)</p>
최단 직선 경로 생성

#### 매개변수 {#minianimate.gen_path.line-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `destination`을 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: `destination`이 시작점에서 한 행 이내인 경우 `false`(깜빡임 감소), 그렇지 않으면 `true`.

  - <span class="help-syntax-keys">\<max_output_steps\></span> `(number)` - 출력의 최대 단계 수. 기본값: 1000.

#### 반환 {#minianimate.gen_path.line-return}


`(function)` 경로 함수 ([MiniAnimate.config.cursor](mini-animate.qmd#minianimate.config.cursor) 참조).

---

### gen_path.angle() {#minianimate.gen_path.angle .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_path.angle`(<span class="help-syntax-special">{opts}</span>)</p>
행/열 각도 경로 생성

#### 매개변수 {#minianimate.gen_path.angle-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `destination`을 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: `destination`이 시작점에서 한 행 이내인 경우 `false`(깜빡임 감소), 그렇지 않으면 `true`.

  - <span class="help-syntax-keys">\<max_output_steps\></span> `(number)` - 출력의 측면당 최대 단계 수. 기본값: 1000.

  - <span class="help-syntax-keys">\<first_direction\></span> `(string)` - "horizontal"(기본값, 초기 행을 따라 먼저 애니메이션화) 또는 "vertical"(초기 열을 따라 먼저 애니메이션화) 중 하나.

#### 반환 {#minianimate.gen_path.angle-return}


`(function)` 경로 함수 ([MiniAnimate.config.cursor](mini-animate.qmd#minianimate.config.cursor) 참조).

---

### gen_path.walls() {#minianimate.gen_path.walls .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_path.walls`(<span class="help-syntax-special">{opts}</span>)</p>
최종 위치에서 닫히는 벽 형태의 경로 생성

#### 매개변수 {#minianimate.gen_path.walls-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `destination`을 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: `destination`이 시작점에서 한 행 이내인 경우 `false`(깜빡임 감소), 그렇지 않으면 `true`.

  - <span class="help-syntax-keys">\<width\></span> `(number)` - 왼쪽 및 오른쪽 벽의 초기 너비. 기본값: 10.

#### 반환 {#minianimate.gen_path.walls-return}


`(function)` 경로 함수 ([MiniAnimate.config.cursor](mini-animate.qmd#minianimate.config.cursor) 참조).

---

### gen_path.spiral() {#minianimate.gen_path.spiral .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_path.spiral`(<span class="help-syntax-special">{opts}</span>)</p>
최종 위치에서 작아지는 나선 형태의 경로 생성

#### 매개변수 {#minianimate.gen_path.spiral-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `destination`을 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: `destination`이 시작점에서 한 행 이내인 경우 `false`(깜빡임 감소), 그렇지 않으면 `true`.

  - <span class="help-syntax-keys">\<width\></span> `(number)` - 나선의 초기 너비. 기본값: 2.

#### 반환 {#minianimate.gen_path.spiral-return}


`(function)` 경로 함수 ([MiniAnimate.config.cursor](mini-animate.qmd#minianimate.config.cursor) 참조).

---

### gen_subscroll {#minianimate.gen_subscroll .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_subscroll`</p>
스크롤 애니메이션 서브스크롤 생성

자세한 내용은 [MiniAnimate.config.scroll](mini-animate.qmd#minianimate.config.scroll)을 참조하세요.

이는 함수 요소가 있는 테이블입니다. 생성기를 실제로 가져오려면 호출하세요.

예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    scroll = {
      -- 균등하게 애니메이션화하되 기본 60단계 대신 최대 120단계 사용
      subscroll = animate.gen_subscroll.equal({ max_output_steps = 120 }),
    }
  })
  ```

---

### gen_subscroll.equal() {#minianimate.gen_subscroll.equal .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_subscroll.equal`(<span class="help-syntax-special">{opts}</span>)</p>
균등한 단계의 서브스크롤 생성

#### 매개변수 {#minianimate.gen_subscroll.equal-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `total_scroll`을 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: `total_scroll`이 1 이하인 경우 `false`(불필요한 대기 감소), 그렇지 않으면 `true`.

  - <span class="help-syntax-keys">\<max_output_steps\></span> `(number)` - 출력의 최대 서브스크롤 단계 수. 부드러움을 희생하면서 계산량을 줄이려면 이 값을 조정하세요. 기본값: 60.

#### 반환 {#minianimate.gen_subscroll.equal-return}


`(function)` 서브스크롤 함수 ([MiniAnimate.config.scroll](mini-animate.qmd#minianimate.config.scroll) 참조).

---

### gen_subresize {#minianimate.gen_subresize .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_subresize`</p>
크기 조정 애니메이션 서브리사이즈 생성

자세한 내용은 [MiniAnimate.config.resize](mini-animate.qmd#minianimate.config.resize)를 참조하세요.

이는 함수 요소가 있는 테이블입니다. 생성기를 실제로 가져오려면 호출하세요.

예시:

  ```lua
  local is_many_wins = function(sizes_from, sizes_to)
    return vim.tbl_count(sizes_from) >= 3
  end
  local animate = require('mini.animate')
  animate.setup({
    resize = {
      -- 창이 3개 이상인 경우에만 애니메이션화
      subresize = animate.gen_subresize.equal({ predicate = is_many_wins }),
    }
  })
  ```

---

### gen_subresize.equal() {#minianimate.gen_subresize.equal .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_subresize.equal`(<span class="help-syntax-special">{opts}</span>)</p>
균등한 단계의 서브리사이즈 생성

#### 매개변수 {#minianimate.gen_subresize.equal-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `sizes_from` 및 `sizes_to`를 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: 항상 `true`.

#### 반환 {#minianimate.gen_subresize.equal-return}


`(function)` 서브리사이즈 함수 ([MiniAnimate.config.resize](mini-animate.qmd#minianimate.config.resize) 참조).

---

### gen_winconfig {#minianimate.gen_winconfig .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_winconfig`</p>
열기/닫기 애니메이션 winconfig 생성

자세한 내용은 [MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 또는 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close)를 참조하세요.

이는 함수 요소가 있는 테이블입니다. 생성기를 실제로 가져오려면 호출하세요.

예시:

  ```lua
  local is_not_single_window = function(win_id)
    local tabpage_id = vim.api.nvim_win_get_tabpage(win_id)
    return #vim.api.nvim_tabpage_list_wins(tabpage_id) > 1
  end
  local animate = require('mini.animate')
  animate.setup({
    open = {
      -- 기본 정적 창 대신 가장 가까운 가장자리에서 닦아내는 효과로 애니메이션화하며,
      -- 탭페이지에 창이 하나만 있는 것이 아닐 때만 수행함
      winconfig = animate.gen_winconfig.wipe({
        predicate = is_not_single_window,
        direction = 'from_edge',
      }),
    },
    close = {
      -- 기본 정적 창 대신 가장 가까운 가장자리로 닦아내는 효과로 애니메이션화하며,
      -- 탭페이지에 창이 하나만 있는 것이 아닐 때만 수행함
      winconfig = animate.gen_winconfig.wipe({
        predicate = is_not_single_window,
        direction = 'to_edge',
      }),
    },
  })
  ```

---

### gen_winconfig.static() {#minianimate.gen_winconfig.static .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_winconfig.static`(<span class="help-syntax-special">{opts}</span>)</p>
정적 플로팅 창을 위한 winconfig 생성

대상 창 전체를 정적으로 덮는 플로팅 창을 생성합니다.

#### 매개변수 {#minianimate.gen_winconfig.static-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `win_id`를 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: 항상 `true`.

  - <span class="help-syntax-keys">\<n_steps\></span> `(number)` - 모두 동일한 설정을 가진 출력 단계 수. `winblend` 설정 옵션에서 수행되는 투명도 애니메이션의 부드러움을 조정하는 데 유용합니다. 기본값: 25.

#### 반환 {#minianimate.gen_winconfig.static-return}


`(function)` Winconfig 함수 ([MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 또는 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close) 참조).

---

### gen_winconfig.center() {#minianimate.gen_winconfig.center .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_winconfig.center`(<span class="help-syntax-special">{opts}</span>)</p>
중심 집중식 애니메이션 플로팅 창을 위한 winconfig 생성

대상 창의 중심에서 커지거나 중심으로 작아지는 플로팅 창을 생성합니다.

#### 매개변수 {#minianimate.gen_winconfig.center-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `win_id`를 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: 항상 `true`.

  - <span class="help-syntax-keys">\<direction\></span> `(string)` - "to_center"(기본값, 전체 범위를 덮는 창이 중심으로 작아짐) 또는 "from_center"(창이 중심에서 전체 범위를 덮도록 커짐) 중 하나.

#### 반환 {#minianimate.gen_winconfig.center-return}


`(function)` Winconfig 함수 ([MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 또는 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close) 참조).

---

### gen_winconfig.wipe() {#minianimate.gen_winconfig.wipe .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_winconfig.wipe`(<span class="help-syntax-special">{opts}</span>)</p>
닦아내기(wipe) 방식의 애니메이션 플로팅 창을 위한 winconfig 생성

가장 가까운 가장자리에서 커지거나 가장자리로 작아지는 플로팅 창을 생성합니다. 이는 대상 창의 분할 유형도 고려합니다. 수직 분할된 창은 수직 가장자리를 향해 진행되고, 수평 분할된 창은 수평 가장자리를 향해 진행됩니다.

#### 매개변수 {#minianimate.gen_winconfig.wipe-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<predicate\></span> `(function)` - `win_id`를 입력으로 받아 애니메이션 수행 여부를 나타내는 불리언 값을 반환하는 콜러블입니다. 기본값: 항상 `true`.

  - <span class="help-syntax-keys">\<direction\></span> `(string)` - "to_edge"(기본값, 전체 범위를 덮는 창이 가장 가까운 가장자리로 작아짐) 또는 "from_edge"(창이 가장자리에서 전체 범위를 덮도록 커짐) 중 하나.

#### 반환 {#minianimate.gen_winconfig.wipe-return}


`(function)` Winconfig 함수 ([MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 또는 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close) 참조).

---

### gen_winblend {#minianimate.gen_winblend .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_winblend`</p>
열기/닫기 애니메이션 `winblend` 진행 생성

자세한 내용은 [MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 또는 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close)를 참조하세요.

이는 함수 요소가 있는 테이블입니다. 투명도 함수를 실제로 가져오려면 호출하세요.

예시:

  ```lua
  local animate = require('mini.animate')
  animate.setup({
    open = {
      -- 투명도를 기본값 80~100 대신 60~80으로 변경
      winblend = animate.gen_winblend.linear({ from = 60, to = 80 }),
    },
    close = {
      -- 투명도를 기본값 80~100 대신 60~80으로 변경
      winblend = animate.gen_winblend.linear({ from = 60, to = 80 }),
    },
  })
  ```

---

### gen_winblend.linear() {#minianimate.gen_winblend.linear .help-syntax-right-anchor}

<p align="center">`MiniAnimate.gen_winblend.linear`(<span class="help-syntax-special">{opts}</span>)</p>
선형 `winblend` 진행 생성

#### 매개변수 {#minianimate.gen_winblend.linear-parameters}



<span class="help-syntax-special">{opts}</span> `(table|nil)` 생성기를 제어하는 옵션. 가능한 키:

  - <span class="help-syntax-keys">\<from\></span> `(number)` - 'winblend'의 초기 값.

  - <span class="help-syntax-keys">\<to\></span> `(number)` - 'winblend'의 최종 값.

#### 반환 {#minianimate.gen_winblend.linear-return}


`(function)` Winblend 함수 ([MiniAnimate.config.open](mini-animate.qmd#minianimate.config.open) 또는 [MiniAnimate.config.close](mini-animate.qmd#minianimate.config.close) 참조).
